// W3 (EU32) — AYARLAR EKRANININ (ekran/ayarlar.js: kalibrasyon gecmisi, depolama, gelismis) TR/EN METINLERI.
//
// ACILIS sozlugunden (sozluk.js) AYRI (EU30 deseni): ekran/ayarlar.js bu dosyayi STATIK ice aktarir, yani
// sozluk yalniz Ayarlar'in modul bolumlerinden biri ilk acilinca iner (Gelismis artik iki dosya: ayarlar.js +
// sozluk_ay.js). Kabugun ay. metinleri (bolum adlari, Dil karti, "modul yuklenemedi") ve birden cok ekranin
// kullandiklari (ay.yenile, ay.yukleniyor) acilis sozlugunde kalir.
// Kurallar sozluk.js'inkiyle AYNI (test/sozluk_ay.test.js).

import { ceviri, sozluktenCeviri } from "./sozluk.js";

const S = (tr, en) => Object.freeze({ tr, en });

export const SOZLUK_AY = Object.freeze({
  // ── Ayarlar ekrani (ekran/ayarlar.js AYE_METIN / KAL_ALANLARI / KAL_NEDEN / TASIYICI_METIN)
  "ay.kal_baslik": S("Kalibrasyon geçmişi", "Calibration history"),
  "ay.kal_salt": S("Salt okunur. Geçmişe kayıt kartta eklenir (Konsol'dan k komutları ya da kayıt başlarken kendiliğinden); bu panel geçmişi değiştirmez.",
    "Read-only. Entries are added on the board (k commands from the Console, or automatically when a recording starts); this panel does not change the history."),
  "ay.kal_kaynak_kart": S("Kaynak: kartın kalibrasyon geçmişi (şu anki durum).", "Source: the board's calibration history (current state)."),
  "ay.kal_kaynak_telefon": S("Kaynak: bu telefondaki kopya — kart akışı {kimlik}, son eşitleme {zaman}. Kartın şu anki geçmişi farklı olabilir.",
    "Source: this phone's copy — board stream {kimlik}, last sync {zaman}. The board's current history may differ."),
  "ay.kal_kaynak_yerel": S("Kaynak: bu tarayıcıdaki kopya — kart akışı {kimlik}, son eşitleme {zaman}. Kartın şu anki geçmişi farklı olabilir.",
    "Source: this browser's copy — board stream {kimlik}, last sync {zaman}. The board's current history may differ."),
  "ay.kal_neden": S("Karttan okunmadı: {neden}", "Not read from the board: {neden}"),
  "ay.kal_neden_imza": S("kart imzalı istek istiyor ve bu tarayıcıyı tanımıyor (Ayarlar → Eşleştirme)", "the board requires signed requests and does not recognise this browser (Settings → Pairing)"),
  "ay.kal_neden_yok": S("kart kalibrasyon geçmişi vermedi (HTTP {kod})", "the board returned no calibration history (HTTP {kod})"),
  "ay.kal_neden_ag": S("karta ulaşılamadı ({mesaj})", "the board could not be reached ({mesaj})"),
  "ay.kal_neden_bozuk": S("kartın yanıtı okunamadı", "the board's reply could not be read"),
  "ay.kal_neden_usb": S("USB bağlantısında bu uç yok — kartın adresinden açın", "not available over USB — open the panel from the board's address"),
  "ay.kal_neden_demo": S("demo kipinde gerçek kart yok", "there is no real board in demo mode"),
  "ay.kal_neden_taban": S("panel kartın kendi adresinden açılmadı (Bağlantı'da başka bir kart adresi yazılı)", "the panel is not opened from the board's own address (another board address is set under Connection)"),
  "ay.kal_hic": S("Kalibrasyon geçmişi yok: kart vermedi ve bu tarayıcıda kopya yok. Kayıtlar'dan eşitlemek geçmişin kopyasını da getirir.",
    "No calibration history: the board did not provide one and this browser has no copy. Syncing in Recordings also brings a copy of the history."),
  "ay.kal_ozet": S("{adet} / {azami} kayıt · kartın şu anki değerleri: {etkin}", "{adet} / {azami} entries · the board's current values: {etkin}"),
  "ay.kal_etkin_no": S("{no} numaralı kayıt", "entry {no}"),
  "ay.kal_taslak": S("Kartın şu anki değerleri geçmişte YOK (taslak): bir sonraki kayıt başlarken kendiliğinden eklenir ya da Konsol'dan kaydedilir.",
    "The board's current values are NOT in the history (draft): they are added automatically when the next recording starts, or saved from the Console."),
  "ay.kal_dolu": S("Geçmiş dolmak üzere ({adet} / {azami}) — dolunca yeni değerler numara alamaz; eski kayıt silinmez.",
    "The history is almost full ({adet} / {azami}) — once full, new values get no number; old entries are not deleted."),
  "ay.kal_tablo": S("Kalibrasyon geçmişi kayıtları, yeniden eskiye", "Calibration history entries, newest first"),
  "ay.kal_no": S("No", "No"),
  "ay.kal_tarih": S("Tarih", "Date"),
  "ay.kal_tur": S("Tür", "Type"),
  "ay.kal_kaynak": S("Kaynak", "Source"),
  "ay.kal_not": S("Not", "Note"),
  "ay.kal_durum": S("Durum", "State"),
  "ay.kal_etkin": S("etkin — kartın şu anki değerleri", "active — the board's current values"),
  "ay.kal_degerler": S("Değerler", "Values"),
  "ay.kal_deger_baslik": S("{no} numaralı kaydın değerleri", "Values of entry {no}"),
  "ay.kal_alan": S("Alan", "Field"),
  "ay.kal_deger": S("Değer", "Value"),
  "ay.kal_saatsiz": S("saat yok (açılış {acilis})", "no clock (boot {acilis})"),
  "ay.kd_normal_n": S("NORMAL · bölücü oranı", "NORMAL · divider ratio"),
  "ay.kd_normal_pga": S("NORMAL · ADC aralığı (V)", "NORMAL · ADC range (V)"),
  "ay.kd_normal_kazanc": S("NORMAL · kazanç düzeltmesi", "NORMAL · gain correction"),
  "ay.kd_normal_sifir_ham": S("NORMAL · sıfır (ham kod)", "NORMAL · zero (raw code)"),
  "ay.kd_normal_tau": S("NORMAL · süzgeç zaman sabiti", "NORMAL · filter time constant"),
  "ay.kd_yuksek_n": S("YÜKSEK · bölücü oranı", "HIGH · divider ratio"),
  "ay.kd_yuksek_pga": S("YÜKSEK · ADC aralığı (V)", "HIGH · ADC range (V)"),
  "ay.kd_yuksek_kazanc": S("YÜKSEK · kazanç düzeltmesi", "HIGH · gain correction"),
  "ay.kd_yuksek_sifir_ham": S("YÜKSEK · sıfır (ham kod)", "HIGH · zero (raw code)"),
  "ay.kd_yuksek_tau": S("YÜKSEK · süzgeç zaman sabiti", "HIGH · filter time constant"),
  "ay.kd_i_ofset": S("Akım · sıfır (ham kod)", "Current · zero (raw code)"),
  "ay.kd_i_pga": S("Akım · ADC aralığı (V)", "Current · ADC range (V)"),
  "ay.kd_sont_ohm": S("Şönt (Ω)", "Shunt (Ω)"),
  "ay.kd_i_duzeltme": S("Akım · kazanç düzeltmesi", "Current · gain correction"),
  "ay.kd_sebeke_hz": S("Şebeke frekansı (Hz; 0 = DC)", "Mains frequency (Hz; 0 = DC)"),
  "ay.kd_faz0": S("Faz kalibrasyonu NORMAL (µs)", "Phase calibration NORMAL (µs)"),
  "ay.kd_faz1": S("Faz kalibrasyonu YÜKSEK (µs)", "Phase calibration HIGH (µs)"),
  "ay.depo_baslik": S("Bu tarayıcıdaki kayıt kopyaları", "Recording copies in this browser"),
  "ay.kota_baslik": S("Tarayıcı depolaması", "Browser storage"),
  "ay.kota": S("Tarayıcı depolama kullanımı", "Browser storage usage"),
  "ay.kota_metin": S("{kullanilan} / {kota} kullanılıyor (%{yuzde})", "{kullanilan} of {kota} used ({yuzde}%)"),
  "ay.kota_guvensiz": S("Tarayıcı kota ve kalıcı depolama bilgisini yalnız güvenli bağlamda (https ya da localhost) verir; panel kartın http:// adresinden açık. Kopyalar yine burada saklanır ama tarayıcı yer gerekince silebilir.",
    "The browser reports quota and persistent storage only in a secure context (https or localhost); the panel is open from the board's http:// address. Copies are still kept here, but the browser may delete them when it needs space."),
  "ay.kota_yok": S("Bu tarayıcı depolama kotasını bildirmiyor.", "This browser does not report its storage quota."),
  "ay.kalici": S("Kalıcı depolama", "Persistent storage"),
  "ay.kalici_acik": S("açık — tarayıcı yer gerekince bu kopyaları kendiliğinden silmez", "on — the browser will not delete these copies on its own when it needs space"),
  "ay.kalici_kapali": S("kapalı — tarayıcı yer gerekince kopyaları silebilir", "off — the browser may delete the copies when it needs space"),
  "ay.kalici_bilinmiyor": S("bilinmiyor", "unknown"),
  "ay.kalici_iste": S("Kalıcı depolama iste", "Request persistent storage"),
  "ay.kalici_verildi": S("Tarayıcı kalıcı depolamayı verdi.", "The browser granted persistent storage."),
  "ay.kalici_reddedildi": S("Tarayıcı kalıcı depolamayı vermedi (çoğu tarayıcı sık açılan ya da yer imine eklenen sitelere verir).",
    "The browser did not grant persistent storage (most browsers grant it to sites you open often or bookmark)."),
  "ay.kalici_hata": S("İstek yapılamadı: {mesaj}", "The request failed: {mesaj}"),
  "ay.depo_tablo": S("Bu tarayıcıdaki kart akışları ve boyutları", "Board streams in this browser and their sizes"),
  "ay.depo_akis": S("Kart akışı", "Board stream"),
  "ay.depo_boyut": S("Boyut", "Size"),
  "ay.depo_oturum": S("Oturum", "Sessions"),
  "ay.depo_son_sira": S("Son sıra", "Last seq."),
  "ay.depo_son": S("Son eşitleme", "Last sync"),
  "ay.depo_arsiv": S("Arşiv", "Archive"),
  "ay.depo_durum": S("Durum", "State"),
  "ay.depo_islem": S("İşlem", "Action"),
  "ay.arsiv_acik": S("açık — kart onay alıyor", "on — the board receives acknowledgements"),
  "ay.arsiv_kapali": S("kapalı", "off"),
  "ay.arsiv_ipucu": S("Arşiv seçimi Kayıtlar'dan değiştirilir (açmak iki aşamalı onay ister).", "The archive choice is changed in Recordings (turning it on needs a two-step confirmation)."),
  "ay.kayitlara_git": S("Kayıtlar'a git", "Go to Recordings"),
  "ay.depo_bos": S("Bu tarayıcıda kayıt kopyası yok.", "There are no recording copies in this browser."),
  "ay.depo_kart_bilinmiyor": S("Kart bu panelden sorulamadı: en yeni açılan akış “bu kart” sayıldı.", "The board could not be asked from this panel: the most recently opened stream is taken as “this board”."),
  "ay.depo_hata": S("Tarayıcı deposu okunamadı: {mesaj}", "Browser storage could not be read: {mesaj}"),
  "ay.gel_baslik": S("Sürüm ve tanı", "Version and diagnostics"),
  "ay.fw": S("Firmware", "Firmware"),
  "ay.fw_yok": S("açılış afişi görülmedi — sürüm kartın açılış afişinden okunur (panel kart açıldıktan sonra bağlandıysa görülmez)",
    "the boot banner was not seen — the version is read from the board's boot banner (not seen if the panel connected after boot)"),
  "ay.panel": S("Kartın arayüz görüntüsü (panel sürümü)", "Board's interface image (panel version)"),
  "ay.panel_metin": S("{surum} · {dosya} dosya · {boyut} gzip", "{surum} · {dosya} files · {boyut} gzip"),
  "ay.panel_yok": S("künye okunamadı ({neden}) — geliştirme sunucusu olabilir; köprü onu karttan WiFi'den okur", "the image manifest could not be read ({neden}) — this may be a development server; the bridge reads it from the board over WiFi"),
  "ay.tasiyici": S("Bağlantı yolu", "Connection path"),
  "ay.tas_seri": S("USB (Web Serial)", "USB (Web Serial)"),
  "ay.tas_akis": S("WiFi / köprü (akış)", "WiFi / bridge (stream)"),
  "ay.tas_demo": S("Demo — sahte kart", "Demo — simulated board"),
  "ay.tas_telefon": S("Telefon (imzalı Wi-Fi)", "Phone (signed Wi-Fi)"),
  "ay.telefon_hata": S("“Bu telefon” bölümü açılamadı: {mesaj}", "The “This phone” section could not be opened: {mesaj}"),
  "ay.konsol_ipucu": S("Ham komut konsolu Konsol ekranında.", "The raw command console is on the Console screen."),
  "ay.konsola_git": S("Konsol'a git", "Go to Console"),
  "ay.sifirla_baslik": S("Tarayıcı ayarları", "Browser settings"),
  "ay.sifirla_aciklama": S("Bu tarayıcıda saklanan panel ayarları ({n} anahtar): görünüm, dil, grafik tercihleri, kart adresi, arşiv seçimleri. Sıfırlamak yalnız bunları siler ve sayfayı yeniden yükler; kayıt kopyaları (Depolama), bu tarayıcının eşleştirmesi (cihaz anahtarı — silmek için Eşleştirme › “Bu tarayıcıyı unut”) ve kartın kendi ayarları değişmez.",
    "Panel settings stored in this browser ({n} keys): appearance, language, chart preferences, board address, archive choices. Resetting deletes only these and reloads the page; the recording copies (Storage), this browser's pairing (device key — to delete it use Pairing › “Forget this browser”) and the board's own settings do not change."),
  "ay.sifirla": S("Tarayıcı ayarlarını sıfırla", "Reset browser settings"),
  "ay.sifirla_eminim": S("Eminim, {n} anahtarı sil", "Yes, delete {n} keys"),
  "ay.sifirla_uyari": S("Arşiv seçimleri de silinir: bu tarayıcı karta yeniden “aldım” onayı göndermez (güvenli yön).",
    "Archive choices are deleted too: this browser stops sending “received” acknowledgements to the board (the safe direction)."),
  "ay.sifirla_yok": S("Bu tarayıcıda saklanan panel ayarı yok.", "No panel settings are stored in this browser."),
});

/** Ayarlar ekrani metni: once bu sozluk, yoksa sozluk.js (kabugun / ortak ay. ve kod aileleri). ATMAZ. */
export function ceviriAy(anahtar, dil = "tr", degiskenler = null) {
  const a = typeof anahtar === "string" ? anahtar : String(anahtar);
  return Object.prototype.hasOwnProperty.call(SOZLUK_AY, a)
    ? sozluktenCeviri(SOZLUK_AY, a, dil, degiskenler) : ceviri(a, dil, degiskenler);
}
