// B73 / 2F — TR/EN SOZLUK (ust tasarim §9 "Dil": metinler sozlukte, ekrana gomulu metin yok).
//
// SOZLUK[anahtar] = { tr, en }. Anahtarlar ASCII nokta ayrimli aileler:
//   sebep.<kod>  oturum.tur.<kod>  olay.<kod>  pil.durum.<kod>  pil.hata.<kod>
//   kal.tur.<kod>  kal.kaynak.<kod>  kal.durum.<ad>   (+ her ailede <onek>bilinmeyen: {kod})
//   bayrak.<ad>  csv.<sutun>  csv.kayit.<tur>  rapor.<alan>  alan.<olay alani>  uyari.<kod>
//   kl.<ad> (web paneli: Kayitlar listesi)  kg.<ad> (web paneli: kayit gorunumu) — 3C;
//   os.<ad> (web paneli: Osiloskop, 3E — app.js OS_METIN + ekran/osiloskop.js); kr.<ad> (web paneli:
//   Karsilastirma, 3G — ekran/karsilastir.js + Kayitlar'daki secim); ay.<ad> (web paneli: Ayarlar,
//   3H — app.js AY_METIN / AYAR_BOLUMLERI / DILLER + ekran/ayarlar.js AYE_METIN / KAL_ALANLARI); ekranlar
//   anahtari DUZ METIN sabitiyle yazar (KL_METIN / KG_METIN), "kullanilmayan anahtar yok" denetimi
//   arayuz3/ekran/*.js'i de tarar (test/sozluk.test.js).
// Birimler SI ve dile gore DEGISMEZ (V, A, W, ohm, mAh, Wh, s, ms). CSV basliklari iki dilde
// de kucuk ASCII snake_case + birim soneki (kopru/arsiv.py D_BASLIK uslubu; Excel/pandas dostu).
//
// ceviri(anahtar, dil, degiskenler) HICBIR ZAMAN ATMAZ:
//   * bilinmeyen anahtar -> ANAHTARIN KENDISI (eksik ceviri ekranda gorunur, uygulama cokmez)
//   * dil 'tr' / 'en' disi -> 'tr'; o dilde metin yoksa (bos) obur dil, o da yoksa anahtar
//   * {ad} yer tutucusu degiskenler[ad] ile (String); verilmeyen yer tutucu oldugu gibi kalir
// ceviriKod(onek, kod, dil): onek+kod varsa onu, yoksa onek+"bilinmeyen" ({kod} ile).
// Kapsam (her SEBEP/OLAY/oturum turu/CSV basligi/rapor alani icin bos olmayan tr VE en; hic
// kullanilmayan anahtar yok) test/sozluk.test.js'te kaynaktan ve firmware basliklarindan olculur.

const S = (tr, en) => Object.freeze({ tr, en });

export const DILLER = Object.freeze(["tr", "en"]);

export const SOZLUK = Object.freeze({
  // ── BITIR sebepleri (kayit_bicim.h KB_SEBEP_*)
  "sebep.1": S("kullanıcı durdurdu", "stopped by user"),
  "sebep.2": S("bellek doldu", "storage full"),
  "sebep.3": S("hata", "error"),
  "sebep.4": S("pil testi bitti", "battery test finished"),
  "sebep.5": S("kart yeniden başladı", "board restarted"),
  "sebep.6": S("başka oturum başladı", "another session started"),
  "sebep.7": S("planlı süre doldu", "scheduled duration elapsed"),
  "sebep.bilinmeyen": S("bilinmeyen sebep ({kod})", "unknown reason ({kod})"),
  "sebep.acik": S("bitmedi (kayıt sürüyor ya da bitişi henüz eşitlenmedi)",
    "not finished (still recording or the end is not synced yet)"),

  // ── oturum turleri (kayit_bicim.h KAYIT_OTURUM_*)
  "oturum.tur.1": S("Ölçüm kaydı", "Measurement recording"),
  "oturum.tur.2": S("Pil testi", "Battery test"),
  "oturum.tur.3": S("Osiloskop günlüğü", "Oscilloscope log"),
  "oturum.tur.bilinmeyen": S("Bilinmeyen oturum türü ({kod})", "Unknown session type ({kod})"),

  // ── OLAY turleri (kayit_bicim.h KO_*)
  "olay.1": S("Pil testi ayarı", "Battery test settings"),
  "olay.2": S("DCIR ölçümü", "DCIR measurement"),
  "olay.3": S("Pil testi sonucu", "Battery test result"),
  "olay.4": S("Osiloskop kalibrasyon eğrisi", "Oscilloscope calibration curve"),
  "olay.5": S("Zamanlanmış kayıt", "Scheduled recording"),
  "olay.bilinmeyen": S("Bilinmeyen olay ({kod})", "Unknown event ({kod})"),

  // ── pil testi durum / hata (pil_test.h PilDurum / PilHata)
  "pil.durum.0": S("beklemede", "idle"),
  "pil.durum.1": S("çalışıyor", "running"),
  "pil.durum.2": S("bitti (kesme gerilimine ulaşıldı)", "finished (cut-off voltage reached)"),
  "pil.durum.3": S("kullanıcı durdurdu", "stopped by user"),
  "pil.durum.4": S("hata", "error"),
  "pil.durum.bilinmeyen": S("bilinmeyen durum ({kod})", "unknown state ({kod})"),
  "pil.hata.0": S("yok", "none"),
  "pil.hata.1": S("gerilim zaten kesme geriliminin altında", "voltage already below cut-off"),
  "pil.hata.2": S("gerilim 38.5 V üstünde (MOSFET Vdss sınırı)", "voltage above 38.5 V (MOSFET Vdss limit)"),
  "pil.hata.3": S("ters polarite", "reverse polarity"),
  "pil.hata.4": S("MOSFET kapalıyken akım var (yük J3'te)", "current flows with the MOSFET off (load on J3)"),
  "pil.hata.5": S("azami süre aşıldı", "maximum duration exceeded"),
  "pil.hata.6": S("yük bağlanmadı (akım akmadı)", "no load connected (no current)"),
  "pil.hata.bilinmeyen": S("bilinmeyen hata ({kod})", "unknown error ({kod})"),

  // ── kalibrasyon gecmisi (kalgec.h KGT_* / KGK_*) ve rapor durumu
  "kal.tur.0": S("belirsiz", "unspecified"),
  "kal.tur.1": S("donanım değişti", "hardware changed"),
  "kal.tur.2": S("ince ayar", "fine tuning"),
  "kal.tur.bilinmeyen": S("bilinmeyen tür ({kod})", "unknown type ({kod})"),
  "kal.kaynak.0": S("elle", "manual"),
  "kal.kaynak.1": S("otomatik (kayıt başlarken)", "automatic (at recording start)"),
  "kal.kaynak.2": S("ilk kayıt (1B öncesi kalibrasyon)", "initial entry (pre-1B calibration)"),
  "kal.kaynak.bilinmeyen": S("bilinmeyen kaynak ({kod})", "unknown source ({kod})"),
  "kal.durum.bulundu": S("geçmişte bulundu", "found in history"),
  "kal.durum.numarasiz": S("numarasız (geçmiş doluydu ya da eski biçim); değerler oturumun kopyasından",
    "unnumbered (history was full or old format); values from the session copy"),
  "kal.durum.gecmis_yok": S("kalibrasyon geçmişi verilmedi", "calibration history not provided"),
  "kal.durum.yok": S("bu numara geçmişte yok", "this number is not in the history"),
  "kal.durum.bozuk": S("kart bu kaydı okuyamadı (bozuk)", "the board could not read this entry (corrupt)"),
  "kal.durum.kopya_yok": S("oturum başlığı yok: kalibrasyon kopyası yok", "no session header: no calibration copy"),

  // ── bayrak adlari (CSV `bayraklar`; KN_* / KAO_* / KA_*)
  "bayrak.yuksek": S("YUKSEK", "HIGH_RANGE"),
  "bayrak.v_hata": S("V_HATA", "V_ERROR"),
  "bayrak.i_hata": S("I_HATA", "I_ERROR"),
  "bayrak.v_doydu": S("V_DOYDU", "V_SATURATED"),
  "bayrak.duraklama": S("DURAKLAMA", "PAUSE"),
  "bayrak.kayip_once": S("KAYIP_ONCE", "LOSS_BEFORE"),
  "bayrak.dcir": S("DCIR", "DCIR"),
  "bayrak.silme": S("SILME", "FLASH_ERASE"),

  // ── CSV basliklari (ASCII snake_case + SI birim soneki)
  "csv.kayit": S("kayit", "row_type"),
  "csv.kayit.nokta": S("nokta", "point"),
  "csv.kayit.dcir": S("dcir", "dcir"),
  "csv.sira": S("sira", "seq"),
  "csv.acilis": S("acilis", "boot"),
  "csv.devam": S("devam", "resumed"),
  "csv.kart_ms": S("kart_ms", "board_ms"),
  "csv.kart_us": S("kart_us", "board_us"),
  "csv.gecen_ms": S("gecen_ms", "elapsed_ms"),
  "csv.unix_s": S("unix_s", "unix_s"),
  "csv.zaman_utc": S("zaman_utc", "time_utc"),
  "csv.n": S("n", "n"),
  "csv.v_ort": S("v_ort_V", "v_avg_V"),
  "csv.v_min": S("v_min_V", "v_min_V"),
  "csv.v_maks": S("v_maks_V", "v_max_V"),
  "csv.i_ort": S("i_ort_A", "i_avg_A"),
  "csv.i_min": S("i_min_A", "i_min_A"),
  "csv.i_maks": S("i_maks_A", "i_max_A"),
  "csv.w_ort": S("w_ort_W", "p_avg_W"),
  "csv.w_min": S("w_min_W", "p_min_W"),
  "csv.w_maks": S("w_maks_W", "p_max_W"),
  "csv.v": S("v_V", "v_V"),
  "csv.i": S("i_A", "i_A"),
  "csv.w": S("w_W", "p_W"),
  "csv.bayrak": S("bayrak", "flags"),
  "csv.ornek_bayrak": S("ornek_bayrak", "sample_flags"),
  "csv.kayit_bayrak": S("kayit_bayrak", "record_flags"),
  "csv.bayraklar": S("bayraklar", "flag_names"),
  "csv.not": S("not", "note"),
  "csv.mah": S("yuk_mAh", "charge_mAh"),
  "csv.wh": S("enerji_Wh", "energy_Wh"),
  "csv.dcir_no": S("dcir_no", "dcir_no"),
  "csv.dcir_v_once": S("dcir_v_once_V", "dcir_v_before_V"),
  "csv.dcir_i_once": S("dcir_i_once_A", "dcir_i_before_A"),
  "csv.dcir_v_ani": S("dcir_v_ani_V", "dcir_v_instant_V"),
  "csv.dcir_v_oturmus": S("dcir_v_oturmus_V", "dcir_v_settled_V"),
  "csv.dcir_r_ani": S("dcir_r_ani_ohm", "dcir_r_instant_ohm"),
  "csv.dcir_r_oturmus": S("dcir_r_oturmus_ohm", "dcir_r_settled_ohm"),
  "csv.dcir_mah": S("dcir_yuk_mAh", "dcir_charge_mAh"),
  "csv.dcir_wh": S("dcir_enerji_Wh", "dcir_energy_Wh"),
  "csv.skop_ornek": S("ornek", "sample"),
  "csv.skop_t": S("t_s", "t_s"),
  "csv.skop_kod": S("kod", "code"),
  "csv.skop_v": S("v_V", "v_V"),

  // ── rapor alan etiketleri (rapor.js RAPOR_ETIKET)
  "rapor.kimlik": S("Kimlik", "Identity"),
  "rapor.oturum_no": S("Oturum no", "Session no"),
  "rapor.tur": S("Tür", "Type"),
  "rapor.ad": S("Ad", "Name"),
  "rapor.etiketler": S("Etiketler", "Tags"),
  "rapor.notlar": S("Notlar", "Notes"),
  "rapor.firmware": S("Firmware", "Firmware"),
  "rapor.hiz": S("Kayıt aralığı (ms; 0 = her örnek)", "Recording interval (ms; 0 = every sample)"),
  "rapor.ayrintili": S("Ayrıntılı kip (her örnek)", "Detailed mode (every sample)"),
  "rapor.basi_eksik": S("Başlık kopyadan (TEKRAR)", "Header from copy (TEKRAR)"),
  "rapor.zaman": S("Zaman", "Time"),
  "rapor.baslangic": S("Başlangıç", "Start"),
  "rapor.bitis": S("Bitiş", "End"),
  "rapor.toplam_sure": S("Toplam süre (boşluklar dahil, ms)", "Total duration (gaps included, ms)"),
  "rapor.olculen_sure": S("Ölçülen süre (ms)", "Measured duration (ms)"),
  "rapor.bosluk_sure": S("Boşluk süresi (ms)", "Gap duration (ms)"),
  "rapor.bosluk_adet": S("Boşluk sayısı", "Gap count"),
  "rapor.sayac": S("Sayılar", "Counts"),
  "rapor.nokta_adet": S("Nokta", "Points"),
  "rapor.ayrinti_adet": S("Örnek (ayrıntılı)", "Samples (detailed)"),
  "rapor.devam_adet": S("Yeniden başlayıp süren (DEVAM)", "Resumed after restart (DEVAM)"),
  "rapor.olay_adet": S("Olay", "Events"),
  "rapor.not_adet": S("Not", "Notes"),
  "rapor.skop_adet": S("Osiloskop yakalaması", "Oscilloscope captures"),
  "rapor.sebep": S("Bitiş sebebi", "Stop reason"),
  "rapor.bitir_nokta": S("Kartın saydığı nokta", "Points counted by the board"),
  "rapor.istatistik": S("İstatistik (ham veriden)", "Statistics (from raw data)"),
  "rapor.gerilim": S("Gerilim (V)", "Voltage (V)"),
  "rapor.akim": S("Akım (A)", "Current (A)"),
  "rapor.guc": S("Güç (W)", "Power (W)"),
  "rapor.adet": S("Adet", "Count"),
  "rapor.min": S("En düşük", "Minimum"),
  "rapor.maks": S("En yüksek", "Maximum"),
  "rapor.ort": S("Ortalama", "Mean"),
  "rapor.rms": S("RMS", "RMS"),
  "rapor.tepe_tepe": S("Tepeden tepeye", "Peak to peak"),
  "rapor.min_sira": S("En düşüğün sırası", "Sequence of minimum"),
  "rapor.maks_sira": S("En yükseğin sırası", "Sequence of maximum"),
  "rapor.min_zaman": S("En düşüğün zamanı (ms)", "Time of minimum (ms)"),
  "rapor.maks_zaman": S("En yükseğin zamanı (ms)", "Time of maximum (ms)"),
  "rapor.enerji": S("Enerji (boşluklar hariç)", "Energy (gaps excluded)"),
  "rapor.wh": S("Enerji (Wh)", "Energy (Wh)"),
  "rapor.mah": S("Yük (mAh)", "Charge (mAh)"),
  "rapor.pil": S("Pil testi", "Battery test"),
  "rapor.pil_ayar": S("Pil testi ayarı", "Battery test settings"),
  "rapor.pil_sonuc": S("Pil testi sonucu", "Battery test result"),
  "rapor.dcir": S("DCIR ölçümleri", "DCIR measurements"),
  "rapor.kalibrasyon": S("Kalibrasyon", "Calibration"),
  "rapor.kal_no": S("Kalibrasyon no", "Calibration no"),
  "rapor.kal_durum": S("Geçmişteki durumu", "Status in history"),
  "rapor.kal_kayit": S("Geçmiş kaydı", "History entry"),
  "rapor.kal_kopya": S("Oturumun kopyası (çevrimde kullanılan)", "Session copy (used for conversion)"),
  "rapor.olaylar": S("Olaylar", "Events"),
  "rapor.skop": S("Osiloskop", "Oscilloscope"),
  "rapor.yakalamalar": S("Yakalamalar", "Captures"),
  "rapor.skop_tam": S("Tam yakalama", "Complete captures"),
  "rapor.skop_eksik": S("Eksik yakalama", "Incomplete captures"),
  "rapor.uyarilar": S("Uyarılar", "Warnings"),
  "rapor.gecen": S("Başlangıçtan beri (ms)", "Since start (ms)"),
  "rapor.unix": S("Unix zamanı (s)", "Unix time (s)"),
  "rapor.iso": S("Tarih-saat (UTC)", "Date-time (UTC)"),
  "rapor.acilis": S("Açılış (0 = başlangıç)", "Boot (0 = start)"),

  // ── olay / pil alanlari (rapor.js ALAN_ETIKET)
  "alan.kesme_v": S("Kesme gerilimi (V)", "Cut-off voltage (V)"),
  "alan.ocv": S("Açık devre gerilimi (V)", "Open-circuit voltage (V)"),
  "alan.azami_s": S("Azami süre (s)", "Maximum duration (s)"),
  "alan.dcir_aralik_ms": S("DCIR aralığı (ms)", "DCIR interval (ms)"),
  "alan.dcir_ms": S("DCIR darbesi (ms)", "DCIR pulse (ms)"),
  "alan.kayit_hz": S("Kayıt hızı (Hz)", "Recording rate (Hz)"),
  "alan.no": S("No", "No"),
  "alan.v_once": S("Darbeden önce gerilim (V)", "Voltage before pulse (V)"),
  "alan.i_once": S("Darbeden önce akım (A)", "Current before pulse (A)"),
  "alan.v_ani": S("Anlık gerilim (V)", "Instant voltage (V)"),
  "alan.v_oturmus": S("Oturmuş gerilim (V)", "Settled voltage (V)"),
  "alan.r_ani": S("Anlık iç direnç (Ω)", "Instant internal resistance (Ω)"),
  "alan.r_oturmus": S("Oturmuş iç direnç (Ω)", "Settled internal resistance (Ω)"),
  "alan.mah": S("Yük (mAh)", "Charge (mAh)"),
  "alan.wh": S("Enerji (Wh)", "Energy (Wh)"),
  "alan.durum": S("Durum", "State"),
  "alan.hata": S("Hata", "Error"),
  "alan.v_son": S("Son gerilim (V)", "Final voltage (V)"),
  "alan.sure_ms": S("Süre (ms)", "Duration (ms)"),
  "alan.dcir_sayisi": S("DCIR sayısı", "DCIR count"),
  "alan.mv": S("Eğri (mV)", "Curve (mV)"),
  "alan.bas_unix": S("Başlangıç (unix s)", "Start (unix s)"),
  "alan.sure_s": S("Süre (s; 0 = durdurulana dek)", "Duration (s; 0 = until stopped)"),
  "alan.hiz_ms": S("Kayıt aralığı (ms)", "Recording interval (ms)"),
  "alan.plan_no": S("Plan no", "Plan no"),
  "alan.ham": S("Ham yük (hex)", "Raw payload (hex)"),

  // ── rapor uyarilari ({sayi}: adet)
  "uyari.baslik_yok": S("Oturum başlığı yok: kalibrasyon bilinmiyor, V ve A hesaplanamadı.",
    "No session header: calibration unknown, V and A could not be computed."),
  "uyari.basi_eksik": S("Başlık temizlikte silinmiş; sektör başı kopyasından (TEKRAR) okundu.",
    "Header was cleaned up; read from the sector copy (TEKRAR)."),
  "uyari.acik": S("Oturumun bitişi yok: kayıt sürüyor ya da sonu eşitlenmedi.",
    "Session has no end: still recording or the end is not synced."),
  "uyari.devam": S("Kart {sayi} kez yeniden başladı, kayıt sürdü (araya boşluk girdi).",
    "The board restarted {sayi} time(s) and recording resumed (gaps in between)."),
  "uyari.nokta_eksik": S("{sayi} nokta eksik (eşitlenmemiş ya da temizlenmiş).",
    "{sayi} point(s) missing (not synced or cleaned up)."),
  "uyari.bos_nokta": S("{sayi} noktada geçerli örnek yok (değerler boş).",
    "{sayi} point(s) have no valid sample (values empty)."),
  "uyari.kayip_once": S("{sayi} yerde kartın kuyruğu taştı, öncesinde veri düştü.",
    "Board queue overflowed at {sayi} place(s); data was dropped before them."),
  "uyari.duraklama": S("{sayi} noktada ölçüm durdu (ör. osiloskop yakalaması).",
    "Measurement paused at {sayi} point(s) (e.g. oscilloscope capture)."),
  "uyari.silme": S("{sayi} kez flaş silmesi ölçümü ~25 ms durdurdu.",
    "Flash erase paused measurement for ~25 ms {sayi} time(s)."),
  "uyari.v_hata": S("{sayi} kayıtta gerilim ADC'si okunamadı.", "Voltage ADC read failed in {sayi} record(s)."),
  "uyari.i_hata": S("{sayi} kayıtta akım ADC'si okunamadı.", "Current ADC read failed in {sayi} record(s)."),
  "uyari.v_doydu": S("{sayi} kayıtta gerilim girişi doydu.", "Voltage input saturated in {sayi} record(s)."),
  "uyari.saat_yok": S("Kartın saati bilinmiyordu: mutlak tarih-saat yok.",
    "Board clock was unknown: no absolute date-time."),
  "uyari.gecen_bilinmiyor": S("{sayi} satırda başlangıçtan beri geçen süre bilinmiyor (yeniden başlama sırasında saat yoktu).",
    "Elapsed time unknown for {sayi} row(s) (no clock across a restart)."),
  "uyari.zaman_belirsiz": S("{sayi} olayın hangi açılışa ait olduğu belirlenemedi (ham kayıtlar verilmedi).",
    "Boot of {sayi} event(s) could not be determined (raw records not provided)."),
  "uyari.not_belirsiz": S("{sayi} notun grafikteki yeri belirsiz (kart_ms birden fazla açılışa uyuyor ya da hiçbirine).",
    "Position of {sayi} note(s) is ambiguous (board_ms fits several boots or none)."),
  "uyari.olay_bilinmeyen": S("{sayi} olayın türü bu sürümde bilinmiyor.", "{sayi} event(s) of a type unknown to this version."),
  "uyari.skop_eksik": S("{sayi} osiloskop yakalaması eksik (parça eşitlenmemiş).",
    "{sayi} oscilloscope capture(s) incomplete (part not synced)."),
  "uyari.kal_farkli": S("Geçmişteki {no} numaralı kalibrasyon oturumun kopyasından farklı; çevrimde kopya kullanıldı.",
    "Calibration no {no} in history differs from the session copy; the copy was used."),
  "uyari.kal_gecersiz": S("Kalibrasyonda şönt direnci 0: akım hesaplanamadı.",
    "Shunt resistance is 0 in the calibration: current could not be computed."),

  // ── web paneli 3C: Kayıtlar listesi (arayuz3/ekran/kayitlar.js KL_METIN, TUR_METIN, NEREDE_METIN)
  "kl.baslik": S("Kayıtlar", "Recordings"),
  "kl.liste": S("Liste", "List"),
  "kl.esitle": S("Eşitle", "Sync"),
  "kl.esitleniyor": S("Eşitleniyor…", "Syncing…"),
  "kl.yenile": S("Yenile", "Refresh"),
  "kl.ilerleme": S("{boyut} alındı", "{boyut} received"),
  "kl.neden_taban": S("Panel başka bir adresteki karta bağlanıyor (Ayarlar → Kart adresi). Kayıtlar yalnız panel kartın KENDİ adresinden açıldığında eşitlenir — paneli kartın adresinden açın. Bu tarayıcıdaki kopyalar aşağıda.",
    "The panel talks to a board at another address (Settings → Board address). Recordings sync only when the panel is opened from the board's OWN address — open the panel from the board's address. Copies in this browser are listed below."),
  "kl.neden_usb": S("USB (seri) bağlantısında kayıt eşitlenmez: kayıt verisi seri yoldan gelmiyor. Paneli kartın adresinden açın; PC'de arşiv için kopru/kayit_esitle.py. Bu tarayıcıdaki kopyalar aşağıda.",
    "Recordings do not sync over USB (serial): recording data is not served on the serial path. Open the panel from the board's address; on a PC use kopru/kayit_esitle.py for archiving. Copies in this browser are listed below."),
  "kl.neden_demo": S("Demo kipinde kayıt eşitlenmez. Bu tarayıcıdaki kopyalar aşağıda.",
    "Recordings do not sync in demo mode. Copies in this browser are listed below."),
  "kl.neden_yok": S("Bu sayfayı sunan yer kart değil (köprü ya da geliştirme sunucusu): kayıt eşitlemesi yalnız kartın kendi adresinden. Paneli kartın adresinden açın.",
    "This page is not served by the board (bridge or development server): recordings sync only from the board's own address. Open the panel from the board's address."),
  "kl.neden_imza": S("Kart imzalı istek istiyor; bu tarayıcı henüz eşleştirilemiyor (panelde eşleştirme yok). Kayıtları PC'de kopru/kayit_esitle.py imzalı eşitler. Bu tarayıcıdaki kopyalar aşağıda.",
    "The board requires signed requests; this browser cannot be paired yet (the panel has no pairing). On a PC, kopru/kayit_esitle.py syncs the recordings with signatures. Copies in this browser are listed below."),
  "kl.neden_mesgul": S("Kart meşgul ya da kayıt hazır değil ({mesaj}) — biraz sonra Yenile'ye basın.",
    "The board is busy or recording is not ready ({mesaj}) — press Refresh in a moment."),
  "kl.neden_host": S("Kart bu adresi reddetti ({mesaj}) — paneli kartın kendi adresinden (IP ya da olcum.local) açın.",
    "The board rejected this address ({mesaj}) — open the panel from the board's own address (IP or olcum.local)."),
  "kl.neden_ag": S("Karta ulaşılamadı ({mesaj}) — kartın açık ve aynı ağda olduğunu denetleyip Yenile'ye basın.",
    "The board could not be reached ({mesaj}) — check that the board is on and on the same network, then press Refresh."),
  "kl.neden_bozuk": S("Kartın yanıtı okunamadı ({mesaj}); bu tarayıcıya hiçbir şey yazılmadı.",
    "The board's reply could not be read ({mesaj}); nothing was written to this browser."),
  "kl.neden_hata": S("Eşitleme yapılamadı ({mesaj}) — Yenile'ye basın.", "Sync failed ({mesaj}) — press Refresh."),
  "kl.neden_akis": S("Kartın kayıt akışı beklenenden farklı ({mesaj}); bu kopyaya eklenmedi. Yenile'ye basın.",
    "The board's recording stream is not what was expected ({mesaj}); nothing was appended to this copy. Press Refresh."),
  "kl.neden_kilit": S("Eşitleme zaten sürüyor ({mesaj}).", "A sync is already running ({mesaj})."),
  "kl.neden_depo": S("Tarayıcı deposu açılamadı ({mesaj}) — özel pencerede değilseniz bu site için tarayıcı depolamasına izin verin.",
    "Browser storage could not be opened ({mesaj}) — unless this is a private window, allow site storage for this page."),
  "kl.sonuc_yeni": S("{yeni} yeni kayıt alındı (son sıra {son}).", "{yeni} new record(s) received (last sequence {son})."),
  "kl.sonuc_guncel": S("Yeni kayıt yok — bu tarayıcı güncel (son sıra {son}).",
    "No new records — this browser is up to date (last sequence {son})."),
  "kl.onay_gitti": S("Karta onay gönderildi ve kart doğruladı: bu tarayıcı arşiv sayılıyor.",
    "Acknowledgement sent and confirmed by the board: this browser counts as an archive."),
  "kl.onay_dogrulanmadi": S("Onay gönderildi ama kart doğrulamadı — sonraki eşitlemede yeniden denenir.",
    "Acknowledgement sent but not confirmed by the board — it will be retried on the next sync."),
  "kl.onay_bagli_degil": S("Arşiv seçili ama panel karta bağlı değil: onay gönderilmedi (bağlanınca sonraki eşitlemede gider).",
    "Archive is selected but the panel is not connected to the board: no acknowledgement was sent (it goes with the next sync once connected)."),
  "kl.bekleyen": S("Kartta {bekleyen} sıra daha görünüyor ama veri gelmedi; yeni kayıt gelince boşluk olarak geçilir.",
    "The board shows {bekleyen} more sequence(s) but no data came; it is skipped as a gap when new records arrive."),
  "kl.kal_hata": S("Kalibrasyon geçmişi alınamadı ({hata}) — Yenile'ye basın.", "Calibration history could not be fetched ({hata}) — press Refresh."),
  "kl.arsiv": S("Bu tarayıcı arşivdir (karta “aldım” onayı gönder)",
    "This browser is an archive (send “received” acknowledgements to the board)"),
  "kl.arsiv_aciklama": S("Kapalıyken (varsayılan) kart bu kopyayı yedek SAYMAZ ve onun için hiçbir kaydı silmez. Açarsanız kart, yer gerekince bu tarayıcıya kopyalanmış eski kayıtları silebilir — o zaman tek kopya burada kalır. Yalnız kalıcı arşiv olarak kullandığınız tarayıcıda açın.",
    "When off (default) the board does NOT count this copy as a backup and deletes nothing because of it. When on, the board may delete old recordings already copied here when it needs space — the only copy then stays here. Turn it on only in a browser you use as a permanent archive."),
  "kl.kart_ozet": S("Kart: {oturum} oturum · doluluk %{doluluk} · eşitlenmemiş %{onaysiz}",
    "Board: {oturum} session(s) · {doluluk}% full · {onaysiz}% not synced"),
  "kl.kart_yok": S("Kartın dizini alınamadı — “nerede” yalnız bu tarayıcıyı gösteriyor.",
    "The board's index is unavailable — “where” only reflects this browser."),
  "kl.ara": S("Ara: ad, etiket, not, numara", "Search: name, tag, note, number"),
  "kl.tur_sec": S("Tür süzgeci", "Type filter"),
  "kl.nerede_sec": S("Nerede süzgeci", "Location filter"),
  "kl.tur_hepsi": S("Bütün türler", "All types"),
  "kl.tur_olcum": S("Ölçüm", "Measurement"),
  "kl.tur_ayrinti": S("Ölçüm (ayrıntılı)", "Measurement (detailed)"),
  "kl.tur_pil": S("Pil testi", "Battery test"),
  "kl.tur_skop": S("Osiloskop", "Oscilloscope"),
  "kl.tur_bilinmeyen": S("Bilinmeyen", "Unknown"),
  "kl.nerede_hepsi": S("Her yer", "Anywhere"),
  "kl.nerede_kart": S("yalnız kartta", "on the board only"),
  "kl.nerede_tarayici": S("yalnız bu tarayıcıda", "in this browser only"),
  "kl.nerede_ikisi": S("ikisinde", "in both"),
  "kl.durum_kayitta": S("kaydediliyor", "recording"),
  "kl.durum_acik": S("açık", "open"),
  "kl.durum_bitti": S("bitti", "finished"),
  "kl.eksik": S("eksik kopya", "incomplete copy"),
  "kl.eski_kart": S("eski kart kopyası", "old board copy"),
  "kl.basi_silindi": S("başı silinmiş", "start deleted"),
  "kl.saatsiz": S("saat yok", "no clock"),
  "kl.bos": S("Henüz kayıt yok — Canlı'da “Başlat” ile bir kayıt açın.", "No recordings yet — start one with “Start” on the Live screen."),
  "kl.bos_suzgec": S("Süzgece uyan kayıt yok.", "No recordings match the filter."),
  "kl.nokta_kisa": S("nokta", "points"),
  "kl.ornek_kisa": S("örnek", "samples"),
  "kl.yakalama_kisa": S("yakalama", "captures"),
  "kl.kopyalar": S("Bu tarayıcıdaki kopyalar", "Copies in this browser"),
  "kl.kopya_satir": S("Kart akışı {kimlik} · {oturum} oturum · {boyut} · son sıra {son}",
    "Board stream {kimlik} · {oturum} session(s) · {boyut} · last sequence {son}"),
  "kl.kopya_guncel": S("bu kart", "this board"),
  "kl.kopya_eski": S("eski kart kopyası", "old board copy"),
  "kl.sil": S("Kopyayı sil", "Delete copy"),
  "kl.sil_onay": S("Eminim, sil", "Yes, delete"),
  "kl.vazgec": S("Vazgeç", "Cancel"),
  "kl.arsiv_onay_uyari": S("Arşiv açılırsa karta “aldım” onayı gider ve kart, yer gerekince bu kayıtları silebilir — tek kopya bu tarayıcıda kalır. Emin misiniz?",
    "If archiving is on, “received” acknowledgements go to the board and it may delete these recordings when it needs space — the only copy stays in this browser. Are you sure?"),
  "kl.arsiv_eminim": S("Eminim, bu tarayıcı arşiv", "Yes, this browser is the archive"),
  "kl.sil_uyari": S("Silinen kopya geri gelmez; kartta da yoksa kayıt tamamen kaybolur.",
    "A deleted copy cannot be restored; if the board no longer has it either, the recording is lost."),
  "kl.yalniz_kartta": S("Bu kayıt yalnız kartta — önce eşitleyin.", "This recording is only on the board — sync first."),
  "kl.bulunamadi": S("Kayıt bulunamadı (#{oturum}).", "Recording not found (#{oturum})."),
  "kl.listeye_don": S("← Kayıtlar", "← Recordings"),
  "kl.yukleniyor": S("Yükleniyor…", "Loading…"),
  "kl.ipucu": S("Satıra dokunun: kayıt açılır. Eşitleme yalnız okur; kartta hiçbir şey silinmez.",
    "Tap a row to open the recording. Syncing only reads; nothing is deleted on the board."),

  // ── web paneli 3C: kayıt görünümü (arayuz3/ekran/kayit_gorunum.js KG_METIN)
  "kg.geri": S("← Kayıtlar", "← Recordings"),
  "kg.rapor": S("Rapor", "Report"),
  "kg.rapor_kapat": S("Kayda dön", "Back to recording"),
  "kg.yazdir": S("Yazdır / PDF", "Print / PDF"),
  "kg.baslik": S("Kayıt", "Recording"),
  "kg.rapor_baslik": S("Kayıt raporu", "Recording report"),
  "kg.grafik": S("Grafik", "Chart"),
  "kg.gerilim": S("Gerilim", "Voltage"),
  "kg.sag_eksen": S("Sağ eksen:", "Right axis:"),
  "kg.akim": S("Akım", "Current"),
  "kg.guc": S("Güç", "Power"),
  "kg.yok": S("yok", "none"),
  "kg.zarf": S("En düşük / en yüksek", "Minimum / maximum"),
  "kg.tumu": S("Tümünü göster", "Show all"),
  "kg.imlec_sil": S("İmleçleri kaldır", "Clear cursors"),
  "kg.grafik_etiket": S("Kaydın zaman grafiği: gerilim, akım ve güç", "Time chart of the recording: voltage, current and power"),
  "kg.gezgin_etiket": S("Kaydın tamamı ve görünen pencere", "Whole recording and the visible window"),
  "kg.grafik_ipucu": S("Çift tıkla: imleç koy (önce A, sonra B) · sürükle: kaydır · tekerlek ya da iki parmak: yakınlaştır · A / B tuşları imleci fareye koyar · alttaki şeritte pencereyi taşı.",
    "Double-click: place a cursor (A first, then B) · drag: pan · wheel or two fingers: zoom · A / B keys put a cursor at the mouse · move the window on the strip below."),
  "kg.imlec_yok": S("İmleç yok — grafikte çift tıklayın.", "No cursor — double-click on the chart."),
  "kg.notlar": S("Notlar", "Notes"),
  "kg.genel_not": S("genel", "general"),
  "kg.not_ipucu": S("Nota tıklayın: grafik o ana gider.", "Click a note: the chart jumps to that moment."),
  "kg.pil": S("Pil testi özeti", "Battery test summary"),
  "kg.yakalamalar": S("Osiloskop yakalamaları", "Oscilloscope captures"),
  "kg.skop_ipucu": S("Yakalamanın grafiği osiloskop ekranında; burada her yakalama CSV olarak indirilebilir.",
    "The capture chart is on the oscilloscope screen; each capture can be downloaded as CSV here."),
  "kg.daha_fazla": S("Daha fazla göster ({kalan} kaldı)", "Show more ({kalan} left)"),
  "kg.veri_yok": S("Bu kayıtta çizilecek veri yok (oturum hemen kapandı ya da yalnız başlığı eşitlendi). Eşitleme sürüyorsa listeden Yenile'ye basın.",
    "This recording has no data to draw (the session closed at once or only its header was synced). If a sync is running, press Refresh in the list."),
  "kg.disari": S("Dışa aktar", "Export"),
  "kg.disari_ipucu": S("Excel (TR): noktalı virgül + ondalık virgül. EN: virgül + ondalık nokta. Ham .kyt: kartın baytları aynen (kopru/kayit_bicim.py okur). Dosyalar bu tarayıcıda üretilir; kart yorulmaz.",
    "Excel (TR): semicolon + decimal comma. EN: comma + decimal point. Raw .kyt: the board's bytes unchanged (read by kopru/kayit_bicim.py). Files are built in this browser; the board is not loaded."),
  "kg.okuma_dt": S("Δt (B − A)", "Δt (B − A)"),
  "kg.okuma_ort": S("ort", "mean"),
  "kg.okuma_min": S("en düşük", "min"),
  "kg.okuma_maks": S("en yüksek", "max"),
  "kg.okuma_fark": S("Δ", "Δ"),
  "kg.okuma_mah": S("Yük A–B", "Charge A–B"),
  "kg.okuma_wh": S("Enerji A–B", "Energy A–B"),
  "kg.okuma_sure": S("Ölçülen süre A–B", "Measured time A–B"),
  "kg.tur": S("Tür", "Type"),
  "kg.no": S("Oturum", "Session"),
  "kg.baslangic": S("Başlangıç", "Start"),
  "kg.saat_yok": S("saat yok (açılıştan beri)", "no clock (since boot)"),
  "kg.sure": S("Süre", "Duration"),
  "kg.nokta": S("Nokta", "Points"),
  "kg.ornek": S("Örnek", "Samples"),
  "kg.yakalama": S("Yakalama", "Captures"),
  "kg.hiz": S("Kayıt aralığı", "Recording interval"),
  "kg.her_ornek": S("her örnek (ayrıntılı kip)", "every sample (detailed mode)"),
  "kg.firmware": S("Firmware", "Firmware"),
  "kg.kal_no": S("Kalibrasyon", "Calibration"),
  "kg.durum": S("Durum", "Status"),
  "kg.acik": S("bitmedi (sürüyor ya da sonu eşitlenmedi)", "not finished (running or end not synced)"),
  "kg.nerede": S("Nerede", "Where"),
  "kg.uyari_tahmini": S("Kart {sayi} kez saatsiz yeniden başladı: o parçaların başlangıca uzaklığı bilinmiyor, grafikte öncekinin ardına (araya boşluk) konuldu.",
    "The board restarted {sayi} time(s) without a clock: the distance of those parts from the start is unknown; on the chart they follow the previous part (with a gap)."),
  "kg.uyari_eksik": S("Kartta bu kaydın daha yeni verisi var — eşitleyin.", "The board has newer data for this recording — sync."),
  "kg.uyari_eski": S("Bu kayıt eski bir kart akışından (kart biçimlenmiş ya da değişmiş); kartta yok.",
    "This recording is from an old board stream (board was formatted or replaced); it is not on the board."),
  "kg.sutun_no": S("No", "No"),
  "kg.sutun_zaman": S("Zaman", "Time"),
  "kg.sutun_ornek": S("Örnek", "Samples"),
  "kg.sutun_hz": S("Hz", "Hz"),
  "kg.sutun_tdiv": S("Zaman/böl", "Time/div"),
  "kg.sutun_tetik": S("Tetik", "Trigger"),
  "kg.sutun_tam": S("Durum", "Status"),
  "kg.evet": S("evet", "yes"),
  "kg.hayir": S("hayır", "no"),
  "kg.eksik_yakalama": S("eksik (parça eşitlenmemiş)", "incomplete (part not synced)"),
  "kg.csv_tr": S("CSV · Excel (TR)", "CSV · Excel (TR)"),
  "kg.csv_en": S("CSV · EN", "CSV · EN"),
  "kg.ayrinti_tr": S("Ayrıntılı CSV · Excel (TR)", "Detailed CSV · Excel (TR)"),
  "kg.ayrinti_en": S("Ayrıntılı CSV · EN", "Detailed CSV · EN"),
  "kg.pil_tr": S("Pil CSV · Excel (TR)", "Battery CSV · Excel (TR)"),
  "kg.pil_en": S("Pil CSV · EN", "Battery CSV · EN"),
  "kg.ham": S("Ham kayıt (.kyt)", "Raw recording (.kyt)"),
  "kg.skop_csv": S("CSV", "CSV"),
  "kg.disari_hata": S("Dosya üretilemedi — sayfayı yenileyip yeniden deneyin.", "The file could not be built — reload the page and try again."),

  // ── 3D: web paneli kabugu (sol serit) — arayuz3/app.js KB_METIN / GORUNUMLER
  "kb.ad": S("Ölçüm Kartı", "Measurement Board"),
  "kb.gezinme": S("Ana gezinme", "Main navigation"),
  "kb.menu_ac": S("Menüyü aç", "Open menu"),
  "kb.menu_kapat": S("Menüyü kapat", "Close menu"),
  "kb.canli": S("Canlı", "Live"),
  "kb.canli_alt": S("V · A · W · enerji · grafik · kayıt", "V · A · W · energy · chart · recording"),
  "kb.skop": S("Osiloskop", "Oscilloscope"),
  "kb.skop_alt": S("yakalama · tetik · hızlı güç ölçümü", "capture · trigger · fast power measurement"),
  "kb.pil": S("Pil testi", "Battery test"),
  "kb.pil_alt": S("deşarj eğrisi · mAh · Wh · iç direnç · kayıt", "discharge curve · mAh · Wh · internal resistance · recording"),
  "kb.kayitlar": S("Kayıtlar", "Recordings"),
  "kb.kayitlar_alt": S("kartın kayıtları · eşitleme · grafik · dışa aktarma", "board recordings · sync · chart · export"),
  "kb.karsilastir": S("Karşılaştırma", "Compare"),
  "kb.karsilastir_alt": S("kayıtlar üst üste · başlangıçtan beri / saat / mAh ekseni · CSV",
    "recordings overlaid · since start / clock / mAh axis · CSV"),
  "kb.ayar": S("Ayarlar", "Settings"),
  "kb.ayar_alt": S("bağlantı · ağ · kalibrasyon ve geçmişi · depolama · dil · görünüm", "connection · network · calibration and its history · storage · language · appearance"),
  "kb.konsol": S("Konsol", "Console"),
  "kb.konsol_alt": S("ham satırlar · komut", "raw lines · commands"),
  "kb.cevrimici": S("Çevrimiçi · {kip}", "Online · {kip}"),
  "kb.cevrimdisi": S("Bağlı değil", "Not connected"),
  "kb.kip_usb": S("USB", "USB"),
  "kb.kip_wifi": S("WiFi", "Wi-Fi"),
  "kb.kip_kopru": S("köprü", "bridge"),
  "kb.kip_demo": S("demo", "demo"),
  "kb.baglan": S("Karta bağlan", "Connect"),
  "kb.kes": S("Bağlantıyı kes", "Disconnect"),
  "kb.esitlenmemis": S("Eşitlenmemiş: %{oran}", "Not synced: {oran}%"),
  "kb.esitlenmemis_yok": S("Eşitlenmemiş: — (kart kayıt durumu göndermedi)", "Not synced: — (no recording state from the board)"),
  "kb.esitlenmemis_bagli_degil": S("Eşitlenmemiş: — (karta bağlı değil)", "Not synced: — (not connected)"),
  "kb.icerige_gec": S("İçeriğe geç", "Skip to content"),
  "kb.pil_calisiyor": S("Pil testi çalışıyor", "Battery test running"),
  "kb.surum_ipucu": S("Sürüm kartın açılış afişinden okunur; panel kart açıldıktan sonra bağlandıysa afiş görülmemiştir.",
    "The version is read from the board's boot banner; if the panel connected after boot, the banner was not seen."),

  // ── 3D: Canli ekrani — arayuz3/app.js CN_METIN (+ parametreli metinler)
  "cn.baslik": S("Canlı", "Live"),
  "cn.okumalar": S("Anlık değerler", "Instant values"),
  "cn.gerilim": S("Gerilim", "Voltage"),
  "cn.akim": S("Akım", "Current"),
  "cn.guc": S("Güç", "Power"),
  "cn.enerji": S("Enerji (sayaç)", "Energy (counter)"),
  "cn.enerji_ipucu": S("Kartın enerji sayacı: son sıfırlamadan (e) ya da açılıştan beri; kayıt oturumuna bağlı değil.",
    "The board's energy counter: since the last reset (e) or boot; not tied to a recording session."),
  "cn.on_saniye": S("10 s: {min} … {maks}", "10 s: {min} … {maks}"),
  "cn.on_saniye_yok": S("10 s: —", "10 s: —"),
  "cn.grafik": S("Grafik", "Chart"),
  "cn.grafik_etiket": S("Canlı zaman grafiği", "Live time chart"),
  "cn.sag_eksen": S("Sağ eksen", "Right axis"),
  "cn.sag_akim": S("Akım", "Current"),
  "cn.sag_guc": S("Güç", "Power"),
  "cn.sag_yok": S("yok", "none"),
  "cn.pencere": S("Pencere", "Window"),
  "cn.yenileme": S("Yenileme", "Refresh"),
  "cn.dondur": S("Dondur", "Freeze"),
  "cn.canliya_don": S("Canlıya dön", "Back to live"),
  "cn.donmus_ipucu": S("Donduruldu — tekerlek yakınlaştırır, sürükle kaydırır, çift tık imleç koyar (A, sonra B).",
    "Frozen — the wheel zooms, drag pans, double-click places a cursor (A, then B)."),
  "cn.veri_yok": S("veri yok — karta bağlan", "no data — connect to the board"),
  "cn.yukleniyor": S("grafik yükleniyor…", "loading chart…"),
  "cn.yuklenemedi": S("Grafik modülü yüklenemedi — kart yeniden başlıyor olabilir; birkaç saniye sonra sayfayı yenileyin.",
    "The chart module did not load — the board may be restarting; reload the page in a few seconds."),
  "cn.tepe": S("tepe {deger}", "peak {deger}"),
  "cn.olcek": S("ölçek ±{deger}", "scale ±{deger}"),
  "cn.kanal_veri_yok": S("veri yok", "no data"),
  "cn.adc_yok_v": S("veri yok — gerilim ADC'si (0x49) yanıt vermiyor; Ayarlar → I²C tara ile denetleyin",
    "no data — the voltage ADC (0x49) does not answer; check with Settings → I²C scan"),
  "cn.adc_yok_i": S("veri yok — akım ADC'si (0x48) yanıt vermiyor; Ayarlar → I²C tara ile denetleyin",
    "no data — the current ADC (0x48) does not answer; check with Settings → I²C scan"),
  "cn.imlec_sil": S("İmleçleri sil", "Clear cursors"),
  "cn.imlec_yok": S("Çift tık: imleç A; ikinci çift tık: B.", "Double-click: cursor A; second double-click: B."),
  "cn.okuma_dt": S("Δt", "Δt"),
  "cn.okuma_dv": S("ΔV", "ΔV"),
  "cn.okuma_ort_i": S("A ort", "I avg"),
  "cn.okuma_yuk": S("Yük", "Charge"),
  "cn.okuma_enerji": S("Enerji", "Energy"),
  "cn.kayit_denetim": S("Kayıt denetimi", "Recording controls"),
  "cn.kayit_hiz": S("Kayıt aralığı", "Recording interval"),
  "cn.her_ornek": S("her örnek (~500/s)", "every sample (~500/s)"),
  "cn.hiz_ms": S("{ms} ms", "{ms} ms"),
  "cn.hiz_s": S("{s} s", "{s} s"),
  "cn.hiz_dk": S("{dk} dk", "{dk} min"),
  "cn.hiz_olculen": S("~{hiz} (ölçülen)", "~{hiz} (measured)"),
  "cn.baslat": S("Kaydı başlat", "Start recording"),
  "cn.durdur": S("Kaydı durdur", "Stop recording"),
  "cn.durdur_eminim": S("Eminim, durdur", "Yes, stop"),
  "cn.not_ekle": S("Not ekle", "Add note"),
  "cn.not_metin": S("Not metni", "Note text"),
  "cn.not_bayt": S("{bayt}/{azami} bayt", "{bayt}/{azami} bytes"),
  "cn.not_gonder": S("Notu ekle", "Add the note"),
  "cn.not_gonderiliyor": S("Ekleniyor…", "Adding…"),
  "cn.vazgec": S("Vazgeç", "Cancel"),
  "cn.zamanla": S("Zamanla", "Schedule"),
  "cn.plan_bas": S("Başlangıç (yerel saat)", "Start (local time)"),
  "cn.plan_sure": S("Süre", "Duration"),
  "cn.plan_sure_ipucu": S("Süre 0 sa 0 dk = durdurulana dek; en çok 30 gün. Kart saati NTP'den: saat yoksa plan kurulmaz.",
    "Duration 0 h 0 min = until stopped; at most 30 days. The board clock comes from NTP: without it no schedule is set."),
  "cn.plan_kur": S("Planı kur", "Set schedule"),
  "cn.plan_iptal": S("Planı iptal et", "Cancel schedule"),
  "cn.plan_iptal_kayit": S("Planı iptal et (süren kayıt da durur)", "Cancel schedule (stops the running recording too)"),
  "cn.plan_iptal_eminim": S("Eminim — plan ve kayıt durur", "Yes — schedule and recording stop"),
  "cn.birim_sa": S("sa", "h"),
  "cn.birim_dk": S("dk", "min"),
  "cn.birim_gun": S("gün", "d"),
  "cn.hata_hiz": S("Kart bu kayıt aralığını kabul etmiyor.", "The board does not accept this recording interval."),
  "cn.hata_oturum": S("Etkin kayıt oturumu yok — not yalnız süren kayda eklenir.", "No active recording session — a note can only be added to a running recording."),
  "cn.hata_not_bos": S("Not boş olamaz.", "The note cannot be empty."),
  "cn.hata_not_karakter": S("Not çift tırnak, ters bölü ya da denetim karakteri içeremez — kart bunları atar.",
    "The note cannot contain double quotes, backslashes or control characters — the board drops them."),
  "cn.hata_not_uzun": S("Not en çok {azami} bayt olabilir (şu an {bayt}); kart fazlasını keserdi.",
    "A note can be at most {azami} bytes (now {bayt}); the board would cut the rest."),
  "cn.hata_komut_uzun": S("Komut en çok {azami} bayt olabilir (şu an {bayt}); kart uzun komutu reddeder.",
    "A command can be at most {azami} bytes (now {bayt}); the board rejects longer commands."),
  "cn.hata_plan_bas": S("Başlangıç tarihini ve saatini seçin.", "Choose a start date and time."),
  "cn.hata_plan_sure": S("Süre 0 ile 30 gün arasında olmalı.", "The duration must be between 0 and 30 days."),
  "cn.hata_plan_eski": S("Başlangıç 2023'ten önce olamaz (kart unix saniyesi bekliyor).", "The start cannot be before 2023 (the board expects unix seconds)."),
  "cn.hata_plan_ileri": S("Başlangıç en çok 1 yıl ileride olabilir.", "The start can be at most 1 year ahead."),
  "cn.hata_plan_gecmis": S("Planın penceresi geçmişte kalıyor — başlangıcı ileri alın ya da süreyi uzatın.",
    "The schedule window is in the past — move the start later or make the duration longer."),
  "cn.hata_bagli_degil": S("Karta bağlı değil — önce “Karta bağlan”a basın.", "Not connected to the board — press “Connect” first."),
  "cn.kart_reddetti": S("Kart reddetti: {satir}", "The board refused: {satir}"),
  "cn.kayit_suruyor": S("Kayıt sürüyor", "Recording"),
  "cn.aktif_kayit": S("Aktif kayıt", "Active recording"),
  "cn.kayit_bilinmiyor": S("Kayıt durumu bilinmiyor (kart G satırı göndermedi).", "Recording state unknown (no G line from the board)."),
  "cn.oturum": S("Oturum {oturum}", "Session {oturum}"),
  "cn.nokta": S("{nokta} nokta", "{nokta} points"),
  "cn.ornek": S("{nokta} örnek", "{nokta} samples"),
  "cn.sure": S("Süre", "Duration"),
  "cn.hiz": S("Aralık", "Interval"),
  "cn.doluluk": S("Kart belleği %{doluluk} dolu · eşitlenmemiş %{onaysiz}", "Board memory {doluluk}% full · not synced {onaysiz}%"),
  "cn.kalan_hesap": S("kalan süre hesaplanıyor (en az 60 s gözlem)", "time left: measuring (at least 60 s)"),
  "cn.kalan_yaklasik": S("~{sure} kaldı", "~{sure} left"),
  "cn.kalan_enaz": S("> {sure} kaldı", "> {sure} left"),
  "cn.plan_yok": S("Plan: yok", "Schedule: none"),
  "cn.plan_durum": S("Plan: {durum}", "Schedule: {durum}"),
  "cn.plan_ayrinti": S("{bas} · {sure} · {hiz}", "{bas} · {sure} · {hiz}"),
  "cn.plan_suresiz": S("durdurulana dek", "until stopped"),
  "cn.dusen": S("Kart {n} noktayı yazamadı (kayıt kuyruğu doldu).", "The board could not write {n} points (recording queue full)."),
  "cn.skop_gunlugu": S("Osiloskop günlüğü sürüyor ({n} yakalama)", "Oscilloscope log running ({n} captures)"),
  "cn.son_olaylar": S("Son olaylar", "Recent events"),
  "cn.olay_yok": S("Henüz olay yok — yalnız bu sekmede, en çok 20.", "No events yet — this tab only, at most 20."),
  "cn.olay_basladi": S("Kayıt başladı · oturum {oturum}", "Recording started · session {oturum}"),
  "cn.olay_yeni_oturum": S("Yeni oturum {oturum}", "New session {oturum}"),
  "cn.olay_durdu": S("Kayıt durdu · oturum {oturum} ({durum})", "Recording stopped · session {oturum} ({durum})"),
  "cn.olay_durum": S("Kayıt durumu: {durum}", "Recording state: {durum}"),
  "cn.olay_dusen": S("Kart {n} noktayı düşürdü", "The board dropped {n} points"),
  "cn.olay_yeniden": S("Kart yeniden başladı", "The board restarted"),
  "cn.olay_surdu": S("Kayıt sürdü · oturum {oturum}", "Recording resumed · session {oturum}"),
  "cn.olay_plan": S("Plan: {durum}", "Schedule: {durum}"),
  "cn.olay_skop_basladi": S("Osiloskop günlüğü başladı", "Oscilloscope log started"),
  "cn.olay_skop_durdu": S("Osiloskop günlüğü durdu", "Oscilloscope log stopped"),

  // ── 3E: osiloskop ekrani (arayuz3/app.js OS_METIN + ekran/osiloskop.js; OS8)
  "os.baslik": S("Osiloskop", "Oscilloscope"),
  "os.alt_baslik": S("12 bit · 611 Sa/s … 83.3 kSa/s · ayarlanabilir zaman tabanı",
    "12-bit · 611 Sa/s … 83.3 kSa/s · adjustable timebase"),
  "os.denetimler": S("Osiloskop denetimleri", "Oscilloscope controls"),
  "os.yakalama": S("Yakalama", "Capture"),
  "os.yakala": S("Yakala", "Capture"),
  "os.yakalaniyor": S("Yakalanıyor…", "Capturing…"),
  "os.surekli": S("▶ Sürekli", "▶ Run"),
  "os.surekli_dur": S("■ Durdur", "■ Stop"),
  "os.surekli_ipucu": S("Sürekli yakala — gerçek osiloskoplardaki RUN/STOP", "Capture continuously — RUN/STOP on a real oscilloscope"),
  "os.otomatik": S("Otomatik", "Auto set"),
  "os.otomatik_ipucu": S("Sinyali bulup zaman tabanını ve tetiği kendisi ayarlar",
    "Finds the signal and sets the timebase and trigger by itself"),
  "os.zaman_tabani": S("Zaman tabanı", "Timebase"),
  "os.hizlandir": S("Zaman tabanını hızlandır", "Faster timebase"),
  "os.yavaslat": S("Zaman tabanını yavaşlat", "Slower timebase"),
  "os.tetik": S("Tetik", "Trigger"),
  "os.tetik_kip": S("Kip", "Mode"),
  "os.kip_oto": S("Oto", "Auto"),
  "os.kip_normal": S("Normal", "Normal"),
  "os.kip_tek": S("Tek atış", "Single"),
  "os.kenar": S("Kenar", "Edge"),
  "os.kenar_yukselen": S("↑ Yükselen", "↑ Rising"),
  "os.kenar_dusen": S("↓ Düşen", "↓ Falling"),
  "os.seviye": S("Seviye", "Level"),
  "os.on_tetik": S("Ön-tetik", "Pre-trigger"),
  "os.onay": S("Onay", "Confirmation"),
  "os.gunluk": S("Yakalama günlüğü", "Capture log"),
  "os.gunluk_ipucu": S("Yakalamalar kartın kayıt belleğine yazılır (ölçüm kaydı sürüyorsa ona eklenir) ve Kayıtlar'da görünür. Her tetikte kipi tetik kipini Normal'e alır.",
    "Captures are written to the board's recording memory (added to a running measurement recording) and appear in Recordings. Every-trigger mode switches the trigger mode to Normal."),
  "os.gunluk_her_tetik": S("Her tetikte", "Every trigger"),
  "os.gunluk_her_n": S("Her N saniyede", "Every N seconds"),
  "os.gunluk_saniye": S("Aralık (s)", "Interval (s)"),
  "os.gunluk_baslat": S("Günlüğü başlat", "Start log"),
  "os.gunluk_durdur": S("Günlüğü durdur", "Stop log"),
  "os.gunluk_elle_yok": S("Günlük sürerken elle yakalama yok — kart reddeder.", "No manual capture while the log runs — the board rejects it."),
  "os.gunluk_bilinmiyor": S("Günlük durumu bilinmiyor (bağlanınca kart söyler).", "Log state unknown (the board reports it on connect)."),
  "os.gunluk_kapali": S("Günlük kapalı", "Log off"),
  "os.gunluk_her_tetik_suruyor": S("Sürüyor: her tetikte · {n} yakalama", "Running: every trigger · {n} captures"),
  "os.gunluk_aralik_suruyor": S("Sürüyor: her {aralik} · {n} yakalama", "Running: every {aralik} · {n} captures"),
  "os.gunluk_yazilamayan": S("{n} yakalama yazılamadı", "{n} captures not written"),
  "os.hata_kip": S("Günlük kipi seçilmedi.", "No log mode selected."),
  "os.hata_aralik": S("Aralık 1 … 3600 s olmalı (kartın sınırı).", "The interval must be 1 … 3600 s (board limit)."),
  "os.hata_bagli_degil": S("Karta bağlı değil.", "Not connected to the board."),
  "os.kart_reddetti": S("Kart reddetti: {satir}", "Board rejected: {satir}"),
  "os.kal_cikisi": S("Kalibrasyon çıkışı", "Calibration output"),
  "os.cal_kapali": S("kapalı", "off"),
  "os.gorev": S("Görev", "Duty"),
  "os.kaynak_kart": S("Kaynak: kartın ölçüm satırı (M)", "Source: the board's measurement line (M)"),
  "os.kaynak_panel": S("Kaynak: panel, kaydın ham kodlarından — kartın hesabıyla (skopOlcKart)",
    "Source: panel, from the recording's raw codes — the board's calculation (skopOlcKart)"),
  "os.kaynak_arsiv": S("Kaynak: köprü arşivi — zaman büyüklükleri kaydın M satırından, gerilimler eksenden",
    "Source: bridge archive — time values from the recording's M line, voltages from the axis"),
  "os.egri_kayitta": S("eksen kaydın eğrisiyle", "axis uses the recording's curve"),
  "os.egri_yok_kayitta": S("eksen HAM (kayıtta eğri yok)", "axis RAW (no curve in the recording)"),
  "os.spektrum": S("Spektrum (FFT)", "Spectrum (FFT)"),
  "os.spektrum_ipucu": S("Yakalamanın bütün ham kodlarından (görünen yakınlaştırma penceresinden değil); DC çıkarılır, grafikte gösterilmez.",
    "From all raw codes of the capture (not the visible zoom window); DC is removed and not plotted."),
  "os.pencere": S("Pencere", "Window"),
  "os.pencere_hann": S("Hann", "Hann"),
  "os.pencere_dikdortgen": S("Dikdörtgen", "Rectangular"),
  "os.genlik": S("Genlik", "Amplitude"),
  "os.birim_v": S("V (tepe)", "V (peak)"),
  "os.birim_dbv": S("dBV", "dBV"),
  "os.tepe_frekans": S("Tepe frekansı", "Peak frequency"),
  "os.tepe_yok": S("belirgin AC bileşen yok", "no significant AC component"),
  "os.harmonik": S("Harmonik", "Harmonic"),
  "os.harmonik_tablo": S("İlk 5 harmonik (1 = temel)", "First 5 harmonics (1 = fundamental)"),
  "os.frekans": S("Frekans", "Frequency"),
  "os.thd": S("THD (yaklaşık, ilk 5)", "THD (approx., first 5)"),
  "os.dc": S("DC (çıkarıldı): {v}", "DC (removed): {v}"),
  "os.cozunurluk": S("çözünürlük {df} · {n} örnek → {nfft} noktalı FFT", "resolution {df} · {n} samples → {nfft}-point FFT"),
  "os.spektrum_yok": S("Yakalama yok — spektrum için önce yakalayın.", "No capture — capture first to see the spectrum."),
  "os.yukleniyor": S("Spektrum modülü yükleniyor…", "Loading the spectrum module…"),
  "os.yuklenemedi": S("Spektrum modülü yüklenemedi (modül inmedi) — kart yeniden başlıyor olabilir; birkaç saniye sonra sayfayı yenileyin.",
    "The spectrum module could not be loaded — the board may be restarting; reload the page in a few seconds."),
  "os.arsiv": S("Arşiv", "Archive"),
  "os.kayitli_serit": S("Kayıt #{oturum} · yakalama {no} · {zaman} — canlı değil", "Recording #{oturum} · capture {no} · {zaman} — not live"),
  "os.saatsiz": S("oturum başından {sure}", "{sure} from session start"),
  "os.zaman_yok": S("zamanı bilinmiyor", "time unknown"),
  "os.canliya_don": S("Canlıya dön", "Back to live"),
  "os.kayda_don": S("Kayda dön", "Back to recording"),
  "os.kayitli_yukleniyor": S("Kayıtlı yakalama açılıyor…", "Opening the recorded capture…"),
  "os.hata_yakalama_yok": S("Bu tarayıcıda oturum #{oturum} içinde {sira} sıralı yakalama yok — Kayıtlar'dan eşitleyin.",
    "This browser has no capture with sequence {sira} in session #{oturum} — sync from Recordings."),
  "os.hata_yakalama_eksik": S("Yakalama {no} eksik (parçaları eşitlenmemiş) — çizilmedi.", "Capture {no} is incomplete (parts not synced) — not drawn."),
  "os.hata_depo": S("Bu tarayıcının kayıt deposu açılamadı: {mesaj}", "This browser's recording store could not be opened: {mesaj}"),
  "os.hata_modul": S("Kayıtlı yakalama modülü yüklenemedi: {mesaj}", "The recorded-capture module could not be loaded: {mesaj}"),
  "os.tuval_etiket": S("Osiloskop dalga şekli (10 × 8 bölme)", "Oscilloscope waveform (10 × 8 divisions)"),
  "os.spektrum_etiket": S("Yakalamanın genlik spektrumu", "Amplitude spectrum of the capture"),
  "os.spektrum_klavye": S("Spektrum: tekerlek ya da + / − yakınlaştırır, ← → kaydırır, Home tümü; çift tık ya da A / B imleç koyar (okuma altta), Esc siler.",
    "Spectrum: wheel or + / − zooms, ← → pans, Home shows all; double-click or A / B places a cursor (reading below), Esc clears."),
  "os.tuval_bos": S("yakalama yok — “Yakala” düğmesine bas", "no capture — press “Capture”"),
  "kg.osiloskopta_ac": S("Osiloskopta aç", "Open in oscilloscope"),

  // ── 3F: Pil testi ekrani — arayuz3/app.js PL_METIN (+ parametreli metinler) ve ekran/pil.js
  "pl.baslik": S("Pil testi", "Battery test"),
  "pl.durdur": S("DURDUR", "STOP"),
  "pl.durdur_ipucu": S("Yükü hemen keser (p0). Test sürmüyorken de güvenli: kart yükü kapalı tutar.",
    "Cuts the load immediately (p0). Safe when no test is running too: the board keeps the load off."),
  "pl.okumalar": S("Pil testi okumaları", "Battery test readings"),
  "pl.gerilim": S("Gerilim", "Voltage"),
  "pl.akim": S("Akım", "Current"),
  "pl.kapasite": S("Kapasite", "Capacity"),
  "pl.enerji": S("Enerji", "Energy"),
  "pl.sure": S("Geçen süre", "Elapsed time"),
  "pl.kesme": S("Kesme gerilimi", "Cut-off voltage"),
  "pl.kaynak_canli": S("canlı (kartın D satırı)", "live (board D line)"),
  "pl.kaynak_sayac": S("kartın sayacı (her örnek)", "board counter (every sample)"),
  "pl.kaynak_sayac_bayat": S("kartın sayacı — {s} s önce okundu", "board counter — read {s} s ago"),
  "pl.kaynak_saat": S("kartın saati (son nokta)", "board clock (last point)"),
  "pl.kaynak_ayar": S("kartın ayarı", "board setting"),
  "pl.kaynak_kayit": S("kayıt (PİL oturumu)", "recording (battery session)"),
  "pl.kaynak_son": S("kartın son değeri", "board's last value"),
  "pl.yuk_kesik": S("yük kesik", "load off"),
  "pl.bilinmiyor": S("bilinmiyor — karta bağlanın", "unknown — connect to the board"),
  "pl.once": S("{sure} önce", "{sure} ago"),
  "pl.grafik": S("Deşarj eğrisi", "Discharge curve"),
  "pl.grafik_etiket": S("Pil deşarj eğrisi: gerilim ve akım", "Battery discharge curve: voltage and current"),
  "pl.x_eksen": S("Yatay eksen", "Horizontal axis"),
  "pl.eksen_zaman": S("zaman", "time"),
  "pl.eksen_mah": S("mAh (tarayıcı hesabı)", "mAh (browser-computed)"),
  "pl.grafik_klavye": S("Eğri: tekerlek ya da + / − yakınlaştırır, sürükle ya da ← → kaydırır, Home tümü; çift tık ya da A / B imleç koyar, Esc siler. R1, R2 … iç direnç (DCIR) ölçüm anları.",
    "Curve: the wheel or + / − zooms, drag or ← → pans, Home shows all; double-click or A / B places a cursor, Esc clears. R1, R2 … are internal-resistance (DCIR) measurements."),
  "pl.yukleniyor": S("eğri yükleniyor…", "loading curve…"),
  "pl.yuklenemedi": S("Eğri modülü yüklenemedi — kart yeniden başlıyor olabilir; birkaç saniye sonra sayfayı yenileyin. DURDUR ve okumalar çalışıyor.",
    "The curve module did not load — the board may be restarting; reload the page in a few seconds. STOP and the readings still work."),
  "pl.egri_yok": S("eğri yok — test başlayınca noktalar burada", "no curve — points appear here once a test starts"),
  "pl.egri_satir": S("Bu bağlantıda eğri yok: kart noktaları /pil ile yalnız kendi WiFi adresinden veriyor (USB / köprüde durum `p` satırından). Bitmiş testin eğrisi Kayıtlar'da.",
    "No curve on this connection: the board serves points via /pil only on its own Wi-Fi address (on USB / bridge the state comes from the `p` line). A finished test's curve is in Recordings."),
  "pl.egri_kayit": S("kaynak: kayıt #{no} (bu tarayıcıdaki eşitlenmiş kopya)", "source: recording #{no} (this browser's synced copy)"),
  "pl.egri_tarayici": S("kaynak: kartın /pil noktaları — bu tarayıcıda {n} nokta", "source: the board's /pil points — {n} points in this browser"),
  "pl.mah_bosluk": S("mAh ekseni kurulamadı: eğride boşluk var (kayıp nokta) — boşluğun üstünden integral uydurulmaz. Zaman ekseni gösteriliyor.",
    "The mAh axis could not be built: the curve has a gap (lost points) — no integral is invented across it. Showing the time axis."),
  "pl.mah_eksi": S("mAh ekseni kurulamadı: akım eksiye döndü (şarj / ters bağlantı). Zaman ekseni gösteriliyor.",
    "The mAh axis could not be built: the current went negative (charging / reversed). Showing the time axis."),
  "pl.mah_karsilastir": S("Eksen sonu {eksen} mAh (tarayıcı, 1 Hz noktalardan) · kartın sayacı {kart} mAh (her örnek)",
    "Axis end {eksen} mAh (browser, from 1 Hz points) · board counter {kart} mAh (every sample)"),
  "pl.okuma_dmah": S("ΔmAh", "ΔmAh"),
  "pl.okuma_aralik_mah": S("A–B mAh (tarayıcı)", "A–B mAh (browser)"),
  "pl.okuma_aralik_wh": S("A–B Wh (tarayıcı)", "A–B Wh (browser)"),
  "pl.imlec_sil": S("İmleçleri sil", "Clear cursors"),
  "pl.nokta_csv": S("Nokta CSV (bu tarayıcı)", "Point CSV (this browser)"),
  "pl.pil_csv": S("Pil CSV (kayıttan)", "Battery CSV (from recording)"),
  "pl.dcir": S("İç direnç (DCIR)", "Internal resistance (DCIR)"),
  "pl.dcir_son": S("Son ölçüm (kart, {n} ölçüm)", "Last measurement (board, {n} total)"),
  "pl.dcir_no": S("No", "No."),
  "pl.dcir_zaman": S("An", "Time"),
  "pl.dcir_ani": S("R ani", "R instant"),
  "pl.dcir_otr": S("R oturmuş", "R settled"),
  "pl.dcir_mah": S("mAh", "mAh"),
  "pl.dcir_yok": S("Henüz iç direnç ölçümü yok — kart her 5 dakikada bir ölçer.", "No internal-resistance measurement yet — the board measures every 5 minutes."),
  "pl.dcir_gorulmedi": S("“—” satırlar panel o sırada izlemediği için görülmedi; değerleri kartın kaydında (Kayıtlar'da aç).",
    "“—” rows were not seen because the panel was not watching; their values are in the board's recording (Open in Recordings)."),
  "pl.dcir_ipucu": S("Yük 200 ms kesilir; ani = 1.5 ms sonra, oturmuş = darbe sonunda. Mutlak değil, aynı pili tekrar ölçünce karşılaştırılabilir bir sağlık göstergesi. Canlıda mAh yoklama anında (≈).",
    "The load is cut for 200 ms; instant = after 1.5 ms, settled = at the end of the pulse. Not absolute — a health indicator comparable between runs on the same cell. Live mAh is at poll time (≈)."),
  "pl.parametreler": S("Test parametreleri", "Test parameters"),
  "pl.ocv": S("Açık devre gerilimi (OCV)", "Open-circuit voltage (OCV)"),
  "pl.dcir_aralik": S("DCIR aralığı", "DCIR interval"),
  "pl.dcir_aralik_deger": S("her {dk} dk · {ms} ms darbe", "every {dk} min · {ms} ms pulse"),
  "pl.dcir_sabit": S("DCIR aralığı ve darbesi kartta sabit (firmware sabiti; panelden değişmez, kapatılamaz).",
    "The DCIR interval and pulse are fixed on the board (firmware constant; cannot be changed or disabled from the panel)."),
  "pl.basla": S("Yeni test", "New test"),
  "pl.kesme_gir": S("Kesme gerilimi, V (0.5 … 38.5)", "Cut-off voltage, V (0.5 … 38.5)"),
  "pl.kesme_yer": S("kartta {v}", "board: {v}"),
  "pl.hazir": S("Hazır kesme değerleri", "Preset cut-off values"),
  "pl.hazir_liion": S("Li-ion 3.0 V", "Li-ion 3.0 V"),
  "pl.hazir_kursun": S("Kurşun-asit 12 V · 10.5 V", "Lead-acid 12 V · 10.5 V"),
  "pl.ad": S("Oturuma ad (isteğe bağlı)", "Session name (optional)"),
  "pl.ad_ipucu": S("Ad, kart PİL oturumunu açınca o oturuma yazılır (Kayıtlar'da görünür).",
    "The name is written to the battery session once the board opens it (shown in Recordings)."),
  "pl.ad_gonder": S("Adı yaz", "Set name"),
  "pl.baslat": S("Testi başlat", "Start test"),
  "pl.baslatiliyor": S("başlatılıyor…", "starting…"),
  "pl.sonuc": S("Son testin sonucu", "Last test result"),
  "pl.bitis_sebebi": S("Bitiş sebebi", "End reason"),
  "pl.kayitlarda_ac": S("Kayıtlar'da aç", "Open in Recordings"),
  "pl.kayit_yukleniyor": S("Kayıt bu tarayıcıdaki kopyadan açılıyor…", "Opening the recording from this browser's copy…"),
  "pl.kayit_esitleniyor": S("Kartın kaydı bu tarayıcıya eşitleniyor…", "Syncing the board's recording to this browser…"),
  "pl.kayit_bu_tarayicida_yok": S("Kayıt #{no} bu tarayıcıda yok — eğri /pil noktalarından. Tam kayıt için Kayıtlar'da aç (panel kartın adresinden açıldıysa eşitler).",
    "Recording #{no} is not in this browser — the curve is from /pil points. For the full recording open it in Recordings (syncs when the panel was opened from the board's address)."),
  "pl.kayit_hata": S("Kayıt #{no} açılamadı: {mesaj}", "Recording #{no} could not be opened: {mesaj}"),
  "pl.kayit_yok_neden": S("Bu test KAYDEDİLMİYOR: {neden}. Eğri ve sonuç yalnız bu tarayıcıda (CSV'yi indirin).",
    "This test is NOT being recorded: {neden}. The curve and result exist only in this browser (download the CSV)."),
  "pl.oturum_no": S("Kayıt #{no}", "Recording #{no}"),
  "pl.oturum_tahmin": S("Kayıt #{no} (başlangıcı görülmedi)", "Recording #{no} (start not seen)"),
  "pl.duyuru_bitti": S("Pil testi bitti: {durum}", "Battery test ended: {durum}"),
  "pl.kart_reddetti": S("Kart reddetti: {satir}", "The board refused: {satir}"),
  "pl.kart_kaydedilmiyor": S("Kart uyarısı: {satir}", "Board warning: {satir}"),
  "pl.hata_kesme": S("Kesme gerilimi 0.5 … 38.5 V arası bir sayı olmalı (Li-ion 3.0, kurşun-asit 10.5) — kart başkasını reddeder.",
    "The cut-off voltage must be a number between 0.5 … 38.5 V (Li-ion 3.0, lead-acid 10.5) — the board rejects anything else."),
  "pl.hata_kesme_yok": S("Kesme gerilimini girin (kartın ayarı henüz okunmadı).", "Enter the cut-off voltage (the board's setting has not been read yet)."),
  "pl.hata_kesme_onay": S("Kart {v} V kesmeyi onaylamadı — test BAŞLATILMADI (yanlış kesmeyle deşarj pili bitirebilir).",
    "The board did not confirm the {v} V cut-off — the test was NOT started (discharging with a wrong cut-off can ruin the cell)."),
  "pl.hata_kesme_farkli": S("Kart testi {kart} V kesmeyle başlattı, istenen {istenen} V — yük HEMEN kesildi (p0). Kesmeyi yeniden girip başlatın.",
    "The board started the test with a {kart} V cut-off, {istenen} V was requested — the load was cut IMMEDIATELY (p0). Re-enter the cut-off and start again."),
  "pl.hata_bagli_degil": S("Karta bağlı değil.", "Not connected to the board."),
  "pl.hata_gonderilemedi": S("Komut gönderilemedi: {mesaj}", "The command could not be sent: {mesaj}"),
  "pl.hata_ad_oturum": S("Oturum numarası henüz bilinmiyor — kart PİL oturumunu açınca ad yazılır.", "The session number is not known yet — the name is written once the board opens the battery session."),
  "pl.hata_ad_bos": S("Ad boş olamaz.", "The name cannot be empty."),
  "pl.hata_ad_karakter": S("Ad çift tırnak, ters bölü ya da denetim karakteri içeremez — kart bunları atar.",
    "The name cannot contain double quotes, backslashes or control characters — the board drops them."),
  "pl.hata_ad_uzun": S("Ad en çok {azami} bayt olabilir (şu an {bayt}); kart fazlasını keserdi.",
    "The name can be at most {azami} bytes (now {bayt}); the board would cut the rest."),
  "pl.hata_kayit_yok": S("Kayıt bu tarayıcıda yok.", "The recording is not in this browser."),
  "pl.hata_kayit_tur": S("#{no} bir pil testi oturumu değil.", "#{no} is not a battery test session."),
  "pl.hata_modul": S("modül yüklenemedi ({mesaj})", "module did not load ({mesaj})"),
  "pl.hata_depo": S("tarayıcı deposu okunamadı ({mesaj})", "browser storage could not be read ({mesaj})"),
  "pl.hata_esitleme": S("eşitlenemedi ({mesaj})", "could not sync ({mesaj})"),

  // ── 3G: Karsilastirma (ekran/karsilastir.js KR_METIN + Kayitlar listesindeki secim, kayitlar.js KL_KR_METIN)
  "kr.karsilastir": S("Karşılaştır", "Compare"),
  "kr.secim_temizle": S("Seçimi temizle", "Clear selection"),
  "kr.secim_bilgi": S("{n} kayıt seçildi (en az 2, en çok {azami})", "{n} selected (at least 2, at most {azami})"),
  "kr.secim_yok": S("Karşılaştırmak için kutuları işaretleyin (en az 2, en çok {azami} kayıt).",
    "Tick the boxes to compare (2 to {azami} recordings)."),
  "kr.sec": S("Karşılaştırmaya ekle: {ad}", "Add to comparison: {ad}"),
  "kr.sec_cikar": S("Karşılaştırmadan çıkar: {ad}", "Remove from comparison: {ad}"),
  "kr.sec_kartta": S("yalnız kartta — önce eşitleyin", "only on the board — sync it first"),
  "kr.sec_skop": S("osiloskop günlüğünün zaman grafiği yok", "an oscilloscope log has no time chart"),
  "kr.sec_bos": S("bu tarayıcıdaki kopyada çizilecek nokta yok", "this browser's copy has no points to draw"),
  "kr.sec_dolu": S("en çok 6 kayıt seçilebilir", "at most 6 recordings can be selected"),
  "kr.baslik": S("Karşılaştırma", "Comparison"),
  "kr.bos": S("Karşılaştırılacak kayıt seçilmedi. Kayıtlar listesinde en az 2, en çok 6 kaydın kutusunu işaretleyip “Karşılaştır”a basın.",
    "No recordings selected. In the Recordings list tick 2 to 6 recordings and press “Compare”."),
  "kr.kayitlara_git": S("Kayıtlar'a git", "Go to Recordings"),
  "kr.kayitlara_don": S("← Kayıtlar (seçimi değiştir)", "← Recordings (change selection)"),
  "kr.alt_baslik": S("{n} kayıt · {kanal} · {kip}", "{n} recordings · {kanal} · {kip}"),
  "kr.kanal": S("Büyüklük", "Quantity"),
  "kr.kanal_v": S("Gerilim (V)", "Voltage (V)"),
  "kr.kanal_i": S("Akım (A)", "Current (A)"),
  "kr.kanal_w": S("Güç (W)", "Power (W)"),
  "kr.x_eksen": S("Yatay eksen", "Horizontal axis"),
  "kr.kip_baslangic": S("başlangıçtan beri", "since start"),
  "kr.kip_saat": S("saat", "clock time"),
  "kr.kip_mah": S("mAh (yalnız pil testleri)", "mAh (battery tests only)"),
  "kr.tumu": S("Tümünü göster", "Show all"),
  "kr.imlec_sil": S("İmleçleri sil", "Clear cursors"),
  "kr.lejant": S("Kayıtlar ve çizgileri", "Recordings and their lines"),
  "kr.yukleniyor": S("Kayıtlar bu tarayıcıdaki kopyadan okunuyor…", "Reading the recordings from this browser's copy…"),
  "kr.cizilecek_yok": S("Bu eksende çizilecek kayıt yok — lejanttaki sebeplere bakın ya da başka bir eksen seçin.",
    "No recording can be drawn on this axis — see the reasons in the legend or choose another axis."),
  "kr.grafik_etiket": S("Karşılaştırma grafiği: {kanal}, yatay eksen {kip}", "Comparison chart: {kanal}, horizontal axis {kip}"),
  "kr.gezgin_etiket": S("Bütün aralık — pencereyi sürükleyerek taşıyın", "Whole range — drag the window to move it"),
  "kr.grafik_ipucu": S("Tekerlek ya da + / − yakınlaştırır, sürükle ya da ← → kaydırır, Home tümü; çift tık ya da A / B imleç koyar, Esc siler. Renk ve çizgi deseni yalnız kayıtları ayırır (4.–6. kayıt kesik çizgi).",
    "The wheel or + / − zooms, drag or ← → pans, Home shows all; double-click or A / B places a cursor, Esc clears. Colour and dash only tell recordings apart (recordings 4–6 are dashed)."),
  "kr.tahmini": S("yeniden başlamadan sonraki parçanın yeri tahmini (saat yok)", "the part after a restart is placed by estimate (no clock)"),
  "kr.mah_son": S("eksen sonu {mah} mAh (tarayıcı, noktalardan)", "axis end {mah} mAh (browser, from points)"),
  "kr.disari": S("bu eksende dışarıda — {sebep}", "left out on this axis — {sebep}"),
  "kr.yok": S("bu tarayıcıda yok — önce Kayıtlar'dan eşitleyin", "not in this browser — sync it from Recordings first"),
  "kr.bos_kayit": S("çizilecek nokta yok", "no points to draw"),
  "kr.disari_saatsiz": S("saat yok (kart saati almadan başlamış)", "no clock (the board started without the time)"),
  "kr.disari_saat_kismi": S("{eksik} / {toplam} noktanın saati bilinmiyor", "{eksik} of {toplam} points have no clock time"),
  "kr.disari_saat_geri": S("kartın saati kayıt sırasında geri gitti", "the board's clock went backwards during the recording"),
  "kr.disari_pil_degil": S("pil testi değil (mAh ekseni yalnız pil testlerinde)", "not a battery test (the mAh axis is for battery tests only)"),
  "kr.disari_mah_bosluk": S("eğride boşluk var — boşluğun üstünden integral uydurulmaz", "the curve has a gap — no integral is invented across it"),
  "kr.disari_mah_eksi": S("akım eksiye döndü (şarj / ters bağlantı)", "the current went negative (charging / reversed)"),
  "kr.okuma": S("İmleç okuması (kayıt başına)", "Cursor reading (per recording)"),
  "kr.imlec_yok": S("Grafikte çift tıklayın ya da A / B tuşuna basın: iki imleç arası her kayıt için ayrı okunur.",
    "Double-click the chart or press A / B: the span between the two cursors is read for every recording separately."),
  "kr.tablo_baslik": S("Kayıt başına imleç değerleri", "Cursor values per recording"),
  "kr.kayit": S("Kayıt", "Recording"),
  "kr.fark": S("Δ (B − A)", "Δ (B − A)"),
  "kr.ort": S("ort (A–B)", "mean (A–B)"),
  "kr.mah": S("mAh (A–B)", "mAh (A–B)"),
  "kr.wh": S("Wh (A–B)", "Wh (A–B)"),
  "kr.imlec_disarida": S("“—”: imleç o kaydın aralığının dışında. Δ, ort, mAh ve Wh yalnız iki imleç de kaydın içindeyse.",
    "“—”: the cursor is outside that recording. Δ, mean, mAh and Wh only when both cursors are inside it."),
  "kr.duyuru": S("{kayit}: A {a} · B {b}", "{kayit}: A {a} · B {b}"),
  "kr.disari_baslik": S("Dışa aktarma", "Export"),
  "kr.csv_tr": S("Birleşik CSV · Excel (TR)", "Combined CSV · Excel (TR)"),
  "kr.csv_en": S("Birleşik CSV · EN", "Combined CSV · EN"),
  "kr.disari_ipucu": S("Her kayıt kendi x ve değer sütunlarıyla yan yana; zamanlar ortak değil, ara değer üretilmez. Yalnız bu eksende çizilen kayıtlar.",
    "Each recording has its own x and value columns side by side; times are not shared and nothing is interpolated. Only the recordings drawn on this axis."),
  "kr.disari_hata": S("Dosya üretilemedi — sayfayı yenileyip yeniden deneyin.", "The file could not be built — reload the page and try again."),
  "kr.csv_onek": S("kayit", "rec"),
  "kr.fazla": S("Adreste {n} kayıt fazlaydı — en çok 6 kayıt karşılaştırılır, ilk 6'sı gösteriliyor.",
    "The address had {n} recordings too many — at most 6 are compared, the first 6 are shown."),
  "kr.gecersiz": S("Adresteki {n} parça anlaşılamadı, yok sayıldı.", "{n} parts of the address could not be read and were ignored."),
  "kr.depo_hata": S("Tarayıcı deposu okunamadı: {mesaj}", "Browser storage could not be read: {mesaj}"),

  // ── 3H-1: Ayarlar (app.js AY_METIN / AYAR_BOLUMLERI / DILLER; ekran/ayarlar.js AYE_METIN / KAL_ALANLARI)
  "ay.bolumler": S("Ayar bölümleri", "Settings sections"),
  "ay.b_baglanti": S("Bağlantı", "Connection"),
  "ay.b_ag": S("Ağ", "Network"),
  "ay.b_kalibrasyon": S("Kalibrasyon", "Calibration"),
  "ay.b_kal_gecmis": S("Kalibrasyon geçmişi", "Calibration history"),
  "ay.b_depolama": S("Depolama", "Storage"),
  "ay.b_dil_gorunum": S("Dil ve görünüm", "Language and appearance"),
  "ay.b_gelismis": S("Gelişmiş", "Advanced"),
  "ay.dil": S("Dil", "Language"),
  "ay.dil_tr": S("Türkçe", "Türkçe"),
  "ay.dil_en": S("English", "English"),
  "ay.dil_ipucu": S("Seçim bu tarayıcıda saklanır ve hemen uygulanır (sayfa yenilenmez). Sayılar iki dilde de nokta ondalıkla yazılır — ölçüm aleti alışkanlığı; CSV'nin Excel-TR biçimi ayrıca virgül kullanır.",
    "Stored in this browser and applied at once (no reload). Numbers use a decimal point in both languages — the instrument convention; the Excel-TR CSV format still uses a comma."),
  "ay.dil_eksik": S("Panelin eski bölümlerindeki bazı metinler henüz yalnız Türkçe; o bölümler yeniden yazıldıkça sözlüğe giriyor.",
    "Some texts in the older parts of the panel are still Turkish only; they move into the dictionary as those parts are rewritten."),
  "ay.mod_yuklenemedi": S("Ayarların bu bölümü yüklenemedi (modül inmedi) — kart yeniden başlıyor olabilir; birkaç saniye sonra sayfayı yenileyin.",
    "This settings section could not be loaded (module did not arrive) — the board may be restarting; reload the page in a few seconds."),
  "ay.yenile": S("Yenile", "Refresh"),
  "ay.yukleniyor": S("Okunuyor…", "Reading…"),
  "ay.kal_baslik": S("Kalibrasyon geçmişi", "Calibration history"),
  "ay.kal_salt": S("Salt okunur. Geçmişe kayıt kartta eklenir (Konsol'dan k komutları ya da kayıt başlarken kendiliğinden); bu panel geçmişi değiştirmez.",
    "Read-only. Entries are added on the board (k commands from the Console, or automatically when a recording starts); this panel does not change the history."),
  "ay.kal_kaynak_kart": S("Kaynak: kartın kalibrasyon geçmişi (şu anki durum).", "Source: the board's calibration history (current state)."),
  "ay.kal_kaynak_yerel": S("Kaynak: bu tarayıcıdaki kopya — kart akışı {kimlik}, son eşitleme {zaman}. Kartın şu anki geçmişi farklı olabilir.",
    "Source: this browser's copy — board stream {kimlik}, last sync {zaman}. The board's current history may differ."),
  "ay.kal_neden": S("Karttan okunmadı: {neden}", "Not read from the board: {neden}"),
  "ay.kal_neden_imza": S("kart imzalı istek istiyor (tarayıcı eşleştirmesi henüz yok)", "the board requires signed requests (browser pairing not available yet)"),
  "ay.kal_neden_yok": S("kart kalibrasyon geçmişi vermedi (HTTP {kod})", "the board returned no calibration history (HTTP {kod})"),
  "ay.kal_neden_ag": S("karta ulaşılamadı ({mesaj})", "the board could not be reached ({mesaj})"),
  "ay.kal_neden_bozuk": S("kartın yanıtı okunamadı", "the board's reply could not be read"),
  "ay.kal_neden_usb": S("USB bağlantısında bu uç yok — kartın adresinden açın", "not available over USB — open the panel from the board's address"),
  "ay.kal_neden_demo": S("demo kipinde gerçek kart yok", "there is no real board in demo mode"),
  "ay.kal_neden_taban": S("panel kartın kendi adresinden açılmadı (Bağlantı'da başka bir kart adresi yazılı)", "the panel is not opened from the board's own address (another board address is set under Connection)"),
  "ay.kal_hic": S("Kalibrasyon geçmişi yok: kart vermedi ve bu tarayıcıda kopya yok. Kayıtlar'dan eşitlemek geçmişin kopyasını da getirir.",
    "No calibration history: the board did not provide one and this browser has no copy. Syncing in Recordings also brings a copy of the history."),
  "ay.kal_ozet": S("{adet} / {azami} kayıt · kartın şu anki değerleri: {etkin}", "{adet} / {azami} entries · the board's current values: {etkin}"),
  "ay.kal_etkin_no": S("{no} numaralı kayıt", "entry {no}"),
  "ay.kal_taslak": S("Kartın şu anki değerleri geçmişte YOK (taslak): bir sonraki kayıt başlarken kendiliğinden eklenir ya da Konsol'dan kaydedilir.",
    "The board's current values are NOT in the history (draft): they are added automatically when the next recording starts, or saved from the Console."),
  "ay.kal_dolu": S("Geçmiş dolmak üzere ({adet} / {azami}) — dolunca yeni değerler numara alamaz; eski kayıt silinmez.",
    "The history is almost full ({adet} / {azami}) — once full, new values get no number; old entries are not deleted."),
  "ay.kal_tablo": S("Kalibrasyon geçmişi kayıtları, yeniden eskiye", "Calibration history entries, newest first"),
  "ay.kal_no": S("No", "No"),
  "ay.kal_tarih": S("Tarih", "Date"),
  "ay.kal_tur": S("Tür", "Type"),
  "ay.kal_kaynak": S("Kaynak", "Source"),
  "ay.kal_not": S("Not", "Note"),
  "ay.kal_durum": S("Durum", "State"),
  "ay.kal_etkin": S("etkin — kartın şu anki değerleri", "active — the board's current values"),
  "ay.kal_degerler": S("Değerler", "Values"),
  "ay.kal_deger_baslik": S("{no} numaralı kaydın değerleri", "Values of entry {no}"),
  "ay.kal_alan": S("Alan", "Field"),
  "ay.kal_deger": S("Değer", "Value"),
  "ay.kal_saatsiz": S("saat yok (açılış {acilis})", "no clock (boot {acilis})"),
  "ay.kd_normal_n": S("NORMAL · bölücü oranı", "NORMAL · divider ratio"),
  "ay.kd_normal_pga": S("NORMAL · ADC aralığı (V)", "NORMAL · ADC range (V)"),
  "ay.kd_normal_kazanc": S("NORMAL · kazanç düzeltmesi", "NORMAL · gain correction"),
  "ay.kd_normal_sifir_ham": S("NORMAL · sıfır (ham kod)", "NORMAL · zero (raw code)"),
  "ay.kd_normal_tau": S("NORMAL · süzgeç zaman sabiti", "NORMAL · filter time constant"),
  "ay.kd_yuksek_n": S("YÜKSEK · bölücü oranı", "HIGH · divider ratio"),
  "ay.kd_yuksek_pga": S("YÜKSEK · ADC aralığı (V)", "HIGH · ADC range (V)"),
  "ay.kd_yuksek_kazanc": S("YÜKSEK · kazanç düzeltmesi", "HIGH · gain correction"),
  "ay.kd_yuksek_sifir_ham": S("YÜKSEK · sıfır (ham kod)", "HIGH · zero (raw code)"),
  "ay.kd_yuksek_tau": S("YÜKSEK · süzgeç zaman sabiti", "HIGH · filter time constant"),
  "ay.kd_i_ofset": S("Akım · sıfır (ham kod)", "Current · zero (raw code)"),
  "ay.kd_i_pga": S("Akım · ADC aralığı (V)", "Current · ADC range (V)"),
  "ay.kd_sont_ohm": S("Şönt (Ω)", "Shunt (Ω)"),
  "ay.kd_i_duzeltme": S("Akım · kazanç düzeltmesi", "Current · gain correction"),
  "ay.kd_sebeke_hz": S("Şebeke frekansı (Hz; 0 = DC)", "Mains frequency (Hz; 0 = DC)"),
  "ay.kd_faz0": S("Faz kalibrasyonu NORMAL (µs)", "Phase calibration NORMAL (µs)"),
  "ay.kd_faz1": S("Faz kalibrasyonu YÜKSEK (µs)", "Phase calibration HIGH (µs)"),
  "ay.depo_baslik": S("Bu tarayıcıdaki kayıt kopyaları", "Recording copies in this browser"),
  "ay.kota_baslik": S("Tarayıcı depolaması", "Browser storage"),
  "ay.kota": S("Tarayıcı depolama kullanımı", "Browser storage usage"),
  "ay.kota_metin": S("{kullanilan} / {kota} kullanılıyor (%{yuzde})", "{kullanilan} of {kota} used ({yuzde}%)"),
  "ay.kota_guvensiz": S("Tarayıcı kota ve kalıcı depolama bilgisini yalnız güvenli bağlamda (https ya da localhost) verir; panel kartın http:// adresinden açık. Kopyalar yine burada saklanır ama tarayıcı yer gerekince silebilir.",
    "The browser reports quota and persistent storage only in a secure context (https or localhost); the panel is open from the board's http:// address. Copies are still kept here, but the browser may delete them when it needs space."),
  "ay.kota_yok": S("Bu tarayıcı depolama kotasını bildirmiyor.", "This browser does not report its storage quota."),
  "ay.kalici": S("Kalıcı depolama", "Persistent storage"),
  "ay.kalici_acik": S("açık — tarayıcı yer gerekince bu kopyaları kendiliğinden silmez", "on — the browser will not delete these copies on its own when it needs space"),
  "ay.kalici_kapali": S("kapalı — tarayıcı yer gerekince kopyaları silebilir", "off — the browser may delete the copies when it needs space"),
  "ay.kalici_bilinmiyor": S("bilinmiyor", "unknown"),
  "ay.kalici_iste": S("Kalıcı depolama iste", "Request persistent storage"),
  "ay.kalici_verildi": S("Tarayıcı kalıcı depolamayı verdi.", "The browser granted persistent storage."),
  "ay.kalici_reddedildi": S("Tarayıcı kalıcı depolamayı vermedi (çoğu tarayıcı sık açılan ya da yer imine eklenen sitelere verir).",
    "The browser did not grant persistent storage (most browsers grant it to sites you open often or bookmark)."),
  "ay.kalici_hata": S("İstek yapılamadı: {mesaj}", "The request failed: {mesaj}"),
  "ay.depo_tablo": S("Bu tarayıcıdaki kart akışları ve boyutları", "Board streams in this browser and their sizes"),
  "ay.depo_akis": S("Kart akışı", "Board stream"),
  "ay.depo_boyut": S("Boyut", "Size"),
  "ay.depo_oturum": S("Oturum", "Sessions"),
  "ay.depo_son_sira": S("Son sıra", "Last seq."),
  "ay.depo_son": S("Son eşitleme", "Last sync"),
  "ay.depo_arsiv": S("Arşiv", "Archive"),
  "ay.depo_durum": S("Durum", "State"),
  "ay.depo_islem": S("İşlem", "Action"),
  "ay.arsiv_acik": S("açık — kart onay alıyor", "on — the board receives acknowledgements"),
  "ay.arsiv_kapali": S("kapalı", "off"),
  "ay.arsiv_ipucu": S("Arşiv seçimi Kayıtlar'dan değiştirilir (açmak iki aşamalı onay ister).", "The archive choice is changed in Recordings (turning it on needs a two-step confirmation)."),
  "ay.kayitlara_git": S("Kayıtlar'a git", "Go to Recordings"),
  "ay.depo_bos": S("Bu tarayıcıda kayıt kopyası yok.", "There are no recording copies in this browser."),
  "ay.depo_kart_bilinmiyor": S("Kart bu panelden sorulamadı: en yeni açılan akış “bu kart” sayıldı.", "The board could not be asked from this panel: the most recently opened stream is taken as “this board”."),
  "ay.depo_hata": S("Tarayıcı deposu okunamadı: {mesaj}", "Browser storage could not be read: {mesaj}"),
  "ay.gel_baslik": S("Sürüm ve tanı", "Version and diagnostics"),
  "ay.fw": S("Firmware", "Firmware"),
  "ay.fw_yok": S("açılış afişi görülmedi — sürüm kartın açılış afişinden okunur (panel kart açıldıktan sonra bağlandıysa görülmez)",
    "the boot banner was not seen — the version is read from the board's boot banner (not seen if the panel connected after boot)"),
  "ay.panel": S("Panel sürümü (arayüz görüntüsü)", "Panel version (interface image)"),
  "ay.panel_metin": S("{surum} · {dosya} dosya · {boyut} gzip", "{surum} · {dosya} files · {boyut} gzip"),
  "ay.panel_yok": S("bu sunucu görüntü künyesi vermiyor ({neden}) — geliştirme sunucusu ya da köprü olabilir", "this server provides no image manifest ({neden}) — it may be a development server or the bridge"),
  "ay.tasiyici": S("Bağlantı yolu", "Connection path"),
  "ay.tas_seri": S("USB (Web Serial)", "USB (Web Serial)"),
  "ay.tas_akis": S("WiFi / köprü (akış)", "WiFi / bridge (stream)"),
  "ay.tas_demo": S("Demo — sahte kart", "Demo — simulated board"),
  "ay.konsol_ipucu": S("Ham komut konsolu Konsol ekranında.", "The raw command console is on the Console screen."),
  "ay.konsola_git": S("Konsol'a git", "Go to Console"),
  "ay.sifirla_baslik": S("Tarayıcı ayarları", "Browser settings"),
  "ay.sifirla_aciklama": S("Bu tarayıcıda saklanan panel ayarları ({n} anahtar): görünüm, dil, grafik tercihleri, kart adresi, arşiv seçimleri. Sıfırlamak yalnız bunları siler ve sayfayı yeniden yükler; kayıt kopyaları (Depolama) ve kartın kendi ayarları değişmez.",
    "Panel settings stored in this browser ({n} keys): appearance, language, chart preferences, board address, archive choices. Resetting deletes only these and reloads the page; the recording copies (Storage) and the board's own settings do not change."),
  "ay.sifirla": S("Tarayıcı ayarlarını sıfırla", "Reset browser settings"),
  "ay.sifirla_eminim": S("Eminim, {n} anahtarı sil", "Yes, delete {n} keys"),
  "ay.sifirla_uyari": S("Arşiv seçimleri de silinir: bu tarayıcı karta yeniden “aldım” onayı göndermez (güvenli yön).",
    "Archive choices are deleted too: this browser stops sending “received” acknowledgements to the board (the safe direction)."),
  "ay.sifirla_yok": S("Bu tarayıcıda saklanan panel ayarı yok.", "No panel settings are stored in this browser."),

  // ── 3D: kayit durumu (kayit_yonet.h KDR_*) ve plan durumu (kayit_plan.h PLAN_*)
  "kayit.durum.0": S("kayıt belleği taranıyor", "scanning recording memory"),
  "kayit.durum.1": S("kayıt yok (hazır)", "not recording (ready)"),
  "kayit.durum.2": S("kaydediyor", "recording"),
  "kayit.durum.3": S("kayıt belleği dolu (eşitle + onayla)", "recording memory full (sync + acknowledge)"),
  "kayit.durum.4": S("yer bekliyor (onay gelince sürer)", "waiting for space (resumes on acknowledgement)"),
  "kayit.durum.5": S("kayıt hatası", "recording error"),
  "kayit.durum.bilinmeyen": S("bilinmeyen kayıt durumu ({kod})", "unknown recording state ({kod})"),
  "plan.durum.0": S("yok", "none"),
  "plan.durum.1": S("bekliyor", "waiting"),
  "plan.durum.2": S("sürüyor", "running"),
  "plan.durum.3": S("bitti", "finished"),
  "plan.durum.4": S("atlandı (o an başka kayıt vardı)", "skipped (another recording was running)"),
  "plan.durum.5": S("kaçırıldı (kart kapalıydı)", "missed (the board was off)"),
  "plan.durum.6": S("saat bekleniyor (NTP)", "waiting for the clock (NTP)"),
  "plan.durum.7": S("başlatılamadı", "could not start"),
  "plan.durum.bilinmeyen": S("bilinmeyen plan durumu ({kod})", "unknown schedule state ({kod})"),
});

/** Sozlukten metin; ATMAZ (dosya basindaki kurallar). */
export function ceviri(anahtar, dil = "tr", degiskenler = null) {
  const a = typeof anahtar === "string" ? anahtar : String(anahtar);
  const g = Object.prototype.hasOwnProperty.call(SOZLUK, a) ? SOZLUK[a] : null;
  if (!g) return a;
  const d = dil === "en" ? "en" : "tr";
  const obur = d === "en" ? "tr" : "en";
  let m = g[d] || g[obur] || a;
  if (degiskenler && typeof degiskenler === "object") {
    m = m.replace(/\{([A-Za-z0-9_]+)\}/g, (tam, ad) => (
      Object.prototype.hasOwnProperty.call(degiskenler, ad) ? String(degiskenler[ad]) : tam));
  }
  return m;
}

/** Kod ailesinden metin: onek+kod varsa o, yoksa onek+"bilinmeyen" ({kod}). ATMAZ. */
export function ceviriKod(onek, kod, dil = "tr") {
  const a = `${onek}${kod}`;
  if (Object.prototype.hasOwnProperty.call(SOZLUK, a)) return ceviri(a, dil);
  return ceviri(`${onek}bilinmeyen`, dil, { kod });
}
