// W3 (EU32) — KAYITLAR ZINCIRININ TR/EN METINLERI: Kayitlar listesi (kl.), kayit gorunumu (kg.), Karsilastirma (kr.).
//
// ACILIS sozlugunden (sozluk.js) AYRI (EU30 deseni, sozluk_es.js / sozluk_pc.js gibi): ekran/kayit_gorunum.js
// bu dosyayi STATIK ice aktarir; Kayitlar (kayitlar.js) ve Karsilastirma (karsilastir.js) kayit_gorunum.js'i
// zaten statik aldigi icin sozluk YALNIZ bu ekranlardan biri ilk acilinca iner — acilis, #/skop, #/pil ve
// eslesmis tarayicinin acilisi indirmez (tasarim/2026-10-02-alt-proje-3-panel.md EU32).
// Burada YALNIZ bu uc dosyanin kullandigi anahtarlar var; baska bir ekranin da kullandigi kl. metinleri
// (or. kl.vazgec, kl.sil — Ayarlar > Depolama) acilis sozlugunde kalir.
// Kurallar sozluk.js'inkiyle AYNI (test/sozluk_kayit.test.js): her anahtarda bos olmayan tr VE en, yer
// tutucular iki dilde ayni, kullanilmayan anahtar yok, zincirin kullandigi her anahtar var, sozluklar ayrik.

import { ceviri, sozluktenCeviri } from "./sozluk.js";

const S = (tr, en) => Object.freeze({ tr, en });

export const SOZLUK_KAYIT = Object.freeze({
  // ── Kayitlar listesi (ekran/kayitlar.js KL_METIN, TUR_METIN; kayit_gorunum.js NEREDE_METIN)
  "kl.baslik": S("Kayıtlar", "Recordings"),
  "kl.liste": S("Liste", "List"),
  "kl.esitle": S("Eşitle", "Sync"),
  "kl.esitleniyor": S("Eşitleniyor…", "Syncing…"),
  "kl.yenile": S("Yenile", "Refresh"),
  "kl.ilerleme": S("{boyut} alındı", "{boyut} received"),
  "kl.neden_taban": S("Panel başka bir adresteki karta bağlanıyor (Ayarlar → Kart adresi). Kayıtlar yalnız panel kartın KENDİ adresinden açıldığında eşitlenir — paneli kartın adresinden açın. Bu tarayıcıdaki kopyalar aşağıda.",
    "The panel talks to a board at another address (Settings → Board address). Recordings sync only when the panel is opened from the board's OWN address — open the panel from the board's address. Copies in this browser are listed below."),
  "kl.neden_usb": S("USB (seri) bağlantısında kayıt eşitlenmez: kayıt verisi seri yoldan gelmiyor. Paneli kartın adresinden açın; PC'de köprü (kopru/pc.py) kayıtları WiFi'den kendisi arşivler. Bu tarayıcıdaki kopyalar aşağıda.",
    "Recordings do not sync over USB (serial): recording data is not served on the serial path. Open the panel from the board's address; on a PC the bridge (kopru/pc.py) archives the recordings over WiFi itself. Copies in this browser are listed below."),
  "kl.neden_demo": S("Demo kipinde kayıt eşitlenmez. Bu tarayıcıdaki kopyalar aşağıda.",
    "Recordings do not sync in demo mode. Copies in this browser are listed below."),
  "kl.neden_yok": S("Bu sayfayı sunan yer kart değil (geliştirme sunucusu ya da köprünün yerel ağ adresi): eşitleme yalnız kartın kendi adresinden. PC arşivi yalnız köprünün çalıştığı bilgisayarda (olcum.localhost:8770) görünür.",
    "This page is not served by the board (a development server or the bridge's local-network address): sync works only from the board's own address. The PC archive is shown only on the computer running the bridge (olcum.localhost:8770)."),
  "kl.neden_imza": S("Kart imzalı istek istiyor ve bu tarayıcıyı tanımıyor: Ayarlar → Eşleştirme'den eşleştirin. PC'de köprü (kopru/pc.py) kendi eşleşmesiyle arşivler. Bu tarayıcıdaki kopyalar aşağıda.",
    "The board requires signed requests and does not recognise this browser: pair it under Settings → Pairing. On a PC the bridge (kopru/pc.py) archives with its own pairing. Copies in this browser are listed below."),
  "kl.neden_mesgul": S("Kart meşgul ya da kayıt hazır değil ({mesaj}) — biraz sonra Yenile'ye basın.",
    "The board is busy or recording is not ready ({mesaj}) — press Refresh in a moment."),
  "kl.neden_host": S("Kart bu adresi reddetti ({mesaj}) — paneli kartın kendi adresinden (IP ya da olcum.local) açın.",
    "The board rejected this address ({mesaj}) — open the panel from the board's own address (IP or olcum.local)."),
  "kl.neden_ag": S("Karta ulaşılamadı ({mesaj}) — kartın açık ve aynı ağda olduğunu denetleyip Yenile'ye basın.",
    "The board could not be reached ({mesaj}) — check that the board is on and on the same network, then press Refresh."),
  "kl.neden_bozuk": S("Kartın yanıtı okunamadı ({mesaj}); bu tarayıcıya hiçbir şey yazılmadı.",
    "The board's reply could not be read ({mesaj}); nothing was written to this browser."),
  "kl.neden_hata": S("Eşitleme yapılamadı ({mesaj}) — Yenile'ye basın.", "Sync failed ({mesaj}) — press Refresh."),
  "kl.neden_akis": S("Kartın kayıt akışı beklenenden farklı ({mesaj}); bu kopyaya eklenmedi. Yenile'ye basın.",
    "The board's recording stream is not what was expected ({mesaj}); nothing was appended to this copy. Press Refresh."),
  "kl.neden_kilit": S("Eşitleme zaten sürüyor ({mesaj}).", "A sync is already running ({mesaj})."),
  "kl.neden_depo": S("Tarayıcı deposu açılamadı ({mesaj}) — özel pencerede değilseniz bu site için tarayıcı depolamasına izin verin.",
    "Browser storage could not be opened ({mesaj}) — unless this is a private window, allow site storage for this page."),
  "kl.sonuc_yeni": S("{yeni} yeni kayıt alındı (son sıra {son}).", "{yeni} new record(s) received (last sequence {son})."),
  "kl.sonuc_guncel": S("Yeni kayıt yok — bu tarayıcı güncel (son sıra {son}).",
    "No new records — this browser is up to date (last sequence {son})."),
  "kl.onay_gitti": S("Karta onay gönderildi ve kart doğruladı: bu tarayıcı arşiv sayılıyor.",
    "Acknowledgement sent and confirmed by the board: this browser counts as an archive."),
  "kl.onay_dogrulanmadi": S("Onay gönderildi ama kart doğrulamadı — sonraki eşitlemede yeniden denenir.",
    "Acknowledgement sent but not confirmed by the board — it will be retried on the next sync."),
  "kl.onay_bagli_degil": S("Arşiv seçili ama panel karta bağlı değil: onay gönderilmedi (bağlanınca sonraki eşitlemede gider).",
    "Archive is selected but the panel is not connected to the board: no acknowledgement was sent (it goes with the next sync once connected)."),
  "kl.bekleyen": S("Kartta {bekleyen} sıra daha görünüyor ama veri gelmedi; yeni kayıt gelince boşluk olarak geçilir.",
    "The board shows {bekleyen} more sequence(s) but no data came; it is skipped as a gap when new records arrive."),
  "kl.kal_hata": S("Kalibrasyon geçmişi alınamadı ({hata}) — Yenile'ye basın.", "Calibration history could not be fetched ({hata}) — press Refresh."),
  "kl.arsiv": S("Bu tarayıcı arşivdir (karta “aldım” onayı gönder)",
    "This browser is an archive (send “received” acknowledgements to the board)"),
  "kl.arsiv_aciklama": S("Kapalıyken (varsayılan) kart bu kopyayı yedek SAYMAZ ve onun için hiçbir kaydı silmez. Açarsanız kart, yer gerekince bu tarayıcıya kopyalanmış eski kayıtları silebilir — o zaman tek kopya burada kalır. Yalnız kalıcı arşiv olarak kullandığınız tarayıcıda açın.",
    "When off (default) the board does NOT count this copy as a backup and deletes nothing because of it. When on, the board may delete old recordings already copied here when it needs space — the only copy then stays here. Turn it on only in a browser you use as a permanent archive."),
  "kl.kart_ozet": S("Kart: {oturum} oturum · doluluk %{doluluk} · eşitlenmemiş %{onaysiz}",
    "Board: {oturum} session(s) · {doluluk}% full · {onaysiz}% not synced"),
  "kl.kart_yok": S("Kartın dizini alınamadı — “nerede” yalnız bu tarayıcıyı gösteriyor.",
    "The board's index is unavailable — “where” only reflects this browser."),
  "kl.ara": S("Ara: ad, etiket, not, numara", "Search: name, tag, note, number"),
  "kl.tur_sec": S("Tür süzgeci", "Type filter"),
  "kl.nerede_sec": S("Nerede süzgeci", "Location filter"),
  "kl.tur_hepsi": S("Bütün türler", "All types"),
  "kl.tur_olcum": S("Ölçüm", "Measurement"),
  "kl.tur_ayrinti": S("Ölçüm (ayrıntılı)", "Measurement (detailed)"),
  "kl.tur_pil": S("Pil testi", "Battery test"),
  "kl.tur_skop": S("Osiloskop", "Oscilloscope"),
  "kl.tur_bilinmeyen": S("Bilinmeyen", "Unknown"),
  "kl.nerede_hepsi": S("Her yer", "Anywhere"),
  "kl.nerede_kart": S("yalnız kartta", "on the board only"),
  "kl.nerede_tarayici": S("yalnız bu tarayıcıda", "in this browser only"),
  "kl.nerede_ikisi": S("ikisinde", "in both"),
  "kl.nerede_telefon": S("yalnız bu telefonda", "on this phone only"),
  "kl.durum_kayitta": S("kaydediliyor", "recording"),
  "kl.durum_acik": S("açık", "open"),
  "kl.durum_bitti": S("bitti", "finished"),
  "kl.eksik": S("eksik kopya", "incomplete copy"),
  "kl.eski_kart": S("eski kart kopyası", "old board copy"),
  "kl.basi_silindi": S("başı silinmiş", "start deleted"),
  "kl.saatsiz": S("saat yok", "no clock"),
  "kl.bos": S("Henüz kayıt yok — Canlı'da “Başlat” ile bir kayıt açın.", "No recordings yet — start one with “Start” on the Live screen."),
  "kl.bos_suzgec": S("Süzgece uyan kayıt yok.", "No recordings match the filter."),
  "kl.nokta_kisa": S("nokta", "points"),
  "kl.ornek_kisa": S("örnek", "samples"),
  "kl.yakalama_kisa": S("yakalama", "captures"),
  "kl.kopyalar": S("Bu tarayıcıdaki kopyalar", "Copies in this browser"),
  "kl.kopya_satir": S("Kart akışı {kimlik} · {oturum} oturum · {boyut} · son sıra {son}",
    "Board stream {kimlik} · {oturum} session(s) · {boyut} · last sequence {son}"),
  "kl.arsiv_onay_uyari": S("Arşiv açılırsa karta “aldım” onayı gider ve kart, yer gerekince bu kayıtları silebilir — tek kopya bu tarayıcıda kalır. Emin misiniz?",
    "If archiving is on, “received” acknowledgements go to the board and it may delete these recordings when it needs space — the only copy stays in this browser. Are you sure?"),
  "kl.arsiv_eminim": S("Eminim, bu tarayıcı arşiv", "Yes, this browser is the archive"),
  // 5P (K10): telefonda yerel kopya Android'in (esitler, onaylar, sifirlar)
  "kl.telefon_kopya": S("Kopya bu telefonda; eşitlemeyi ve karta onayı uygulama yürütür. Boyut ve sıfırlama: Ayarlar › Bu telefon › Eşitleme.",
    "The copy is on this phone; the app runs syncing and acknowledgements. Size and reset: Settings › This phone › Sync."),
  "kl.yalniz_kartta": S("Bu kayıt yalnız kartta — önce eşitleyin.", "This recording is only on the board — sync first."),
  "kl.bulunamadi": S("Kayıt bulunamadı (#{oturum}).", "Recording not found (#{oturum})."),
  "kl.listeye_don": S("← Kayıtlar", "← Recordings"),
  "kl.yukleniyor": S("Yükleniyor…", "Loading…"),
  "kl.ipucu": S("Satıra dokunun: kayıt açılır. Eşitleme yalnız okur; kartta hiçbir şey silinmez.",
    "Tap a row to open the recording. Syncing only reads; nothing is deleted on the board."),

  // ── kayit gorunumu (ekran/kayit_gorunum.js KG_METIN)
  "kg.geri": S("← Kayıtlar", "← Recordings"),
  "kg.rapor": S("Rapor", "Report"),
  "kg.rapor_kapat": S("Kayda dön", "Back to recording"),
  "kg.yazdir": S("Yazdır / PDF", "Print / PDF"),
  "kg.baslik": S("Kayıt", "Recording"),
  "kg.rapor_baslik": S("Kayıt raporu", "Recording report"),
  "kg.grafik": S("Grafik", "Chart"),
  "kg.gerilim": S("Gerilim", "Voltage"),
  "kg.sag_eksen": S("Sağ eksen:", "Right axis:"),
  "kg.olcek_sol": S("Sol ölçek:", "Left scale:"),
  "kg.olcek_sag": S("Sağ ölçek:", "Right scale:"),
  "kg.olcek_oto": S("Otomatik", "Auto"),
  "kg.olcek_sifir": S("0'dan", "From 0"),
  "kg.olcek_elle": S("Elle", "Manual"),
  "kg.olcek_en_az": S("En az", "Min"),
  "kg.olcek_en_cok": S("En çok", "Max"),
  "kg.akim": S("Akım", "Current"),
  "kg.guc": S("Güç", "Power"),
  "kg.yok": S("yok", "none"),
  "kg.zarf": S("En düşük / en yüksek", "Minimum / maximum"),
  "kg.tumu": S("Tümünü göster", "Show all"),
  "kg.imlec_sil": S("İmleçleri kaldır", "Clear cursors"),
  "kg.grafik_etiket": S("Kaydın zaman grafiği: gerilim, akım ve güç", "Time chart of the recording: voltage, current and power"),
  "kg.gezgin_etiket": S("Kaydın tamamı ve görünen pencere", "Whole recording and the visible window"),
  "kg.grafik_ipucu": S("Çift tıkla: imleç koy (önce A, sonra B) · sürükle: kaydır · tekerlek ya da iki parmak: yakınlaştır · A / B tuşları imleci fareye koyar · alttaki şeritte pencereyi taşı.",
    "Double-click: place a cursor (A first, then B) · drag: pan · wheel or two fingers: zoom · A / B keys put a cursor at the mouse · move the window on the strip below."),
  "kg.imlec_yok": S("İmleç yok — grafikte çift tıklayın.", "No cursor — double-click on the chart."),
  "kg.notlar": S("Notlar", "Notes"),
  "kg.genel_not": S("genel", "general"),
  "kg.not_ipucu": S("Nota tıklayın: grafik o ana gider.", "Click a note: the chart jumps to that moment."),
  "kg.pil": S("Pil testi özeti", "Battery test summary"),
  "kg.yakalamalar": S("Osiloskop yakalamaları", "Oscilloscope captures"),
  "kg.skop_ipucu": S("Yakalamanın grafiği osiloskop ekranında; burada her yakalama CSV olarak indirilebilir.",
    "The capture chart is on the oscilloscope screen; each capture can be downloaded as CSV here."),
  "kg.daha_fazla": S("Daha fazla göster ({kalan} kaldı)", "Show more ({kalan} left)"),
  "kg.veri_yok": S("Bu kayıtta çizilecek veri yok (oturum hemen kapandı ya da yalnız başlığı eşitlendi). Eşitleme sürüyorsa listeden Yenile'ye basın.",
    "This recording has no data to draw (the session closed at once or only its header was synced). If a sync is running, press Refresh in the list."),
  "kg.disari": S("Dışa aktar", "Export"),
  "kg.disari_ipucu": S("Excel (TR): noktalı virgül + ondalık virgül. EN: virgül + ondalık nokta. Ham .kyt: kartın baytları aynen (kopru/kayit_bicim.py okur). Dosyalar bu tarayıcıda üretilir; kart yorulmaz.",
    "Excel (TR): semicolon + decimal comma. EN: comma + decimal point. Raw .kyt: the board's bytes unchanged (read by kopru/kayit_bicim.py). Files are built in this browser; the board is not loaded."),
  "kg.okuma_dt": S("Δt (B − A)", "Δt (B − A)"),
  "kg.okuma_ort": S("ort", "mean"),
  "kg.okuma_min": S("en düşük", "min"),
  "kg.okuma_maks": S("en yüksek", "max"),
  "kg.okuma_fark": S("Δ", "Δ"),
  "kg.okuma_mah": S("Yük A–B", "Charge A–B"),
  "kg.okuma_wh": S("Enerji A–B", "Energy A–B"),
  "kg.okuma_sure": S("Ölçülen süre A–B", "Measured time A–B"),
  "kg.tur": S("Tür", "Type"),
  "kg.no": S("Oturum", "Session"),
  "kg.baslangic": S("Başlangıç", "Start"),
  "kg.saat_yok": S("saat yok (açılıştan beri)", "no clock (since boot)"),
  "kg.sure": S("Süre", "Duration"),
  "kg.nokta": S("Nokta", "Points"),
  "kg.ornek": S("Örnek", "Samples"),
  "kg.yakalama": S("Yakalama", "Captures"),
  "kg.hiz": S("Kayıt aralığı", "Recording interval"),
  "kg.her_ornek": S("her örnek (ayrıntılı kip)", "every sample (detailed mode)"),
  "kg.firmware": S("Firmware", "Firmware"),
  "kg.kal_no": S("Kalibrasyon", "Calibration"),
  "kg.durum": S("Durum", "Status"),
  "kg.acik": S("bitmedi (sürüyor ya da sonu eşitlenmedi)", "not finished (running or end not synced)"),
  "kg.nerede": S("Nerede", "Where"),
  "kg.uyari_tahmini": S("Kart {sayi} kez saatsiz yeniden başladı: o parçaların başlangıca uzaklığı bilinmiyor, grafikte öncekinin ardına (araya boşluk) konuldu.",
    "The board restarted {sayi} time(s) without a clock: the distance of those parts from the start is unknown; on the chart they follow the previous part (with a gap)."),
  "kg.uyari_eksik": S("Kartta bu kaydın daha yeni verisi var — eşitleyin.", "The board has newer data for this recording — sync."),
  "kg.uyari_eski": S("Bu kayıt eski bir kart akışından (kart biçimlenmiş ya da değişmiş); kartta yok.",
    "This recording is from an old board stream (board was formatted or replaced); it is not on the board."),
  "kg.sutun_no": S("No", "No"),
  "kg.sutun_zaman": S("Zaman", "Time"),
  "kg.sutun_ornek": S("Örnek", "Samples"),
  "kg.sutun_hz": S("Hz", "Hz"),
  "kg.sutun_tdiv": S("Zaman/böl", "Time/div"),
  "kg.sutun_tetik": S("Tetik", "Trigger"),
  "kg.sutun_tam": S("Durum", "Status"),
  "kg.evet": S("evet", "yes"),
  "kg.hayir": S("hayır", "no"),
  "kg.eksik_yakalama": S("eksik (parça eşitlenmemiş)", "incomplete (part not synced)"),
  "kg.csv_tr": S("CSV · Excel (TR)", "CSV · Excel (TR)"),
  "kg.csv_en": S("CSV · EN", "CSV · EN"),
  "kg.ayrinti_tr": S("Ayrıntılı CSV · Excel (TR)", "Detailed CSV · Excel (TR)"),
  "kg.ayrinti_en": S("Ayrıntılı CSV · EN", "Detailed CSV · EN"),
  "kg.pil_tr": S("Pil CSV · Excel (TR)", "Battery CSV · Excel (TR)"),
  "kg.pil_en": S("Pil CSV · EN", "Battery CSV · EN"),
  "kg.ham": S("Ham kayıt (.kyt)", "Raw recording (.kyt)"),
  "kg.skop_csv": S("CSV", "CSV"),
  "kg.disari_hata": S("Dosya üretilemedi — sayfayı yenileyip yeniden deneyin.", "The file could not be built — reload the page and try again."),
  "kg.osiloskopta_ac": S("Osiloskopta aç", "Open in oscilloscope"),

  // ── Karsilastirma (ekran/karsilastir.js KR_METIN + Kayitlar listesindeki secim, kayitlar.js KL_KR_METIN)
  "kr.karsilastir": S("Karşılaştır", "Compare"),
  "kr.secim_temizle": S("Seçimi temizle", "Clear selection"),
  "kr.secim_bilgi": S("{n} kayıt seçildi (en az 2, en çok {azami})", "{n} selected (at least 2, at most {azami})"),
  "kr.secim_yok": S("Karşılaştırmak için kutuları işaretleyin (en az 2, en çok {azami} kayıt).",
    "Tick the boxes to compare (2 to {azami} recordings)."),
  "kr.sec": S("Karşılaştırmaya ekle: {ad}", "Add to comparison: {ad}"),
  "kr.sec_cikar": S("Karşılaştırmadan çıkar: {ad}", "Remove from comparison: {ad}"),
  "kr.sec_kartta": S("yalnız kartta — önce eşitleyin", "only on the board — sync it first"),
  "kr.sec_skop": S("osiloskop günlüğünün zaman grafiği yok", "an oscilloscope log has no time chart"),
  "kr.sec_bos": S("bu tarayıcıdaki kopyada çizilecek nokta yok", "this browser's copy has no points to draw"),
  "kr.sec_dolu": S("en çok 6 kayıt seçilebilir", "at most 6 recordings can be selected"),
  "kr.baslik": S("Karşılaştırma", "Comparison"),
  "kr.bos": S("Karşılaştırılacak kayıt seçilmedi. Kayıtlar listesinde en az 2, en çok 6 kaydın kutusunu işaretleyip “Karşılaştır”a basın.",
    "No recordings selected. In the Recordings list tick 2 to 6 recordings and press “Compare”."),
  "kr.kayitlara_git": S("Kayıtlar'a git", "Go to Recordings"),
  "kr.kayitlara_don": S("← Kayıtlar (seçimi değiştir)", "← Recordings (change selection)"),
  "kr.alt_baslik": S("{n} kayıt · {kanal} · {kip}", "{n} recordings · {kanal} · {kip}"),
  "kr.kanal": S("Büyüklük", "Quantity"),
  "kr.kanal_v": S("Gerilim (V)", "Voltage (V)"),
  "kr.kanal_i": S("Akım (A)", "Current (A)"),
  "kr.kanal_w": S("Güç (W)", "Power (W)"),
  "kr.x_eksen": S("Yatay eksen", "Horizontal axis"),
  "kr.kip_baslangic": S("başlangıçtan beri", "since start"),
  "kr.kip_saat": S("saat", "clock time"),
  "kr.kip_mah": S("mAh (yalnız pil testleri)", "mAh (battery tests only)"),
  "kr.tumu": S("Tümünü göster", "Show all"),
  "kr.imlec_sil": S("İmleçleri sil", "Clear cursors"),
  "kr.lejant": S("Kayıtlar ve çizgileri", "Recordings and their lines"),
  "kr.yukleniyor": S("Kayıtlar bu tarayıcıdaki kopyadan okunuyor…", "Reading the recordings from this browser's copy…"),
  "kr.cizilecek_yok": S("Bu eksende çizilecek kayıt yok — lejanttaki sebeplere bakın ya da başka bir eksen seçin.",
    "No recording can be drawn on this axis — see the reasons in the legend or choose another axis."),
  "kr.grafik_etiket": S("Karşılaştırma grafiği: {kanal}, yatay eksen {kip}", "Comparison chart: {kanal}, horizontal axis {kip}"),
  "kr.gezgin_etiket": S("Bütün aralık — pencereyi sürükleyerek taşıyın", "Whole range — drag the window to move it"),
  "kr.grafik_ipucu": S("Tekerlek ya da + / − yakınlaştırır, sürükle ya da ← → kaydırır, Home tümü; çift tık ya da A / B imleç koyar, Esc siler. Renk ve çizgi deseni yalnız kayıtları ayırır (4.–6. kayıt kesik çizgi).",
    "The wheel or + / − zooms, drag or ← → pans, Home shows all; double-click or A / B places a cursor, Esc clears. Colour and dash only tell recordings apart (recordings 4–6 are dashed)."),
  "kr.tahmini": S("yeniden başlamadan sonraki parçanın yeri tahmini (saat yok)", "the part after a restart is placed by estimate (no clock)"),
  "kr.mah_son": S("eksen sonu {mah} mAh (tarayıcı, noktalardan)", "axis end {mah} mAh (browser, from points)"),
  "kr.disari": S("bu eksende dışarıda — {sebep}", "left out on this axis — {sebep}"),
  "kr.yok": S("bu tarayıcıda yok — önce Kayıtlar'dan eşitleyin", "not in this browser — sync it from Recordings first"),
  "kr.bos_kayit": S("çizilecek nokta yok", "no points to draw"),
  "kr.disari_saatsiz": S("saat yok (kart saati almadan başlamış)", "no clock (the board started without the time)"),
  "kr.disari_saat_kismi": S("{eksik} / {toplam} noktanın saati bilinmiyor", "{eksik} of {toplam} points have no clock time"),
  "kr.disari_saat_geri": S("kartın saati kayıt sırasında geri gitti", "the board's clock went backwards during the recording"),
  "kr.disari_pil_degil": S("pil testi değil (mAh ekseni yalnız pil testlerinde)", "not a battery test (the mAh axis is for battery tests only)"),
  "kr.disari_mah_bosluk": S("eğride boşluk var — boşluğun üstünden integral uydurulmaz", "the curve has a gap — no integral is invented across it"),
  "kr.disari_mah_eksi": S("akım eksiye döndü (şarj / ters bağlantı)", "the current went negative (charging / reversed)"),
  "kr.okuma": S("İmleç okuması (kayıt başına)", "Cursor reading (per recording)"),
  "kr.imlec_yok": S("Grafikte çift tıklayın ya da A / B tuşuna basın: iki imleç arası her kayıt için ayrı okunur.",
    "Double-click the chart or press A / B: the span between the two cursors is read for every recording separately."),
  "kr.tablo_baslik": S("Kayıt başına imleç değerleri", "Cursor values per recording"),
  "kr.kayit": S("Kayıt", "Recording"),
  "kr.fark": S("Δ (B − A)", "Δ (B − A)"),
  "kr.ort": S("ort (A–B)", "mean (A–B)"),
  "kr.mah": S("mAh (A–B)", "mAh (A–B)"),
  "kr.wh": S("Wh (A–B)", "Wh (A–B)"),
  "kr.imlec_disarida": S("“—”: imleç o kaydın aralığının dışında. Δ, ort, mAh ve Wh yalnız iki imleç de kaydın içindeyse.",
    "“—”: the cursor is outside that recording. Δ, mean, mAh and Wh only when both cursors are inside it."),
  "kr.duyuru": S("{kayit}: A {a} · B {b}", "{kayit}: A {a} · B {b}"),
  "kr.disari_baslik": S("Dışa aktarma", "Export"),
  "kr.csv_tr": S("Birleşik CSV · Excel (TR)", "Combined CSV · Excel (TR)"),
  "kr.csv_en": S("Birleşik CSV · EN", "Combined CSV · EN"),
  "kr.disari_ipucu": S("Her kayıt kendi x ve değer sütunlarıyla yan yana; zamanlar ortak değil, ara değer üretilmez. Yalnız bu eksende çizilen kayıtlar.",
    "Each recording has its own x and value columns side by side; times are not shared and nothing is interpolated. Only the recordings drawn on this axis."),
  "kr.disari_hata": S("Dosya üretilemedi — sayfayı yenileyip yeniden deneyin.", "The file could not be built — reload the page and try again."),
  "kr.csv_onek": S("kayit", "rec"),
  "kr.fazla": S("Adreste {n} kayıt fazlaydı — en çok 6 kayıt karşılaştırılır, ilk 6'sı gösteriliyor.",
    "The address had {n} recordings too many — at most 6 are compared, the first 6 are shown."),
  "kr.gecersiz": S("Adresteki {n} parça anlaşılamadı, yok sayıldı.", "{n} parts of the address could not be read and were ignored."),
  "kr.depo_hata": S("Tarayıcı deposu okunamadı: {mesaj}", "Browser storage could not be read: {mesaj}"),
});

/** Kayitlar zinciri metni: once bu sozluk, yoksa sozluk.js (ortak kl. / kod aileleri). ceviri() gibi ATMAZ. */
export function ceviriKayit(anahtar, dil = "tr", degiskenler = null) {
  const a = typeof anahtar === "string" ? anahtar : String(anahtar);
  return Object.prototype.hasOwnProperty.call(SOZLUK_KAYIT, a)
    ? sozluktenCeviri(SOZLUK_KAYIT, a, dil, degiskenler) : ceviri(a, dil, degiskenler);
}
