// Telefona ozel metinler (TR/EN). ortak/src/sozluk.js'ten AYRI (sozluk_pc.js deseni): ortak sozluk
// degistirilmez; burada yalniz telefon ekranlarinin metinleri durur. Anahtarlar "m." ile baslar.
// Kurallar (test/sozluk.test.js): her anahtarda bos olmayan tr VE en, yer tutucular iki dilde ayni,
// kullanilmayan anahtar yok, kullanilan her anahtar var, ortak sozlukle cakisma yok.
// ceviriMobil: once bu sozluk, yoksa ortak sozluk — HICBIR ZAMAN ATMAZ.

import { ceviri, sozluktenCeviri } from "@ortak/sozluk.js";

const S = (tr, en) => Object.freeze({ tr, en });

export const SOZLUK_MOBIL = Object.freeze({
  "m.uygulama": S("Ölçüm Kartı", "Measurement Board"),
  // ── Karti bul (ekran/KartBul.vue)
  "m.kb.baslik": S("Kartı bul", "Find the board"),
  "m.kb.elle": S("Adres (isteğe bağlı)", "Address (optional)"),
  "m.kb.elle_ornek": S("örn. 192.168.1.20", "e.g. 192.168.1.20"),
  "m.kb.ara": S("Ara", "Search"),
  "m.kb.araniyor": S("Aranıyor…", "Searching…"),
  "m.kb.adres": S("Adres", "Address"),
  "m.kb.kimlik": S("Kart kimliği", "Board ID"),
  "m.kb.kaynak": S("Nasıl bulundu", "Found via"),
  "m.kb.sure": S("Süre", "Time"),
  "m.kb.sure_ms": S("{ms} ms", "{ms} ms"),
  "m.kb.txt": S("Duyurudaki kimlik", "Announced ID"),
  "m.kb.txt_uyuyor": S("kartınkiyle aynı", "matches the board"),
  "m.kb.txt_uymuyor": S("UYMUYOR", "DOES NOT MATCH"),
  "m.kb.duyurular": S("Ağdaki duyurular", "Network announcements"),
  "m.sonuc.tamam": S("yanıt verdi", "responded"),
  "m.sonuc.zaman_asimi": S("yanıt yok", "no response"),
  "m.sonuc.baglanti": S("bağlanılamadı", "could not connect"),
  "m.sonuc.cleartext": S("şifresiz bağlantı engellendi", "cleartext connection blocked"),
  "m.sonuc.yanit_gecersiz": S("kart değil", "not a board"),
  "m.sonuc.govde_buyuk": S("yanıt çok büyük", "response too large"),
  "m.sonuc.wifi_yok": S("Wi-Fi yok", "no Wi-Fi"),
  "m.sonuc.ozel_degil": S("yerel adres değil", "not a local address"),
  "m.sonuc.ad_cozulmedi": S("ad çözülemedi", "name not resolved"),
  "m.sonuc.mesgul": S("meşgul", "busy"),
  "m.sonuc.ic_hata": S("hata", "error"),
  "m.ws.engellendi": S("engellendi", "blocked"),
  "m.ws.bos": S("içeriksiz", "empty"),
  "m.ws.gecti": S("GEÇTİ — kapı delik", "PASSED — gate is open"),
  // ── Baglanti (ekran/Baglanti.vue) — gecici, 5C'de kabuga tasinir
  "m.bg.baslik": S("Bağlantı", "Connection"),
  "m.bg.baglan": S("Bağlan", "Connect"),
  "m.bg.durum": S("Durum", "Status"),
  "m.bg.durum_bagli": S("eşleşmiş, bağlı", "paired, connected"),
  "m.bg.durum_eslesmemis": S("kart bulundu, eşleşmemiş", "board found, not paired"),
  "m.bg.durum_bulunamadi": S("kart bulunamadı", "board not found"),
  "m.bg.durum_kimlik": S("bu adresteki kart eşleştiğin kart değil", "the board at this address is not the paired one"),
  "m.bg.esles": S("Bu kartla eşleş", "Pair with this board"),
  "m.bg.dene": S("İmzalı isteği dene", "Try a signed request"),
  "m.bg.imzali_tamam": S("İmzalı istek geçti: {oturum} oturum", "Signed request succeeded: {oturum} session(s)"),
  "m.bg.kaldir": S("Eşleşmeyi kaldır", "Remove pairing"),
  "m.bg.kaldirildi": S("Eşleşme kartta ve telefonda kaldırıldı.", "Pairing removed on the board and the phone."),
  "m.bg.kaldirildi_yerel": S("Eşleşme yalnız telefonda kaldırıldı (karta ulaşılamadı).", "Pairing removed on the phone only (board unreachable)."),
  "m.bg.kaldirildi_belirsiz": S(
    "Eşleşme telefonda kaldırıldı. Kart silmeyi onaylamadı: kayıt kartta kalmış olabilir — kartın panelinden ya da USB'den silin.",
    "Pairing removed on the phone. The board did not confirm the removal: the entry may still be on the board — delete it from the board's panel or over USB.",
  ),
  "m.bg.kasa_bozuk": S(
    "Telefondaki eşleşme kaydı bozuk ya da okunamıyor. Eşleşmeyi kaldırıp yeniden eşleş.",
    "The pairing record on the phone is damaged or unreadable. Remove the pairing and pair again.",
  ),
  "m.bg.hata": S("Olmadı ({tur}).", "Failed ({tur})."),
  "m.ol.durdur": S("DURDUR süre ölçümü (20 tekrar)", "STOP timing (20 runs)"),
  "m.ol.durdur_sonuc": S("DURDUR {tekrar} tekrar: {basari} başarılı · en az {enaz} ms · ortanca {ortanca} ms · en çok {encok} ms", "STOP {tekrar} runs: {basari} ok · min {enaz} ms · median {ortanca} ms · max {encok} ms"),
  "m.ol.pbkdf2": S("PBKDF2 süre ölçümü", "PBKDF2 timing"),
  "m.ol.suruyor": S("Ölçülüyor…", "Measuring…"),
  "m.ol.pbkdf2_sonuc": S("PBKDF2 {tur} tur: en az {enaz} ms · ortanca {ortanca} ms · en çok {encok} ms", "PBKDF2 {tur} rounds: min {enaz} ms · median {ortanca} ms · max {encok} ms"),
  "m.ay.gorunum": S("Görünüm", "Appearance"),
  "m.ay.dil": S("Dil", "Language"),
  "m.ay.dil_tr": S("Türkçe", "Türkçe"),
  "m.ay.dil_en": S("English", "English"),
  "m.ay.tema": S("Tema", "Theme"),
  "m.ay.tema_sistem": S("Sistem", "System"),
  "m.ay.tema_koyu": S("Koyu", "Dark"),
  "m.ay.tema_acik": S("Açık", "Light"),
  "m.ws.dugme": S("WebView ağ sınaması", "WebView network self-test"),
  "m.ws.suruyor": S("Sınanıyor…", "Testing…"),
  "m.kb.denenenler": S("Denenen adresler", "Addresses tried"),
  "m.kb.kaynak_elle": S("elle girilen", "entered by hand"),
  "m.kb.kaynak_onbellek": S("son bilinen adres", "last known address"),
  "m.kb.kaynak_ad": S("olcum.local adı", "olcum.local name"),
  "m.kb.kaynak_nsd": S("ağ duyurusu", "network announcement"),
  "m.kb.kaynak_ap": S("kartın kendi ağı", "the board's own network"),
  "m.kb.hata_bulunamadi": S("Kart bu ağda bulunamadı.", "The board was not found on this network."),
  "m.kb.hata_kimlik": S("Bu adresteki kart, eşleştiğin kart değil.", "The board at this address is not the one you paired with."),
  "m.kb.hata_bicim": S("Adres yanlış yazılmış.", "The address is not written correctly."),
  "m.kb.hata_ozel_degil": S("Yalnız yerel ağ adresleri kabul edilir.", "Only local network addresses are accepted."),
  "m.kb.hata_ad_izinsiz": S("Ad yerine kartın IP adresini yaz.", "Enter the board's IP address instead of a name."),
  "m.kb.hata_wifi_yok": S("Wi-Fi kapalı ya da bağlı değil.", "Wi-Fi is off or not connected."),
  "m.kb.hata_bilinmeyen": S("Beklenmeyen bir hata oldu.", "An unexpected error occurred."),
  // ── Eslestirme (ekran/Esles.vue, ekran/esles_durum.js)
  "m.es.baslik": S("Kartla eşleştir", "Pair with the board"),
  "m.es.kart_dogru_mu": S("Bu, eşleştirmek istediğin kart mı? Kimliği kontrol et.", "Is this the board you want to pair with? Check its ID."),
  "m.es.ad": S("Bu telefonun adı (kartta görünür)", "Name of this phone (shown on the board)"),
  "m.es.ad_varsayilan": S("Telefon", "Phone"),
  "m.es.parola": S("Kartın WEB parolası — Wi-Fi parolası DEĞİL", "The board's WEB password — NOT the Wi-Fi password"),
  "m.es.parola_not": S(
    "Parola yalnız eşleştirme sırasında kullanılır; telefonda saklanmaz ve ağa çıkmaz.",
    "The password is used only while pairing; it is not stored on the phone and never leaves it.",
  ),
  "m.es.gonder": S("Eşleştir", "Pair"),
  "m.es.suruyor": S("Eşleştiriliyor…", "Pairing…"),
  "m.es.suruyor_not": S("Bu birkaç saniye sürebilir.", "This may take a few seconds."),
  "m.es.tamam": S("Eşleştirildi.", "Paired."),
  "m.es.hata_parola_kisa": S("Web parolası en az 12 karakter olmalı.", "The web password must be at least 12 characters."),
  "m.es.hata_parola_yanlis": S(
    "Parola yanlış. Kartın WEB parolasını gir (Wi-Fi parolası değil).",
    "Wrong password. Enter the board's WEB password (not the Wi-Fi password).",
  ),
  "m.es.hata_parola_yok": S(
    "Kartta web parolası yok ya da çok kısa. Önce kartta en az 12 karakterlik bir web parolası belirle.",
    "The board has no web password, or it is too short. Set a web password of at least 12 characters on the board first.",
  ),
  "m.es.hata_bekle": S("Çok fazla yanlış deneme. Biraz bekleyip yeniden dene.", "Too many wrong attempts. Wait a little and try again."),
  "m.es.hata_bekle_saniye": S(
    "Çok fazla yanlış deneme. {saniye} saniye sonra yeniden dene.",
    "Too many wrong attempts. Try again in {saniye} seconds.",
  ),
  "m.es.hata_liste_dolu": S(
    "Kartın cihaz listesi dolu (8). Kullanılmayan bir cihazı karttan kaldır.",
    "The board's device list is full (8). Remove an unused device from the board.",
  ),
  "m.es.hata_sure_doldu": S("Eşleştirme süresi doldu. Yeniden dene.", "Pairing timed out. Try again."),
  "m.es.hata_kart_sahte": S(
    "Bu kart parolayı bilmiyor — senin kartın olmayabilir. Eşleştirme YAPILMADI. Kart senin değilse kartının web parolasını değiştir.",
    "This board does not know the password — it may not be your board. Pairing was NOT done. If it is not your board, change your board's web password.",
  ),
  "m.es.hata_tur": S(
    "Kart güvensiz bir ayar bildirdi; sahte olabilir. Eşleştirme YAPILMADI.",
    "The board reported an unsafe setting; it may be fake. Pairing was NOT done.",
  ),
  "m.es.hata_kart_gecersiz": S("Karttan anlaşılmayan bir yanıt geldi.", "The board sent a response that was not understood."),
  "m.es.hata_kimlik": S(
    "Bu adresteki kart değişti. Kartı yeniden bul ve kimliğini kontrol et.",
    "The board at this address has changed. Find the board again and check its ID.",
  ),
  "m.es.hata_ag": S("Karta ulaşılamadı. Wi-Fi bağlantısını kontrol et.", "Could not reach the board. Check the Wi-Fi connection."),
  "m.es.hata_kasa": S("Anahtar telefona kaydedilemedi. Eşleştirme geri alındı.", "The key could not be saved on the phone. Pairing was undone."),
  "m.es.hata_ad": S("Ad 1–24 bayt olmalı.", "The name must be 1–24 bytes."),
  "m.es.hata_bagli_degil": S("Önce kartı bul.", "Find the board first."),
  "m.es.hata_zaten_esli": S("Bu telefon zaten eşleşmiş.", "This phone is already paired."),
  "m.es.hata_bilinmeyen": S("Eşleştirme sırasında beklenmeyen bir hata oldu.", "An unexpected error occurred while pairing."),
  // ── Kabuk (App.vue): sekmeler
  "m.sk.gezinme": S("Gezinme", "Navigation"),
  "m.sk.durum": S("Durum", "Status"),
  "m.sk.canli": S("Canlı", "Live"),
  "m.sk.kayitlar": S("Kayıtlar", "Recordings"),
  "m.sk.ayarlar": S("Ayarlar", "Settings"),
  // ── ACIL DURDUR seridi (bilesen/DurdurSeridi.vue, A8–A11)
  "m.dd.dugme": S("DURDUR", "STOP"),
  "m.dd.etiket": S("Acil durdur: yükü kes", "Emergency stop: cut the load"),
  "m.dd.gonderiliyor": S("Durdurma gönderiliyor…", "Sending stop…"),
  "m.dd.durduruldu": S("Durduruldu: kart yükü kesti.", "Stopped: the board cut the load."),
  "m.dd.baska_yanit": S(
    "Başka bir adres yanıt verdi — kartın durduğu doğrulanamadı. Yükü kontrol et, yeniden dene.",
    "Another address answered — could not confirm the board stopped. Check the load, try again.",
  ),
  "m.dd.ulasilamadi": S(
    "ULAŞILAMADI — kart durdurulamadı. Yükü elle kes, sonra yeniden dene.",
    "UNREACHABLE — the board was not stopped. Cut the load by hand, then try again.",
  ),
  // ── Durum (ekran/Durum.vue, ekran/durum_gorunum.js)
  "m.dr.bu_agda": S("Bu ağda", "On this network"),
  "m.dr.ulasilamiyor": S("Ulaşılamıyor", "Unreachable"),
  "m.dr.araniyor": S("Kart aranıyor…", "Looking for the board…"),
  "m.dr.eslesmemis": S("Kart bulundu, bu telefon eşleşmemiş", "Board found, this phone is not paired"),
  "m.dr.kasa_bozuk": S("Telefondaki eşleşme kaydı okunamıyor", "The pairing record on the phone is unreadable"),
  "m.dr.esles": S("Eşleş (Ayarlar)", "Pair (Settings)"),
  "m.dr.yeniden": S("Yeniden dene", "Try again"),
  "m.dr.son_gorulme": S("son görülme", "last seen"),
  "m.dr.once_sn": S("{n} sn önce", "{n} s ago"),
  "m.dr.once_dk": S("{n} dk önce", "{n} min ago"),
  "m.dr.once_sa": S("{n} sa önce", "{n} h ago"),
  "m.dr.kayit_yok": S("Kayıt yok", "Not recording"),
  "m.dr.kayit_bilinmiyor": S("Kayıt durumu bilinmiyor", "Recording state unknown"),
  "m.dr.oturum": S("Oturum", "Session"),
  "m.dr.bellek": S("Kart belleği", "Board memory"),
  "m.dr.esitlenmemis": S("Eşitlenmemiş", "Not synced"),
  "m.dr.yuzde": S("%{n}", "{n}%"),
  "m.dr.pil_testi": S("Pil testi sürüyor", "Battery test running"),
  "m.dr.skop_gunlugu": S("Osiloskop günlüğü", "Scope log"),
  "m.dr.pil_salt_okuma": S(
    "Pil testi karttan ya da panelden yönetilir. Acil durumda DURDUR.",
    "The battery test is controlled from the board or the panel. In an emergency use STOP.",
  ),
  // ── Kayit esitlemesi (ekran/durum_gorunum.js esitlemeGorunumu, ekran/EsitlemeAyar.vue; A20–A23)
  "m.es.yok": S("Eşitleme kullanılamıyor.", "Sync is unavailable."),
  "m.es.kart_yok": S("Kart bu ağda değil: kayıtlar eşitlenmiyor.", "Board not on this network: recordings are not syncing."),
  "m.es.bekliyor": S("Kayıtlar eşitlenecek…", "Recordings will sync…"),
  "m.es.kopya_suruyor": S("Kayıtlar telefona alınıyor…", "Copying recordings to the phone…"),
  "m.es.tamam_simdi": S("Telefondaki kopya güncel.", "The copy on the phone is up to date."),
  "m.es.kopya_tamam": S("Telefondaki kopya güncel · {dk} dk önce", "The copy on the phone is up to date · {dk} min ago"),
  "m.es.kopya_geride": S("Telefondaki kopya kartın gerisinde.", "The copy on the phone is behind the board."),
  "m.es.bekleyen": S(
    "Kartta daha yeni kayıt var ama henüz okunamadı; sonraki eşitlemede alınacak.",
    "The board has newer records that could not be read yet; they will be fetched next time.",
  ),
  "m.es.bosluk": S("Kartta silinmiş kayıtlar var: kopyada boşluk kaldı.", "Some records were already erased on the board: the copy has a gap."),
  "m.es.simdi": S("Şimdi eşitle", "Sync now"),
  "m.es.kopya_hata_bagli_degil": S("Eşitlenemedi: kart bağlı değil.", "Sync failed: board not connected."),
  "m.es.kopya_hata_ag": S("Eşitlenemedi: karta ulaşılamadı. Yeniden denenecek.", "Sync failed: board unreachable. Will retry."),
  "m.es.hata_mesgul": S("Başka bir eşitleme sürüyor.", "Another sync is running."),
  "m.es.hata_kopya": S("Telefondaki kopya kartla uyuşmuyor.", "The copy on the phone does not match the board."),
  "m.es.hata_depo": S("Eşitlenemedi: telefona yazılamadı (depolama dolu olabilir).", "Sync failed: could not write to the phone (storage may be full)."),
  "m.es.hata_yanit": S("Eşitlenemedi: karttan bozuk veri geldi. Yeniden denenecek.", "Sync failed: corrupt data from the board. Will retry."),
  "m.es.hata_silinmis": S("Eşitlenemedi: bu telefon kartta silinmiş. Yeniden eşleştir.", "Sync failed: this phone was removed on the board. Pair again."),
  "m.es.hata_genel": S("Eşitlenemedi ({tur}).", "Sync failed ({tur})."),
  "m.es.sifirla_oner": S(
    "Kart biçimlendirilmiş ya da kopya bozulmuş olabilir. Ayarlar › Eşitleme › Kopyayı sıfırla ile baştan alınır.",
    "The board may have been formatted or the copy damaged. Use Settings › Sync › Reset copy to start over.",
  ),
  "m.ay.esitleme": S("Eşitleme", "Sync"),
  "m.es.onay": S("Bu telefon da onaylasın", "Let this phone acknowledge too"),
  "m.es.onay_acik": S("Açık", "On"),
  "m.es.onay_kapali": S("Kapalı", "Off"),
  "m.es.onay_not": S(
    "Açarsan kart, PC'nin henüz almadığı kayıtları silebilir. Arşivin PC'deyse kapalı bırak.",
    "If you turn this on, the board may erase records the PC has not fetched yet. Leave it off if your archive is on the PC.",
  ),
  "m.es.depolama": S("Telefondaki kopya", "Copy on the phone"),
  "m.es.depolama_yok": S("Kart bilinmiyor", "Board unknown"),
  "m.es.sifirla": S("Kopyayı sıfırla", "Reset copy"),
  "m.es.sifirla_eminim": S("Emin misin? Kopya silinecek — yeniden dokun", "Sure? The copy will be deleted — tap again"),
  "m.es.sifirla_not": S(
    "Yalnız telefondaki kopya silinir; karttaki kayıtlara dokunulmaz ve sonraki eşitlemede yeniden alınır.",
    "Only the copy on the phone is deleted; records on the board are untouched and are fetched again on the next sync.",
  ),
  "m.es.sifirla_hata": S("Sıfırlanamadı ({tur}).", "Could not reset ({tur})."),
  "m.es.sifirlandi": S("Kopya silindi.", "Copy deleted."),
  // ── Bildirimler (ekran/BildirimAyar.vue, ekran/bildirim_gorunum.js; 5E-4)
  "m.ay.bildirim": S("Bildirimler", "Notifications"),
  "m.bl.ayar": S("Bildirim ayarı", "Notification setup"),
  "m.bl.zarf_var": S("Karttan alındı", "Fetched from the board"),
  "m.bl.zarf_yok": S("Alınmadı — uygulamayı kartın ağında aç", "Not fetched — open the app on the board's network"),
  "m.bl.kartta_ayarsiz": S(
    "Kartta internet bildirimi ayarlı değil (kartın USB'sinden ayarlanır).",
    "Internet notifications are not set up on the board (configured over the board's USB).",
  ),
  "m.bl.kart_yok": S("Kart bilinmiyor — önce kartla eşleş.", "Board unknown — pair with the board first."),
  "m.bl.yenile": S("Karttan yenile", "Refresh from the board"),
  "m.bl.yenileniyor": S("Karttan alınıyor…", "Fetching from the board…"),
  "m.bl.yenile_tamam": S("Bildirim ayarı karttan alındı.", "Notification setup fetched from the board."),
  "m.bl.hata_bagli_degil": S("Kart bu ağda değil: ayar alınamadı.", "Board not on this network: setup could not be fetched."),
  "m.bl.hata_ag": S("Karta ulaşılamadı. Yeniden dene.", "Could not reach the board. Try again."),
  "m.bl.hata_silinmis": S("Bu telefon kartta silinmiş. Yeniden eşleştir.", "This phone was removed on the board. Pair again."),
  "m.bl.hata_zarf": S(
    "Karttan gelen ayar bu telefonun anahtarıyla açılmadı. Eşleşmeyi kaldırıp yeniden eşleş.",
    "The setup from the board could not be opened with this phone's key. Remove the pairing and pair again.",
  ),
  "m.bl.hata_adres": S(
    "Kartın verdiği sunucu adresi güvenli (mqtts://) değil: bağlanılmayacak. Karttaki ayarı düzelt.",
    "The server address from the board is not secure (mqtts://): will not connect. Fix the setting on the board.",
  ),
  "m.bl.hata_genel": S("Olmadı ({tur}).", "Failed ({tur})."),
  "m.bl.izin": S("Bildirim izni", "Notification permission"),
  "m.bl.izin_var": S("Verildi", "Granted"),
  "m.bl.izin_yok": S("Verilmedi", "Not granted"),
  "m.bl.izin_iste": S("İzin ver", "Grant permission"),
  "m.bl.izin_not": S(
    "Kayıt bitti, pil testi bitti, bellek doldu ve karttan haber kesildi bildirimleri için gerekir. İzin vermezsen uygulama çalışır ama bildirim göstermez.",
    "Needed for the recording finished, battery test finished, memory full and board went silent notifications. Without it the app works but shows no notifications.",
  ),
  "m.bl.anlik": S("Anlık izleme", "Live monitoring"),
  "m.bl.acik": S("Açık", "On"),
  "m.bl.kapali": S("Kapalı", "Off"),
  "m.bl.anlik_not": S(
    "Açıkken, kayıt sürdüğü sürece uygulama kapalıyken de internet üzerinden kart izlenir ve kalıcı bir bildirim durur; kayıt bitince kendiliğinden kapanır. Kapalıyken bildirim gelmez.",
    "When on, the board is monitored over the internet for as long as a recording runs, even with the app closed, and a persistent notification stays; it stops by itself when the recording ends. When off, no notifications arrive.",
  ),
  "m.bl.pil": S("Pil kısıtlaması", "Battery restriction"),
  "m.bl.pil_muaf": S("Kaldırıldı", "Removed"),
  "m.bl.pil_kisitli": S("Var — bildirim gecikebilir", "Present — notifications may be delayed"),
  "m.bl.pil_iste": S("Kısıtlamayı kaldır", "Remove restriction"),
  "m.bl.pil_not": S(
    "Android, ekran kapalıyken arka plandaki bağlantıyı keser. Anlık izlemenin saatler süren kayıtta çalışması için bu uygulamanın pil kısıtlaması kaldırılmalı. Açılan pencere Android'in kendi penceresidir.",
    "Android cuts background connections while the screen is off. For live monitoring to work through hours-long recordings, this app's battery restriction must be removed. The dialog that opens is Android's own.",
  ),
  "m.bl.izleme": S("İzleme", "Monitoring"),
  "m.bl.izleme_durduruldu": S("Çalışmıyor", "Not running"),
  "m.bl.izleme_baglaniyor": S("Bildirim sunucusuna bağlanılıyor…", "Connecting to the notification server…"),
  "m.bl.izleme_izleniyor": S("Kart izleniyor", "Monitoring the board"),
  "m.bl.izleme_internet": S("Telefonun interneti yok — kart izlenemiyor", "Phone has no internet — cannot monitor the board"),
  "m.bl.izleme_guven": S("Güvenli bağlantı kurulamadı", "Secure connection failed"),
  "m.bl.izleme_araci": S("Bildirim sunucusu bağlantıyı kabul etmedi", "The notification server refused the connection"),
  "m.bl.izleme_kayit_bitti": S("Kayıt bitti — izleme kapandı", "Recording finished — monitoring stopped"),
  "m.bl.izleme_ayar": S("Bildirim ayarı yenilenmeli — kartın ağında \"Karttan yenile\"ye dokun", "Notification setup needs refreshing — tap \"Refresh from the board\" on the board's network"),
  "m.bl.izleme_ic_hata": S("İzleme beklenmedik biçimde durdu", "Monitoring stopped unexpectedly"),
  "m.bl.siniflar": S("Hangi olaylar bildirilsin", "Which events to notify"),
  "m.bl.sinif_kopuk": S("Karttan haber kesildi (kayıt sürerken)", "Board went silent (during a recording)"),
  "m.bl.sinif_bitti": S("Kayıt / pil testi bitti", "Recording / battery test finished"),
  "m.bl.sinif_dolu": S("Kartın belleği doldu", "Board memory full"),
  "m.bl.sinif_esik": S("Eşitlenmemiş veri eşiği aşıldı", "Unsynced data threshold exceeded"),
  "m.bl.sinif_yeniden_basladi": S("Kart yeniden başladı", "Board restarted"),
  "m.bl.sinif_kacirilan": S("Kaçırılan bildirim sayısı", "Missed notification count"),
  "m.bl.sinif_deneme": S("Kartın deneme bildirimi", "Board's test notification"),
  "m.bl.deneme": S("Deneme bildirimi göster", "Show a test notification"),
  "m.bl.deneme_tamam": S("Deneme bildirimi gönderildi (yalnız bu telefonda; karta gidilmedi).", "Test notification posted (on this phone only; the board was not contacted)."),
  "m.bl.deneme_izin_yok": S("Bildirim izni yok: deneme bildirimi görünmez.", "No notification permission: the test notification will not show."),
  // ── Canli (ekran/Canli.vue, ekran/canli_gorunum.js)
  "m.cn.gerilim": S("Gerilim", "Voltage"),
  "m.cn.akim": S("Akım", "Current"),
  "m.cn.guc": S("Güç", "Power"),
  "m.cn.kart_yok": S("Kart bu ağda değil", "The board is not on this network"),
  "m.cn.dolu": S("Karta 4 izleyici bağlı", "4 viewers are connected to the board"),
  "m.cn.baglaniyor": S("Bağlanıyor…", "Connecting…"),
  "m.cn.akis_yok": S("Akış hazır değil", "The live stream is not available"),
  "m.cn.grafik_etiket": S("Canlı grafik: gerilim, akım, güç", "Live chart: voltage, current, power"),
  "m.cn.pencere": S("Grafik süresi", "Chart span"),
  "m.cn.pencere_60s": S("60 s", "60 s"),
  "m.cn.pencere_5dk": S("5 dk", "5 min"),
  "m.cn.sol_eksen": S("Sol eksen", "Left axis"),
  "m.cn.sag_eksen": S("Sağ eksen", "Right axis"),
  "m.cn.hiz": S("Kayıt hızı", "Recording rate"),
  "m.cn.komut_hata": S("Komut karta ulaşmadı ({tur}).", "The command did not reach the board ({tur})."),
  // ── Kayitlar (ekran/Kayitlar.vue, ekran/kayitlar_gorunum.js; A25, A41)
  "m.ky.arama": S("Ara: ad, etiket, not, #numara", "Search: name, tag, note, #number"),
  "m.ky.tur": S("Tür", "Type"),
  "m.ky.tur_hepsi": S("Hepsi", "All"),
  "m.ky.tur_olcum": S("Ölçüm", "Measurement"),
  "m.ky.tur_ayrinti": S("Ayrıntılı ölçüm", "Detailed measurement"),
  "m.ky.tur_pil": S("Pil testi", "Battery test"),
  "m.ky.tur_skop": S("Osiloskop", "Scope"),
  "m.ky.tur_bilinmeyen": S("Bilinmeyen tür", "Unknown type"),
  "m.ky.suz_pil": S("Pil", "Battery"),
  "m.ky.suz_skop": S("Skop", "Scope"),
  "m.ky.nerede_kart": S("Kartta", "On board"),
  "m.ky.nerede_telefon": S("Telefonda", "On phone"),
  "m.ky.nerede_ikisi": S("Kart + telefon", "Board + phone"),
  "m.ky.adsiz": S("Oturum #{n}", "Session #{n}"),
  "m.ky.eski_kart": S("Eski kayıt akışı", "Old recording stream"),
  "m.ky.kayitta": S("Kayıtta", "Recording"),
  "m.ky.once_esitle": S("Yalnız kartta: açmak için önce eşitle.", "Only on the board: sync first to open it."),
  "m.ky.eksik": S("Kartta daha yeni veri var; eşitlenince tamamlanır.", "The board has newer data; it completes after sync."),
  "m.ky.yukleniyor": S("Kayıtlar okunuyor…", "Reading recordings…"),
  "m.ky.bos": S("Telefonda henüz kayıt yok. Kart bu ağdayken kendiliğinden eşitlenir.", "No recordings on the phone yet. They sync automatically when the board is on this network."),
  "m.ky.bulunamadi": S("Aramaya uyan kayıt yok.", "No recordings match."),
  "m.ky.kart_yok": S("Kart bu ağda değil: liste telefondaki kopyadan.", "Board not on this network: list is from the copy on the phone."),
  "m.ky.kart_okunamadi": S("Kartın listesi okunamadı: liste telefondaki kopyadan.", "Could not read the board's list: showing the copy on the phone."),
  "m.ky.kart_eslesmemis": S("Kartla eşleşilmemiş: liste telefondaki kopyadan.", "Not paired with the board: showing the copy on the phone."),
  "m.ky.hata": S("Kayıtlar okunamadı ({tur}).", "Could not read recordings ({tur})."),
  // ── Grafik olcumu (ekran/GrafikOlcum.vue; Ö6, A27)
  "m.go.baslat": S("Grafik ölçümü (800 bin nokta)", "Chart benchmark (800k points)"),
  "m.go.suruyor": S("Ölçülüyor: 200 yakınlaştırma / kaydırma karesi…", "Measuring: 200 zoom / pan frames…"),
  "m.go.hata": S("Grafik ölçümü yapılamadı.", "The chart benchmark failed."),
  "m.go.gecersiz": S("Ölçüm GEÇERSİZ: grafik çizilmedi (tuval görünmüyor). Ekranı kaydırmadan yeniden dene.", "Benchmark INVALID: nothing was drawn (canvas not visible). Try again without scrolling."),
  "m.go.gecti": S("GEÇTİ: kare aralığı p95 {p95} ms (ölçüt < {olcut} ms)", "PASS: frame interval p95 {p95} ms (limit < {olcut} ms)"),
  "m.go.kaldi": S("KALDI: kare aralığı p95 {p95} ms (ölçüt < {olcut} ms)", "FAIL: frame interval p95 {p95} ms (limit < {olcut} ms)"),
  "m.go.ozet": S("{nokta} nokta · {kare} kare · hazırlık {hazirlik} ms", "{nokta} points · {kare} frames · setup {hazirlik} ms"),
  "m.go.aralik": S("kare aralığı: ortanca {ortanca} · p95 {p95} · en uzun {enUzun} ms", "frame interval: median {ortanca} · p95 {p95} · max {enUzun} ms"),
  "m.go.cizim": S("çizim süresi: ortanca {ortanca} · p95 {p95} · en uzun {enUzun} ms", "draw time: median {ortanca} · p95 {p95} · max {enUzun} ms"),
  // ── Kayit gorunumu (ekran/Kayit.vue)
  "m.kg.geri": S("Kayıtlar", "Recordings"),
  "m.kg.yok": S("Bu oturum telefondaki kopyada yok.", "This session is not in the copy on the phone."),
  "m.kg.bos": S("Bu oturumda grafiği çizilecek ölçüm yok.", "This session has no measurements to plot."),
  "m.kg.olcumsuz": S(
    "Bu oturumdaki {n} noktanın hiçbirinde geçerli ölçüm yok (kart gerilimi ve akımı okuyamamış).",
    "None of the {n} points in this session has a valid measurement (the board could not read voltage and current).",
  ),
  "m.kg.sure": S("Süre", "Duration"),
  "m.kg.tahmini": S("Kart yeniden başlamış: sonraki parçanın konumu tahmini.", "The board restarted: the position of the later part is estimated."),
  "m.kg.grafik_etiket": S("Kayıt grafiği: gerilim, akım, güç", "Recording chart: voltage, current, power"),
  "m.kg.tumu": S("Tümünü göster", "Show all"),
  "m.kg.ipucu": S("İki parmakla yakınlaştır, tek parmakla kaydır. Aşağıdaki değerler görünen aralık içindir.", "Pinch to zoom, drag to pan. The values below are for the visible range."),
  "m.kg.aralik": S("Görünen aralık", "Visible range"),
  "m.kg.ort": S("Ort", "Avg"),
  "m.kg.min": S("En az", "Min"),
  "m.kg.maks": S("En çok", "Max"),
  "m.kg.mah": S("Yük · mAh", "Charge · mAh"),
  "m.kg.wh": S("Enerji · Wh", "Energy · Wh"),
  "m.kg.ornek": S("{n} örnek", "{n} samples"),
  "m.kg.notlar": S("Notlar", "Notes"),
  // ── Ayarlar (ekran/Ayarlar.vue)
  "m.ay.kart": S("Kart", "Board"),
  "m.ay.gelismis": S("Gelişmiş", "Advanced"),
  "m.ay.gelismis_goster": S("Gelişmiş araçları göster", "Show advanced tools"),
  "m.ay.gelismis_gizle": S("Gelişmiş araçları gizle", "Hide advanced tools"),
  "m.ol.dogru": S("Sonuç başvuru değeriyle AYNI.", "The result MATCHES the reference value."),
  "m.ol.yanlis": S("Sonuç YANLIŞ: başvuru değeriyle uyuşmuyor.", "The result is WRONG: it does not match the reference value."),
  "m.ol.basvuru_yok": S("Bu tur sayısı için başvuru değeri yok.", "There is no reference value for this round count."),
  "m.ol.ozet": S("Türetilen değer (ilk 16 hane): {ozet}", "Derived value (first 16 digits): {ozet}"),
  "m.ol.uygulama": S("Uygulama: saf JS (WebView)", "Implementation: pure JS (WebView)"),
});

export function ceviriMobil(anahtar, dil = "tr", degiskenler = null) {
  if (Object.hasOwn(SOZLUK_MOBIL, anahtar)) return sozluktenCeviri(SOZLUK_MOBIL, anahtar, dil, degiskenler);
  return ceviri(anahtar, dil, degiskenler);
}
