// Telefona ozel metinler (TR/EN). ortak/src/sozluk.js'ten AYRI (sozluk_pc.js deseni): ortak sozluk
// degistirilmez; burada yalniz telefona ozel metinler durur (Bu telefon bolumu src/telefon/, telefon ortami
// src/ortam/, rapor metni). Anahtarlar "m." ile baslar. 5P (P6): eski Ionic ekranlarinin anahtarlari silindi.
// Kurallar (test/sozluk.test.js): her anahtarda bos olmayan tr VE en, yer tutucular iki dilde ayni,
// kullanilmayan anahtar yok, kullanilan her anahtar var, ortak sozlukle cakisma yok.
// ceviriMobil: once bu sozluk, yoksa ortak sozluk — HICBIR ZAMAN ATMAZ.

import { ceviri, sozluktenCeviri } from "@ortak/sozluk.js";

const S = (tr, en) => Object.freeze({ tr, en });

export const SOZLUK_MOBIL = Object.freeze({
  // ── Kart bulma / eslestirme hatalari (telefon/kart_bolum.js, ekran/esles_durum.js)
  "m.kb.baslik": S("Kartı bul", "Find the board"),
  "m.kb.elle": S("Adres (isteğe bağlı)", "Address (optional)"),
  "m.kb.elle_ornek": S("örn. 192.168.1.20", "e.g. 192.168.1.20"),
  "m.kb.ara": S("Ara", "Search"),
  "m.kb.araniyor": S("Aranıyor…", "Searching…"),
  "m.kb.adres": S("Adres", "Address"),
  "m.kb.kimlik": S("Kart kimliği", "Board ID"),
  "m.kb.kaynak": S("Nasıl bulundu", "Found via"),
  "m.kb.sure": S("Süre", "Time"),
  "m.kb.sure_ms": S("{ms} ms", "{ms} ms"),
  "m.kb.txt": S("Duyurudaki kimlik", "Announced ID"),
  "m.kb.txt_uyuyor": S("kartınkiyle aynı", "matches the board"),
  "m.kb.txt_uymuyor": S("UYMUYOR", "DOES NOT MATCH"),
  "m.kb.duyurular": S("Ağdaki duyurular", "Network announcements"),
  "m.sonuc.tamam": S("yanıt verdi", "responded"),
  "m.sonuc.zaman_asimi": S("yanıt yok", "no response"),
  "m.sonuc.baglanti": S("bağlanılamadı", "could not connect"),
  "m.sonuc.cleartext": S("şifresiz bağlantı engellendi", "cleartext connection blocked"),
  "m.sonuc.yanit_gecersiz": S("kart değil", "not a board"),
  "m.sonuc.govde_buyuk": S("yanıt çok büyük", "response too large"),
  "m.sonuc.wifi_yok": S("Wi-Fi yok", "no Wi-Fi"),
  "m.sonuc.ozel_degil": S("yerel adres değil", "not a local address"),
  "m.sonuc.ad_cozulmedi": S("ad çözülemedi", "name not resolved"),
  "m.sonuc.mesgul": S("meşgul", "busy"),
  "m.sonuc.ic_hata": S("hata", "error"),
  "m.ws.engellendi": S("engellendi", "blocked"),
  "m.ws.bos": S("içeriksiz", "empty"),
  "m.ws.gecti": S("GEÇTİ — kapı delik", "PASSED — gate is open"),
  // ── Baglanti (telefon/KartBolumu.vue, ekran/esles_durum.js)
  "m.bg.baglan": S("Bağlan", "Connect"),
  "m.bg.durum_bagli": S("eşleşmiş, bağlı", "paired, connected"),
  "m.bg.durum_eslesmemis": S("kart bulundu, eşleşmemiş", "board found, not paired"),
  "m.bg.durum_bulunamadi": S("kart bulunamadı", "board not found"),
  "m.bg.durum_kimlik": S("bu adresteki kart eşleştiğin kart değil", "the board at this address is not the paired one"),
  "m.bg.dene": S("İmzalı isteği dene", "Try a signed request"),
  "m.bg.imzali_tamam": S("İmzalı istek geçti: {oturum} oturum", "Signed request succeeded: {oturum} session(s)"),
  "m.bg.kaldir": S("Eşleşmeyi kaldır", "Remove pairing"),
  "m.bg.kaldirildi": S("Eşleşme kartta ve telefonda kaldırıldı.", "Pairing removed on the board and the phone."),
  "m.bg.kaldirildi_yerel": S("Eşleşme yalnız telefonda kaldırıldı (karta ulaşılamadı).", "Pairing removed on the phone only (board unreachable)."),
  "m.bg.kaldirildi_belirsiz": S(
    "Eşleşme telefonda kaldırıldı. Kart silmeyi onaylamadı: kayıt kartta kalmış olabilir — kartın panelinden ya da USB'den silin.",
    "Pairing removed on the phone. The board did not confirm the removal: the entry may still be on the board — delete it from the board's panel or over USB.",
  ),
  "m.bg.kasa_bozuk": S(
    "Telefondaki eşleşme kaydı bozuk ya da okunamıyor. Eşleşmeyi kaldırıp yeniden eşleş.",
    "The pairing record on the phone is damaged or unreadable. Remove the pairing and pair again.",
  ),
  "m.bg.hata": S("Olmadı ({tur}).", "Failed ({tur})."),
  "m.ol.durdur": S("DURDUR süre ölçümü (20 tekrar)", "STOP timing (20 runs)"),
  "m.ol.durdur_sonuc": S("DURDUR {tekrar} tekrar: {basari} başarılı · en az {enaz} ms · ortanca {ortanca} ms · en çok {encok} ms", "STOP {tekrar} runs: {basari} ok · min {enaz} ms · median {ortanca} ms · max {encok} ms"),
  "m.ol.pbkdf2": S("PBKDF2 süre ölçümü", "PBKDF2 timing"),
  "m.ol.suruyor": S("Ölçülüyor…", "Measuring…"),
  "m.ol.pbkdf2_sonuc": S("PBKDF2 {tur} tur: en az {enaz} ms · ortanca {ortanca} ms · en çok {encok} ms", "PBKDF2 {tur} rounds: min {enaz} ms · median {ortanca} ms · max {encok} ms"),
  "m.ws.dugme": S("WebView ağ sınaması", "WebView network self-test"),
  "m.ws.suruyor": S("Sınanıyor…", "Testing…"),
  "m.kb.denenenler": S("Denenen adresler", "Addresses tried"),
  "m.kb.kaynak_elle": S("elle girilen", "entered by hand"),
  "m.kb.kaynak_onbellek": S("son bilinen adres", "last known address"),
  "m.kb.kaynak_ad": S("olcum.local adı", "olcum.local name"),
  "m.kb.kaynak_nsd": S("ağ duyurusu", "network announcement"),
  "m.kb.kaynak_ap": S("kartın kendi ağı", "the board's own network"),
  "m.kb.hata_bulunamadi": S("Kart bu ağda bulunamadı.", "The board was not found on this network."),
  "m.kb.hata_kimlik": S("Bu adresteki kart, eşleştiğin kart değil.", "The board at this address is not the one you paired with."),
  "m.kb.hata_bicim": S("Adres yanlış yazılmış.", "The address is not written correctly."),
  "m.kb.hata_ozel_degil": S("Yalnız yerel ağ adresleri kabul edilir.", "Only local network addresses are accepted."),
  "m.kb.hata_ad_izinsiz": S("Ad yerine kartın IP adresini yaz.", "Enter the board's IP address instead of a name."),
  "m.kb.hata_wifi_yok": S("Wi-Fi kapalı ya da bağlı değil.", "Wi-Fi is off or not connected."),
  "m.kb.hata_bilinmeyen": S("Beklenmeyen bir hata oldu.", "An unexpected error occurred."),
  // ── Eslestirme (telefon/KartBolumu.vue, ekran/esles_durum.js)
  "m.es.baslik": S("Kartla eşleştir", "Pair with the board"),
  "m.es.kart_dogru_mu": S("Bu, eşleştirmek istediğin kart mı? Kimliği kontrol et.", "Is this the board you want to pair with? Check its ID."),
  "m.es.ad": S("Bu telefonun adı (kartta görünür)", "Name of this phone (shown on the board)"),
  "m.es.ad_varsayilan": S("Telefon", "Phone"),
  "m.es.parola": S("Kartın WEB parolası — Wi-Fi parolası DEĞİL", "The board's WEB password — NOT the Wi-Fi password"),
  "m.es.parola_not": S(
    "Parola yalnız eşleştirme sırasında kullanılır; telefonda saklanmaz ve ağa çıkmaz.",
    "The password is used only while pairing; it is not stored on the phone and never leaves it.",
  ),
  "m.es.gonder": S("Eşleştir", "Pair"),
  "m.es.suruyor": S("Eşleştiriliyor…", "Pairing…"),
  "m.es.suruyor_not": S("Bu birkaç saniye sürebilir.", "This may take a few seconds."),
  "m.es.tamam": S("Eşleştirildi.", "Paired."),
  "m.es.hata_parola_kisa": S("Web parolası en az 12 karakter olmalı.", "The web password must be at least 12 characters."),
  "m.es.hata_parola_yanlis": S(
    "Parola yanlış. Kartın WEB parolasını gir (Wi-Fi parolası değil).",
    "Wrong password. Enter the board's WEB password (not the Wi-Fi password).",
  ),
  "m.es.hata_parola_yok": S(
    "Kartta web parolası yok ya da çok kısa. Önce kartta en az 12 karakterlik bir web parolası belirle.",
    "The board has no web password, or it is too short. Set a web password of at least 12 characters on the board first.",
  ),
  "m.es.hata_bekle": S("Çok fazla yanlış deneme. Biraz bekleyip yeniden dene.", "Too many wrong attempts. Wait a little and try again."),
  "m.es.hata_bekle_saniye": S(
    "Çok fazla yanlış deneme. {saniye} saniye sonra yeniden dene.",
    "Too many wrong attempts. Try again in {saniye} seconds.",
  ),
  "m.es.hata_liste_dolu": S(
    "Kartın cihaz listesi dolu (8). Kullanılmayan bir cihazı karttan kaldır.",
    "The board's device list is full (8). Remove an unused device from the board.",
  ),
  "m.es.hata_sure_doldu": S("Eşleştirme süresi doldu. Yeniden dene.", "Pairing timed out. Try again."),
  "m.es.hata_kart_sahte": S(
    "Bu kart parolayı bilmiyor — senin kartın olmayabilir. Eşleştirme YAPILMADI. Kart senin değilse kartının web parolasını değiştir.",
    "This board does not know the password — it may not be your board. Pairing was NOT done. If it is not your board, change your board's web password.",
  ),
  "m.es.hata_tur": S(
    "Kart güvensiz bir ayar bildirdi; sahte olabilir. Eşleştirme YAPILMADI.",
    "The board reported an unsafe setting; it may be fake. Pairing was NOT done.",
  ),
  "m.es.hata_kart_gecersiz": S("Karttan anlaşılmayan bir yanıt geldi.", "The board sent a response that was not understood."),
  "m.es.hata_kimlik": S(
    "Bu adresteki kart değişti. Kartı yeniden bul ve kimliğini kontrol et.",
    "The board at this address has changed. Find the board again and check its ID.",
  ),
  "m.es.hata_ag": S("Karta ulaşılamadı. Wi-Fi bağlantısını kontrol et.", "Could not reach the board. Check the Wi-Fi connection."),
  "m.es.hata_kasa": S("Anahtar telefona kaydedilemedi. Eşleştirme geri alındı.", "The key could not be saved on the phone. Pairing was undone."),
  "m.es.hata_ad": S("Ad 1–24 bayt olmalı.", "The name must be 1–24 bytes."),
  "m.es.hata_bagli_degil": S("Önce kartı bul.", "Find the board first."),
  "m.es.hata_zaten_esli": S("Bu telefon zaten eşleşmiş.", "This phone is already paired."),
  "m.es.hata_bilinmeyen": S("Eşleştirme sırasında beklenmeyen bir hata oldu.", "An unexpected error occurred while pairing."),
  // ── Kayit esitlemesi (telefon/EsitlemeBolumu.vue; A20–A23)
  "m.ay.esitleme": S("Eşitleme", "Sync"),
  "m.es.onay": S("Bu telefon da onaylasın", "Let this phone acknowledge too"),
  "m.es.onay_not": S(
    "Açarsan kart, PC'nin henüz almadığı kayıtları silebilir. Arşivin PC'deyse kapalı bırak.",
    "If you turn this on, the board may erase records the PC has not fetched yet. Leave it off if your archive is on the PC.",
  ),
  "m.es.depolama": S("Telefondaki kopya", "Copy on the phone"),
  "m.es.depolama_yok": S("Kart bilinmiyor", "Board unknown"),
  "m.es.sifirla": S("Kopyayı sıfırla", "Reset copy"),
  "m.es.sifirla_not": S(
    "Yalnız telefondaki kopya silinir; karttaki kayıtlara dokunulmaz ve sonraki eşitlemede yeniden alınır.",
    "Only the copy on the phone is deleted; records on the board are untouched and are fetched again on the next sync.",
  ),
  "m.es.sifirla_hata": S("Sıfırlanamadı ({tur}).", "Could not reset ({tur})."),
  "m.es.sifirlandi": S("Kopya silindi.", "Copy deleted."),
  // ── Bildirimler (telefon/BildirimBolumu.vue, ekran/bildirim_gorunum.js, ortam/soru_cizim.js; 5E-4)
  "m.ay.bildirim": S("Bildirimler", "Notifications"),
  "m.bl.ayar": S("Bildirim ayarı", "Notification setup"),
  "m.bl.zarf_var": S("Karttan alındı", "Fetched from the board"),
  "m.bl.zarf_yok": S("Alınmadı — uygulamayı kartın ağında aç", "Not fetched — open the app on the board's network"),
  "m.bl.kartta_ayarsiz": S(
    "Kartta internet bildirimi ayarlı değil (kartın USB'sinden ayarlanır).",
    "Internet notifications are not set up on the board (configured over the board's USB).",
  ),
  "m.bl.kartta_ayarsiz_zarf": S(
    "Kart, internet bildiriminin ayarlı olmadığını söyledi. Telefondaki önceki ayar duruyor (silinmedi).",
    "The board says internet notifications are not set up. The previous setup on this phone was kept (not deleted).",
  ),
  "m.bl.kart_yok": S("Kart bilinmiyor — önce kartla eşleş.", "Board unknown — pair with the board first."),
  "m.bl.yenile": S("Karttan yenile", "Refresh from the board"),
  "m.bl.yenileniyor": S("Karttan alınıyor…", "Fetching from the board…"),
  "m.bl.yenile_tamam": S("Bildirim ayarı karttan alındı.", "Notification setup fetched from the board."),
  "m.bl.hata_bagli_degil": S("Kart bu ağda değil: ayar alınamadı.", "Board not on this network: setup could not be fetched."),
  "m.bl.hata_ag": S("Karta ulaşılamadı. Yeniden dene.", "Could not reach the board. Try again."),
  "m.bl.hata_silinmis": S("Bu telefon kartta silinmiş. Yeniden eşleştir.", "This phone was removed on the board. Pair again."),
  "m.bl.hata_zarf": S(
    "Karttan gelen ayar bu telefonun anahtarıyla açılmadı. Eşleşmeyi kaldırıp yeniden eşleş.",
    "The setup from the board could not be opened with this phone's key. Remove the pairing and pair again.",
  ),
  "m.bl.hata_adres": S(
    "Kartın verdiği sunucu adresi güvenli (mqtts://) değil: bağlanılmayacak. Karttaki ayarı düzelt.",
    "The server address from the board is not secure (mqtts://): will not connect. Fix the setting on the board.",
  ),
  "m.bl.hata_genel": S("Olmadı ({tur}).", "Failed ({tur})."),
  "m.bl.izin": S("Bildirim izni", "Notification permission"),
  "m.bl.izin_var": S("Verildi", "Granted"),
  "m.bl.izin_yok": S("Verilmedi", "Not granted"),
  "m.bl.izin_iste": S("İzin ver", "Grant permission"),
  "m.bl.izin_not": S(
    "Kayıt bitti, pil testi bitti, bellek doldu ve karttan haber kesildi bildirimleri için gerekir. İzin vermezsen uygulama çalışır ama bildirim göstermez.",
    "Needed for the recording finished, battery test finished, memory full and board went silent notifications. Without it the app works but shows no notifications.",
  ),
  "m.bl.anlik": S("Anlık izleme", "Live monitoring"),
  "m.bl.anlik_not": S(
    "Açıkken, kayıt sürdüğü sürece uygulama kapalıyken de internet üzerinden kart izlenir ve kalıcı bir bildirim durur; kayıt bitince kendiliğinden kapanır. Kapalıyken bildirimler 15 dakikaya kadar gecikebilir.",
    "When on, the board is monitored over the internet for as long as a recording runs, even with the app closed, and a persistent notification stays; it stops by itself when the recording ends. When off, notifications may be up to 15 minutes late.",
  ),
  "m.bl.pil": S("Pil kısıtlaması", "Battery restriction"),
  "m.bl.pil_muaf": S("Kaldırıldı", "Removed"),
  "m.bl.pil_kisitli": S("Var — bildirim gecikebilir", "Present — notifications may be delayed"),
  "m.bl.pil_iste": S("Kısıtlamayı kaldır", "Remove restriction"),
  "m.bl.pil_not": S(
    "Android, ekran kapalıyken arka plandaki bağlantıyı keser. Anlık izlemenin saatler süren kayıtta çalışması için bu uygulamanın pil kısıtlaması kaldırılmalı. Açılan pencere Android'in kendi penceresidir.",
    "Android cuts background connections while the screen is off. For live monitoring to work through hours-long recordings, this app's battery restriction must be removed. The dialog that opens is Android's own.",
  ),
  "m.bl.yn_goster": S("Telefonun pil yöneticisi — adımları göster", "Phone battery manager — show the steps"),
  "m.bl.yn_gizle": S("Adımları gizle", "Hide the steps"),
  "m.bl.yn_neden": S(
    "Bazı telefonlar, pil kısıtlaması kaldırılsa bile arka plandaki uygulamayı kendi pil yöneticisiyle kapatır. Uzun kayıtlarda bildirimin kesilmemesi için şu ayarları elle yap:",
    "Some phones close background apps with their own battery manager even after the battery restriction is removed. For notifications to keep working through long recordings, set the following by hand:",
  ),
  "m.bl.yn_honor_1": S("Ayarlar › Uygulamalar › Uygulama başlatma'yı aç.", "Open Settings › Apps › App launch."),
  "m.bl.yn_honor_2": S("Listede Ölçüm Kartı'nı bul; \"Otomatik yönet\"i KAPAT.", "Find Measurement Board in the list; turn OFF \"Manage automatically\"."),
  "m.bl.yn_honor_3": S("Açılan pencerede üçünü de AÇ: Otomatik başlatma, İkincil başlatma, Arka planda çalıştır.", "In the dialog turn ON all three: Auto-launch, Secondary launch, Run in background."),
  "m.bl.yn_honor_4": S("Son uygulamalar ekranında Ölçüm Kartı'nı aşağı çekip kilitle (kilit simgesi).", "In the recent apps screen pull Measurement Board down to lock it (lock icon)."),
  "m.bl.yn_xiaomi_1": S("Aşağıdaki düğmeyle uygulama ayarlarını aç; \"Otomatik başlatma\"yı AÇ.", "Open the app settings with the button below; turn ON \"Autostart\"."),
  "m.bl.yn_xiaomi_2": S("Aynı sayfada \"Pil tasarrufu\" › \"Kısıtlama yok\"u seç.", "On the same page choose \"Battery saver\" › \"No restrictions\"."),
  "m.bl.yn_xiaomi_3": S("Son uygulamalar ekranında Ölçüm Kartı'na uzun basıp kilitle (kilit simgesi).", "In the recent apps screen long-press Measurement Board and lock it (lock icon)."),
  "m.bl.yn_samsung_1": S("Aşağıdaki düğmeyle uygulama ayarlarını aç; Pil › \"Kısıtlanmamış\"ı seç.", "Open the app settings with the button below; choose Battery › \"Unrestricted\"."),
  "m.bl.yn_samsung_2": S("Ayarlar › Pil › Arka plan kullanım sınırları: Ölçüm Kartı \"Uyuyan uygulamalar\" listesinde OLMASIN.", "Settings › Battery › Background usage limits: Measurement Board must NOT be in \"Sleeping apps\"."),
  "m.bl.yn_diger_1": S("Aşağıdaki düğmeyle uygulama ayarlarını aç; Pil bölümünde \"Kısıtlanmamış\" / \"Kısıtlama yok\"u seç.", "Open the app settings with the button below; in Battery choose \"Unrestricted\" / \"No restrictions\"."),
  "m.bl.yn_diger_2": S("Telefonunda \"otomatik başlatma\" ya da \"arka planda çalışma\" izni varsa Ölçüm Kartı için aç.", "If your phone has an \"autostart\" or \"run in background\" permission, turn it on for Measurement Board."),
  "m.bl.yn_not": S(
    "Menü adları telefonun sürümüne göre biraz farklı olabilir. Bu ayarları uygulama değiştiremez; sen yaparsın.",
    "Menu names may differ slightly with the phone's software version. The app cannot change these settings; you do.",
  ),
  "m.bl.yn_ac": S("Uygulama ayarlarını aç", "Open app settings"),
  "m.bl.izleme": S("İzleme", "Monitoring"),
  "m.bl.izleme_durduruldu": S("Çalışmıyor", "Not running"),
  "m.bl.izleme_baglaniyor": S("Bildirim sunucusuna bağlanılıyor…", "Connecting to the notification server…"),
  "m.bl.izleme_izleniyor": S("Kart izleniyor", "Monitoring the board"),
  "m.bl.izleme_internet": S("Telefonun interneti yok — kart izlenemiyor", "Phone has no internet — cannot monitor the board"),
  "m.bl.izleme_guven": S("Güvenli bağlantı kurulamadı", "Secure connection failed"),
  "m.bl.izleme_araci": S("Bildirim sunucusu bağlantıyı kabul etmedi", "The notification server refused the connection"),
  "m.bl.izleme_kayit_bitti": S("Kayıt bitti — izleme kapandı", "Recording finished — monitoring stopped"),
  "m.bl.izleme_ayar": S("Bildirim ayarı yenilenmeli — kartın ağında \"Karttan yenile\"ye dokun", "Notification setup needs refreshing — tap \"Refresh from the board\" on the board's network"),
  "m.bl.izleme_ic_hata": S("İzleme beklenmedik biçimde durdu", "Monitoring stopped unexpectedly"),
  "m.bl.soru": S(
    "Bu kayıt için anlık izleme açılsın mı? Uygulama kapalıyken de kart internet üzerinden izlenir; kayıt bitince kendiliğinden kapanır.",
    "Turn on live monitoring for this recording? The board is monitored over the internet even with the app closed; it stops by itself when the recording ends.",
  ),
  "m.bl.soru_evet": S("Aç", "Turn on"),
  "m.bl.soru_hayir": S("Hayır", "No"),
  "m.bl.soru_acildi": S("Bu kayıt anlık izleniyor.", "This recording is being monitored live."),
  "m.bl.soru_acilamadi": S("Anlık izleme açılamadı. Ayarlar › Bildirimler'e bak.", "Live monitoring could not be turned on. See Settings › Notifications."),
  "m.bl.siniflar": S("Hangi olaylar bildirilsin", "Which events to notify"),
  "m.bl.sinif_kopuk": S("Karttan haber kesildi (kayıt sürerken)", "Board went silent (during a recording)"),
  "m.bl.sinif_bitti": S("Kayıt / pil testi bitti", "Recording / battery test finished"),
  "m.bl.sinif_dolu": S("Kartın belleği doldu", "Board memory full"),
  "m.bl.sinif_esik": S("Eşitlenmemiş veri eşiği aşıldı", "Unsynced data threshold exceeded"),
  "m.bl.sinif_yeniden_basladi": S("Kart yeniden başladı", "Board restarted"),
  "m.bl.sinif_kacirilan": S("Kaçırılan bildirim sayısı", "Missed notification count"),
  "m.bl.sinif_deneme": S("Kartın deneme bildirimi", "Board's test notification"),
  "m.bl.deneme": S("Deneme bildirimi göster", "Show a test notification"),
  "m.bl.deneme_tamam": S("Deneme bildirimi gönderildi (yalnız bu telefonda; karta gidilmedi).", "Test notification posted (on this phone only; the board was not contacted)."),
  "m.bl.deneme_izin_yok": S("Bildirim izni yok: deneme bildirimi görünmez.", "No notification permission: the test notification will not show."),
  // ── Rapor metni (cekirdek/rapor_metin.js; 5F)
  "m.ps.rapor_baslik": S("Ölçüm kartı — kayıt raporu", "Measurement board — recording report"),
  "m.ps.bicim_surum": S("Kayıt biçimi sürümü", "Record format version"),
  "m.ps.tekrar_adet": S("Başlık kopyası (TEKRAR) sayısı", "Header copies (TEKRAR)"),
  "m.ps.sure_s": S("Süre (s)", "Duration (s)"),
  "m.ps.nokta_ms": S("Grafikteki yeri (kart saati, ms)", "Position on the graph (board clock, ms)"),
  "m.ps.sira": S("Kayıt sırası", "Record sequence"),
  "m.ps.metin": S("Metin", "Text"),
  "m.ps.genel": S("Oturumun geneline ait", "Applies to the whole session"),
  "m.ps.evet": S("evet", "yes"),
  "m.ps.hayir": S("hayır", "no"),
  // ── Bolum basliklari ve Gelismis (telefon/*Bolumu.vue, ekran/olcum_gorunum.js)
  "m.ay.kart": S("Kart", "Board"),
  "m.ay.gelismis": S("Gelişmiş", "Advanced"),
  "m.ol.dogru": S("Sonuç başvuru değeriyle AYNI.", "The result MATCHES the reference value."),
  "m.ol.yanlis": S("Sonuç YANLIŞ: başvuru değeriyle uyuşmuyor.", "The result is WRONG: it does not match the reference value."),
  "m.ol.basvuru_yok": S("Bu tur sayısı için başvuru değeri yok.", "There is no reference value for this round count."),
  "m.ol.ozet": S("Türetilen değer (ilk 16 hane): {ozet}", "Derived value (first 16 digits): {ozet}"),
  "m.ol.uygulama": S("Uygulama: saf JS (WebView)", "Implementation: pure JS (WebView)"),
  // ── Panelin Ayarlar'inda "Bu telefon" bolumu (telefon/, 5P K13 K14)
  "m.bt.baslik": S("Bu telefon", "This phone"),
  "m.bt.aciklama": S(
    "Bu ayarlar yalnız bu telefon için: kartla bağlantı ve eşleşme, telefondaki kopya, bildirimler.",
    "These settings apply to this phone only: board connection and pairing, the copy on the phone, notifications.",
  ),
  "m.bt.durum_yok": S("Henüz bağlanılmadı", "Not connected yet"),
  "m.bt.bul_ipucu": S("Adres boşsa kart bu ağda (ve telefonun erişim noktasında) aranır.", "With no address the board is searched for on this network (and on the phone's hotspot)."),
  "m.bt.bulunamadi_ipucu": S("Ayrıntı için Gelişmiş › Kartı bul: denenen her adres ve sonucu görünür.", "For details see Advanced › Find the board: every address tried and its result are shown."),
  "m.bt.kaynak_paylasim": S("telefonun erişim noktası", "the phone's hotspot"),
  "m.bt.saat": S("Kartın saati", "Board clock"),
  "m.bt.saat_0": S("yok — kayıtlar zamansız", "none — recordings have no time"),
  "m.bt.saat_1": S("internetten (NTP)", "from the internet (NTP)"),
  "m.bt.saat_2": S("bir cihazdan verildi", "set by a device"),
  "m.bt.saat_ver": S("Kart saatini ver", "Set the board clock"),
  "m.bt.saat_ipucu": S(
    "Kartın internet saati yoksa kayıtlar bu telefonun saatiyle zamanlanır. Saat bağlantı başına bir kez verilir.",
    "If the board has no internet time, recordings are timed with this phone's clock. The clock is set once per connection.",
  ),
  "m.bt.saat_verildi": S("Kartın saati bu telefondan verildi.", "The board clock was set from this phone."),
  "m.bt.saat_gerekmedi": S("Gerekmedi: kartın internet saati var ya da bu bağlantıda zaten verildi.", "Not needed: the board has internet time or it was already set on this connection."),
  "m.bt.vazgec": S("Vazgeç", "Cancel"),
  "m.bt.kaldir_eminim": S("Eminim — eşleşmeyi kaldır", "I'm sure — remove pairing"),
  "m.bt.kaldir_uyari": S(
    "Bu telefon kartın listesinden ve telefondan silinir. Yeniden eşleşmek için kartın web parolası gerekir.",
    "This phone is removed from the board's list and from the phone. Pairing again needs the board's web password.",
  ),
  "m.bt.ad_ipucu": S("En çok 24 bayt; kartın cihaz listesinde bu adla görünür.", "At most 24 bytes; shown under this name in the board's device list."),
  "m.bt.liste_baslik": S("Kartla eşleşmiş cihazlar", "Devices paired with the board"),
  "m.bt.yenile": S("Yenile", "Refresh"),
  "m.bt.yukleniyor": S("Okunuyor…", "Reading…"),
  "m.bt.bu_telefon": S("bu telefon", "this phone"),
  "m.bt.no": S("no {n}", "no {n}"),
  "m.bt.cihaz_zaman": S("Eklendi {eklenme} · son görülme {son}", "Added {eklenme} · last seen {son}"),
  "m.bt.sil": S("Kaldır", "Remove"),
  "m.bt.sil_ad": S("{ad} cihazını karttan kaldır", "Remove {ad} from the board"),
  "m.bt.sil_eminim": S("Eminim — kaldır", "I'm sure — remove"),
  "m.bt.sil_uyari": S(
    "Seçilen cihaz kartta silinir; o cihaz yeniden eşleşmeden karta bağlanamaz.",
    "The selected device is removed on the board; it cannot connect until it pairs again.",
  ),
  "m.bt.silindi": S("{n} numaralı cihaz karttan kaldırıldı.", "Device no {n} was removed from the board."),
  "m.bt.sil_hata": S("{n} numaralı cihaz kaldırılamadı ({tur}).", "Device no {n} could not be removed ({tur})."),
  "m.bt.liste_bos": S("Kartta eşleşmiş cihaz yok.", "No devices are paired with the board."),
  "m.bt.liste_hata": S("Cihaz listesi alınamadı ({tur}).", "The device list could not be read ({tur})."),
  "m.bt.sifirla_eminim": S("Eminim — kopyayı sil", "I'm sure — delete the copy"),
  "m.bt.surumler": S("Sürümler", "Versions"),
  "m.bt.uygulama": S("Uygulama", "App"),
  "m.bt.panel": S("Kartın paneli", "Board's panel"),
  "m.bt.panel_surum": S("{surum} · {dosya} dosya", "{surum} · {dosya} files"),
  "m.bt.panel_bagli_degil": S("kart bağlı değil (eşleşmiş kartla bağlan)", "board not connected (connect to the paired board)"),
  "m.bt.panel_okunamadi": S("okunamadı ({tur})", "could not be read ({tur})"),
  "m.bt.tani_ipucu": S(
    "Kartı arar ve denenen her adresin sonucunu gösterir; bağlantıyı değiştirmez.",
    "Searches for the board and shows the result for every address tried; does not change the connection.",
  ),
  "m.bt.olcumler": S("Ölçümler", "Measurements"),
});

export function ceviriMobil(anahtar, dil = "tr", degiskenler = null) {
  if (Object.hasOwn(SOZLUK_MOBIL, anahtar)) return sozluktenCeviri(SOZLUK_MOBIL, anahtar, dil, degiskenler);
  return ceviri(anahtar, dil, degiskenler);
}
