// 5E-4 — bildirimin WebView yarisi. Kosum (mobil/ icinden): node mutasyon/kos.mjs --neden 5E-4J
const B = "src/cekirdek/bildirim.js";
const G = "src/ekran/bildirim_gorunum.js";
const K = "src/ekran/kabuk_durum.js";
const T = "test/bildirim.test.js";

export default [
  { ad: "5E-4J: bagli olmayan karta da zarf istegi gidiyor", dosya: B,
    bul: 'if (!d || d.durum !== "bagli" || typeof d.kimlik !== "string" || !KIMLIK.test(d.kimlik)) throw new BildirimHatasi("bagli-degil");',
    koy: 'if (!d) throw new BildirimHatasi("bagli-degil");', test: T },
  { ad: "K10: 404'te eldeki zarf siliniyor", dosya: B, bul: '        return "kartta-ayarsiz";\n',
    koy: '        await cagir("zarfSil", { kimlik: d.kimlik });\n        return "kartta-ayarsiz";\n', test: T },
  { ad: "K10: 404 hata sayiliyor (kartta ayarsiz denmiyor)", dosya: B, bul: '        return "kartta-ayarsiz";\n', koy: "", test: T },
  { ad: "5E-4J: her HTTP hatasinda zarf siliniyor", dosya: B, bul: 'if (tur === "http" && e.durum === 404) {', koy: 'if (tur === "http") {', test: T },
  { ad: "5E-4J: boyu tutmayan govde eklentiye veriliyor", dosya: B,
    bul: 'if (govde.length < ZARF_EN_AZ || govde.length > ZARF_AZAMI) throw new BildirimHatasi("bicim");\n', koy: "", test: T },
  { ad: "5E-4J: zarf ust siniri 4096", dosya: B, bul: "export const ZARF_AZAMI = 2048;", koy: "export const ZARF_AZAMI = 4096;", test: T },
  { ad: "5E-4J: eklentinin hata MESAJI yukari cikiyor", dosya: B,
    bul: 'throw new BildirimHatasi(e && typeof e.code === "string" && TUR.test(e.code) ? e.code : "ic-hata");',
    koy: 'throw new BildirimHatasi(e && e.message ? e.message : "ic-hata");', test: T },
  { ad: "5E-4J: kartin ag hatasi 'kart' diye gosteriliyor", dosya: B,
    bul: 'tur === "ag" || tur === "cihaz-silinmis"', koy: 'tur === "cihaz-silinmis"', test: T },
  { ad: "5E-4J: durum: izin alani oldugu gibi geciyor (tur denetimi yok)", dosya: B, bul: "izin: y.izin === true,", koy: "izin: y.izin,", test: T },
  { ad: "5E-4J: durum: bilinmeyen izleme adi geciyor", dosya: B,
    bul: 'izleme: IZLEME_DURUMLARI.has(y.izleme) ? y.izleme : "durduruldu",', koy: "izleme: y.izleme,", test: T },
  { ad: "5E-4J: durum: eklentinin butun alanlari yukari cikiyor", dosya: B, bul: "    return {\n      zarf: y.zarf === true,", koy: "    return {\n      ...y,\n      zarf: y.zarf === true,", test: T },
  { ad: "5E-4J: durum: bilinmeyen sinif geciyor", dosya: B,
    bul: "kapali: SINIFLAR.filter((s) => Array.isArray(y.kapali) && y.kapali.includes(s)),", koy: "kapali: Array.isArray(y.kapali) ? y.kapali : [],", test: T },
  { ad: "5E-4J: ayarYaz: gecersiz dil gidiyor", dosya: B, bul: "if (DILLER.includes(dil)) veri.dil = dil;", koy: "if (dil) veri.dil = dil;", test: T },
  { ad: "5E-4J: ayarYaz: anlik tur denetimsiz", dosya: B, bul: 'if (typeof anlik === "boolean") veri.anlik = anlik;', koy: "if (anlik) veri.anlik = anlik;", test: T },
  { ad: "5E-4J: yerel: eksi / kesirli sayi eklentiye gidiyor", dosya: B,
    bul: 'if (!Number.isInteger(kod) || !Number.isInteger(oturum) || kod < 0 || oturum < 0) throw new BildirimHatasi("bicim");\n', koy: "", test: T },
  { ad: "5E-4J: izlemeBaslat: kimlik denetimsiz", dosya: B,
    bul: 'const y = await cagir("izlemeBaslat", { kimlik: kimlikli(kimlik) });', koy: 'const y = await cagir("izlemeBaslat", { kimlik });', test: T },
  { ad: "5E-4J: bekliyor durumu kayit sayilmiyor", dosya: B, bul: "export const KAYITTA = Object.freeze([2, 4]);", koy: "export const KAYITTA = Object.freeze([2]);", test: T },
  { ad: "5E-4J: izleyici: zarf her tikte yenileniyor", dosya: B, bul: "    if (!oncekiBagli) {\n      oncekiBagli = true;\n      if (typeof adres", koy: "    if (true) {\n      oncekiBagli = true;\n      if (typeof adres", test: T },
  { ad: "5E-4J: izleyici: baglanti kopunca sifirlanmiyor (yeniden baglaninca zarf yenilenmez)", dosya: B,
    bul: "      oncekiBagli = false;\n      sonG = null;\n      return;", koy: "      return;", test: T },
  { ad: "5E-4J: izleyici: arka plandayken de calisiyor", dosya: B, bul: "if (!gorunur || !bagli ||", koy: "if (!bagli ||", test: T },
  { ad: "5E-4J: izleyici: ayni kayit durumu her tikte iletiliyor", dosya: B, bul: "    if (g === sonG) return;\n", koy: "", test: T },
  { ad: "5E-4J: izleyici: kayit bitince de izleme baslatiliyor", dosya: B,
    bul: "if (KAYITTA.includes(durum)) await bildirim.izlemeBaslat(kimlik).catch(() => {});", koy: "await bildirim.izlemeBaslat(kimlik).catch(() => {});", test: T },
  { ad: "5E-4J: izleyici: izleme baslatilamazsa yerel durum iletilmiyor", dosya: B,
    bul: "await bildirim.izlemeBaslat(kimlik).catch(() => {});", koy: "await bildirim.izlemeBaslat(kimlik);", test: T },
  { ad: "5E-4J: izleyici: isler sirasiz (zarf yazilmadan izleme baslar)", dosya: B,
    bul: "const sirayla = (is) => { kuyruk = kuyruk.then(is).catch(() => {}); };", koy: "const sirayla = (is) => { is().catch(() => {}); };", test: T },
  { ad: "5E-4J: izleyici: bicimsiz G satiri iletiliyor", dosya: B,
    bul: "if (!kayit || !Number.isInteger(kayit.durum) || !Number.isInteger(kayit.oturum) || kayit.durum < 0 || kayit.oturum < 0) return;",
    koy: "if (!kayit) return;", test: T },
  { ad: "5E-4J: kabuk: izleyicinin hatasi tiki durduruyor", dosya: K,
    bul: "    } catch { /* bildirim yok sayilir */ }\n", koy: "    } finally { /* yok */ }\n", test: T },
  { ad: "5E-4J: kabuk: izleyiciye kayit durumu verilmiyor", dosya: K, bul: "adres: b ? b.adres : null, kayit: akis.value.kayit });", koy: "adres: b ? b.adres : null, kayit: null });", test: T },
  { ad: "5E-4J: kabuk: eslesmemis kart 'bagli' sayiliyor", dosya: K,
    bul: 'bildirimIzle.tik({ gorunur, bagli: Boolean(b) && b.durum === "bagli",', koy: "bildirimIzle.tik({ gorunur, bagli: Boolean(b),", test: T },
  { ad: "5E-4J: gorunum: pil kisitlamasi anlik izleme kapaliyken de isteniyor", dosya: G, bul: "pilIste: d.anlik === true && !d.pilMuaf,", koy: "pilIste: !d.pilMuaf,", test: T },
  { ad: "5E-4J: gorunum: izin dugmesi izin varken de gorunuyor", dosya: G, bul: "izinIste: !d.izin && d.izinGerekli === true,", koy: "izinIste: d.izinGerekli === true,", test: T },
  { ad: "K10: gorunum: zarf dururken kartin 'ayarli degil' demesi gizleniyor", dosya: G,
    bul: '  if (ayarsiz) ayar = zarf ? "m.bl.kartta_ayarsiz_zarf" : "m.bl.kartta_ayarsiz";', koy: '  if (ayarsiz && !zarf) ayar = "m.bl.kartta_ayarsiz";', test: T },
  { ad: "K10: gorunum: zarf dururken 'ayarli degil' uyari sayilmiyor", dosya: G,
    bul: "ayarUyari: !zarf || (ayarsiz && kimlik !== null),", koy: "ayarUyari: !zarf,", test: T },
  { ad: "K10: gorunum: zarf dururken 'silinmedi' denmiyor", dosya: G,
    bul: 'zarf ? "m.bl.kartta_ayarsiz_zarf" : "m.bl.kartta_ayarsiz"', koy: '"m.bl.kartta_ayarsiz"', test: T },
  { ad: "5E-4J: gorunum: 'internet yok' uyari sayilmiyor", dosya: G,
    bul: 'izlemeUyari: ["internet", "guven", "araci", "ayar", "ic-hata"]', koy: 'izlemeUyari: ["guven", "araci", "ayar", "ic-hata"]', test: T },
  { ad: "5E-4J: gorunum: sinifCevir butun siniflari ceviriyor", dosya: G,
    bul: "(s === sinif ? !simdiKapali : kapali.includes(s))", koy: "(!simdiKapali)", test: T },
  { ad: "5E-4J: gorunum: zarf acilmadi hatasi genel metinle", dosya: G, bul: 'etiket: "m.bl.hata_zarf", ', koy: "", test: T },
  { ad: "5E-4J: soru: anlik izleme acikken de soruluyor", dosya: B,
    bul: "if (k !== kusak || d.anlik || d.calisiyor || !d.zarf) return;", koy: "if (k !== kusak || d.calisiyor || !d.zarf) return;", test: T },
  { ad: "5E-4J: soru: zarf yokken de soruluyor", dosya: B,
    bul: "if (k !== kusak || d.anlik || d.calisiyor || !d.zarf) return;", koy: "if (k !== kusak || d.anlik || d.calisiyor) return;", test: T },
  { ad: "5E-4J: soru: servis calisirken de soruluyor", dosya: B,
    bul: "if (k !== kusak || d.anlik || d.calisiyor || !d.zarf) return;", koy: "if (k !== kusak || d.anlik || !d.zarf) return;", test: T },
  { ad: "5E-4J: soru: 'ac' ayari asmiyor (buKayit gitmiyor)", dosya: B,
    bul: "basladi = (await bildirim.izlemeBaslat(kimlik, { buKayit: true })).basladi;", koy: "basladi = (await bildirim.izlemeBaslat(kimlik)).basladi;", test: T },
  { ad: "5E-4J: soru: sorulmadan 'ac' calisiyor", dosya: B,
    bul: "    if (hal !== \"soruluyor\") return;\n    const k = kusak;", koy: "    const k = kusak;", test: T },
  { ad: "5E-4J: soru: izin istenmiyor", dosya: B,
    bul: "if (!d.izin && d.izinGerekli) await bildirim.izinIste();", koy: "", test: T },
  { ad: "5E-4J: soru: izin penceresi olmayan surumde de izin isteniyor", dosya: B,
    bul: "if (!d.izin && d.izinGerekli) await bildirim.izinIste();", koy: "if (!d.izin) await bildirim.izinIste();", test: T },
  { ad: "5E-4J: soru: baslatilamayinca 'acildi' deniyor", dosya: B,
    bul: "if (k === kusak) yay(basladi ? \"acildi\" : \"acilamadi\");", koy: "if (k === kusak) yay(\"acildi\");", test: T },
  { ad: "5E-4J: soru: kayit bittikten sonra biten islem sonucu yaziyor", dosya: B,
    bul: "if (k === kusak) yay(basladi ? \"acildi\" : \"acilamadi\");", koy: "yay(basladi ? \"acildi\" : \"acilamadi\");", test: T },
  { ad: "5E-4J: soru: 'hayir' soruyu kapatmiyor", dosya: B,
    bul: "hayir: () => { if (hal === \"soruluyor\") yay(\"yok\"); },", koy: "hayir: () => {},", test: T },
  { ad: "5E-4J: soru: kayit bitince kalkmiyor", dosya: B,
    bul: "kayitBitti: () => { kusak += 1; yay(\"yok\"); },", koy: "kayitBitti: () => { kusak += 1; },", test: T },
  { ad: "5E-4J: izlemeBaslat: buKayit her zaman gidiyor", dosya: B,
    bul: "buKayit === true ? { kimlik: kimlikli(kimlik), buKayit: true } : { kimlik: kimlikli(kimlik) }", koy: "{ kimlik: kimlikli(kimlik), buKayit: true }", test: T },
  { ad: "5E-4J: adres: yeni baglantida servise verilmiyor", dosya: "src/cekirdek/bildirim.js",
    bul: "      if (typeof adres === \"string\" && typeof bildirim.adresYaz === \"function\") sirayla(() => bildirim.adresYaz(kimlik, adres));\n", koy: "", test: T },
  { ad: "5E-4J: adres: boy / tur denetimi yok", dosya: "src/cekirdek/bildirim.js",
    bul: "      if (typeof adres !== \"string\" || adres.length === 0 || adres.length > 21) throw new BildirimHatasi(\"bicim\");\n", koy: "", test: T },
  { ad: "5E-4J: kabuk: izleyiciye adres verilmiyor", dosya: "src/ekran/kabuk_durum.js",
    bul: "adres: b ? b.adres : null, kayit:", koy: "adres: null, kayit:", test: T },
  { ad: "5E-4J: yonerge: uretici suzulmeden geciyor", dosya: "src/cekirdek/bildirim.js",
    bul: "uretici: URETICILER.includes(y.uretici) ? y.uretici : \"diger\",", koy: "uretici: y.uretici,", test: T },
  { ad: "5E-4J: yonerge: bilinmeyen uretici cokertiyor / bos", dosya: "src/ekran/bildirim_gorunum.js",
    bul: "const u = Object.hasOwn(YONERGE, uretici) ? uretici : \"diger\";", koy: "const u = uretici;", test: T },
  { ad: "5E-4J: yonerge: Honor'a genel adimlar", dosya: "src/ekran/bildirim_gorunum.js",
    bul: "  honor: [\"m.bl.yn_honor_1\", \"m.bl.yn_honor_2\", \"m.bl.yn_honor_3\", \"m.bl.yn_honor_4\"],\n", koy: "  honor: [\"m.bl.yn_diger_1\", \"m.bl.yn_diger_2\"],\n", test: T },
  { ad: "5E-4J: yonerge: adim listesi disaridan degistirilebiliyor", dosya: "src/ekran/bildirim_gorunum.js",
    bul: "adimlar: [...YONERGE[u]], ozel:", koy: "adimlar: YONERGE[u], ozel:", test: T },
  { ad: "5E-4J: yonerge: 'diger' ozel sayiliyor", dosya: "src/ekran/bildirim_gorunum.js",
    bul: "ozel: u !== \"diger\" };", koy: "ozel: true };", test: T },
  { ad: "5E-4J: yonerge: gorunume tasinmiyor", dosya: "src/ekran/bildirim_gorunum.js",
    bul: "    yonerge: pilYonergesi(d.uretici),\n", koy: "    yonerge: pilYonergesi(\"diger\"),\n", test: T },
  { ad: "5E-C: B12: basarisiz zarf yenilemesi yeniden denenmiyor", dosya: B,
    bul: "        yenileBekle = YENILE_ARALIK_TIK;\n", koy: "        yenileBekle = 0;\n", test: "test/curutucu-5e" },
  { ad: "5E-C: B12: yeniden deneme araligi 300 tik", dosya: B,
    bul: "export const YENILE_ARALIK_TIK = 30;", koy: "export const YENILE_ARALIK_TIK = 300;", test: "test/curutucu-5e" },
  { ad: "5E-C: B12: yeniden deneme basarinca izleme yeniden baslatilmiyor", dosya: B,
    bul: "        if (yeniden && sonuc === \"yazildi\") sonG = null;", koy: "", test: "test/curutucu-5e" },
  { ad: "5E-C: B12: ilk basarida da izleme iki kez baslatiliyor", dosya: B,
    bul: "if (yeniden && sonuc === \"yazildi\") sonG = null;", koy: "if (sonuc === \"yazildi\") sonG = null;", test: "test/curutucu-5e" },
  { ad: "5E-C: B12: 'kartta ayarsiz' hata sayilip yeniden deneniyor", dosya: B,
    bul: "if (sonuc === \"yazildi\" || sonuc === \"kartta-ayarsiz\") {", koy: "if (sonuc === \"yazildi\") {", test: "test/curutucu-5e" },
  { ad: "5E-C: B13: iletilmeyen yerel durum yeniden iletilmiyor", dosya: B,
    bul: "      else if (basladi) yerelKalan = YEREL_DENEME;", koy: "", test: "test/curutucu-5e" },
  { ad: "5E-C: B13: servis baslatilmasa da yeniden iletiliyor", dosya: B,
    bul: "      else if (basladi) yerelKalan = YEREL_DENEME;", koy: "      else yerelKalan = YEREL_DENEME;", test: "test/curutucu-5e" },
  { ad: "5E-C: B13: iletildikten sonra da yeniden iletiliyor", dosya: B,
    bul: "      if (iletildi) yerelKalan = 0;\n      else if", koy: "      if (false) yerelKalan = 0;\n      else if", test: "test/curutucu-5e" },
  { ad: "5E-C: B14: kart degisince durum sifirlanmiyor", dosya: B,
    bul: "    if (bagliKimlik !== kimlik) {\n      bagliKimlik = kimlik;\n      sifirla();", koy: "    if (bagliKimlik === null) {\n      bagliKimlik = kimlik;\n      sifirla();", test: "test/curutucu-5e" },
  { ad: "5E-C: B15: izin penceresinden sonra kusak denetlenmiyor", dosya: B,
    bul: "      if (k !== kusak) return;                                      // izin penceresi acikken kayit bitti: BASLATILMAZ\n", koy: "", test: "test/curutucu-5e" },
  { ad: "5E-C: J02: kayitBasladi kusak denetimi yok", dosya: B,
    bul: "if (k !== kusak || d.anlik || d.calisiyor || !d.zarf) return;", koy: "if (d.anlik || d.calisiyor || !d.zarf) return;", test: "test/curutucu-5e" },
  { ad: "5E-C: J09: 'hayir' acilmis izlemenin sonucunu siliyor", dosya: B,
    bul: "hayir: () => { if (hal === \"soruluyor\") yay(\"yok\"); },", koy: "hayir: () => { yay(\"yok\"); },", test: "test/curutucu-5e" },
  { ad: "5E-C: J05: calisiyor tur denetimsiz", dosya: B,
    bul: "calisiyor: y.calisiyor === true,", koy: "calisiyor: Boolean(y.calisiyor),", test: "test/curutucu-5e" },
  { ad: "5E-C: J06: zarf tur denetimsiz", dosya: B,
    bul: "zarf: y.zarf === true,", koy: "zarf: Boolean(y.zarf),", test: "test/curutucu-5e" },
  { ad: "5E-C: J11: neden suzulmeden geciyor", dosya: B,
    bul: "neden: typeof y.neden === \"string\" && TUR.test(y.neden) ? y.neden : \"\" };", koy: "neden: y.neden };", test: "test/curutucu-5e" },
  { ad: "5E-C: J12: iletildi tur denetimsiz", dosya: B,
    bul: "return (await cagir(\"yerel\", { kimlik: kimlikli(kimlik), durum: kod, oturum })).iletildi === true;", koy: "return (await cagir(\"yerel\", { kimlik: kimlikli(kimlik), durum: kod, oturum })).iletildi;", test: "test/curutucu-5e" },
  { ad: "5E-C: K-11: KAYIT -> BEKLIYOR 'bitti' sayiliyor", dosya: B,
    bul: "return KAYITTA.includes(onceki) && Number.isInteger(yeni) && !KAYITTA.includes(yeni);", koy: "return KAYITTA.includes(onceki) && Number.isInteger(yeni) && yeni !== 2;", test: "test/curutucu-5e" },
  { ad: "5E-C: K-11: akis kopunca (bilinmiyor) 'bitti' sayiliyor", dosya: B,
    bul: "return KAYITTA.includes(onceki) && Number.isInteger(yeni) && !KAYITTA.includes(yeni);", koy: "return KAYITTA.includes(onceki) && !KAYITTA.includes(yeni);", test: "test/curutucu-5e" },
];
