// 5E-4 — bildirimin WebView yarisi. Kosum (mobil/ icinden): node mutasyon/kos.mjs --neden 5E-4J
const B = "src/cekirdek/bildirim.js";
const G = "src/ekran/bildirim_gorunum.js";
const K = "src/ekran/kabuk_durum.js";
const T = "test/bildirim.test.js";

export default [
  { ad: "5E-4J: bagli olmayan karta da zarf istegi gidiyor", dosya: B,
    bul: 'if (!d || d.durum !== "bagli" || typeof d.kimlik !== "string" || !KIMLIK.test(d.kimlik)) throw new BildirimHatasi("bagli-degil");',
    koy: 'if (!d) throw new BildirimHatasi("bagli-degil");', test: T },
  { ad: "5E-4J: 404'te eldeki zarf silinmiyor", dosya: B, bul: '        await cagir("zarfSil", { kimlik: d.kimlik });\n', koy: "", test: T },
  { ad: "5E-4J: her HTTP hatasinda zarf siliniyor", dosya: B, bul: 'if (tur === "http" && e.durum === 404) {', koy: 'if (tur === "http") {', test: T },
  { ad: "5E-4J: boyu tutmayan govde eklentiye veriliyor", dosya: B,
    bul: 'if (govde.length < ZARF_EN_AZ || govde.length > ZARF_AZAMI) throw new BildirimHatasi("bicim");\n', koy: "", test: T },
  { ad: "5E-4J: zarf ust siniri 4096", dosya: B, bul: "export const ZARF_AZAMI = 2048;", koy: "export const ZARF_AZAMI = 4096;", test: T },
  { ad: "5E-4J: eklentinin hata MESAJI yukari cikiyor", dosya: B,
    bul: 'throw new BildirimHatasi(e && typeof e.code === "string" && TUR.test(e.code) ? e.code : "ic-hata");',
    koy: 'throw new BildirimHatasi(e && e.message ? e.message : "ic-hata");', test: T },
  { ad: "5E-4J: kartin ag hatasi 'kart' diye gosteriliyor", dosya: B,
    bul: 'tur === "ag" || tur === "cihaz-silinmis"', koy: 'tur === "cihaz-silinmis"', test: T },
  { ad: "5E-4J: durum: izin alani oldugu gibi geciyor (tur denetimi yok)", dosya: B, bul: "izin: y.izin === true,", koy: "izin: y.izin,", test: T },
  { ad: "5E-4J: durum: bilinmeyen izleme adi geciyor", dosya: B,
    bul: 'izleme: IZLEME_DURUMLARI.has(y.izleme) ? y.izleme : "durduruldu",', koy: "izleme: y.izleme,", test: T },
  { ad: "5E-4J: durum: eklentinin butun alanlari yukari cikiyor", dosya: B, bul: "    return {\n      zarf: y.zarf === true,", koy: "    return {\n      ...y,\n      zarf: y.zarf === true,", test: T },
  { ad: "5E-4J: durum: bilinmeyen sinif geciyor", dosya: B,
    bul: "kapali: SINIFLAR.filter((s) => Array.isArray(y.kapali) && y.kapali.includes(s)),", koy: "kapali: Array.isArray(y.kapali) ? y.kapali : [],", test: T },
  { ad: "5E-4J: ayarYaz: gecersiz dil gidiyor", dosya: B, bul: "if (DILLER.includes(dil)) veri.dil = dil;", koy: "if (dil) veri.dil = dil;", test: T },
  { ad: "5E-4J: ayarYaz: anlik tur denetimsiz", dosya: B, bul: 'if (typeof anlik === "boolean") veri.anlik = anlik;', koy: "if (anlik) veri.anlik = anlik;", test: T },
  { ad: "5E-4J: yerel: eksi / kesirli sayi eklentiye gidiyor", dosya: B,
    bul: 'if (!Number.isInteger(kod) || !Number.isInteger(oturum) || kod < 0 || oturum < 0) throw new BildirimHatasi("bicim");\n', koy: "", test: T },
  { ad: "5E-4J: izlemeBaslat: kimlik denetimsiz", dosya: B,
    bul: 'const y = await cagir("izlemeBaslat", { kimlik: kimlikli(kimlik) });', koy: 'const y = await cagir("izlemeBaslat", { kimlik });', test: T },
  { ad: "5E-4J: bekliyor durumu kayit sayilmiyor", dosya: B, bul: "export const KAYITTA = Object.freeze([2, 4]);", koy: "export const KAYITTA = Object.freeze([2]);", test: T },
  { ad: "5E-4J: izleyici: zarf her tikte yenileniyor", dosya: B, bul: "    if (!oncekiBagli) {\n      oncekiBagli = true;", koy: "    if (true) {\n      oncekiBagli = true;", test: T },
  { ad: "5E-4J: izleyici: baglanti kopunca sifirlanmiyor (yeniden baglaninca zarf yenilenmez)", dosya: B,
    bul: "      oncekiBagli = false;\n      sonG = null;\n      return;", koy: "      return;", test: T },
  { ad: "5E-4J: izleyici: arka plandayken de calisiyor", dosya: B, bul: "if (!gorunur || !bagli ||", koy: "if (!bagli ||", test: T },
  { ad: "5E-4J: izleyici: ayni kayit durumu her tikte iletiliyor", dosya: B, bul: "    if (g === sonG) return;\n", koy: "", test: T },
  { ad: "5E-4J: izleyici: kayit bitince de izleme baslatiliyor", dosya: B,
    bul: "if (KAYITTA.includes(durum)) await bildirim.izlemeBaslat(kimlik).catch(() => {});", koy: "await bildirim.izlemeBaslat(kimlik).catch(() => {});", test: T },
  { ad: "5E-4J: izleyici: izleme baslatilamazsa yerel durum iletilmiyor", dosya: B,
    bul: "await bildirim.izlemeBaslat(kimlik).catch(() => {});", koy: "await bildirim.izlemeBaslat(kimlik);", test: T },
  { ad: "5E-4J: izleyici: isler sirasiz (zarf yazilmadan izleme baslar)", dosya: B,
    bul: "const sirayla = (is) => { kuyruk = kuyruk.then(is).catch(() => {}); };", koy: "const sirayla = (is) => { is().catch(() => {}); };", test: T },
  { ad: "5E-4J: izleyici: bicimsiz G satiri iletiliyor", dosya: B,
    bul: "if (!kayit || !Number.isInteger(kayit.durum) || !Number.isInteger(kayit.oturum) || kayit.durum < 0 || kayit.oturum < 0) return;",
    koy: "if (!kayit) return;", test: T },
  { ad: "5E-4J: kabuk: izleyicinin hatasi tiki durduruyor", dosya: K,
    bul: "    } catch { /* bildirim yok sayilir */ }\n", koy: "    } finally { /* yok */ }\n", test: T },
  { ad: "5E-4J: kabuk: izleyiciye kayit durumu verilmiyor", dosya: K, bul: "kimlik: b ? b.kimlik : null, kayit: akis.value.kayit });", koy: "kimlik: b ? b.kimlik : null, kayit: null });", test: T },
  { ad: "5E-4J: kabuk: eslesmemis kart 'bagli' sayiliyor", dosya: K,
    bul: 'bildirimIzle.tik({ gorunur, bagli: Boolean(b) && b.durum === "bagli",', koy: "bildirimIzle.tik({ gorunur, bagli: Boolean(b),", test: T },
  { ad: "5E-4J: gorunum: pil kisitlamasi anlik izleme kapaliyken de isteniyor", dosya: G, bul: "pilIste: d.anlik === true && !d.pilMuaf,", koy: "pilIste: !d.pilMuaf,", test: T },
  { ad: "5E-4J: gorunum: izin dugmesi izin varken de gorunuyor", dosya: G, bul: "izinIste: !d.izin && d.izinGerekli === true,", koy: "izinIste: d.izinGerekli === true,", test: T },
  { ad: "5E-4J: gorunum: zarf varken eski 'kartta ayarsiz' sonucu gosteriliyor", dosya: G,
    bul: 'if (!zarf && son === "kartta-ayarsiz")', koy: 'if (son === "kartta-ayarsiz")', test: T },
  { ad: "5E-4J: gorunum: 'internet yok' uyari sayilmiyor", dosya: G,
    bul: 'izlemeUyari: ["internet", "guven", "araci", "ayar", "ic-hata"]', koy: 'izlemeUyari: ["guven", "araci", "ayar", "ic-hata"]', test: T },
  { ad: "5E-4J: gorunum: sinifCevir butun siniflari ceviriyor", dosya: G,
    bul: "(s === sinif ? !simdiKapali : kapali.includes(s))", koy: "(!simdiKapali)", test: T },
  { ad: "5E-4J: gorunum: zarf acilmadi hatasi genel metinle", dosya: G, bul: 'etiket: "m.bl.hata_zarf", ', koy: "", test: T },
];
