// 5D-1 — depo.js mutasyonlari. Kosum (mobil/ icinden): node mutasyon/kos.mjs --neden 5D-depo
const DEPO = "src/cekirdek/depo.js";
const T = "test/depo.test.js";

export default [
  { ad: "5D-depo: kimlik denetlenmiyor (yol kacisi eklentiye kalir)", dosya: DEPO,
    bul: 'if (typeof kimlik !== "string" || !KIMLIK.test(kimlik)) throw new DepoHatasi("bicim");', koy: "", test: T },
  { ad: "5D-depo: kilit yok (iki esitleme ayni dosyaya yazar)", dosya: DEPO,
    bul: 'if (kilitler.has(kimlik)) throw new CalismaHatasi("depo: baska bir esitleme suruyor");', koy: "", test: T },
  { ad: "5D-depo: kilit nesneye bagli (ayni kimlikli ikinci depo kilidi gormez)", dosya: DEPO,
    bul: "      kilitler.add(kimlik);", koy: "      kilitler.add({});", test: T },
  { ad: "5D-depo: iki kez birakmak baskasinin kilidini aciyor", dosya: DEPO,
    bul: "        if (birakildi) return;", koy: "", test: T },
  { ad: "5D-depo: esitleme surerken sifirlanabiliyor", dosya: DEPO,
    bul: 'if (kilitler.has(kimlik)) throw new CalismaHatasi("depo: esitleme surerken sifirlanamaz");', koy: "", test: T },
  { ad: "5D-depo: bozuk durum.json 'bos depo' sayiliyor", dosya: DEPO,
    bul: 'try { d = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(b)); } catch { throw new DepoHatasi("bozuk"); }',
    koy: 'try { d = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(b)); } catch { return null; }', test: T },
  { ad: "5D-depo: nesne olmayan durum kabul ediliyor", dosya: DEPO,
    bul: '      if (d === null || typeof d !== "object" || Array.isArray(d)) throw new DepoHatasi("bozuk");', koy: "", test: T },
  { ad: "5D-depo: okuma tek parcada kaliyor (buyuk dosyanin yalniz basi okunur)", dosya: DEPO,
    bul: "        konum += b.length;", koy: "        break;", test: T },
  { ad: "5D-depo: okuma bas'i yok sayiyor", dosya: DEPO,
    bul: "for (let konum = bas; ;) {", koy: "for (let konum = 0; ;) {", test: T },
  { ad: "5D-depo: yazma yalniz ilk parcayi ekliyor", dosya: DEPO,
    bul: "for (let a = 0; a < v.length; a += yazmaParca) {", koy: "for (let a = 0; a < Math.min(v.length, 1); a += yazmaParca) {", test: T },
  { ad: "5D-depo: gorunumun (subarray) tamponunun TAMAMI ekleniyor", dosya: DEPO,
    bul: "if (ArrayBuffer.isView(b)) return new Uint8Array(b.buffer, b.byteOffset, b.byteLength);",
    koy: "if (ArrayBuffer.isView(b)) return new Uint8Array(b.buffer);", test: T },
  { ad: "5D-depo: eklentinin hata kodu suzulmuyor (yol / mesaj tur olarak disari cikar)", dosya: DEPO,
    bul: 'e && typeof e.code === "string" && TURLER.has(e.code) ? e.code : "ic-hata"',
    koy: 'e && typeof e.code === "string" ? e.code : "ic-hata"', test: T },
  { ad: "5D-depo: eklentinin sacma boyu 0 sayiliyor", dosya: DEPO,
    bul: '      if (!Number.isSafeInteger(y.boy) || y.boy < 0) throw new DepoHatasi("ic-hata");', koy: "", test: T },
  { ad: "5D-depo: eklenti istenenden buyuk parca dondurebiliyor", dosya: DEPO,
    bul: '        if (b.length > okumaParca) throw new DepoHatasi("ic-hata");', koy: "", test: T },
  { ad: "5D-depo: kirpma boyu denetlenmiyor", dosya: DEPO,
    bul: '      if (!Number.isSafeInteger(n) || n < 0) throw new RangeError("kirpma boyu gecersiz");', koy: "", test: T },
  { ad: "5D-depo: arsiv asil kalibrasyon dosyasinin ustune yaziyor", dosya: DEPO,
    bul: 'const y = await cagir("kalArsivle", { veri: base64Kodla(baytlar(b)) });',
    koy: 'await cagir("kalYaz", { veri: base64Kodla(baytlar(b)) }); const y = await cagir("kalArsivle", { veri: base64Kodla(baytlar(b)) });', test: T },
];
