// 5D-2 — esitleme.js mutasyonlari. Kosum (mobil/ icinden): node mutasyon/kos.mjs --neden 5D-esit
const E = "src/cekirdek/esitleme.js";
const T = "test/esitleme.test.js";
const TK = "test/esitleme_kabuk.test.js";
const KB = "src/ekran/kabuk_durum.js";
const DG = "src/ekran/durum_gorunum.js";

export default [
  { ad: "5D-esit: onay varsayilan ACIK (karta Go gider — A21 ihlali)", dosya: E,
    bul: "const onayli = onayAcik() === true;", koy: "const onayli = true;", test: T },
  { ad: "5D-esit: onay icin gevsek dogruluk (1, 'true', {} de acar)", dosya: E,
    bul: "const onayli = onayAcik() === true;", koy: "const onayli = Boolean(onayAcik());", test: T },
  { ad: "5D-esit: onay acikken de Go gitmiyor", dosya: E,
    bul: "        onay: onayli\n", koy: "        onay: false\n", test: T },
  { ad: "5D-esit: her simdi() yeni tur baslatiyor (suren tura baglanmiyor)", dosya: E,
    bul: "    if (!suren) {\n      suren = kos()", koy: "    if (true) {\n      suren = kos()", test: T },
  { ad: "5D-esit: istekler arasi bekleme yok", dosya: E,
    bul: "      if (kalan > 0) await bekle(kalan);", koy: "", test: T },
  { ad: "5D-esit: bekleme istek BITISINDEN sayiliyor (baslangictan degil)", dosya: E,
    bul: "    sonIstek = simdiMs();\n    return is();", koy: "    try { return await is(); } finally { sonIstek = simdiMs(); }", test: T },
  { ad: "5D-esit: kart bagli degilken esitleme deneniyor", dosya: E,
    bul: 'if (!d || d.durum !== "bagli" || typeof d.kimlik !== "string")', koy: 'if (!d || typeof d.kimlik !== "string")', test: T },
  { ad: "5D-esit: tik arka planda da esitliyor", dosya: E,
    bul: "    if (!gorunur || !bagli || suren) return false;", koy: "    if (!bagli || suren) return false;", test: T },
  { ad: "5D-esit: tik kart bagli degilken de esitliyor", dosya: E,
    bul: "    if (!gorunur || !bagli || suren) return false;", koy: "    if (!gorunur || suren) return false;", test: T },
  { ad: "5D-esit: tik araligi yok (her saniye esitler)", dosya: E,
    bul: "    if (sonDeneme !== null && simdiMs() - sonDeneme < aralikMs) return false;", koy: "", test: T },
  { ad: "5D-esit: tur surerken gelen olay unutuluyor (kaydin sonu sonraki 60 s'ye kalir)", dosya: E,
    bul: "    if (suren) tekrar = true;", koy: "    if (suren) tekrar = false;", test: T },
  { ad: "5D-esit: ek tur bayragi sifirlanmiyor (sonsuz tur)", dosya: E,
    bul: "if (tekrar) { tekrar = false; simdi(); }", koy: "if (tekrar) { simdi(); }", test: T },
  { ad: "5D-esit: kopya uyusmazliginda 'sifirla' onerilmiyor", dosya: E,
    bul: 'return { tur: "kopya-uyusmuyor", sifirlaOner: true };', koy: 'return { tur: "kopya-uyusmuyor", sifirlaOner: false };', test: T },
  { ad: "5D-esit: bozuk durum dosyasinda 'sifirla' onerilmiyor", dosya: E,
    bul: 'sifirlaOner: e.tur === "bozuk" };', koy: "sifirlaOner: false };", test: T },
  { ad: "5D-esit: hata dinleyicilere yayilmiyor", dosya: E,
    bul: '      yay({ hal: "hata", ', koy: '      hal = ({ ...hal, hal: "hata" }); void ({ hal: "hata", ', test: T },
  { ad: "5D-esit: dinleyicinin hatasi esitlemeyi dusuruyor", dosya: E,
    bul: "try { fn(hal); } catch { /* arayuz hatasi esitlemeyi etkilemez */ }", koy: "fn(hal);", test: T },
  { ad: "5D-esit: sifirla durumu 'bos'a cevirmiyor", dosya: E,
    bul: "    sonDeneme = null;\n    yay({ ...BOS });", koy: "    sonDeneme = null;", test: T },
  { ad: "5D-esit: ilk esitlemenin baslangic boslugu 'kopyada bosluk' sayiliyor", dosya: E,
    bul: "return liste.filter((b) => Array.isArray(b) && b[0] > 1).length;", koy: "return liste.length;", test: T },
  { ad: "5D-esit: gercek bosluk sayilmiyor", dosya: E,
    bul: "        bosluk: bosluklar(s.bosluk),", koy: "        bosluk: 0,", test: T },
  { ad: "5D-esit: kart yokken kopya sifirlanamiyor (son kimlik kullanilmiyor)", dosya: E,
    bul: "    if (kimlik === null) { try { kimlik = sonKimlik(); } catch { kimlik = null; } }\n    if (typeof kimlik", koy: "    if (typeof kimlik", test: T },
  { ad: "5D-esit: parca 8192 B degil", dosya: E,
    bul: "export const PARCA_BAYT = 8192;", koy: "export const PARCA_BAYT = 1100;", test: T },
  // ── kabuk ve ekran baglantisi (test/esitleme_kabuk.test.js) ──
  { ad: "5D-esit: kabuk eslesmemis kartta da esitleme kuruyor", dosya: KB,
    bul: '    const bagli = Boolean(b) && b.durum === "bagli";\n    if (!esit) {', koy: '    const bagli = Boolean(b);\n    if (!esit) {', test: TK },
  { ad: "5D-esit: yeni baglantida 'baglandi' yerine tik (ilk esitleme 60 s gecikebilir)", dosya: KB,
    bul: "    if (gorunur && bagli && !oncekiBagli) esit.baglandi();\n    else esit.tik({ gorunur, bagli });", koy: "    esit.tik({ gorunur, bagli });", test: TK },
  { ad: "5D-esit: her tikte 'baglandi' (60 s kurali devre disi)", dosya: KB,
    bul: "    oncekiBagli = gorunur && bagli;", koy: "    oncekiBagli = false;", test: TK },
  { ad: "5D-esit: kayit bitince esitleme tetiklenmiyor", dosya: KB,
    bul: "izleme.value.durum !== KDR.KAYIT) esit.kayitBitti();", koy: "izleme.value.durum !== KDR.KAYIT) void 0;", test: TK },
  { ad: "5D-esit: kayit SURERKEN de 'kayitBitti' tetikleniyor", dosya: KB,
    bul: "if (esit && onceki && onceki.durum === KDR.KAYIT && izleme.value && izleme.value.durum !== KDR.KAYIT)", koy: "if (esit && onceki && onceki.durum === KDR.KAYIT && izleme.value)", test: TK },
  { ad: "5D-esit: esitleme durumu ekrana yansimiyor (dinleyici baglanmiyor)", dosya: KB,
    bul: "      e.dinle((d) => { esitleme.value = { hazir: true, ...d }; });\n", koy: "", test: TK },
  { ad: "5D-esit: modul yuklenemezse 'hazir: false' denmiyor", dosya: KB,
    bul: "      esitleme.value = { ...ESITLEME_YOK, hazir: false };", koy: "", test: TK },
  { ad: "5D-esit: kopyaSifirla hatanin mesajini tur diye disari veriyor", dosya: KB,
    bul: '      await esit.sifirla();\n    } catch (e) {\n      throw new KabukHatasi(e && typeof e.tur === "string" ? e.tur : "?");', koy: "      await esit.sifirla();\n    } catch (e) {\n      throw new KabukHatasi(e.message);", test: TK },
  { ad: "5D-esit: gorunum — kart bagli degilken 'Simdi esitle' acik", dosya: DG,
    bul: 'anahtar, degerler: null, sinif, suruyor: false, dugme: bagli,', koy: 'anahtar, degerler: null, sinif, suruyor: false, dugme: true,', test: TK },
  { ad: "5D-esit: gorunum — esitleme surerken dugme acik", dosya: DG,
    bul: 'return sonuc("m.es.suruyor", "", { suruyor: true, dugme: false });', koy: 'return sonuc("m.es.suruyor", "", { suruyor: true });', test: TK },
  { ad: "5D-esit: gorunum — sifirla onerisi gevsek dogrulukla", dosya: DG,
    bul: "sifirlaOner: e.sifirlaOner === true,", koy: "sifirlaOner: Boolean(e.sifirlaOner),", test: TK },
  { ad: "5D-esit: gorunum — eksi dakika yaziliyor (saat geri gidince)", dosya: DG,
    bul: "Math.max(0, Math.floor((simdiMs - e.sonMs) / 60000))", koy: "Math.floor((simdiMs - e.sonMs) / 60000)", test: TK },
  { ad: "5D-esit: gorunum — bilinmeyen hata turu sozlukte olmayan anahtara gidiyor (prototip adi)", dosya: DG,
    bul: "const bilinen = Object.hasOwn(ESIT_HATA, e.hata) ? ESIT_HATA[e.hata] : null;", koy: 'const bilinen = typeof ESIT_HATA[e.hata] === "function" || ESIT_HATA[e.hata] ? ESIT_HATA[e.hata] : null;', test: TK },
  { ad: "5D-esit: onay ayari gevsek ('true', '0' disi her sey acik)", dosya: "src/cekirdek/esitleme_ayar.js",
    bul: 'return depo.getItem(ONAY_ANAHTARI) === "1";', koy: 'return Boolean(depo.getItem(ONAY_ANAHTARI));', test: TK },
  { ad: "5D-esit: onayYaz dogru olmayan degerle de aciyor", dosya: "src/cekirdek/esitleme_ayar.js",
    bul: "if (acik === true) depo.setItem", koy: "if (acik) depo.setItem", test: TK },
  { ad: "5D-esit: Durum'da 'Simdi esitle' hep acik", dosya: "src/ekran/Durum.vue",
    bul: ':disabled="!esit.dugme" @click="kabuk.simdiEsitle()"', koy: '@click="kabuk.simdiEsitle()"', test: TK },
  { ad: "5D-esit: kopya TEK dokunusla siliniyor", dosya: "src/ekran/EsitlemeAyar.vue",
    bul: "if (suruyor.value || !onayci.bas()) return;", koy: "if (suruyor.value) return;", test: TK },
  { ad: "5D-esit: esitleme acilis paketine statik giriyor / onay sabit", dosya: "src/cekirdek/uygulama.js",
    bul: "    onayAcik: esitlemeOnayi,", koy: "    onayAcik: () => true,", test: TK },
];
