// 5C-kabuk mutasyonlari (kabuk, ACIL DURDUR seridi, Durum / Canli gorunumleri).
// Kosum: node mutasyon/kos.mjs --liste mutasyon/kabuk-liste.mjs
const KABUK = "test/kabuk.test.js";
const EKRAN = "test/ekran.test.js";

export default [
  {
    ad: "5C-kabuk: DURDUR seridi yonlendirici cikisinin icine alindi",
    dosya: "src/App.vue",
    bul: '<main id="icerik" class="icerik"><router-view /></main>\n    <DurdurSeridi />',
    koy: '<main id="icerik" class="icerik"><router-view /><DurdurSeridi /></main>',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: DURDUR seridi sekmelerin altina indi",
    dosya: "src/App.vue",
    bul: "    <DurdurSeridi />\n",
    koy: "",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: serit yalniz kart bagliyken gorunuyor",
    dosya: "src/App.vue",
    bul: "<DurdurSeridi />",
    koy: '<DurdurSeridi v-if="kabuk.baglanti.value" />',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: serit bir ekrana da kondu (tek yerde degil)",
    dosya: "src/ekran/Kayitlar.vue",
    bul: 'import Ikon from "../bilesen/Ikon.vue";',
    koy: 'import Ikon from "../bilesen/Ikon.vue";\nimport DurdurSeridi from "../bilesen/DurdurSeridi.vue";',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: dokunus isleyicisine bekleme eklendi (once kart kuruluyor)",
    dosya: "src/bilesen/DurdurSeridi.vue",
    bul: '@click="acilDurdur"',
    koy: '@click="async () => { await kartAl(); acilDurdur(); }"',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: dokunus isleyicisine onay eklendi",
    dosya: "src/bilesen/DurdurSeridi.vue",
    bul: '@click="acilDurdur"',
    koy: '@click="onayla() && acilDurdur()"',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: acilDurdur kart kurulumunu bekliyor",
    dosya: "src/cekirdek/uygulama.js",
    bul: "  return durdurNesnesi.durdur();",
    koy: "  return parcalar().then(() => durdurNesnesi.durdur());",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: durdur adreslerinde onbellek okunmuyor",
    dosya: "src/cekirdek/uygulama.js",
    bul: "  try { kayit = yerelOnbellek(localStorage).oku(); } catch { kayit = null; }",
    koy: "  kayit = null;",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: durdur adreslerinde bagli adres okunmuyor",
    dosya: "src/cekirdek/uygulama.js",
    bul: "  try { bagli = kurulu ? kurulu.durum().adres : null; } catch { bagli = null; }",
    koy: "  bagli = null;",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: onbellek deposuna erisilemeyince bagli adres de kayboluyor (yakalama yok)",
    dosya: "src/cekirdek/uygulama.js",
    bul: "  try { kayit = yerelOnbellek(localStorage).oku(); } catch { kayit = null; }",
    koy: "  kayit = yerelOnbellek(localStorage).oku();",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: durdurma dugmesi gonderilirken kapaniyor",
    dosya: "src/bilesen/DurdurSeridi.vue",
    bul: '<button id="durdur" type="button" class="durdur" ',
    koy: '<button id="durdur" type="button" class="durdur" :disabled="hal === \'gonderiliyor\'" ',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: ULASILAMADI uyarisi birkac saniyede siliniyor",
    dosya: "src/bilesen/durdur_gorunum.js",
    bul: '  return hal === "durduruldu" ? DURDURULDU_SURE_MS : 0;',
    koy: "  return DURDURULDU_SURE_MS;",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: ULASILAMADI icin ayri gorunum yok",
    dosya: "src/bilesen/durdur_gorunum.js",
    bul: "  return Object.hasOwn(GORUNUM, hal) ? GORUNUM[hal] : GORUNUM.bos;",
    koy: '  return Object.hasOwn(GORUNUM, hal) && hal !== "ulasilamadi" ? GORUNUM[hal] : GORUNUM.bos;',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: DURDUR yuksekligi 56 px'in altina inebiliyor",
    dosya: "src/tema.css",
    bul: "--durdur-yukseklik: max(3.5rem, 56px);",
    koy: "--durdur-yukseklik: max(3.5rem, 44px);",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: sekme yuksekligi 48 px'in altinda",
    dosya: "src/tema.css",
    bul: "--sekme-yukseklik: max(3.5rem, 48px);",
    koy: "--sekme-yukseklik: max(2.5rem, 40px);",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: acik temada bir degisken eksik",
    dosya: "src/tema.css",
    bul: "    --volt: #2f63c6; --amper: #a85a06; --watt: #15784f;\n    --durdur",
    koy: "    --volt: #2f63c6; --amper: #a85a06;\n    --durdur",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: acik temada ikincil metin kontrasti dusuk",
    dosya: "src/tema.css",
    bul: "  --yazi: #18202a; --soluk: #5b6775; --vurgu: #0b5d67; --vurgu-zemin: #e3f1f2;\n  --dolgu",
    koy: "  --yazi: #18202a; --soluk: #9aa3ad; --vurgu: #0b5d67; --vurgu-zemin: #e3f1f2;\n  --dolgu",
    test: KABUK,
  },
  {
    ad: "5C-kabuk: 'Kaydi durdur' DURDUR gorunumunu kullaniyor",
    dosya: "src/ekran/KayitDugmesi.vue",
    bul: 'id="kayit-durdur" type="button" class="dugme"',
    koy: 'id="kayit-durdur" type="button" class="durdur"',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: eslestirme tam sayfa katmanda aciliyor (seridi orter)",
    dosya: "src/ekran/Esles.vue",
    bul: '  <div id="es-ekran" class="ayar">',
    koy: '  <div id="es-ekran" class="ayar ion-page">',
    test: KABUK,
  },
  {
    ad: "5C-kabuk: hiz eslemesi yanlis (5/s -> 100 ms)",
    dosya: "src/ekran/canli_gorunum.js",
    bul: '  Object.freeze({ ms: 200, yazi: "5/s" }),\n  Object.freeze({ ms: 100, yazi: "10/s" }),',
    koy: '  Object.freeze({ ms: 100, yazi: "5/s" }),\n  Object.freeze({ ms: 200, yazi: "10/s" }),',
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: hiz komutu listede olmayan degeri de yolluyor",
    dosya: "src/ekran/canli_gorunum.js",
    bul: "  return HIZLAR.some((h) => h.ms === ms) ? `Gb${ms}` : null;",
    koy: "  return `Gb${ms}`;",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: kart yok durumu atlandi (Canli 'baglaniyor' diyor)",
    dosya: "src/ekran/canli_gorunum.js",
    bul: '  if (!baglanti) return sonuc(araniyor ? "m.dr.araniyor" : "m.cn.kart_yok", araniyor ? "" : "uyari");',
    koy: '  if (!baglanti) return sonuc("m.cn.baglaniyor", "");',
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: akis hatasinda 'kart bu agda degil' denmiyor",
    dosya: "src/ekran/canli_gorunum.js",
    bul: '    case "hata": return sonuc("m.cn.kart_yok", "uyari");',
    koy: '    case "hata": return sonuc("m.dr.bu_agda", "iyi", { akiyor: true, komut: true });',
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: yuva doluyken '4 izleyici' denmiyor",
    dosya: "src/ekran/canli_gorunum.js",
    bul: '    case "dolu": return sonuc("m.cn.dolu", "uyari", { komut: true });',
    koy: '    case "dolu": return sonuc("m.cn.baglaniyor", "", { komut: true });',
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: akis akmiyorken eski olcum gosteriliyor",
    dosya: "src/ekran/Canli.vue",
    bul: "olcumYazilari(hal.value.akiyor ? kabuk.akis.value.son : null)",
    koy: "olcumYazilari(kabuk.akis.value.son)",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: G satiri yokken 'kayit yok' deniyor (bilinmiyor yerine)",
    dosya: "src/ekran/durum_gorunum.js",
    bul: 'return { var: false, suruyor: false, rozet: "m.dr.kayit_bilinmiyor"',
    koy: 'return { var: false, suruyor: false, rozet: "m.dr.kayit_yok"',
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: ilk G'de suren kaydin suresi uyduruluyor",
    dosya: "src/ekran/durum_gorunum.js",
    bul: "basMs: onceki ? simdiMs : null",
    koy: "basMs: simdiMs",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: doluluk bindesi yuzde diye gosteriliyor",
    dosya: "src/ekran/durum_gorunum.js",
    bul: "Math.round(binde / 10)",
    koy: "Math.round(binde)",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: guc iki yerine uc haneli",
    dosya: "src/ekran/durum_gorunum.js",
    bul: "Math.abs(w) >= 1000 ? 1 : 2",
    koy: "Math.abs(w) >= 1000 ? 1 : 3",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: ADC hatasinda gerilim yine gosteriliyor",
    dosya: "src/ekran/durum_gorunum.js",
    bul: "    v: vYok ? YOK : voltYaz(son.v),",
    koy: "    v: voltYaz(son.v),",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: arka plana gecince akis kapanmiyor",
    dosya: "src/ekran/kabuk_durum.js",
    bul: '    if (belge && belge.visibilityState === "hidden") kapat();\n    else ac().catch(() => {});',
    koy: "    ac().catch(() => {});",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: canli beklenirken arka plana gecilse de akis aciliyor",
    dosya: "src/ekran/kabuk_durum.js",
    bul: "    if (!gorunur) return;                                   // beklerken arka plana gecti: ACMA\n",
    koy: "",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: eslesmemis kartta da akis aciliyor",
    dosya: "src/ekran/kabuk_durum.js",
    bul: '    if (!gorunur || !baglanti.value || baglanti.value.durum !== "bagli") return;',
    koy: "    if (!gorunur || !baglanti.value) return;",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: secilen hiz yeni oturuma yazilmiyor",
    dosya: "src/ekran/kabuk_durum.js",
    bul: "    bekleyenHiz = bekleyen;\n",
    koy: "",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: kart bulunamayinca yeniden denenmiyor",
    dosya: "src/ekran/kabuk_durum.js",
    bul: '    if ((!b || b.durum === "bulunamadi") && t - sonDeneme >= YENIDEN_DENE_MS) { yenidenBaglan(); return; }\n',
    koy: "",
    test: EKRAN,
  },
  {
    ad: "5C-kabuk: PBKDF2 yanlis sonucu 'basvuru yok' diye gosteriliyor",
    dosya: "src/ekran/olcum_gorunum.js",
    bul: 'o.dogru === false ? "m.ol.yanlis" : "m.ol.basvuru_yok"',
    koy: '"m.ol.basvuru_yok"',
    test: EKRAN,
  },
];
