// Kotlin (JVM birim testi) mutasyonlari: her iddianin onu YALANLAYAN degisikligi.
//   ad    : "<dilim>: ne bozuluyor"
//   dosya : mobil/'e gore; bul: kaynakta TAM BIR KEZ gecen dizgi; koy: yerine konan
//   kirmizi: bu mutasyonda kirmiziya donmesi beklenen test (elle dogrulandi, 2026-10-04)
// Test: cd android && ./gradlew.bat testDebugUnitTest  (her mutasyon ayri kosu, ~1 dk) — KIRMIZI beklenir.
// fsync'in kalkmasi JVM testinde gozlenemez (elektrik kesmesi gerekir): bilerek listede YOK.
const KASA = "android/app/src/main/java/tr/olcumkarti/mobil/kasa/";
const AG = "android/app/src/main/java/tr/olcumkarti/mobil/ag/";
const DEPO = "android/app/src/main/java/tr/olcumkarti/mobil/depo/";
const BILDIRIM = "android/app/src/main/java/tr/olcumkarti/mobil/bildirim/";

import { guncelle } from "./guncel-desen.mjs";

const HAM = [
  // ── 5F paylasim deposu ──
  { ad: "5F-K: ad denetimi yok (dizin disina yazilabilir)", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "if (ad == null || !AD.matches(ad) || ad.contains(\"..\")) throw PaylasHatasi(\"bicim\")", koy: "if (ad == null) throw PaylasHatasi(\"bicim\")",
    kirmizi: "PaylasDeposuTest.adDosyaSisteminegider_gecersizAdHerIslemdeReddedilir_dizinDisinaYazilmaz" },
  { ad: "5F-K: '..' iceren ad kabul", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: " || ad.contains(\"..\")) throw PaylasHatasi(\"bicim\")", koy: ") throw PaylasHatasi(\"bicim\")",
    kirmizi: "PaylasDeposuTest.adDosyaSisteminegider_gecersizAdHerIslemdeReddedilir_dizinDisinaYazilmaz" },
  { ad: "5F-K: her uzanti kabul", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "\\.(csv|kyt|txt|html|pdf)$\")", koy: "\\.[a-z]+$\")",
    kirmizi: "PaylasDeposuTest.adDosyaSisteminegider_gecersizAdHerIslemdeReddedilir_dizinDisinaYazilmaz" },
  { ad: "5F-K: baslat onceki dosyayi silmiyor", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "        val hedef = dosya(ad)\n        temizle()\n", koy: "        val hedef = dosya(ad)\n",
    kirmizi: "PaylasDeposuTest.baslat_oncekiPaylasiminDosyasiniSiler_tekDosyaKalir" },
  { ad: "5F-K: baslatilmadan yazilabiliyor", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "        if (acik == null || acik != ad) throw PaylasHatasi(\"sira\")\n        if (parca.size > PARCA_AZAMI)", koy: "        if (parca.size > PARCA_AZAMI)",
    kirmizi: "PaylasDeposuTest.sira_baslatilmadanYaDaBaskaAdlaYazilamaz_bitirildiktenSonraYazilamaz" },
  { ad: "5F-K: bitirildikten sonra yazilabiliyor", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "        acik = null\n        if (boy <= 0 || boy != yazilan", koy: "        if (boy <= 0 || boy != yazilan",
    kirmizi: "PaylasDeposuTest.sira_baslatilmadanYaDaBaskaAdlaYazilamaz_bitirildiktenSonraYazilamaz" },
  { ad: "5F-K: boy denetimi yok", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "if (boy <= 0 || boy != yazilan || hedef.length() != boy) { temizle(); throw PaylasHatasi(\"boy\") }", koy: "",
    kirmizi: "PaylasDeposuTest.boy_beklenenleTutmazsaDosyaSilinir_bosDosyaPaylasilmaz" },
  { ad: "5F-K: boyu tutmayan dosya silinmiyor", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "if (boy <= 0 || boy != yazilan || hedef.length() != boy) { temizle(); throw PaylasHatasi(\"boy\") }", koy: "if (boy <= 0 || boy != yazilan || hedef.length() != boy) { throw PaylasHatasi(\"boy\") }",
    kirmizi: "PaylasDeposuTest.boy_beklenenleTutmazsaDosyaSilinir_bosDosyaPaylasilmaz" },
  { ad: "5F-K: toplam boy siniri yok", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "if (yazilan + parca.size > AZAMI) { temizle(); throw PaylasHatasi(\"cok-buyuk\") }", koy: "",
    kirmizi: "PaylasDeposuTest.sinirlar_parcaVeToplamBoy" },
  { ad: "5F-K: parca boy siniri yok", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "        if (parca.size > PARCA_AZAMI) throw PaylasHatasi(\"bicim\")\n", koy: "",
    kirmizi: "PaylasDeposuTest.sinirlar_parcaVeToplamBoy" },
  { ad: "5F-K: parcalar ustune yaziliyor (ekleme degil)", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/paylas/PaylasDeposu.kt",
    bul: "FileOutputStream(hedef, true).use { it.write(parca) }", koy: "FileOutputStream(hedef, false).use { it.write(parca) }",
    kirmizi: "PaylasDeposuTest.baslatYazBitir_parcalarSirayla_dosyaAyniBaytlar" },
  {
    ad: "5B-K: sayacta geri denetimi kalkti",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (isaret < eski) throw KasaHatasi("geri")',
    koy: "",
    kirmizi: "SayacDosyasiTest.kucukDegerGeri_dosyaDegismez",
  },
  {
    ad: "5B-K: sayacta ESIT yazim kabul ediliyor (ikinci yazar ayni blogu kullanir — curutucu 5B S4)",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (vardi && isaret == eski) throw KasaHatasi("geri")',
    koy: "",
    kirmizi: "SayacDosyasiTest.esitYazimGeri_buyukKabul",
  },
  {
    ad: "5B-K: dosya yokken ilk yazim (0 dahil) 'geri' sayiliyor",
    dosya: KASA + "SayacDosyasi.kt",
    bul: "if (vardi && isaret == eski) throw",
    koy: "if (isaret == eski) throw",
    kirmizi: "SayacDosyasiTest.dosyaYokkenHerDegerIlkYazimdir_sifirDahil",
  },
  {
    ad: "5B-K: sil once sayaci siliyor (yarida kalirsa eski K sayac 0 ile yasar)",
    dosya: KASA + "KasaDeposu.kt",
    bul: "if (it == kimlik + ANAHTAR_EK) 0 else 1",
    koy: "if (it == kimlik + ANAHTAR_EK) 1 else 0",
    kirmizi: "KasaDeposuTest.silOnceAnahtariSiler_yaridaKalirsaAnahtarYasamaz",
  },
  {
    ad: "5B-K: bozuk saglamali sayac dosyasi kabul ediliyor",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (satirlar[1] != saglama(satirlar[0])) throw KasaHatasi("bozuk")',
    koy: "",
    kirmizi: "SayacDosyasiTest.bozukVeYarimDosyaBozuk_sifirDonmez",
  },
  {
    ad: "5B-K: kimlik deseni gevsedi (yol kacisi)",
    dosya: KASA + "KasaKayit.kt",
    bul: "kimlik.all { it in '0'..'9' || it in 'a'..'f' }",
    koy: "true",
    kirmizi: "KasaDeposuTest.kotuKimlikHerIslemdeBicim_dizinDisinaCikilamaz",
  },
  {
    ad: "5B-K: AAD'den kimlik cikti",
    dosya: KASA + "KasaKayit.kt",
    bul: "SIHIR + byteArrayOf(SURUM) + kimlik.toByteArray(Charsets.US_ASCII)",
    koy: "SIHIR + byteArrayOf(SURUM)",
    kirmizi: "KasaKayitTest.yanlisKimlikleAcilmaz",
  },
  {
    ad: "5B-K: anahtar uzunlugu denetimi kalkti",
    dosya: KASA + "KasaKayit.kt",
    bul: 'if (anahtar.size != ANAHTAR_BOYU) throw KasaHatasi("bicim")',
    koy: "",
    kirmizi: "KasaKayitTest.anahtarUzunluguTam32",
  },
  {
    ad: "5B-K: sil sayac dosyasini birakiyor",
    dosya: KASA + "KasaDeposu.kt",
    bul: 'ad.startsWith("$kimlik.")',
    koy: "ad == kimlik + ANAHTAR_EK",
    kirmizi: "KasaDeposuTest.silSonrasiYokVeSayacSifir",
  },
  {
    ad: "5A-K: HttpIstek toplam sure bekcisi kurulmuyor",
    dosya: AG + "HttpIstek.kt",
    bul: "}, zamanAsimiMs.toLong(), TimeUnit.MILLISECONDS)",
    koy: "}, Long.MAX_VALUE / 2, TimeUnit.MILLISECONDS)",
    kirmizi: "HttpIstekTest.baslikDamlatanSunucuToplamSureyleKesilir",
  },
  {
    ad: "5A-K: cozulen adres ozel adres suzgecinden gecmiyor",
    dosya: AG + "HedefCoz.kt",
    bul: "adresler.firstOrNull { Hedef.ozelAdres(it) }",
    koy: "adresler.firstOrNull()",
    kirmizi: "HedefCozTest.adCozulurVeCozulenAdresDeKuraldanGecer",
  },
  {
    ad: "5C-K: 4096 bayti asan SSE satiri bos satir gibi isleniyor (olay yarim veriyle dagitilir)",
    dosya: AG + "SseAyirici.kt",
    bul: "if (uzun) {",
    koy: "if (false) {",
    kirmizi: "SseAyiriciTest.satirSiniri4096Bayt_uzunSatirinOlayiAtilirSonrakiSaglam",
  },
  {
    ad: "5C-K: adli olaylar (kimlik: oturum jetonu) da satir olarak JS'e tasiniyor",
    dosya: AG + "Akis.kt",
    bul: 'if (o.ad.isEmpty() || o.ad == "message") satirlar.add(o.veri)',
    koy: "satirlar.add(o.veri)",
    kirmizi: "AkisTest.kartGibiAkis_satirlarSirayla_kimlikOlayiTasinmaz_baglantiBitinceKapandi",
  },
  {
    ad: "5C-K: kapat() baglantiyi kesmiyor (bloklu okuma surer, kartin yuvasi dolu kalir)",
    dosya: AG + "Akis.kt",
    bul: "try { baglanti?.disconnect() } catch (_: Exception) {}",
    koy: "",
    kirmizi: "AkisTest.kapat_blokluOkumayiHemenKeser_tekBitis_sonrasindaSatirYok",
  },
  // ── 5D-1 KartDepo ──
  { ad: "5D-K: kimlik bicimi denetlenmiyor (yol kacisi)", dosya: DEPO + "KartDepo.kt",
    bul: "if (kimlik == null || !KIMLIK.matches(kimlik)) throw DepoHatasi(\"bicim\")", koy: "if (kimlik == null) throw DepoHatasi(\"bicim\")",
    kirmizi: "KartDepoTest.kimlikYalniz16OnaltilikHane_yolKacisiYok" },
  { ad: "5D-K: ekleme dosyanin ustune yaziyor (sona eklemiyor)", dosya: DEPO + "KartDepo.kt",
    bul: "FileOutputStream(f, true).use { a ->", koy: "FileOutputStream(f, false).use { a ->",
    kirmizi: "KartDepoTest.ekle_sonaEkler_boyDoner_parcaliOkumaAyniBaytlar" },
  { ad: "5D-K: okuma bas konumuna gitmiyor", dosya: DEPO + "KartDepo.kt",
    bul: "                r.seek(bas)\n", koy: "",
    kirmizi: "KartDepoTest.ekle_sonaEkler_boyDoner_parcaliOkumaAyniBaytlar" },
  { ad: "5D-K: kirpma dosya boyunu degistirmiyor", dosya: DEPO + "KartDepo.kt",
    bul: "                r.setLength(n)\n", koy: "",
    kirmizi: "KartDepoTest.kirp_kisaltir_uzatirsaSifirDoldurur" },
  { ad: "5D-K: durum gecici dosyaya degil dogrudan hedefe yaziliyor (yarim durum gorulebilir)", dosya: DEPO + "KartDepo.kt",
    bul: "val g = File(hedef.parentFile, hedef.name + GECICI_EK)", koy: "val g = File(hedef.parentFile, hedef.name)",
    kirmizi: "KartDepoTest.durumVeKalibrasyon_atomik_geciciKalintiOkumayiEtkilemez" },
  { ad: "5D-K: arsiv ayni adin ustune yaziyor", dosya: DEPO + "KartDepo.kt",
    bul: "while (File(d, ad).exists()) {", koy: "while (false) {",
    kirmizi: "KartDepoTest.arsiv_zamanDamgaliAd_cakismadaNumara_icerikAyni" },
  { ad: "5D-K: okuma tavani yok", dosya: DEPO + "KartDepo.kt",
    bul: "if (bas < 0 || azami < 1 || azami > OKUMA_AZAMI) throw DepoHatasi(\"bicim\")", koy: "if (bas < 0 || azami < 1) throw DepoHatasi(\"bicim\")",
    kirmizi: "KartDepoTest.sinirlar_okumaYazmaKirpma" },
  { ad: "5D-K: sifirla dizini birakiyor", dosya: DEPO + "KartDepo.kt",
    bul: "        if (!d.delete() && d.exists()) throw DepoHatasi(\"yazilamadi\")\n    }\n\n    /** Depolama", koy: "    }\n\n    /** Depolama",
    kirmizi: "KartDepoTest.sifirla_yalnizOKartinDosyalari_sonraBos" },
  // ── 5E-3 bildirim karar katmani (Python basvurusuyla vektor esdegerligi) ──
  { ad: "5E-3K: vasiyet kayit SURMEZKEN de 'karttan haber yok' (A33 ihlali)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (suruyor != true) return\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kart yerelde gorunse de 'karttan haber yok' (ev interneti ayirt edilmiyor, A36)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "val hedef = if (yerelErisim()) \"ev\" else \"kopuk\"", koy: "val hedef = \"kopuk\"",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kart donunce bildirim guncellenmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (baglanti != null) geriGeldi(pyIcinde(d[\"k\"], KAYITTA), d[\"o\"])\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: donuste kayit bitmisse de 'kayit suruyor' deniyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (suruyor) goster(\"baglanti\", \"kopuk\", \"bld.geri_kayit\", mapOf(\"oturum\" to oturum))\n        else goster(\"baglanti\", \"kopuk\", \"bld.geri\", emptyMap())", koy: "goster(\"baglanti\", \"kopuk\", \"bld.geri_kayit\", mapOf(\"oturum\" to oturum))",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: QoS 1 yeniden teslim ikinci bildirim uretiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (an in goruldu) return                               // QoS 1 yeniden teslim\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: onceki calismada gorulen olay yeniden bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (pr != null && pr.first == a && n <= pr.second && !sonN.containsKey(a)) return", koy: "if (false) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kacirilan olaylar sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            kacirilan += eksik\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yeni acilisin ilk olaylari kacirilan sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (sonA != null) eksik = n - 1", koy: "if (sonA != null) eksik = 0",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: dolu sebebi (2) siradan 'bitti' gibi bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (pyEsit(s, 2)) {", koy: "if (false) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yeniden baslama sebebi (5) siradan 'bitti' gibi bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "} else if (pyEsit(s, 5)) {", koy: "} else if (false) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: basladi olayi devam almasa da bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "\"basladi\" -> if (pyEsit(d[\"devam\"], 1)) {", koy: "\"basladi\" -> if (true) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yollar arasi yineleme ayiklanmiyor (yerel + MQTT iki ayri bildirim)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        val m = eslesen(aile, a, oturum, simdi)\n", koy: "        val m: Kayit? = null\n",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: daha AZ ayrintili haber ayrintiliyi eziyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (sira <= m.sira) return", koy: "            if (false) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: guncelleme sessiz degil (ayni olay icin iki kez ses)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "cikis(Bildirim(m.etiket, sinif, anahtar, metinDegerleri(m), m.gosterildi))", koy: "cikis(Bildirim(m.etiket, sinif, anahtar, metinDegerleri(m), false))",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kapali sinif yine de gosteriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (!acik(sinif)) return\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: pencere dolan kayit silinmiyor (cok eski bildirim guncellenir)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        kayitlar.removeAll { simdi - it.t > pencereS }\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: oturumu bilinmeyen haber zaman sinirsiz esleniyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            } else if (simdi - r.t > yakinS) {\n                continue\n", koy: "            } else if (false) {\n                continue\n",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: farkli oturumlar ayni bildirimde birlesiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "                if (r.oturum != oturum) continue\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: deneme olaylari birbirini ayikliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (aile == \"deneme\") return null\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yerel yolda kopukluk kayit yokken de bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (suruyor == true) {\n                baglanti = \"yerel\"", koy: "            if (true) {\n                baglanti = \"yerel\"",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: MQTT bagliyken de yerel sessizlik 'kopuk' sayiliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (!yerelYol) return\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yerel G: oturum degisimi 'bitti' sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (od in KAYITTA && (durumKodu !in KAYITTA || oturum != oo)) {", koy: "if (od in KAYITTA && (durumKodu !in KAYITTA)) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: BEKLIYOR (4) durumu kayit sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "val KAYITTA = setOf(2L, 4L)", koy: "val KAYITTA = setOf(2L)",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kayit durumu: eski haber yenisini eziyor (yerel her zaman kazanir)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "(d == null || dt == null || gt >= dt)) return", koy: "(true)) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kesildi bildirimi oturum turunu / son gorulmeyi tasimiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (r.anahtar == \"bld.kesildi\") {", koy: "        if (false) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: etiket oturuma bagli degil (ayni oturumun guncellemesi baska bildirim kimligine gider)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (aile == \"oturum_sonu\" && oturum != null && oturum >= 0) return", koy: "if (false) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: Python esitligi: 1.0 / true cevrimici sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            is Double -> x == n.toDouble()\n            is Boolean -> (if (x) 1L else 0L) == n\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: 5.0 gibi ondalik deger tamsayi sayiliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "fun tam(x: Any?): Long? = x as? Long", koy: "fun tam(x: Any?): Long? = (x as? Long) ?: (x as? Double)?.toLong()",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: telefon penceresi PC ile ayni degil (900 s)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "const val PENCERE_S = 900.0", koy: "const val PENCERE_S = 30.0",
    kirmizi: "BildirimKararTest.telefonPencereleri_pcIleAyni_900Ve120Saniye" },
  { ad: "5E-3K: gorulen olay bellegi sinirsiz buyuyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        while (goruldu.size > AN_AZAMI) goruldu.remove(goruldu.first())\n", koy: "",
    kirmizi: "BildirimKararTest.gorulenOlayBellegiSinirli_enEskiAtilir" },
  { ad: "5E-3K: son (a, n) kalici yazilmiyor (yeniden baslayinca eski olaylar yeniden bildirilir)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        kaliciYaz(a, n)\n", koy: "",
    kirmizi: "BildirimKararTest.kaliciYazim_herYeniOlaydaSonAN_yinelenenVeBicimsizdeYok" },
  // ── 5E-3 bildirim metni (PC ile ayni cumleler) ──
  { ad: "5E-3M: yer tutucular doldurulmuyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "        for ((ad, d) in deg) s = s.replace(\"{$ad}\", d)\n", koy: "",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: bilinmeyen kod bos metin veriyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "?: metin(k.onek + \"bilinmeyen\", mapOf(\"kod\" to kodYazi))", koy: "?: \"\"",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: tr'de ondalik virgul yok", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "return if (dil == \"tr\") y.replace('.', ',') else y", koy: "return y",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: en'de ondalik virgul", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "return if (dil == \"tr\") y.replace('.', ',') else y", koy: "return y.replace('.', ',')",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: sayi olceklenmiyor (milli -> birim)", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "BigDecimal(x.toDouble() / s.bolen)", koy: "BigDecimal(x.toDouble())",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: yuvarlama yarim-yukari (Python'dan farkli)", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "RoundingMode.HALF_EVEN", koy: "RoundingMode.HALF_UP",
    kirmizi: "BildirimMetinTest.sayiSureKodVeEksikSablon" },
  { ad: "5E-3M: tamsayi olmayan deger sayi diye yaziliyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "val x = s.x as? Long ?: return \"?\"", koy: "val x = (s.x as? Number)?.toLong() ?: return \"?\"",
    kirmizi: "BildirimMetinTest.sayiSureKodVeEksikSablon" },
  { ad: "5E-3M: eksi sure yaziliyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "        if (m < 0) return \"?\"\n", koy: "",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: sure dakikalari 60'i asiyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "sn / 3600, sn / 60 % 60, sn % 60", koy: "sn / 3600, sn / 60, sn % 60",
    kirmizi: "BildirimMetinTest.pcIleAyniCumleler_butunSenaryolar_trVeEn" },
  { ad: "5E-3M: saat eki verilen dilimi kullanmiyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: ".apply { timeZone = saatDilimi }", koy: "",
    kirmizi: "BildirimMetinTest.sayiSureKodVeEksikSablon" },
  { ad: "5E-3M: eksik sablonda cokme yerine bos metin", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "var s = sozluk(anahtar) ?: return anahtar", koy: "var s = sozluk(anahtar) ?: return \"\"",
    kirmizi: "BildirimMetinTest.sayiSureKodVeEksikSablon" },
  { ad: "5E-3M: null deger 'null' yaziliyor", dosya: BILDIRIM + "BildirimMetin.kt",
    bul: "        null -> \"?\"\n", koy: "        null -> \"null\"\n",
    kirmizi: "BildirimMetinTest.sayiSureKodVeEksikSablon" },
  // ── 5E-4 izleyici (zarf -> araci -> karar zinciri) ──
  { ad: "5E-4K: onek disi konu isleniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (y.konu.startsWith(onek)) {", koy: "if (true) {",
    kirmizi: "IzleyiciTest.onekDisiKonu_yokSayilir_sayilmaz" },
  { ad: "5E-4K: atilan mesaj sayilmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                                atilan++\n", koy: "",
    kirmizi: "IzleyiciTest.etiketiTutmayanMesajAtilirVeSayilir_cozulenVarkenOturumSurer" },
  { ad: "5E-4K: cozulen mesaj sayilmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                                cozulen++\n", koy: "",
    kirmizi: "IzleyiciTest.zincir_kararVektorundekiSenaryo_araciUzerindenAyniBildirimler" },
  { ad: "5E-4K: anahtar siniri yok (cozulmeyen mesajlarla sonsuza dek dinler)", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (cozulen == 0 && atilan >= ATILAN_SINIR) bitir(\"anahtar\")", koy: "",
    kirmizi: "IzleyiciTest.hicMesajCozulemedenUcMesajAtilirsa_anahtar_ayarYenile" },
  { ad: "5E-4K: cozulen mesaj varken de anahtar eskidi deniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (cozulen == 0 && atilan >= ATILAN_SINIR)", koy: "if (atilan >= ATILAN_SINIR)",
    kirmizi: "IzleyiciTest.etiketiTutmayanMesajAtilirVeSayilir_cozulenVarkenOturumSurer" },
  { ad: "5E-4K: anahtar siniri 2", dosya: BILDIRIM + "Izleyici.kt",
    bul: "const val ATILAN_SINIR = 3", koy: "const val ATILAN_SINIR = 2",
    kirmizi: "IzleyiciTest.hicMesajCozulemedenUcMesajAtilirsa_anahtar_ayarYenile" },
  { ad: "5E-4K: tek seferlik okuma durumda kapanmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (tekSefer && kalan == \"durum\") bitir(\"durum-okundu\")", koy: "",
    kirmizi: "IzleyiciTest.tekSefer_kaliciDurumOkununcaKapanir_sonrakiMesajIslenmez" },
  { ad: "5E-4K: tek seferlik okuma herhangi bir mesajda kapaniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (tekSefer && kalan == \"durum\")", koy: "if (tekSefer)",
    kirmizi: "IzleyiciTest.tekSefer_kaliciDurumOkununcaKapanir_sonrakiMesajIslenmez" },
  { ad: "5E-4K: surekli kip de durumda kapaniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (tekSefer && kalan == \"durum\")", koy: "if (kalan == \"durum\")",
    kirmizi: "IzleyiciTest.tekSefer_durumGelmezse_20SaniyedeSureIleKapanir_surekliKipSurer" },
  { ad: "5E-4K: tek seferlik okuma sure dolunca kapanmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (tekSefer && simdiMs() >= son) bitir(\"sure\")", koy: "",
    kirmizi: "IzleyiciTest.tekSefer_durumGelmezse_20SaniyedeSureIleKapanir_surekliKipSurer" },
  { ad: "5E-4K: surekli kip de surede kapaniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (tekSefer && simdiMs() >= son)", koy: "if (simdiMs() >= son)",
    kirmizi: "IzleyiciTest.tekSefer_durumGelmezse_20SaniyedeSureIleKapanir_surekliKipSurer" },
  { ad: "5E-4K: tek seferlik sure 60 s", dosya: BILDIRIM + "Izleyici.kt",
    bul: "const val TEK_SEFER_MS = 20_000L", koy: "const val TEK_SEFER_MS = 60_000L",
    kirmizi: "IzleyiciTest.tekSefer_durumGelmezse_20SaniyedeSureIleKapanir_surekliKipSurer" },
  { ad: "5E-4K: tik karara ulasmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                        synchronized(kilit) { karar.tik() }\n", koy: "",
    kirmizi: "IzleyiciTest.tik_oturumBoyuncaKararaUlasir_yerelYolKopuguBildirilir" },
  { ad: "5E-4K: istemci dongusunde tik cagrilmiyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                tik()                                  // en gec TIK_MS'de bir (cagiranin saat isleri)\n", koy: "",
    kirmizi: "IzleyiciTest.tik_oturumBoyuncaKararaUlasir_yerelYolKopuguBildirilir" },
  { ad: "5E-4K: baglaninca karara bildirilmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                        synchronized(kilit) { karar.mqttBagliOldu(true) }\n", koy: "",
    kirmizi: "IzleyiciTest.mqttBagli_oturumBoyuncaDogru_bitinceYanlis" },
  { ad: "5E-4K: oturum bitince mqttBagli dogru kaliyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (bagli) synchronized(kilit) { karar.mqttBagliOldu(false) }", koy: "",
    kirmizi: "IzleyiciTest.mqttBagli_oturumBoyuncaDogru_bitinceYanlis" },
  { ad: "5E-4K: CONNACK 4/5 ayar sayilmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "b.tur == \"ret\" && (b.kod == 4 || b.kod == 5) ->", koy: "false ->",
    kirmizi: "IzleyiciTest.connackReddi_4ve5AyarYenile_digerleriAraci" },
  { ad: "5E-4K: her CONNACK reddi ayar sayiliyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "b.tur == \"ret\" && (b.kod == 4 || b.kod == 5) ->", koy: "b.tur == \"ret\" ->",
    kirmizi: "IzleyiciTest.connackReddi_4ve5AyarYenile_digerleriAraci" },
  { ad: "5E-4K: TLS hatasi 'internet yok' diye gosteriliyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "IzlemeBitis(if (e.tur == \"tls\") \"tls\" else \"ag\")", koy: "IzlemeBitis(\"ag\")",
    kirmizi: "IzleyiciTest.baglantiHatalari_tlsGuven_agInternet" },
  { ad: "5E-4K: ayar hatasi yeniden deneniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "\"ayar\", \"tamam\" -> null", koy: "\"tamam\" -> null",
    kirmizi: "IzleyiciTest.bekleme_ayarVeTamamDenenmez_internetHizli_guvenVeAraciSeyrek" },
  { ad: "5E-4K: internet kopmasinda ilk deneme 60 s", dosya: BILDIRIM + "Izleyici.kt",
    bul: "longArrayOf(2_000, 5_000,", koy: "longArrayOf(60_000, 5_000,",
    kirmizi: "IzleyiciTest.bekleme_ayarVeTamamDenenmez_internetHizli_guvenVeAraciSeyrek" },
  { ad: "5E-4K: guven hatasi hizli deneniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                \"internet\" -> INTERNET_MS", koy: "                \"internet\", \"guven\" -> INTERNET_MS",
    kirmizi: "IzleyiciTest.bekleme_ayarVeTamamDenenmez_internetHizli_guvenVeAraciSeyrek" },
  { ad: "5E-4K: zarf hatasi ayar sinifinda degil", dosya: BILDIRIM + "Izleyici.kt",
    bul: "\"zarf\", \"adres\", \"kimlik-ret\", \"anahtar\" -> \"ayar\"", koy: "\"adres\", \"kimlik-ret\", \"anahtar\" -> \"ayar\"",
    kirmizi: "IzleyiciTest.zarfAcilmazsa_zarf_baglantiDenenmez" },
  { ad: "5E-4K: kopma internet sinifinda degil (kart alarmi gibi islenir)", dosya: BILDIRIM + "Izleyici.kt",
    bul: "\"ag\", \"koptu\", \"sessiz\", \"zaman-asimi\" -> \"internet\"", koy: "\"ag\", \"sessiz\", \"zaman-asimi\" -> \"internet\"",
    kirmizi: "IzleyiciTest.aginKopmasi_internet_kartAlarmiDegil" },
  { ad: "5E-4K: kullanici ve giris zarftan alinmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "bilgi.kullanici.ifEmpty { null }, bilgi.parola.ifEmpty { null }", koy: "null, null",
    kirmizi: "IzleyiciTest.baglanti_zarftakiAdreseVeKimlikle_aboneligiOnekle_yalnizAbone" },
  { ad: "5E-4K: bos kullanici CONNECT'e bos dize diye konuyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "bilgi.kullanici.ifEmpty { null }", koy: "bilgi.kullanici",
    kirmizi: "IzleyiciTest.bosKullaniciVeGiris_connecteKonmaz" },
  { ad: "5E-4K: abonelik oneksiz (#: aracidaki her konu)", dosya: BILDIRIM + "Izleyici.kt",
    bul: "\"$onek#\",", koy: "\"#\",",
    kirmizi: "IzleyiciTest.baglanti_zarftakiAdreseVeKimlikle_aboneligiOnekle_yalnizAbone" },
  { ad: "5E-4K: baslamadan once durdur yok sayiliyor (baglanti aciliyor)", dosya: BILDIRIM + "Izleyici.kt",
    bul: "            if (dur) return IzlemeBitis(\"durduruldu\")\n", koy: "",
    kirmizi: "IzleyiciTest.durdur_baslamadanOnceCagrilirsaBaglanmaz_sirasindaCagrilirsaBiter" },
  { ad: "5E-4K: istemci kimligi sabit", dosya: BILDIRIM + "Izleyici.kt",
    bul: "            SecureRandom().nextBytes(b)\n", koy: "",
    kirmizi: "IzleyiciTest.bitisNesnesiVeIstemciKimligi_sirTasimaz" },
  // ── 5E-4b bildirim kabugunun saf parcalari (depo, ayar, kanal, dongu, kayit bitince durma) ──
  { ad: "5E-4B: zarf dosyasinda kimlik denetimi yok (dizin disina yazilabilir)", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (!KasaKayit.kimlikGecerli(kimlik)) throw ZarfHatasi(\"bicim\")\n        return File(kok, kimlik + ek)", koy: "return File(kok, kimlik + ek)",
    kirmizi: "BildirimKabukTest.kimlikDosyaAdinaGider_gecersizKimlikHerIslemdeReddedilir" },
  { ad: "5E-4B: sihirsiz veri zarf diye yaziliyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "for (i in Zarf.SIHIR.indices) if (zarf[i] != Zarf.SIHIR[i]) throw ZarfHatasi(\"bicim\")\n", koy: "",
    kirmizi: "BildirimKabukTest.zarf_bicimiTutmayanYazilmaz_eskiDosyaKalir" },
  { ad: "5E-4B: zarf boy siniri yok (yazarken)", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (zarf.size < Zarf.EN_AZ || zarf.size > ZARF_AZAMI) throw ZarfHatasi(\"bicim\")\n", koy: "",
    kirmizi: "BildirimKabukTest.zarf_bicimiTutmayanYazilmaz_eskiDosyaKalir" },
  { ad: "5E-4B: diskte bozulmus zarf okunuyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (!d.isFile || d.length() < Zarf.EN_AZ || d.length() > ZARF_AZAMI) return null", koy: "if (!d.isFile) return null",
    kirmizi: "BildirimKabukTest.zarf_diskteBozulmusDosya_yokSayilir" },
  { ad: "5E-4B: zarf ust siniri 4096", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "const val ZARF_AZAMI = 2048", koy: "const val ZARF_AZAMI = 4096",
    kirmizi: "BildirimKabukTest.zarf_bicimiTutmayanYazilmaz_eskiDosyaKalir" },
  { ad: "5E-4B: zarf silinmiyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (d.exists() && !d.delete()) throw ZarfHatasi(\"ic-hata\")", koy: "",
    kirmizi: "BildirimKabukTest.zarf_yazOkuSil_oldugunGibi_ustuneYazilir" },
  { ad: "5E-4B: son olay: eksi sayi kabul", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (a < 0 || n < 0) null else Pair(a, n)", koy: "Pair(a, n)",
    kirmizi: "BildirimKabukTest.sonOlay_yazOku_bozukDosyaNull" },
  { ad: "5E-4B: son olay: boyu tutmayan dosya okunuyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (!d.isFile || d.length() != 16L) return null", koy: "if (!d.isFile) return null",
    kirmizi: "BildirimKabukTest.sonOlay_yazOku_bozukDosyaNull" },
  { ad: "5E-4B: zarf kasa silmesinin kapsamadigi adla saklaniyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "const val ZARF_EK = \".zarf\"", koy: "const val ZARF_EK = \"-zarf\"",
    kirmizi: "BildirimKabukTest.eslesmeKaldirilinca_kasaSilmesiZarfiVeOlayiDaSiler" },
  { ad: "5E-4B: anlik izleme varsayilani ACIK", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "class BildirimAyar(val anlik: Boolean = false,", koy: "class BildirimAyar(val anlik: Boolean = true,",
    kirmizi: "BildirimKabukTest.ayar_varsayilan_anlikKapali_butunSiniflarAcik" },
  { ad: "5E-4B: bozuk ayarda anlik izleme aciliyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "val anlik = d[\"anlik\"] as? Boolean ?: false", koy: "val anlik = d[\"anlik\"] as? Boolean ?: true",
    kirmizi: "BildirimKabukTest.ayar_yazOku_gidisDonus_bozukVeGecersizAlanlarAyiklanir" },
  { ad: "5E-4B: ayarda bilinmeyen sinif tutuluyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "?.filterIsInstance<String>()?.filter { it in SINIFLAR }?.toSet() ?: emptySet()\n            val dil", koy: "?.filterIsInstance<String>()?.toSet() ?: emptySet()\n            val dil",
    kirmizi: "BildirimKabukTest.ayar_yazOku_gidisDonus_bozukVeGecersizAlanlarAyiklanir" },
  { ad: "5E-4B: ayarda bilinmeyen dil kabul", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "(d[\"dil\"] as? String)?.takeIf { it in DILLER } ?: \"tr\"", koy: "(d[\"dil\"] as? String) ?: \"tr\"",
    kirmizi: "BildirimKabukTest.ayar_yazOku_gidisDonus_bozukVeGecersizAlanlarAyiklanir" },
  { ad: "5E-4B: kapali sinif acik sayiliyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "fun acik(sinif: String): Boolean = sinif !in kapali", koy: "fun acik(sinif: String): Boolean = true",
    kirmizi: "BildirimKabukTest.ayar_yazOku_gidisDonus_bozukVeGecersizAlanlarAyiklanir" },
  { ad: "5E-4B: 'karttan haber yok' sessiz kanalda", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "\"kopuk\", \"dolu\", \"esik\" -> UYARI", koy: "\"dolu\", \"esik\" -> UYARI",
    kirmizi: "BildirimKabukTest.kanal_uyariSesliSiniflar_gerisiBilgi" },
  { ad: "5E-4B: dongu: ayar hatasinda yeniden deniyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "                \"ayar\" -> return \"ayar\"\n", koy: "",
    kirmizi: "BildirimKabukTest.dongu_ayarHatasindaDenemez_guvenVeAraciSeyrekDener" },
  { ad: "5E-4B: dongu: kayit bitince 'durduruldu' diyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "return if (b.tur == \"gerek-kalmadi\") \"kayit-bitti\" else \"durduruldu\"", koy: "return \"durduruldu\"",
    kirmizi: "BildirimKabukTest.dongu_internetYokkenHizlaYenidenDener_baglaninca_izleniyor_kayitBitinceDurur" },
  { ad: "5E-4B: dongu: baglanip kopan oturum bastan saymiyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "deneme = if (b.baglandi) 1 else deneme + 1", koy: "deneme = deneme + 1",
    kirmizi: "BildirimKabukTest.dongu_baglanipKopanOturumBastanSayar" },
  { ad: "5E-4B: dongu: deneme sayaci artmiyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "deneme = if (b.baglandi) 1 else deneme + 1", koy: "deneme = 1",
    kirmizi: "BildirimKabukTest.dongu_internetYokkenHizlaYenidenDener_baglaninca_izleniyor_kayitBitinceDurur" },
  { ad: "5E-4B: dongu: durum bildirilmiyor (kalici bildirim guncellenmez)", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "            durum(b.sinif)\n", koy: "",
    kirmizi: "BildirimKabukTest.dongu_internetYokkenHizlaYenidenDener_baglaninca_izleniyor_kayitBitinceDurur" },
  { ad: "5E-4B: dongu: baglaninca 'izleniyor' denmiyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "val b = oturum { durum(\"izleniyor\") }", koy: "val b = oturum { }",
    kirmizi: "BildirimKabukTest.dongu_internetYokkenHizlaYenidenDener_baglaninca_izleniyor_kayitBitinceDurur" },
  { ad: "5E-4B: dongu: durdurulan oturumun bitisi yorumlaniyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "            if (dur) break\n", koy: "",
    kirmizi: "BildirimKabukTest.dongu_durdurBeklerkenYaDaOturumdaGelirse_yeniOturumAcilmaz" },
  { ad: "5E-4B: izleyici: kayit bitince durmuyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "else if (simdiMs() - gereksiz >= GEREKSIZ_MS) bitir(\"gerek-kalmadi\")", koy: "",
    kirmizi: "IzleyiciTest.surdurHayirDerse_10SaniyeSonraGerekKalmadi_oAradaGelenMesajIslenir" },
  { ad: "5E-4B: izleyici: kayit bitince HEMEN duruyor (ayrinti kaybolur)", dosya: BILDIRIM + "Izleyici.kt",
    bul: "const val GEREKSIZ_MS = 10_000L", koy: "const val GEREKSIZ_MS = 0L",
    kirmizi: "IzleyiciTest.surdurHayirDerse_10SaniyeSonraGerekKalmadi_oAradaGelenMesajIslenir" },
  { ad: "5E-4B: izleyici: surdur yeniden evet deyince sayac sifirlanmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (surdur()) gereksiz = -1L\n                        else if (gereksiz < 0)", koy: "if (surdur()) { }\n                        else if (gereksiz < 0)",
    kirmizi: "IzleyiciTest.surdurYenidenEvetDerse_sayacSifirlanir_varsayilandaHicDurmaz" },
  { ad: "5E-4B: izleyici: gerek-kalmadi yeniden deneniyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "\"durduruldu\", \"durum-okundu\", \"sure\", \"gerek-kalmadi\" -> \"tamam\"", koy: "\"durduruldu\", \"durum-okundu\", \"sure\" -> \"tamam\"",
    kirmizi: "IzleyiciTest.surdurHayirDerse_10SaniyeSonraGerekKalmadi_oAradaGelenMesajIslenir" },
  // ── 5E-4c 15 dakikalik yoklama (A29 c, A30) ──
  { ad: "5E-4C: onceki durum SESLI oynatiliyor (her yoklamada eski bildirimler)", dosya: BILDIRIM + "Yoklama.kt",
    bul: "val k = BildirimKarar({ if (sesli) cikis(it) }, { saat }, acik)", koy: "val k = BildirimKarar({ cikis(it) }, { saat }, acik)",
    kirmizi: "YoklamaTest.kayitSurerkenKartCevrimdisi_kartanHaberYokBirKez_donunceAyniEtiketle" },
  { ad: "5E-4C: kayit durumu karsilastirilmiyor (kayit bitti hic bildirilmez)", dosya: BILDIRIM + "Yoklama.kt",
    bul: "        if (cevrimici) yerel(k, simdi)\n", koy: "",
    kirmizi: "YoklamaTest.kayitSuruyordu_artikSurmuyor_kayitBittiBirKez" },
  { ad: "5E-4C: onceki kayit durumu oynatilmiyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "            k.mqttMesaj(\"durum\", eski)\n            yerel(k, eski)\n", koy: "            k.mqttMesaj(\"durum\", eski)\n",
    kirmizi: "YoklamaTest.kayitSuruyordu_artikSurmuyor_kayitBittiBirKez" },
  { ad: "5E-4C: onceki 'haber yok' unutuluyor (her yoklamada yeniden alarm)", dosya: BILDIRIM + "Yoklama.kt",
    bul: "if (eski != null && onceki.kopuk) k.mqttMesaj(\"durum\", mapOf(\"c\" to 0L))", koy: "",
    kirmizi: "YoklamaTest.kayitSurerkenKartCevrimdisi_kartanHaberYokBirKez_donunceAyniEtiketle" },
  { ad: "5E-4C: sanal sure yok: eski yerel haber 'kart yerelde' sayiliyor (ev interneti koptu denir)", dosya: BILDIRIM + "Yoklama.kt",
    bul: "private const val ARALIK_S = 1000.0", koy: "private const val ARALIK_S = 0.0",
    kirmizi: "YoklamaTest.kayitSurerkenKartCevrimdisi_kartanHaberYokBirKez_donunceAyniEtiketle" },
  { ad: "5E-4C: okunamayan yoklama ozeti siliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "if (simdi == null) return Sonuc(onceki, false)", koy: "if (simdi == null) return Sonuc(null, false)",
    kirmizi: "YoklamaTest.okunamayanYoklama_ozetDegismez_bildirimYok" },
  { ad: "5E-4C: cevrimdisi durumda son cevrimici ozet atiliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "else YoklamaDurumu(eski, k.baglanti != null)", koy: "else YoklamaDurumu(null, k.baglanti != null)",
    kirmizi: "YoklamaTest.kayitSurerkenKartCevrimdisi_kartanHaberYokBirKez_donunceAyniEtiketle" },
  { ad: "5E-4C: kopuk bayragi hic yazilmiyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "else YoklamaDurumu(eski, k.baglanti != null)", koy: "else YoklamaDurumu(eski, false)",
    kirmizi: "YoklamaTest.kayitSurerkenKartCevrimdisi_kartanHaberYokBirKez_donunceAyniEtiketle" },
  { ad: "5E-4C: kopuk bayragi kayit yokken de yaziliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "else YoklamaDurumu(eski, k.baglanti != null)", koy: "else YoklamaDurumu(eski, true)",
    kirmizi: "YoklamaTest.kayitYokkenKartCevrimdisi_sessiz_ozetKopukDegil" },
  { ad: "5E-4C: cevrimdisiyken 'kayit suruyor' deniyor (servis bosuna baslar)", dosya: BILDIRIM + "Yoklama.kt",
    bul: "return Sonuc(yeni, cevrimici && k.kayitSuruyor() == true)", koy: "return Sonuc(yeni, k.kayitSuruyor() == true)",
    kirmizi: "YoklamaTest.kayitSurerkenKartCevrimdisi_kartanHaberYokBirKez_donunceAyniEtiketle" },
  { ad: "5E-4C: kayit suruyor bilgisi hep yanlis (servis hic baslamaz)", dosya: BILDIRIM + "Yoklama.kt",
    bul: "return Sonuc(yeni, cevrimici && k.kayitSuruyor() == true)", koy: "return Sonuc(yeni, false)",
    kirmizi: "YoklamaTest.ilkYoklama_bildirimYok_ozetSaklanir_kayitSuruyorBilgisiDoner" },
  { ad: "5E-4C: ozet: olcum / fazla alan diske yaziliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "ALANLAR.mapNotNull { a -> (d[a] as? Long)?.let { \"\\\"$a\\\":$it\" } }", koy: "d.keys.mapNotNull { a -> (d[a] as? Long)?.let { \"\\\"$a\\\":$it\" } }",
    kirmizi: "YoklamaTest.ozet_jsonGidisDonus_yalnizKararAlanlari_bozukNull" },
  { ad: "5E-4C: ozet: diskten gelen fazla alan ayiklanmiyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "?.filter { it.key in ALANLAR && it.value is Long }", koy: "?.filter { it.value is Long }",
    kirmizi: "YoklamaTest.ozet_jsonGidisDonus_yalnizKararAlanlari_bozukNull" },
  { ad: "5E-4C: ozet: kopuk bayragi gevsek okunuyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "m[\"kopuk\"] == true)", koy: "m[\"kopuk\"] != null)",
    kirmizi: "YoklamaTest.ozet_jsonGidisDonus_yalnizKararAlanlari_bozukNull" },
  { ad: "5E-4C: servis ozeti: cevrimdisinda son cevrimici durum atiliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "-> YoklamaDurumu(onceki?.cevrimici, kopuk)", koy: "-> YoklamaDurumu(null, kopuk)",
    kirmizi: "YoklamaTest.servisinOzeti_yoklamaServisinBildirdiginiYinelemez" },
  { ad: "5E-4C: servis ozeti: cevrimici durumda kopuk bayragi kaliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "-> YoklamaDurumu(icerik, false)", koy: "-> YoklamaDurumu(icerik, kopuk || (onceki?.kopuk == true))",
    kirmizi: "YoklamaTest.servisinOzeti_yoklamaServisinBildirdiginiYinelemez" },
  { ad: "5E-4C: ozet dosyasinda boy siniri yok", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (!d.isFile || d.length() > DURUM_AZAMI) return null", koy: "if (!d.isFile) return null",
    kirmizi: "YoklamaTest.ozetDosyasi_yazOku_kimlikDenetimi_eslesmeKalkincaSilinir" },
  { ad: "5E-4C: ozet kasa silmesinin kapsamadigi adla saklaniyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "const val DURUM_EK = \".durum\"", koy: "const val DURUM_EK = \"-durum\"",
    kirmizi: "YoklamaTest.ozetDosyasi_yazOku_kimlikDenetimi_eslesmeKalkincaSilinir" },
  { ad: "5E-4C: izleyici: gorulen durum cagirana verilmiyor (yoklama hicbir sey okumaz)", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                                if (kalan == \"durum\") durumGoruldu(icerik)\n", koy: "",
    kirmizi: "IzleyiciTest.tekSefer_kaliciDurumOkununcaKapanir_sonrakiMesajIslenmez" },
  // ── 5E-4d yerel yoklama (A36) ──
  { ad: "5E-4D: kimlik karsilastirilmiyor (o adresteki HER kart 'bizim kart')", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "DuzJson.nesne(String(y.govde, Charsets.UTF_8))[\"kimlik\"] == kimlik", koy: "DuzJson.nesne(String(y.govde, Charsets.UTF_8))[\"kimlik\"] != null",
    kirmizi: "YerelYoklamaTest.baskaKart_hataKodu_bozukYanit_agHatasi_gorunmuyor" },
  { ad: "5E-4D: hata kodlu yanit 'gorunuyor' sayiliyor", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "if (y.kod != 200 || y.govde.size > GOVDE_AZAMI) return false", koy: "if (y.govde.size > GOVDE_AZAMI) return false",
    kirmizi: "YerelYoklamaTest.baskaKart_hataKodu_bozukYanit_agHatasi_gorunmuyor" },
  { ad: "5E-4D: buyuk yanit kabul", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "if (y.kod != 200 || y.govde.size > GOVDE_AZAMI) return false", koy: "if (y.kod != 200) return false",
    kirmizi: "YerelYoklamaTest.baskaKart_hataKodu_bozukYanit_agHatasi_gorunmuyor" },
  { ad: "5E-4D: herkese acik IP yoklaniyor", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "            if (!Hedef.ozelAdres(h.ad)) return null\n", koy: "",
    kirmizi: "YerelYoklamaTest.adres_yalnizOzelIPv4_adVeHerkeseAcikAdreseISTEK_GITMEZ" },
  { ad: "5E-4D: kart cevrimiciyken / bilinmiyorken de yoklaniyor", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "fun gerekli(kartCevrimici: Boolean?): Boolean = kartCevrimici == false", koy: "fun gerekli(kartCevrimici: Boolean?): Boolean = kartCevrimici != true",
    kirmizi: "YerelYoklamaTest.gerekli_yalnizAraciAcikcaCevrimdisiDediginde" },
  { ad: "5E-4D: hic yoklanmiyor", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "fun gerekli(kartCevrimici: Boolean?): Boolean = kartCevrimici == false", koy: "fun gerekli(kartCevrimici: Boolean?): Boolean = false",
    kirmizi: "YerelYoklamaTest.gerekli_yalnizAraciAcikcaCevrimdisiDediginde" },
  { ad: "5E-4D: yoklama baska yola gidiyor", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "const val YOL = \"/eslestir/bilgi\"", koy: "const val YOL = \"/komut\"",
    kirmizi: "YerelYoklamaTest.kartGorunuyor_imzasizBilgiIstegi_kimlikTamEsitse" },
  { ad: "5E-4D: zaman asimi 20 s", dosya: BILDIRIM + "YerelYoklama.kt",
    bul: "const val ZAMAN_ASIMI_MS = 2_000", koy: "const val ZAMAN_ASIMI_MS = 20_000",
    kirmizi: "YerelYoklamaTest.kartGorunuyor_imzasizBilgiIstegi_kimlikTamEsitse" },
  { ad: "5E-4D: adres dosyasina gecersiz adres yaziliyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (adres == null || YerelYoklama.url(adres) == null) throw ZarfHatasi(\"bicim\")", koy: "if (adres == null) throw ZarfHatasi(\"bicim\")",
    kirmizi: "YerelYoklamaTest.adresDosyasi_yalnizOzelIPv4Yazilir_bozukDosyaNull_eslesmeKalkincaSilinir" },
  { ad: "5E-4D: diskte degistirilmis adres okunuyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "return if (YerelYoklama.url(a) != null) a else null", koy: "return a",
    kirmizi: "YerelYoklamaTest.adresDosyasi_yalnizOzelIPv4Yazilir_bozukDosyaNull_eslesmeKalkincaSilinir" },
  { ad: "5E-4D: adres kasa silmesinin kapsamadigi adla saklaniyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "const val ADRES_EK = \".adres\"", koy: "const val ADRES_EK = \"-adres\"",
    kirmizi: "YerelYoklamaTest.adresDosyasi_yalnizOzelIPv4Yazilir_bozukDosyaNull_eslesmeKalkincaSilinir" },
  { ad: "5E-C: B1: yoklama cozulemeyen kalici durumu 'anahtar' saymiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: " || (tekSefer && kalan == \"durum\"))) bitir(\"anahtar\")", koy: ")) bitir(\"anahtar\")",
    kirmizi: "Curutucu5eTest.b1_yoklama_eskimisAnahtarla_ayarYenilenmeliDemeli" },
  { ad: "5E-C: B2: bilinmeyen alt konu sayiliyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (kalan == \"durum\" || kalan == \"olay\") {", koy: "if (kalan != \"\") {",
    kirmizi: "Curutucu5eTest.b2_ucSahteMesaj_gecerliDurumdanOnceGelirse_izlemeAyaraDusmemeli" },
  { ad: "5E-C: B5: araciya ulasilamayinca kayit durumuna bakilmiyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "                if (!surdur()) return IzlemeBitis(\"gerek-kalmadi\")\n", koy: "",
    kirmizi: "Curutucu5eTest.b5_internetYokkenKayitBittiyse_donguBitmeli" },
  { ad: "5E-C: K09: olay mesaji 'durum goruldu' sayiliyor", dosya: BILDIRIM + "Izleyici.kt",
    bul: "if (kalan == \"durum\") durumGoruldu(icerik)", koy: "durumGoruldu(icerik)",
    kirmizi: "Curutucu5eEkTest.k09_olayMesaji_durumGorulduSayilmaz" },
  { ad: "5E-C: B3: telefonda ilk olayin oncesi 'kacirilan' sayiliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (!acilisBoslugu) eksik = 0                       // telefon: bu calismanin ilk olayi — oncesi sayilmaz\n            else if (sonA != null)", koy: "            if (sonA != null)",
    kirmizi: "Curutucu5eTest.b3_yeniAcilistaIlkIzlenenKayit_kacirilanBildirimiCikmamali" },
  { ad: "5E-C: B3: ayni calismadaki bosluk da sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            eksik = maxOf(0L, n - once - 1)\n", koy: "            eksik = 0L\n",
    kirmizi: "Curutucu5eEkTest.b3_ayniCalismadakiBosluk_yineSayilir_pcDavranisiAcilabilir" },
  { ad: "5E-C: B11: telefonda yerel sessizlik kopukluk sayiliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "val yerelYol = yerelKopukluk && (!mqttBagli || kartCevrimici == null)", koy: "val yerelYol = (!mqttBagli || kartCevrimici == null)",
    kirmizi: "Curutucu5eTest.b11_kaliciDurumYokken_yerelGdenYirmiSaniyeSonra_kopukDenmemeli" },
  { ad: "5E-C: B10: eksik alanli durum ozeti eziyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "        if (BildirimKarar.pyEsit(simdi[\"c\"], 1) && (simdi[\"k\"] !is Long || simdi[\"o\"] !is Long)) return Sonuc(onceki, false)\n", koy: "",
    kirmizi: "Curutucu5eTest.b10_eksikAlanliDurum_kayitDurumuOzettenSilinmemeli" },
  { ad: "5E-C: B4: yerel haber ozeti ilerletmiyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "YoklamaDurumu((onceki?.cevrimici ?: mapOf(\"c\" to 1L)) + mapOf(\"k\" to kod, \"o\" to oturum), onceki?.kopuk ?: false)", koy: "YoklamaDurumu(onceki?.cevrimici ?: mapOf(\"c\" to 1L), onceki?.kopuk ?: false)",
    kirmizi: "Curutucu5eTest.b4_servisinYerelYoldanBildirdigiBitis_yoklamadaYinelenmemeli" },
  { ad: "5E-C: B4: yerel haber 'haber yok' bayragini siliyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "+ mapOf(\"k\" to kod, \"o\" to oturum), onceki?.kopuk ?: false)", koy: "+ mapOf(\"k\" to kod, \"o\" to oturum), false)",
    kirmizi: "Curutucu5eEkTest.b4_ozetYerel_kayitDurumuIlerler_digerAlanlarKorunur_ilkHaberdeDeCalisir" },
  { ad: "5E-C: B6: SUBACK oncesi yayin birikimi sinirsiz", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                    if (bekleyenYayin.size >= BEKLEYEN_AZAMI) return MqttBitis(\"bicim\")\n", koy: "",
    kirmizi: "Curutucu5eTest.b6_subacktenOnceYayinSeli_bellektekiBirikimSinirliOlmali" },
  { ad: "5E-C: K05: ilk paketin CONNACK oldugu denetlenmiyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "            if (c.first shr 4 != MqttPaket.CONNACK) return MqttBitis(\"bicim\")\n", koy: "",
    kirmizi: "Curutucu5eEkTest.k05_connackYerineBaskaPaket_bicim" },
  { ad: "5E-C: B7: tampon siniri okuma payi birakmiyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "if (boy > azami + 5 || n > azami + 5) throw MqttHatasi(\"buyuk\")", koy: "if (boy + n > azami + 5) throw MqttHatasi(\"buyuk\")",
    kirmizi: "Curutucu5eTest.b7_azamiBoydaIkiPaket_4096lukOkumalarla_buyukDenmemeli" },
  { ad: "5E-C: B9: \\u kacisinda ASCII olmayan rakam kabul", dosya: BILDIRIM + "DuzJson.kt",
    bul: "val h = when (ch) { in '0'..'9' -> ch - '0'; in 'a'..'f' -> ch - 'a' + 10; in 'A'..'F' -> ch - 'A' + 10; else -> throw JsonHatasi() }", koy: "val h = Character.digit(ch, 16); if (h < 0) throw JsonHatasi()",
    kirmizi: "Curutucu5eTest.b9_json_uKacisindaYalnizAsciiOnaltilik" },
  { ad: "5E-C: B8: adres ham haliyle yaziliyor (okunamaz)", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "AtomikYazim.yaz(hedef, sade.toByteArray(Charsets.US_ASCII))", koy: "AtomikYazim.yaz(hedef, adres!!.toByteArray(Charsets.US_ASCII))",
    kirmizi: "Curutucu5eTest.b8_yazilanAdres_okunabilmeli" },
  { ad: "5E-C: K16: ayar dosyasinda boy siniri yok", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "if (dosya.isFile && dosya.length() <= 1024)", koy: "if (dosya.isFile)",
    kirmizi: "BildirimKabukTest.ayar_yazOku_gidisDonus_bozukVeGecersizAlanlarAyiklanir" },
  { ad: "5E-C: K18: Redmi / Poco markasi taninmiyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "\"xiaomi\" in u || \"redmi\" in u || \"poco\" in u -> \"xiaomi\"", koy: "\"xiaomi\" in u -> \"xiaomi\"",
    kirmizi: "BildirimKabukTest.ureticiSinifi_pilYonergesiIcin_modelSizdirmaz" },
  { ad: "5E-C: K26: anahtar boyu denetlenmiyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "if (anahtar.size != ANAHTAR || veri.size < EN_AZ) throw ZarfHatasi(\"bicim\")", koy: "if (veri.size < EN_AZ) throw ZarfHatasi(\"bicim\")",
    kirmizi: "Curutucu5eEkTest.k26_zarfCoz_anahtarBoyuTutmazsaBicim_etiketDegil" },
  { ad: "5E-C: K-5: baglanip hemen kopan oturum bastan sayiyor", dosya: BILDIRIM + "IzlemeDongusu.kt",
    bul: "deneme = if (b.baglandi && simdiMs() - bas >= KARARLI_MS) 1 else deneme + 1", koy: "deneme = if (b.baglandi) 1 else deneme + 1",
    kirmizi: "BildirimKabukTest.dongu_baglanipHemenKopanAraci_bastanSaymaz_geriCekilmeSurer" },
  // ── 5E-2 MQTT istemcisi ve TLS (S2) ──
  { ad: "5E-2K: TLS'te ad dogrulamasi el sikismada KAPALI (yanlis adli sertifika kabul edilir)", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "                p.endpointIdentificationAlgorithm = \"HTTPS\"\n", koy: "",
    kirmizi: "TlsBaglantiTest.guvenilenSertifika_YANLIS_AD_REDDEDILIR_elSikismaKatmani" },
  { ad: "5E-2K: TLS'te ikinci katman (platform ad dogrulayicisi) sorulmuyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "                if (!adDogrula(adres.ad, soket.session)) throw SSLException(\"ad\")\n", koy: "",
    kirmizi: "TlsBaglantiTest.ikinciKatman_platformDogrulayicisiHayirDerse_REDDEDILIR" },
  { ad: "5E-2K: sifresiz mqtt:// adresi kabul ediliyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "Regex(\"^mqtts://([^/:?#\\\\s]+)", koy: "Regex(\"^mqtts?://([^/:?#\\\\s]+)",
    kirmizi: "TlsBaglantiTest.adresYalnizMqtts_baskaHerBicimReddedilir" },
  { ad: "5E-2K: araci adresi olarak IP kabul ediliyor (sertifika adi dogrulanamaz)", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "if (!AD.matches(ad) || ad.all { it.isDigit() || it == '.' }) throw AraciHatasi(\"adres-gecersiz\")", koy: "if (!AD.matches(ad)) throw AraciHatasi(\"adres-gecersiz\")",
    kirmizi: "TlsBaglantiTest.adresYalnizMqtts_baskaHerBicimReddedilir" },
  { ad: "5E-2K: baglanti hatasi asil istisnayi (adresiyle) zincire tasiyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "                throw AraciHatasi(\"ag\")", koy: "                throw AraciHatasi(\"ag\").apply { initCause(e) }",
    kirmizi: "TlsBaglantiTest.baglanilamayanPort_ag_hataMetniAdresTasimaz" },
  { ad: "5E-2K: AraciAdresi.toString adresi yaziyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "override fun toString(): String = \"AraciAdresi(***)\"", koy: "override fun toString(): String = \"AraciAdresi($ad:$port)\"",
    kirmizi: "TlsBaglantiTest.baglanilamayanPort_ag_hataMetniAdresTasimaz" },
  { ad: "5E-2K: CONNACK ret kodu yok sayiliyor (yanlis parolayla 'baglandi')", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "            if (kod != 0) return MqttBitis(\"ret\", kod)\n", koy: "",
    kirmizi: "MqttIstemciTest.connackReddi_kodDoner_aboneOlunmaz" },
  { ad: "5E-2K: abonelik reddi (0x80) gorulmuyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                    if (s.second == 0x80) return MqttBitis(\"abone-ret\")\n", koy: "",
    kirmizi: "MqttIstemciTest.aboneReddi_veBicimHatalari" },
  { ad: "5E-2K: QoS 1 yayina PUBACK gonderilmiyor (araci surekli yeniden yollar)", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (y.qos == 1) gonder(MqttPaket.puback(y.paketNo!!))\n", koy: "",
    kirmizi: "MqttIstemciTest.qos1Yayin_oncePuback_sonraMesaj_qos0PubackYok_kaliciBayrakTasinir" },
  { ad: "5E-2K: QoS 2 yayin isleniyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (y.qos == 2) return MqttBitis(\"bicim\")\n", koy: "",
    kirmizi: "MqttIstemciTest.aboneReddi_veBicimHatalari" },
  { ad: "5E-2K: SUBACK'ten once gelen kalici mesaj atiliyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (p.first shr 4 == MqttPaket.PUBLISH) bekleyenYayin.add(p)", koy: "                if (false) bekleyenYayin.add(p)",
    kirmizi: "MqttIstemciTest.subacktanOnceGelenKaliciMesajKaybolmaz" },
  { ad: "5E-2K: PINGREQ hic gonderilmiyor (araci 7.5 s'de dusurur)", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (pingZamani < 0 && simdi - sonGiden >= KEEPALIVE_S * 1000L) {", koy: "                if (false) {",
    kirmizi: "MqttIstemciTest.keepalive_5SaniyeSessizlikteBirPingreq_yanitGelinceSurer" },
  { ad: "5E-2K: PINGRESP gelmese de oturum suruyor ('telefonun interneti' hic fark edilmez)", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (pingZamani >= 0 && simdi - pingZamani >= SESSIZLIK_MS) return MqttBitis(\"sessiz\")\n", koy: "",
    kirmizi: "MqttIstemciTest.pingYanitsizKalirsa_7buCukSaniyedeSessiz_kartAlarmiDegil" },
  { ad: "5E-2K: aracidan gelen paket canlilik sayilmiyor (yayin akarken 'sessiz')", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "if (n > 0) { ayristirici.besle(tampon, n); pingZamani = -1L }", koy: "if (n > 0) { ayristirici.besle(tampon, n) }",
    kirmizi: "MqttIstemciTest.aracidanHerhangiBirPaketCanlilikSayilir_pingBeklemesiSifirlanir" },
  { ad: "5E-2K: akis bitince (EOF) fark edilmiyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (n < 0) throw IOException(\"bitti\")\n", koy: "",
    kirmizi: "MqttIstemciTest.baglantiKoparsa_koptu_hataMetniSirTasimaz" },
  { ad: "5E-2K: mesaj isleyicisinin hatasi oturumu dusuruyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                try { mesaj(y) } catch (_: RuntimeException) {}", koy: "                mesaj(y)",
    kirmizi: "MqttIstemciTest.mesajIsleyicisiAtarsaOturumCokmez_istisnaDisariCikmaz" },
  { ad: "5E-2K: oturum bitince baglanti kapatilmiyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "            try { baglanti.kapat() } catch (_: Exception) {}", koy: "",
    kirmizi: "MqttIstemciTest.connackReddi_kodDoner_aboneOlunmaz" },
  // ── 5E-1 bildirim cekirdegi (DuzJson, Zarf, MqttPaket) ──
  { ad: "5E-K: zarfta sihir denetlenmiyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "for (i in SIHIR.indices) if (veri[i] != SIHIR[i]) throw ZarfHatasi(\"bicim\")", koy: "",
    kirmizi: "BildirimCekirdekTest.zarf_redVektorleri_hepsiReddedilir_turDogru" },
  { ad: "5E-K: zarfta AAD (konu adi) dogrulamaya girmiyor — baska konunun mesaji kabul edilir", dosya: BILDIRIM + "Zarf.kt",
    bul: "            c.updateAAD(aad)\n", koy: "",
    kirmizi: "BildirimCekirdekTest.zarf_ortakVektorler_duzMetinBaytBayt" },
  { ad: "5E-K: zarf hatasi platform istisnasini (mesajiyla) zincire tasiyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "            throw ZarfHatasi(\"etiket\")", koy: "            throw ZarfHatasi(\"etiket\").apply { initCause(e) }",
    kirmizi: "BildirimCekirdekTest.zarfHatasi_sirTasimaz" },
  { ad: "5E-K: bilgi AAD'sinde n yok (baska cihazin zarfi acilir)", dosya: BILDIRIM + "Zarf.kt",
    bul: "\"OK1-bildirim\\n$kimlik\\n$n\"", koy: "\"OK1-bildirim\\n$kimlik\\n\"",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: bilgide onek bicimi denetlenmiyor (konu adina satir sonu / joker girer)", dosya: BILDIRIM + "Zarf.kt",
    bul: "if (uri.isEmpty() || !ONEK.matches(onek) || !ANAHTAR_HEX.matches(a))", koy: "if (uri.isEmpty() || !ANAHTAR_HEX.matches(a))",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: bilgide bos araci adresi kabul ediliyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "if (uri.isEmpty() || !ONEK.matches(onek)", koy: "if (!ONEK.matches(onek)",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: AraciBilgisi.toString parolayi yaziyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "override fun toString(): String = \"AraciBilgisi(***)\"", koy: "override fun toString(): String = \"AraciBilgisi($uri $kullanici $parola $onek)\"",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: zarf icerigi gecersiz UTF-8 ise U+FFFD ile kabul ediliyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT)", koy: "Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPLACE).onUnmappableCharacter(CodingErrorAction.REPLACE)",
    kirmizi: "BildirimCekirdekTest.zarf_redVektorleri_hepsiReddedilir_turDogru" },
  { ad: "5E-K: JSON sondaki fazla veriyi kabul ediyor", dosya: BILDIRIM + "DuzJson.kt",
    bul: "        if (o.i != metin.length) throw JsonHatasi()\n", koy: "",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: JSON kacissiz kontrol karakterini kabul ediyor", dosya: BILDIRIM + "DuzJson.kt",
    bul: "                    c.code < 0x20 -> throw JsonHatasi()\n", koy: "",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: JSON derinlik siniri yok (yigin tasmasi)", dosya: BILDIRIM + "DuzJson.kt",
    bul: "if (derinlik > DERINLIK_AZAMI || i >= s.length) throw JsonHatasi()", koy: "if (i >= s.length) throw JsonHatasi()",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: JSON bastaki sifiri kabul ediyor (01)", dosya: BILDIRIM + "DuzJson.kt",
    bul: "            if (s[i] == '0') {\n                i++\n            } else if (s[i] in '1'..'9') {", koy: "            if (s[i] in '0'..'9') {",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: MQTT connect parola bayragini koymuyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "if (parola != null) { bayrak = bayrak or 0x40; yuk += dize(parola) }", koy: "if (parola != null) { yuk += dize(parola) }",
    kirmizi: "BildirimCekirdekTest.mqtt_connectSubscribeVeSabitPaketler" },
  { ad: "5E-K: MQTT subscribe bayragi yanlis (0x02 yok: araci baglantiyi keser)", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "return paket((SUBSCRIBE shl 4) or 0x02,", koy: "return paket((SUBSCRIBE shl 4),",
    kirmizi: "BildirimCekirdekTest.mqtt_connectSubscribeVeSabitPaketler" },
  { ad: "5E-K: MQTT publish'te paket numarasi yuke karisiyor (QoS 1)", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "            i += 2\n        }\n        return Yayin(", koy: "        }\n        return Yayin(",
    kirmizi: "BildirimCekirdekTest.mqtt_publishCozVeRed" },
  { ad: "5E-K: MQTT QoS 3 kabul ediliyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "if (qos == 3 || govde.size < 2) throw MqttHatasi(\"bicim\")", koy: "if (govde.size < 2) throw MqttHatasi(\"bicim\")",
    kirmizi: "BildirimCekirdekTest.mqtt_publishCozVeRed" },
  { ad: "5E-K: MQTT ayristirici buyuk paketi reddetmiyor (bellek dolar)", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "            if (u.first > azami) throw MqttHatasi(\"buyuk\")\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi" },
  { ad: "5E-K: MQTT ayristirici tampon siniri yok", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "                if (boy + n > azami + 5) throw MqttHatasi(\"buyuk\")\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi" },
  // CIKARILDI (2026-10-05): "5E-K: MQTT ayristirici islenen paketi tampondan atmiyor" — bu degisiklik istemcinin
  // el sikisma dongusunu SONSUZA sokuyor (ayni CONNACK yeniden verilir); kosucu zaman asimina dusuyor ve asili
  // kalan Gradle sureci sonraki mutasyonlarin kopyasini kilitliyor. Iddia testte acikca duruyor:
  // BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi ("ayni paket yeniden verildi").
  { ad: "5E-K: MQTT kalan uzunluk 4 bayti asinca reddedilmiyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "        if (i >= 4) throw MqttHatasi(\"bicim\")\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi" },
  { ad: "5D-K: sifirla durum.json'i once siliyor (yarida kalirsa kopya sessizce sifirdan sayilir)", dosya: DEPO + "KartDepo.kt",
    bul: "dosyalar.sortedBy { if (it.name == DURUM) 1 else 0 }", koy: "dosyalar.sortedBy { if (it.name == DURUM) 0 else 1 }",
    kirmizi: "KartDepoTest.sifirla_durumEnSonSilinir_yaridaKalirsaDurumYerinde" },
  // ── 5D-3 yerel dosya akitma (DepoYolu) ──
  { ad: "5D-K: depo dosyasi GET disi yontemlere de veriliyor (curutucu 5D Y13)", dosya: DEPO + "DepoYolu.kt",
    bul: "if (yontem == \"GET\") kimlik(url) else null", koy: "kimlik(url)",
    kirmizi: "DepoYoluTest.dosyaYalnizGetIleVerilir" },
  { ad: "5D-K: WebKapi Capacitor'in dosya on ekini geciriyor (curutucu 5D B13)", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/WebKapi.kt",
    bul: "if (yol.contains('%') || yol.contains(\"/_capacitor_\")) return false", koy: "if (yol.contains('%')) return false",
    kirmizi: "WebKapiTest.capacitorDosyaOnEkleriKapali_yuzdeKacisiYoldaYok" },
  { ad: "5D-K: WebKapi yolda yuzde kacisini kabul ediyor (%5Fcapacitor_file_)", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/WebKapi.kt",
    bul: "if (yol.contains('%') || yol.contains(\"/_capacitor_\")) return false", koy: "if (yol.contains(\"/_capacitor_\")) return false",
    kirmizi: "WebKapiTest.capacitorDosyaOnEkleriKapali_yuzdeKacisiYoldaYok" },
  { ad: "5D-K: depo adresi buyuk harfli kimligi kabul ediyor (dosya sistemi ayni dizine gidebilir)", dosya: DEPO + "DepoYolu.kt",
    bul: "([0-9a-f]{16})/kayitlar", koy: "([0-9a-fA-F]{16})/kayitlar",
    kirmizi: "DepoYoluTest.baskaHerBicimReddedilir" },
  { ad: "5D-K: depo adresi tam esleme yerine icinde arama yapiyor", dosya: DEPO + "DepoYolu.kt",
    bul: "BICIM.matchEntire(url)", koy: "BICIM.find(url)",
    kirmizi: "DepoYoluTest.baskaHerBicimReddedilir" },
  { ad: "5D-K: depo on ekini tasiyan bozuk adres dosya sunucusuna birakiliyor", dosya: DEPO + "DepoYolu.kt",
    bul: "fun depoAdresi(url: String?): Boolean = url != null && url.startsWith(ON_EK)", koy: "fun depoAdresi(url: String?): Boolean = kimlik(url) != null",
    kirmizi: "DepoYoluTest.depoOnEkiTasiyanBozukAdresDosyaSunucusunaBirakilmaz" },
  // ── 5C curutucu duzeltmeleri (DURUM 2026-10-05, bulgu 1, 8, 10) ─────────
  {
    ad: "5C-KD: p0'da her 2xx basari sayiliyor (kart olmayan adres 'durduruldu' der)",
    dosya: AG + "P0.kt",
    bul: "if (kod == BASARI_KODU) return deneme",
    koy: "if (kod in 200..299) return deneme",
    kirmizi: "P0Test.yalniz204Basaridir_baska2xxBasariDegilVeYenidenDenenmez",
  },
  {
    ad: "5C-KD: baska adresin basarisi beklemeyi bitiriyor (asil kartin yeniden denemesi sonuca girmez)",
    dosya: AG + "P0.kt",
    bul: "if (!asilVar || adres == asil) bitti.countDown()",
    koy: "bitti.countDown()",
    kirmizi: "P0Test.baskaAdresinBasarisiAsilKartinYenidenDenemesiniKesmez",
  },
  {
    ad: "5C-KD: asil yokken de ilk adres bekleniyor (cozulemeyen olcum.local sonucu bekletir)",
    dosya: AG + "P0.kt",
    bul: "p0.durdur(adresler, asilVar = asilVar) } catch",
    koy: "p0.durdur(adresler) } catch",
    kirmizi: "P0Test.asilYokkenTurAyriSayilir",
  },
  {
    ad: "5C-KD: kalici hata (Wi-Fi yok) da yeniden deneniyor",
    dosya: AG + "P0.kt",
    bul: "if (e.tur in KALICI_HATALAR) return 0",
    koy: "",
    kirmizi: "P0Test.kaliciHataYenidenDenenmez_geciciHataDenenir",
  },
  {
    ad: "5C-KD: suren p0 turuna baglanilmiyor (her dokunus yeni is parcaciklari acar)",
    dosya: AG + "P0.kt",
    bul: "if (b != null && surenAdresler == adresler && surenAsilVar == asilVar) {",
    koy: "if (b != null && surenAdresler == null) {",
    kirmizi: "P0Test.surenTuraBaglanir_yeniIsParcacigiAcmaz_turBitinceYeniTurBaslar",
  },
  {
    ad: "5C-KD: SSE alan adi harfe duyarli ('Event: kimlik' varsayilan olay olur, jeton tasinir)",
    dosya: AG + "SseAyirici.kt",
    bul: "when (alan.lowercase()) {",
    koy: "when (alan) {",
    kirmizi: "SseAyiriciTest.alanAdlariBuyukKucukHarfeDuyarsiz",
  },
  {
    ad: "5C-KD: kimlik olayinda ad degisince veri tasiniyor (gizli isareti konmuyor)",
    dosya: AG + "SseAyirici.kt",
    bul: "                    gizli = true\n",
    koy: "",
    kirmizi: "SseAyiriciTest.kimlikOlayininVerisiHicbirYoldanTasinmaz",
  },
  // ── curutucu 5E K-13 (yoklamada yeniden baslama) + K-8 (eszamanli ozet yazimi), 2026-10-05 ──
  { ad: "K13: ayni oturum surerken yeniden baslama bildirilmiyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "if (suruyor) k.mqttMesaj(\"olay\", mapOf(\"n\" to 1L, \"a\" to ya, \"o\" to \"basladi\"", koy: "if (false) k.mqttMesaj(\"olay\", mapOf(\"n\" to 1L, \"a\" to ya, \"o\" to \"basladi\"",
    kirmizi: "YoklamaTest.kartYenidenBasladi_ayniOturumSuruyor_yenidenBasladiBirKez_servisleAyniEtiket" },
  { ad: "K13: acilis degismese de yeniden basladi deniyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "if (ea == ya || eski[\"k\"] !in BildirimKarar.KAYITTA) return", koy: "if (eski[\"k\"] !in BildirimKarar.KAYITTA) return",
    kirmizi: "YoklamaTest.acilisDegismediyse_yaDaKayitSurmuyorduysa_yenidenBasladiDenmez" },
  { ad: "K13: kayit surmuyorken de yeniden basladi deniyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "if (ea == ya || eski[\"k\"] !in BildirimKarar.KAYITTA) return", koy: "if (ea == ya) return",
    kirmizi: "YoklamaTest.acilisDegismediyse_yaDaKayitSurmuyorduysa_yenidenBasladiDenmez" },
  { ad: "K13: oturum degisse de 'kayit suruyor' deniyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "simdi[\"k\"] in BildirimKarar.KAYITTA && simdi[\"o\"] == eo", koy: "simdi[\"k\"] in BildirimKarar.KAYITTA",
    kirmizi: "YoklamaTest.pilYaDaSkopOturumuYenidenBaslamaylaKesildi_kesildiDenir_olcumOturumuSiradanBiter" },
  { ad: "K13: kesilen pil / skop oturumu siradan 'bitti' deniyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "else if (eski[\"y\"] in KESILEN_TURLER) k.mqttMesaj", koy: "else if (false) k.mqttMesaj",
    kirmizi: "YoklamaTest.pilYaDaSkopOturumuYenidenBaslamaylaKesildi_kesildiDenir_olcumOturumuSiradanBiter" },
  { ad: "K13: olcum oturumunun bitisi de 'kesildi' deniyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "else if (eski[\"y\"] in KESILEN_TURLER) k.mqttMesaj", koy: "else if (true) k.mqttMesaj",
    kirmizi: "YoklamaTest.pilYaDaSkopOturumuYenidenBaslamaylaKesildi_kesildiDenir_olcumOturumuSiradanBiter" },
  { ad: "K13: skop oturumu kesilen turlerde yok", dosya: BILDIRIM + "Yoklama.kt",
    bul: "setOf<Any?>(2L, 3L)", koy: "setOf<Any?>(2L)",
    kirmizi: "YoklamaTest.pilYaDaSkopOturumuYenidenBaslamaylaKesildi_kesildiDenir_olcumOturumuSiradanBiter" },
  { ad: "K13: 'son haber' saati yeni durumdan aliniyor", dosya: BILDIRIM + "Yoklama.kt",
    bul: "        if (cevrimici && eski != null) yenidenBasladi(k, eski, simdi)      // yeni durumdan ONCE: \"son haber\" eski saat kalsin\n        k.mqttMesaj(\"durum\", simdi)\n", koy: "        k.mqttMesaj(\"durum\", simdi)\n        if (cevrimici && eski != null) yenidenBasladi(k, eski, simdi)\n",
    kirmizi: "YoklamaTest.pilYaDaSkopOturumuYenidenBaslamaylaKesildi_kesildiDenir_olcumOturumuSiradanBiter" },
  { ad: "K8: atomik yazim kilitsiz (ayni gecici dosya iki yazarda)", dosya: KASA + "AtomikYazim.kt",
    bul: "fun yaz(hedef: File, veri: ByteArray) = synchronized(this) {", koy: "fun yaz(hedef: File, veri: ByteArray) = run {",
    kirmizi: "OzetEszamanTest.ayniHedefeEszamanliAtomikYazim_hataYok_hedefHepTamBirIcerik" },
  { ad: "K8: ozetin oku-degistir-yaz'i kilitsiz", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "= synchronized(DURUM_KILIDI) {", koy: "= run {",
    kirmizi: "OzetEszamanTest.ozetGuncelle_okuDegistirYazTekParca_arayaGirenYazimEzilmez" },
  { ad: "K8: servis ozeti eski kalipla (oku, sonra yaz) guncelliyor", dosya: BILDIRIM + "IzlemeServisi.kt",
    bul: "depo.durumGuncelle(kimlik) { Yoklama.ozetYerel(it, kod, oturum) }", koy: "depo.durumYaz(kimlik, Yoklama.ozetYerel(depo.durumOku(kimlik), kod, oturum))",
    kirmizi: "OzetEszamanTest.servisVeYoklama_ozetiYalnizTekParcaGunceller_kaynakta" },
  { ad: "K8: ozet guncellemede null ozeti siliyor", dosya: BILDIRIM + "BildirimDeposu.kt",
    bul: "        durumYaz(kimlik, degistir(durumOku(kimlik)))\n", koy: "        durumYaz(kimlik, degistir(durumOku(kimlik)) ?: YoklamaDurumu(null, false))\n",
    kirmizi: "OzetEszamanTest.ozetGuncelle_nullDonerseOzetDegismez_ilkOkumadaNullVerir_kimlikDenetlenir" },
  // ── curutucu 5E K-7 (vazgecme suresi), 2026-10-05 ──
  { ad: "K7: vazgecme suresi hic dolmuyor", dosya: BILDIRIM + "Vazgecme.kt",
    bul: "        return simdiMs - bas >= sureMs\n", koy: "        return false\n",
    kirmizi: "VazgecmeTest.kartKesintisizAltiSaatCevrimdisiysa_dolar_oncesindeDolmaz" },
  { ad: "K7: vazgecme suresi 6 dakika", dosya: BILDIRIM + "Vazgecme.kt",
    bul: "const val SURE_MS = 6 * 60 * 60 * 1000L", koy: "const val SURE_MS = 6 * 60 * 1000L",
    kirmizi: "VazgecmeTest.kartKesintisizAltiSaatCevrimdisiysa_dolar_oncesindeDolmaz" },
  { ad: "K7: kart donunce sure sifirlanmiyor", dosya: BILDIRIM + "Vazgecme.kt",
    bul: "if (cevrimici == true) { kopukBas = null; return false }", koy: "if (cevrimici == true) return false",
    kirmizi: "VazgecmeTest.kartCevrimiciGorulurse_sureSifirlanir" },
  { ad: "K7: durum bilinmiyorken de doluyor", dosya: BILDIRIM + "Vazgecme.kt",
    bul: "        if (cevrimici == null) return false\n", koy: "",
    kirmizi: "VazgecmeTest.durumBilinmiyorken_dolmaz_amaSureDeSifirlanmaz_cevrimiciKartHicDolmaz" },
  { ad: "K7: durum bilinmiyorken sure sifirlaniyor", dosya: BILDIRIM + "Vazgecme.kt",
    bul: "        if (cevrimici == null) return false\n", koy: "        if (cevrimici == null) { kopukBas = null; return false }\n",
    kirmizi: "VazgecmeTest.durumBilinmiyorken_dolmaz_amaSureDeSifirlanmaz_cevrimiciKartHicDolmaz" },
  { ad: "K7: sure her sorguda bastan basliyor", dosya: BILDIRIM + "Vazgecme.kt",
    bul: "val bas = kopukBas ?: simdiMs.also { kopukBas = it }", koy: "val bas = simdiMs",
    kirmizi: "VazgecmeTest.kartKesintisizAltiSaatCevrimdisiysa_dolar_oncesindeDolmaz" },
  { ad: "K7: servis vazgecmeyi surdur kararina katmiyor", dosya: BILDIRIM + "IzlemeServisi.kt",
    bul: "k.kayitSuruyor() != false && !vazgecme.doldu(k.kartCevrimici, SystemClock.elapsedRealtime()) } },", koy: "k.kayitSuruyor() != false } },",
    kirmizi: "VazgecmeTest.servis_surdurKararinaVazgecmeyiKatar" },
];

// Kaynak degistikce eskiyen desenler guncel-desen.mjs'ten (ada gore) alinir.
export default guncelle(HAM);
