// Kotlin (JVM birim testi) mutasyonlari: her iddianin onu YALANLAYAN degisikligi.
//   ad    : "<dilim>: ne bozuluyor"
//   dosya : mobil/'e gore; bul: kaynakta TAM BIR KEZ gecen dizgi; koy: yerine konan
//   kirmizi: bu mutasyonda kirmiziya donmesi beklenen test (elle dogrulandi, 2026-10-04)
// Test: cd android && ./gradlew.bat testDebugUnitTest  (her mutasyon ayri kosu, ~1 dk) — KIRMIZI beklenir.
// fsync'in kalkmasi JVM testinde gozlenemez (elektrik kesmesi gerekir): bilerek listede YOK.
const KASA = "android/app/src/main/java/tr/olcumkarti/mobil/kasa/";
const AG = "android/app/src/main/java/tr/olcumkarti/mobil/ag/";
const DEPO = "android/app/src/main/java/tr/olcumkarti/mobil/depo/";
const BILDIRIM = "android/app/src/main/java/tr/olcumkarti/mobil/bildirim/";

export default [
  {
    ad: "5B-K: sayacta geri denetimi kalkti",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (isaret < eski) throw KasaHatasi("geri")',
    koy: "",
    kirmizi: "SayacDosyasiTest.kucukDegerGeri_dosyaDegismez",
  },
  {
    ad: "5B-K: sayacta ESIT yazim kabul ediliyor (ikinci yazar ayni blogu kullanir — curutucu 5B S4)",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (vardi && isaret == eski) throw KasaHatasi("geri")',
    koy: "",
    kirmizi: "SayacDosyasiTest.esitYazimGeri_buyukKabul",
  },
  {
    ad: "5B-K: dosya yokken ilk yazim (0 dahil) 'geri' sayiliyor",
    dosya: KASA + "SayacDosyasi.kt",
    bul: "if (vardi && isaret == eski) throw",
    koy: "if (isaret == eski) throw",
    kirmizi: "SayacDosyasiTest.dosyaYokkenHerDegerIlkYazimdir_sifirDahil",
  },
  {
    ad: "5B-K: sil once sayaci siliyor (yarida kalirsa eski K sayac 0 ile yasar)",
    dosya: KASA + "KasaDeposu.kt",
    bul: "if (it == kimlik + ANAHTAR_EK) 0 else 1",
    koy: "if (it == kimlik + ANAHTAR_EK) 1 else 0",
    kirmizi: "KasaDeposuTest.silOnceAnahtariSiler_yaridaKalirsaAnahtarYasamaz",
  },
  {
    ad: "5B-K: bozuk saglamali sayac dosyasi kabul ediliyor",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (satirlar[1] != saglama(satirlar[0])) throw KasaHatasi("bozuk")',
    koy: "",
    kirmizi: "SayacDosyasiTest.bozukVeYarimDosyaBozuk_sifirDonmez",
  },
  {
    ad: "5B-K: kimlik deseni gevsedi (yol kacisi)",
    dosya: KASA + "KasaKayit.kt",
    bul: "kimlik.all { it in '0'..'9' || it in 'a'..'f' }",
    koy: "true",
    kirmizi: "KasaDeposuTest.kotuKimlikHerIslemdeBicim_dizinDisinaCikilamaz",
  },
  {
    ad: "5B-K: AAD'den kimlik cikti",
    dosya: KASA + "KasaKayit.kt",
    bul: "SIHIR + byteArrayOf(SURUM) + kimlik.toByteArray(Charsets.US_ASCII)",
    koy: "SIHIR + byteArrayOf(SURUM)",
    kirmizi: "KasaKayitTest.yanlisKimlikleAcilmaz",
  },
  {
    ad: "5B-K: anahtar uzunlugu denetimi kalkti",
    dosya: KASA + "KasaKayit.kt",
    bul: 'if (anahtar.size != ANAHTAR_BOYU) throw KasaHatasi("bicim")',
    koy: "",
    kirmizi: "KasaKayitTest.anahtarUzunluguTam32",
  },
  {
    ad: "5B-K: sil sayac dosyasini birakiyor",
    dosya: KASA + "KasaDeposu.kt",
    bul: 'ad.startsWith("$kimlik.")',
    koy: "ad == kimlik + ANAHTAR_EK",
    kirmizi: "KasaDeposuTest.silSonrasiYokVeSayacSifir",
  },
  {
    ad: "5A-K: HttpIstek toplam sure bekcisi kurulmuyor",
    dosya: AG + "HttpIstek.kt",
    bul: "}, zamanAsimiMs.toLong(), TimeUnit.MILLISECONDS)",
    koy: "}, Long.MAX_VALUE / 2, TimeUnit.MILLISECONDS)",
    kirmizi: "HttpIstekTest.baslikDamlatanSunucuToplamSureyleKesilir",
  },
  {
    ad: "5A-K: cozulen adres ozel adres suzgecinden gecmiyor",
    dosya: AG + "HedefCoz.kt",
    bul: "adresler.firstOrNull { Hedef.ozelAdres(it) }",
    koy: "adresler.firstOrNull()",
    kirmizi: "HedefCozTest.adCozulurVeCozulenAdresDeKuraldanGecer",
  },
  {
    ad: "5C-K: 4096 bayti asan SSE satiri bos satir gibi isleniyor (olay yarim veriyle dagitilir)",
    dosya: AG + "SseAyirici.kt",
    bul: "if (uzun) {",
    koy: "if (false) {",
    kirmizi: "SseAyiriciTest.satirSiniri4096Bayt_uzunSatirinOlayiAtilirSonrakiSaglam",
  },
  {
    ad: "5C-K: adli olaylar (kimlik: oturum jetonu) da satir olarak JS'e tasiniyor",
    dosya: AG + "Akis.kt",
    bul: 'if (o.ad.isEmpty() || o.ad == "message") satirlar.add(o.veri)',
    koy: "satirlar.add(o.veri)",
    kirmizi: "AkisTest.kartGibiAkis_satirlarSirayla_kimlikOlayiTasinmaz_baglantiBitinceKapandi",
  },
  {
    ad: "5C-K: kapat() baglantiyi kesmiyor (bloklu okuma surer, kartin yuvasi dolu kalir)",
    dosya: AG + "Akis.kt",
    bul: "try { baglanti?.disconnect() } catch (_: Exception) {}",
    koy: "",
    kirmizi: "AkisTest.kapat_blokluOkumayiHemenKeser_tekBitis_sonrasindaSatirYok",
  },
  // ── 5D-1 KartDepo ──
  { ad: "5D-K: kimlik bicimi denetlenmiyor (yol kacisi)", dosya: DEPO + "KartDepo.kt",
    bul: "if (kimlik == null || !KIMLIK.matches(kimlik)) throw DepoHatasi(\"bicim\")", koy: "if (kimlik == null) throw DepoHatasi(\"bicim\")",
    kirmizi: "KartDepoTest.kimlikYalniz16OnaltilikHane_yolKacisiYok" },
  { ad: "5D-K: ekleme dosyanin ustune yaziyor (sona eklemiyor)", dosya: DEPO + "KartDepo.kt",
    bul: "FileOutputStream(f, true).use { a ->", koy: "FileOutputStream(f, false).use { a ->",
    kirmizi: "KartDepoTest.ekle_sonaEkler_boyDoner_parcaliOkumaAyniBaytlar" },
  { ad: "5D-K: okuma bas konumuna gitmiyor", dosya: DEPO + "KartDepo.kt",
    bul: "                r.seek(bas)\n", koy: "",
    kirmizi: "KartDepoTest.ekle_sonaEkler_boyDoner_parcaliOkumaAyniBaytlar" },
  { ad: "5D-K: kirpma dosya boyunu degistirmiyor", dosya: DEPO + "KartDepo.kt",
    bul: "                r.setLength(n)\n", koy: "",
    kirmizi: "KartDepoTest.kirp_kisaltir_uzatirsaSifirDoldurur" },
  { ad: "5D-K: durum gecici dosyaya degil dogrudan hedefe yaziliyor (yarim durum gorulebilir)", dosya: DEPO + "KartDepo.kt",
    bul: "val g = File(hedef.parentFile, hedef.name + GECICI_EK)", koy: "val g = File(hedef.parentFile, hedef.name)",
    kirmizi: "KartDepoTest.durumVeKalibrasyon_atomik_geciciKalintiOkumayiEtkilemez" },
  { ad: "5D-K: arsiv ayni adin ustune yaziyor", dosya: DEPO + "KartDepo.kt",
    bul: "while (File(d, ad).exists()) {", koy: "while (false) {",
    kirmizi: "KartDepoTest.arsiv_zamanDamgaliAd_cakismadaNumara_icerikAyni" },
  { ad: "5D-K: okuma tavani yok", dosya: DEPO + "KartDepo.kt",
    bul: "if (bas < 0 || azami < 1 || azami > OKUMA_AZAMI) throw DepoHatasi(\"bicim\")", koy: "if (bas < 0 || azami < 1) throw DepoHatasi(\"bicim\")",
    kirmizi: "KartDepoTest.sinirlar_okumaYazmaKirpma" },
  { ad: "5D-K: sifirla dizini birakiyor", dosya: DEPO + "KartDepo.kt",
    bul: "        if (!d.delete() && d.exists()) throw DepoHatasi(\"yazilamadi\")\n    }\n\n    /** Depolama", koy: "    }\n\n    /** Depolama",
    kirmizi: "KartDepoTest.sifirla_yalnizOKartinDosyalari_sonraBos" },
  // ── 5E-3 bildirim karar katmani (Python basvurusuyla vektor esdegerligi) ──
  { ad: "5E-3K: vasiyet kayit SURMEZKEN de 'karttan haber yok' (A33 ihlali)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (suruyor != true) return\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kart yerelde gorunse de 'karttan haber yok' (ev interneti ayirt edilmiyor, A36)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "val hedef = if (yerelErisim()) \"ev\" else \"kopuk\"", koy: "val hedef = \"kopuk\"",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kart donunce bildirim guncellenmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (baglanti != null) geriGeldi(pyIcinde(d[\"k\"], KAYITTA), d[\"o\"])\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: donuste kayit bitmisse de 'kayit suruyor' deniyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (suruyor) goster(\"baglanti\", \"kopuk\", \"bld.geri_kayit\", mapOf(\"oturum\" to oturum))\n        else goster(\"baglanti\", \"kopuk\", \"bld.geri\", emptyMap())", koy: "goster(\"baglanti\", \"kopuk\", \"bld.geri_kayit\", mapOf(\"oturum\" to oturum))",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: QoS 1 yeniden teslim ikinci bildirim uretiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (an in goruldu) return                               // QoS 1 yeniden teslim\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: onceki calismada gorulen olay yeniden bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (pr != null && pr.first == a && n <= pr.second && !sonN.containsKey(a)) return", koy: "if (false) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kacirilan olaylar sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            kacirilan += eksik\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yeni acilisin ilk olaylari kacirilan sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (sonA != null) eksik = n - 1", koy: "if (sonA != null) eksik = 0",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: dolu sebebi (2) siradan 'bitti' gibi bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (pyEsit(s, 2)) {", koy: "if (false) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yeniden baslama sebebi (5) siradan 'bitti' gibi bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "} else if (pyEsit(s, 5)) {", koy: "} else if (false) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: basladi olayi devam almasa da bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "\"basladi\" -> if (pyEsit(d[\"devam\"], 1)) {", koy: "\"basladi\" -> if (true) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yollar arasi yineleme ayiklanmiyor (yerel + MQTT iki ayri bildirim)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        val m = eslesen(aile, a, oturum, simdi)\n", koy: "        val m: Kayit? = null\n",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: daha AZ ayrintili haber ayrintiliyi eziyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (sira <= m.sira) return", koy: "            if (false) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: guncelleme sessiz degil (ayni olay icin iki kez ses)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "cikis(Bildirim(m.etiket, sinif, anahtar, metinDegerleri(m), m.gosterildi))", koy: "cikis(Bildirim(m.etiket, sinif, anahtar, metinDegerleri(m), false))",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kapali sinif yine de gosteriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (!acik(sinif)) return\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: pencere dolan kayit silinmiyor (cok eski bildirim guncellenir)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        kayitlar.removeAll { simdi - it.t > pencereS }\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: oturumu bilinmeyen haber zaman sinirsiz esleniyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            } else if (simdi - r.t > yakinS) {\n                continue\n", koy: "            } else if (false) {\n                continue\n",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: farkli oturumlar ayni bildirimde birlesiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "                if (r.oturum != oturum) continue\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: deneme olaylari birbirini ayikliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (aile == \"deneme\") return null\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yerel yolda kopukluk kayit yokken de bildiriliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            if (suruyor == true) {\n                baglanti = \"yerel\"", koy: "            if (true) {\n                baglanti = \"yerel\"",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: MQTT bagliyken de yerel sessizlik 'kopuk' sayiliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (!yerelYol) return\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: yerel G: oturum degisimi 'bitti' sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (od in KAYITTA && (durumKodu !in KAYITTA || oturum != oo)) {", koy: "if (od in KAYITTA && (durumKodu !in KAYITTA)) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: BEKLIYOR (4) durumu kayit sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "val KAYITTA = setOf(2L, 4L)", koy: "val KAYITTA = setOf(2L)",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kayit durumu: eski haber yenisini eziyor (yerel her zaman kazanir)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "(d == null || dt == null || gt >= dt)) return", koy: "(true)) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: kesildi bildirimi oturum turunu / son gorulmeyi tasimiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        if (r.anahtar == \"bld.kesildi\") {", koy: "        if (false) {",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: etiket oturuma bagli degil (ayni oturumun guncellemesi baska bildirim kimligine gider)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "if (aile == \"oturum_sonu\" && oturum != null && oturum >= 0) return", koy: "if (false) return",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: Python esitligi: 1.0 / true cevrimici sayilmiyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "            is Double -> x == n.toDouble()\n            is Boolean -> (if (x) 1L else 0L) == n\n", koy: "",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: 5.0 gibi ondalik deger tamsayi sayiliyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "fun tam(x: Any?): Long? = x as? Long", koy: "fun tam(x: Any?): Long? = (x as? Long) ?: (x as? Double)?.toLong()",
    kirmizi: "BildirimKararTest.pythonBasvurusuylaAyniBildirimDizisi_butunSenaryolar" },
  { ad: "5E-3K: telefon penceresi 30 s degil (A35)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "const val PENCERE_S = 30.0", koy: "const val PENCERE_S = 900.0",
    kirmizi: "BildirimKararTest.telefonPencereleri_A35_varsayilan30Saniye" },
  { ad: "5E-3K: gorulen olay bellegi sinirsiz buyuyor", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        while (goruldu.size > AN_AZAMI) goruldu.remove(goruldu.first())\n", koy: "",
    kirmizi: "BildirimKararTest.gorulenOlayBellegiSinirli_enEskiAtilir" },
  { ad: "5E-3K: son (a, n) kalici yazilmiyor (yeniden baslayinca eski olaylar yeniden bildirilir)", dosya: BILDIRIM + "BildirimKarar.kt",
    bul: "        kaliciYaz(a, n)\n", koy: "",
    kirmizi: "BildirimKararTest.kaliciYazim_herYeniOlaydaSonAN_yinelenenVeBicimsizdeYok" },
  // ── 5E-2 MQTT istemcisi ve TLS (S2) ──
  { ad: "5E-2K: TLS'te ad dogrulamasi el sikismada KAPALI (yanlis adli sertifika kabul edilir)", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "                p.endpointIdentificationAlgorithm = \"HTTPS\"\n", koy: "",
    kirmizi: "TlsBaglantiTest.guvenilenSertifika_YANLIS_AD_REDDEDILIR_elSikismaKatmani" },
  { ad: "5E-2K: TLS'te ikinci katman (platform ad dogrulayicisi) sorulmuyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "                if (!adDogrula(adres.ad, soket.session)) throw SSLException(\"ad\")\n", koy: "",
    kirmizi: "TlsBaglantiTest.ikinciKatman_platformDogrulayicisiHayirDerse_REDDEDILIR" },
  { ad: "5E-2K: sifresiz mqtt:// adresi kabul ediliyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "Regex(\"^mqtts://([^/:?#\\\\s]+)", koy: "Regex(\"^mqtts?://([^/:?#\\\\s]+)",
    kirmizi: "TlsBaglantiTest.adresYalnizMqtts_baskaHerBicimReddedilir" },
  { ad: "5E-2K: araci adresi olarak IP kabul ediliyor (sertifika adi dogrulanamaz)", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "if (!AD.matches(ad) || ad.all { it.isDigit() || it == '.' }) throw AraciHatasi(\"adres-gecersiz\")", koy: "if (!AD.matches(ad)) throw AraciHatasi(\"adres-gecersiz\")",
    kirmizi: "TlsBaglantiTest.adresYalnizMqtts_baskaHerBicimReddedilir" },
  { ad: "5E-2K: baglanti hatasi asil istisnayi (adresiyle) zincire tasiyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "                throw AraciHatasi(\"ag\")", koy: "                throw AraciHatasi(\"ag\").apply { initCause(e) }",
    kirmizi: "TlsBaglantiTest.baglanilamayanPort_ag_hataMetniAdresTasimaz" },
  { ad: "5E-2K: AraciAdresi.toString adresi yaziyor", dosya: BILDIRIM + "TlsBaglanti.kt",
    bul: "override fun toString(): String = \"AraciAdresi(***)\"", koy: "override fun toString(): String = \"AraciAdresi($ad:$port)\"",
    kirmizi: "TlsBaglantiTest.baglanilamayanPort_ag_hataMetniAdresTasimaz" },
  { ad: "5E-2K: CONNACK ret kodu yok sayiliyor (yanlis parolayla 'baglandi')", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "            if (kod != 0) return MqttBitis(\"ret\", kod)\n", koy: "",
    kirmizi: "MqttIstemciTest.connackReddi_kodDoner_aboneOlunmaz" },
  { ad: "5E-2K: abonelik reddi (0x80) gorulmuyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                    if (s.second == 0x80) return MqttBitis(\"abone-ret\")\n", koy: "",
    kirmizi: "MqttIstemciTest.aboneReddi_veBicimHatalari" },
  { ad: "5E-2K: QoS 1 yayina PUBACK gonderilmiyor (araci surekli yeniden yollar)", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (y.qos == 1) gonder(MqttPaket.puback(y.paketNo!!))\n", koy: "",
    kirmizi: "MqttIstemciTest.qos1Yayin_oncePuback_sonraMesaj_qos0PubackYok_kaliciBayrakTasinir" },
  { ad: "5E-2K: QoS 2 yayin isleniyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (y.qos == 2) return MqttBitis(\"bicim\")\n", koy: "",
    kirmizi: "MqttIstemciTest.aboneReddi_veBicimHatalari" },
  { ad: "5E-2K: SUBACK'ten once gelen kalici mesaj atiliyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (p.first shr 4 == MqttPaket.PUBLISH) bekleyenYayin.add(p)", koy: "                if (false) bekleyenYayin.add(p)",
    kirmizi: "MqttIstemciTest.subacktanOnceGelenKaliciMesajKaybolmaz" },
  { ad: "5E-2K: PINGREQ hic gonderilmiyor (araci 7.5 s'de dusurur)", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (pingZamani < 0 && simdi - sonGiden >= KEEPALIVE_S * 1000L) {", koy: "                if (false) {",
    kirmizi: "MqttIstemciTest.keepalive_5SaniyeSessizlikteBirPingreq_yanitGelinceSurer" },
  { ad: "5E-2K: PINGRESP gelmese de oturum suruyor ('telefonun interneti' hic fark edilmez)", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (pingZamani >= 0 && simdi - pingZamani >= SESSIZLIK_MS) return MqttBitis(\"sessiz\")\n", koy: "",
    kirmizi: "MqttIstemciTest.pingYanitsizKalirsa_7buCukSaniyedeSessiz_kartAlarmiDegil" },
  { ad: "5E-2K: aracidan gelen paket canlilik sayilmiyor (yayin akarken 'sessiz')", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "if (n > 0) { ayristirici.besle(tampon, n); pingZamani = -1L }", koy: "if (n > 0) { ayristirici.besle(tampon, n) }",
    kirmizi: "MqttIstemciTest.aracidanHerhangiBirPaketCanlilikSayilir_pingBeklemesiSifirlanir" },
  { ad: "5E-2K: akis bitince (EOF) fark edilmiyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                if (n < 0) throw IOException(\"bitti\")\n", koy: "",
    kirmizi: "MqttIstemciTest.baglantiKoparsa_koptu_hataMetniSirTasimaz" },
  { ad: "5E-2K: mesaj isleyicisinin hatasi oturumu dusuruyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "                try { mesaj(y) } catch (_: RuntimeException) {}", koy: "                mesaj(y)",
    kirmizi: "MqttIstemciTest.mesajIsleyicisiAtarsaOturumCokmez_istisnaDisariCikmaz" },
  { ad: "5E-2K: oturum bitince baglanti kapatilmiyor", dosya: BILDIRIM + "MqttIstemci.kt",
    bul: "            try { baglanti.kapat() } catch (_: Exception) {}", koy: "",
    kirmizi: "MqttIstemciTest.connackReddi_kodDoner_aboneOlunmaz" },
  // ── 5E-1 bildirim cekirdegi (DuzJson, Zarf, MqttPaket) ──
  { ad: "5E-K: zarfta sihir denetlenmiyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "for (i in SIHIR.indices) if (veri[i] != SIHIR[i]) throw ZarfHatasi(\"bicim\")", koy: "",
    kirmizi: "BildirimCekirdekTest.zarf_redVektorleri_hepsiReddedilir_turDogru" },
  { ad: "5E-K: zarfta AAD (konu adi) dogrulamaya girmiyor — baska konunun mesaji kabul edilir", dosya: BILDIRIM + "Zarf.kt",
    bul: "            c.updateAAD(aad)\n", koy: "",
    kirmizi: "BildirimCekirdekTest.zarf_ortakVektorler_duzMetinBaytBayt" },
  { ad: "5E-K: zarf hatasi platform istisnasini (mesajiyla) zincire tasiyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "            throw ZarfHatasi(\"etiket\")", koy: "            throw ZarfHatasi(\"etiket\").apply { initCause(e) }",
    kirmizi: "BildirimCekirdekTest.zarfHatasi_sirTasimaz" },
  { ad: "5E-K: bilgi AAD'sinde n yok (baska cihazin zarfi acilir)", dosya: BILDIRIM + "Zarf.kt",
    bul: "\"OK1-bildirim\\n$kimlik\\n$n\"", koy: "\"OK1-bildirim\\n$kimlik\\n\"",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: bilgide onek bicimi denetlenmiyor (konu adina satir sonu / joker girer)", dosya: BILDIRIM + "Zarf.kt",
    bul: "if (uri.isEmpty() || !ONEK.matches(onek) || !ANAHTAR_HEX.matches(a))", koy: "if (uri.isEmpty() || !ANAHTAR_HEX.matches(a))",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: bilgide bos araci adresi kabul ediliyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "if (uri.isEmpty() || !ONEK.matches(onek)", koy: "if (!ONEK.matches(onek)",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: AraciBilgisi.toString parolayi yaziyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "override fun toString(): String = \"AraciBilgisi(***)\"", koy: "override fun toString(): String = \"AraciBilgisi($uri $kullanici $parola $onek)\"",
    kirmizi: "BildirimCekirdekTest.bilgi_ortakVektorler_cozulur_yaDaReddedilir" },
  { ad: "5E-K: zarf icerigi gecersiz UTF-8 ise U+FFFD ile kabul ediliyor", dosya: BILDIRIM + "Zarf.kt",
    bul: "Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT)", koy: "Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPLACE).onUnmappableCharacter(CodingErrorAction.REPLACE)",
    kirmizi: "BildirimCekirdekTest.zarf_redVektorleri_hepsiReddedilir_turDogru" },
  { ad: "5E-K: JSON sondaki fazla veriyi kabul ediyor", dosya: BILDIRIM + "DuzJson.kt",
    bul: "        if (o.i != metin.length) throw JsonHatasi()\n", koy: "",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: JSON kacissiz kontrol karakterini kabul ediyor", dosya: BILDIRIM + "DuzJson.kt",
    bul: "                    c.code < 0x20 -> throw JsonHatasi()\n", koy: "",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: JSON derinlik siniri yok (yigin tasmasi)", dosya: BILDIRIM + "DuzJson.kt",
    bul: "if (derinlik > DERINLIK_AZAMI || i >= s.length) throw JsonHatasi()", koy: "if (i >= s.length) throw JsonHatasi()",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: JSON bastaki sifiri kabul ediyor (01)", dosya: BILDIRIM + "DuzJson.kt",
    bul: "            if (s[i] == '0') {\n                i++\n            } else if (s[i] in '1'..'9') {", koy: "            if (s[i] in '0'..'9') {",
    kirmizi: "BildirimCekirdekTest.json_katidir_gevsekBicimlerReddedilir" },
  { ad: "5E-K: MQTT connect parola bayragini koymuyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "if (parola != null) { bayrak = bayrak or 0x40; yuk += dize(parola) }", koy: "if (parola != null) { yuk += dize(parola) }",
    kirmizi: "BildirimCekirdekTest.mqtt_connectSubscribeVeSabitPaketler" },
  { ad: "5E-K: MQTT subscribe bayragi yanlis (0x02 yok: araci baglantiyi keser)", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "return paket((SUBSCRIBE shl 4) or 0x02,", koy: "return paket((SUBSCRIBE shl 4),",
    kirmizi: "BildirimCekirdekTest.mqtt_connectSubscribeVeSabitPaketler" },
  { ad: "5E-K: MQTT publish'te paket numarasi yuke karisiyor (QoS 1)", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "            i += 2\n        }\n        return Yayin(", koy: "        }\n        return Yayin(",
    kirmizi: "BildirimCekirdekTest.mqtt_publishCozVeRed" },
  { ad: "5E-K: MQTT QoS 3 kabul ediliyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "if (qos == 3 || govde.size < 2) throw MqttHatasi(\"bicim\")", koy: "if (govde.size < 2) throw MqttHatasi(\"bicim\")",
    kirmizi: "BildirimCekirdekTest.mqtt_publishCozVeRed" },
  { ad: "5E-K: MQTT ayristirici buyuk paketi reddetmiyor (bellek dolar)", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "            if (u.first > azami) throw MqttHatasi(\"buyuk\")\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi" },
  { ad: "5E-K: MQTT ayristirici tampon siniri yok", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "                if (boy + n > azami + 5) throw MqttHatasi(\"buyuk\")\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi" },
  { ad: "5E-K: MQTT ayristirici islenen paketi tampondan atmiyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "            boy -= son\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_ayristirici_parcaliAkis_buyukPaketReddi" },
  { ad: "5E-K: MQTT kalan uzunluk 4 bayti asinca reddedilmiyor", dosya: BILDIRIM + "MqttPaket.kt",
    bul: "        if (i >= 4) throw MqttHatasi(\"bicim\")\n", koy: "",
    kirmizi: "BildirimCekirdekTest.mqtt_uzunlukVeDize" },
  { ad: "5D-K: sifirla durum.json'i once siliyor (yarida kalirsa kopya sessizce sifirdan sayilir)", dosya: DEPO + "KartDepo.kt",
    bul: "dosyalar.sortedBy { if (it.name == DURUM) 1 else 0 }", koy: "dosyalar.sortedBy { if (it.name == DURUM) 0 else 1 }",
    kirmizi: "KartDepoTest.sifirla_durumEnSonSilinir_yaridaKalirsaDurumYerinde" },
  // ── 5D-3 yerel dosya akitma (DepoYolu) ──
  { ad: "5D-K: depo dosyasi GET disi yontemlere de veriliyor (curutucu 5D Y13)", dosya: DEPO + "DepoYolu.kt",
    bul: "if (yontem == \"GET\") kimlik(url) else null", koy: "kimlik(url)",
    kirmizi: "DepoYoluTest.dosyaYalnizGetIleVerilir" },
  { ad: "5D-K: WebKapi Capacitor'in dosya on ekini geciriyor (curutucu 5D B13)", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/WebKapi.kt",
    bul: "if (yol.contains('%') || yol.contains(\"/_capacitor_\")) return false", koy: "if (yol.contains('%')) return false",
    kirmizi: "WebKapiTest.capacitorDosyaOnEkleriKapali_yuzdeKacisiYoldaYok" },
  { ad: "5D-K: WebKapi yolda yuzde kacisini kabul ediyor (%5Fcapacitor_file_)", dosya: "android/app/src/main/java/tr/olcumkarti/mobil/WebKapi.kt",
    bul: "if (yol.contains('%') || yol.contains(\"/_capacitor_\")) return false", koy: "if (yol.contains(\"/_capacitor_\")) return false",
    kirmizi: "WebKapiTest.capacitorDosyaOnEkleriKapali_yuzdeKacisiYoldaYok" },
  { ad: "5D-K: depo adresi buyuk harfli kimligi kabul ediyor (dosya sistemi ayni dizine gidebilir)", dosya: DEPO + "DepoYolu.kt",
    bul: "([0-9a-f]{16})/kayitlar", koy: "([0-9a-fA-F]{16})/kayitlar",
    kirmizi: "DepoYoluTest.baskaHerBicimReddedilir" },
  { ad: "5D-K: depo adresi tam esleme yerine icinde arama yapiyor", dosya: DEPO + "DepoYolu.kt",
    bul: "BICIM.matchEntire(url)", koy: "BICIM.find(url)",
    kirmizi: "DepoYoluTest.baskaHerBicimReddedilir" },
  { ad: "5D-K: depo on ekini tasiyan bozuk adres dosya sunucusuna birakiliyor", dosya: DEPO + "DepoYolu.kt",
    bul: "fun depoAdresi(url: String?): Boolean = url != null && url.startsWith(ON_EK)", koy: "fun depoAdresi(url: String?): Boolean = kimlik(url) != null",
    kirmizi: "DepoYoluTest.depoOnEkiTasiyanBozukAdresDosyaSunucusunaBirakilmaz" },
  // ── 5C curutucu duzeltmeleri (DURUM 2026-10-05, bulgu 1, 8, 10) ─────────
  {
    ad: "5C-KD: p0'da her 2xx basari sayiliyor (kart olmayan adres 'durduruldu' der)",
    dosya: AG + "P0.kt",
    bul: "if (kod == BASARI_KODU) return deneme",
    koy: "if (kod in 200..299) return deneme",
    kirmizi: "P0Test.yalniz204Basaridir_baska2xxBasariDegilVeYenidenDenenmez",
  },
  {
    ad: "5C-KD: baska adresin basarisi beklemeyi bitiriyor (asil kartin yeniden denemesi sonuca girmez)",
    dosya: AG + "P0.kt",
    bul: "if (!asilVar || adres == asil) bitti.countDown()",
    koy: "bitti.countDown()",
    kirmizi: "P0Test.baskaAdresinBasarisiAsilKartinYenidenDenemesiniKesmez",
  },
  {
    ad: "5C-KD: asil yokken de ilk adres bekleniyor (cozulemeyen olcum.local sonucu bekletir)",
    dosya: AG + "P0.kt",
    bul: "p0.durdur(adresler, asilVar = asilVar) } catch",
    koy: "p0.durdur(adresler) } catch",
    kirmizi: "P0Test.asilYokkenTurAyriSayilir",
  },
  {
    ad: "5C-KD: kalici hata (Wi-Fi yok) da yeniden deneniyor",
    dosya: AG + "P0.kt",
    bul: "if (e.tur in KALICI_HATALAR) return 0",
    koy: "",
    kirmizi: "P0Test.kaliciHataYenidenDenenmez_geciciHataDenenir",
  },
  {
    ad: "5C-KD: suren p0 turuna baglanilmiyor (her dokunus yeni is parcaciklari acar)",
    dosya: AG + "P0.kt",
    bul: "if (b != null && surenAdresler == adresler && surenAsilVar == asilVar) {",
    koy: "if (b != null && surenAdresler == null) {",
    kirmizi: "P0Test.surenTuraBaglanir_yeniIsParcacigiAcmaz_turBitinceYeniTurBaslar",
  },
  {
    ad: "5C-KD: SSE alan adi harfe duyarli ('Event: kimlik' varsayilan olay olur, jeton tasinir)",
    dosya: AG + "SseAyirici.kt",
    bul: "when (alan.lowercase()) {",
    koy: "when (alan) {",
    kirmizi: "SseAyiriciTest.alanAdlariBuyukKucukHarfeDuyarsiz",
  },
  {
    ad: "5C-KD: kimlik olayinda ad degisince veri tasiniyor (gizli isareti konmuyor)",
    dosya: AG + "SseAyirici.kt",
    bul: "                    gizli = true\n",
    koy: "",
    kirmizi: "SseAyiriciTest.kimlikOlayininVerisiHicbirYoldanTasinmaz",
  },
];
