// Kotlin (JVM birim testi) mutasyonlari: her iddianin onu YALANLAYAN degisikligi.
//   ad    : "<dilim>: ne bozuluyor"
//   dosya : mobil/'e gore; bul: kaynakta TAM BIR KEZ gecen dizgi; koy: yerine konan
//   kirmizi: bu mutasyonda kirmiziya donmesi beklenen test (elle dogrulandi, 2026-10-04)
// Test: cd android && ./gradlew.bat testDebugUnitTest  (her mutasyon ayri kosu, ~1 dk) — KIRMIZI beklenir.
// fsync'in kalkmasi JVM testinde gozlenemez (elektrik kesmesi gerekir): bilerek listede YOK.
const KASA = "android/app/src/main/java/tr/olcumkarti/mobil/kasa/";
const AG = "android/app/src/main/java/tr/olcumkarti/mobil/ag/";
const DEPO = "android/app/src/main/java/tr/olcumkarti/mobil/depo/";

export default [
  {
    ad: "5B-K: sayacta geri denetimi kalkti",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (isaret < eski) throw KasaHatasi("geri")',
    koy: "",
    kirmizi: "SayacDosyasiTest.kucukDegerGeri_dosyaDegismez",
  },
  {
    ad: "5B-K: sayacta ESIT yazim kabul ediliyor (ikinci yazar ayni blogu kullanir — curutucu 5B S4)",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (vardi && isaret == eski) throw KasaHatasi("geri")',
    koy: "",
    kirmizi: "SayacDosyasiTest.esitYazimGeri_buyukKabul",
  },
  {
    ad: "5B-K: dosya yokken ilk yazim (0 dahil) 'geri' sayiliyor",
    dosya: KASA + "SayacDosyasi.kt",
    bul: "if (vardi && isaret == eski) throw",
    koy: "if (isaret == eski) throw",
    kirmizi: "SayacDosyasiTest.dosyaYokkenHerDegerIlkYazimdir_sifirDahil",
  },
  {
    ad: "5B-K: sil once sayaci siliyor (yarida kalirsa eski K sayac 0 ile yasar)",
    dosya: KASA + "KasaDeposu.kt",
    bul: "if (it == kimlik + ANAHTAR_EK) 0 else 1",
    koy: "if (it == kimlik + ANAHTAR_EK) 1 else 0",
    kirmizi: "KasaDeposuTest.silOnceAnahtariSiler_yaridaKalirsaAnahtarYasamaz",
  },
  {
    ad: "5B-K: bozuk saglamali sayac dosyasi kabul ediliyor",
    dosya: KASA + "SayacDosyasi.kt",
    bul: 'if (satirlar[1] != saglama(satirlar[0])) throw KasaHatasi("bozuk")',
    koy: "",
    kirmizi: "SayacDosyasiTest.bozukVeYarimDosyaBozuk_sifirDonmez",
  },
  {
    ad: "5B-K: kimlik deseni gevsedi (yol kacisi)",
    dosya: KASA + "KasaKayit.kt",
    bul: "kimlik.all { it in '0'..'9' || it in 'a'..'f' }",
    koy: "true",
    kirmizi: "KasaDeposuTest.kotuKimlikHerIslemdeBicim_dizinDisinaCikilamaz",
  },
  {
    ad: "5B-K: AAD'den kimlik cikti",
    dosya: KASA + "KasaKayit.kt",
    bul: "SIHIR + byteArrayOf(SURUM) + kimlik.toByteArray(Charsets.US_ASCII)",
    koy: "SIHIR + byteArrayOf(SURUM)",
    kirmizi: "KasaKayitTest.yanlisKimlikleAcilmaz",
  },
  {
    ad: "5B-K: anahtar uzunlugu denetimi kalkti",
    dosya: KASA + "KasaKayit.kt",
    bul: 'if (anahtar.size != ANAHTAR_BOYU) throw KasaHatasi("bicim")',
    koy: "",
    kirmizi: "KasaKayitTest.anahtarUzunluguTam32",
  },
  {
    ad: "5B-K: sil sayac dosyasini birakiyor",
    dosya: KASA + "KasaDeposu.kt",
    bul: 'ad.startsWith("$kimlik.")',
    koy: "ad == kimlik + ANAHTAR_EK",
    kirmizi: "KasaDeposuTest.silSonrasiYokVeSayacSifir",
  },
  {
    ad: "5A-K: HttpIstek toplam sure bekcisi kurulmuyor",
    dosya: AG + "HttpIstek.kt",
    bul: "}, zamanAsimiMs.toLong(), TimeUnit.MILLISECONDS)",
    koy: "}, Long.MAX_VALUE / 2, TimeUnit.MILLISECONDS)",
    kirmizi: "HttpIstekTest.baslikDamlatanSunucuToplamSureyleKesilir",
  },
  {
    ad: "5A-K: cozulen adres ozel adres suzgecinden gecmiyor",
    dosya: AG + "HedefCoz.kt",
    bul: "adresler.firstOrNull { Hedef.ozelAdres(it) }",
    koy: "adresler.firstOrNull()",
    kirmizi: "HedefCozTest.adCozulurVeCozulenAdresDeKuraldanGecer",
  },
  {
    ad: "5C-K: 4096 bayti asan SSE satiri bos satir gibi isleniyor (olay yarim veriyle dagitilir)",
    dosya: AG + "SseAyirici.kt",
    bul: "if (uzun) {",
    koy: "if (false) {",
    kirmizi: "SseAyiriciTest.satirSiniri4096Bayt_uzunSatirinOlayiAtilirSonrakiSaglam",
  },
  {
    ad: "5C-K: adli olaylar (kimlik: oturum jetonu) da satir olarak JS'e tasiniyor",
    dosya: AG + "Akis.kt",
    bul: 'if (o.ad.isEmpty() || o.ad == "message") satirlar.add(o.veri)',
    koy: "satirlar.add(o.veri)",
    kirmizi: "AkisTest.kartGibiAkis_satirlarSirayla_kimlikOlayiTasinmaz_baglantiBitinceKapandi",
  },
  {
    ad: "5C-K: kapat() baglantiyi kesmiyor (bloklu okuma surer, kartin yuvasi dolu kalir)",
    dosya: AG + "Akis.kt",
    bul: "try { baglanti?.disconnect() } catch (_: Exception) {}",
    koy: "",
    kirmizi: "AkisTest.kapat_blokluOkumayiHemenKeser_tekBitis_sonrasindaSatirYok",
  },
  // ── 5D-1 KartDepo ──
  { ad: "5D-K: kimlik bicimi denetlenmiyor (yol kacisi)", dosya: DEPO + "KartDepo.kt",
    bul: "if (kimlik == null || !KIMLIK.matches(kimlik)) throw DepoHatasi(\"bicim\")", koy: "if (kimlik == null) throw DepoHatasi(\"bicim\")",
    kirmizi: "KartDepoTest.kimlikYalniz16OnaltilikHane_yolKacisiYok" },
  { ad: "5D-K: ekleme dosyanin ustune yaziyor (sona eklemiyor)", dosya: DEPO + "KartDepo.kt",
    bul: "FileOutputStream(f, true).use { a ->", koy: "FileOutputStream(f, false).use { a ->",
    kirmizi: "KartDepoTest.ekle_sonaEkler_boyDoner_parcaliOkumaAyniBaytlar" },
  { ad: "5D-K: okuma bas konumuna gitmiyor", dosya: DEPO + "KartDepo.kt",
    bul: "                r.seek(bas)\n", koy: "",
    kirmizi: "KartDepoTest.ekle_sonaEkler_boyDoner_parcaliOkumaAyniBaytlar" },
  { ad: "5D-K: kirpma dosya boyunu degistirmiyor", dosya: DEPO + "KartDepo.kt",
    bul: "                r.setLength(n)\n", koy: "",
    kirmizi: "KartDepoTest.kirp_kisaltir_uzatirsaSifirDoldurur" },
  { ad: "5D-K: durum gecici dosyaya degil dogrudan hedefe yaziliyor (yarim durum gorulebilir)", dosya: DEPO + "KartDepo.kt",
    bul: "val g = File(hedef.parentFile, hedef.name + GECICI_EK)", koy: "val g = File(hedef.parentFile, hedef.name)",
    kirmizi: "KartDepoTest.durumVeKalibrasyon_atomik_geciciKalintiOkumayiEtkilemez" },
  { ad: "5D-K: arsiv ayni adin ustune yaziyor", dosya: DEPO + "KartDepo.kt",
    bul: "while (File(d, ad).exists()) {", koy: "while (false) {",
    kirmizi: "KartDepoTest.arsiv_zamanDamgaliAd_cakismadaNumara_icerikAyni" },
  { ad: "5D-K: okuma tavani yok", dosya: DEPO + "KartDepo.kt",
    bul: "if (bas < 0 || azami < 1 || azami > OKUMA_AZAMI) throw DepoHatasi(\"bicim\")", koy: "if (bas < 0 || azami < 1) throw DepoHatasi(\"bicim\")",
    kirmizi: "KartDepoTest.sinirlar_okumaYazmaKirpma" },
  { ad: "5D-K: sifirla dizini birakiyor", dosya: DEPO + "KartDepo.kt",
    bul: "        if (!d.delete() && d.exists()) throw DepoHatasi(\"yazilamadi\")\n    }\n\n    /** Depolama", koy: "    }\n\n    /** Depolama",
    kirmizi: "KartDepoTest.sifirla_yalnizOKartinDosyalari_sonraBos" },
  // ── 5D-3 yerel dosya akitma (DepoYolu) ──
  { ad: "5D-K: depo adresi buyuk harfli kimligi kabul ediyor (dosya sistemi ayni dizine gidebilir)", dosya: DEPO + "DepoYolu.kt",
    bul: "([0-9a-f]{16})/kayitlar", koy: "([0-9a-fA-F]{16})/kayitlar",
    kirmizi: "DepoYoluTest.baskaHerBicimReddedilir" },
  { ad: "5D-K: depo adresi tam esleme yerine icinde arama yapiyor", dosya: DEPO + "DepoYolu.kt",
    bul: "BICIM.matchEntire(url)", koy: "BICIM.find(url)",
    kirmizi: "DepoYoluTest.baskaHerBicimReddedilir" },
  { ad: "5D-K: depo on ekini tasiyan bozuk adres dosya sunucusuna birakiliyor", dosya: DEPO + "DepoYolu.kt",
    bul: "fun depoAdresi(url: String?): Boolean = url != null && url.startsWith(ON_EK)", koy: "fun depoAdresi(url: String?): Boolean = kimlik(url) != null",
    kirmizi: "DepoYoluTest.depoOnEkiTasiyanBozukAdresDosyaSunucusunaBirakilmaz" },
  // ── 5C curutucu duzeltmeleri (DURUM 2026-10-05, bulgu 1, 8, 10) ─────────
  {
    ad: "5C-KD: p0'da her 2xx basari sayiliyor (kart olmayan adres 'durduruldu' der)",
    dosya: AG + "P0.kt",
    bul: "if (kod == BASARI_KODU) return deneme",
    koy: "if (kod in 200..299) return deneme",
    kirmizi: "P0Test.yalniz204Basaridir_baska2xxBasariDegilVeYenidenDenenmez",
  },
  {
    ad: "5C-KD: baska adresin basarisi beklemeyi bitiriyor (asil kartin yeniden denemesi sonuca girmez)",
    dosya: AG + "P0.kt",
    bul: "if (!asilVar || adres == asil) bitti.countDown()",
    koy: "bitti.countDown()",
    kirmizi: "P0Test.baskaAdresinBasarisiAsilKartinYenidenDenemesiniKesmez",
  },
  {
    ad: "5C-KD: asil yokken de ilk adres bekleniyor (cozulemeyen olcum.local sonucu bekletir)",
    dosya: AG + "P0.kt",
    bul: "p0.durdur(adresler, asilVar = asilVar) } catch",
    koy: "p0.durdur(adresler) } catch",
    kirmizi: "P0Test.asilYokkenTurAyriSayilir",
  },
  {
    ad: "5C-KD: kalici hata (Wi-Fi yok) da yeniden deneniyor",
    dosya: AG + "P0.kt",
    bul: "if (e.tur in KALICI_HATALAR) return 0",
    koy: "",
    kirmizi: "P0Test.kaliciHataYenidenDenenmez_geciciHataDenenir",
  },
  {
    ad: "5C-KD: suren p0 turuna baglanilmiyor (her dokunus yeni is parcaciklari acar)",
    dosya: AG + "P0.kt",
    bul: "if (b != null && surenAdresler == adresler && surenAsilVar == asilVar) {",
    koy: "if (b != null && surenAdresler == null) {",
    kirmizi: "P0Test.surenTuraBaglanir_yeniIsParcacigiAcmaz_turBitinceYeniTurBaslar",
  },
  {
    ad: "5C-KD: SSE alan adi harfe duyarli ('Event: kimlik' varsayilan olay olur, jeton tasinir)",
    dosya: AG + "SseAyirici.kt",
    bul: "when (alan.lowercase()) {",
    koy: "when (alan) {",
    kirmizi: "SseAyiriciTest.alanAdlariBuyukKucukHarfeDuyarsiz",
  },
  {
    ad: "5C-KD: kimlik olayinda ad degisince veri tasiniyor (gizli isareti konmuyor)",
    dosya: AG + "SseAyirici.kt",
    bul: "                    gizli = true\n",
    koy: "",
    kirmizi: "SseAyiriciTest.kimlikOlayininVerisiHicbirYoldanTasinmaz",
  },
];
