// Mutasyon listesi: her iddianin onu YALANLAYAN degisikligi.
//   ad    : "<dilim>: ne bozuluyor"  (--neden ONEK ile suzulur)
//   dosya : mobil/'e gore; bul: kaynakta TAM BIR KEZ gecen dizgi; koy: yerine konan
//   test  : vitest dosyasi (mobil/'e gore) ya da { komut: [...] }
import curutucu from "../test/curutucu/yasayan-liste.mjs";
import curutucu5b from "../test/curutucu-5b/duzeltme-liste.mjs";
import p0 from "./p0-liste.mjs";
import akis from "./akis-liste.mjs";
import kabuk from "./kabuk-liste.mjs";
import curutucu5c from "../test/curutucu-5c/yasayan-liste.mjs";
import duzeltme5c from "./duzeltme5c-liste.mjs";

export default [
  ...curutucu.map((m) => ({ ...m, ad: `5A-7 ${m.ad}` })),
  // Curutucu 5B: yasayan mutasyonlar + duzeltmelerin mutasyonlari ("5B-C: ..." adlariyla gelir).
  ...curutucu5b,
  ...curutucu5c,
  ...duzeltme5c,
  ...p0,
  ...akis,
  ...kabuk,
  {
    ad: "5A-2: sozlukte EN metni bos",
    dosya: "src/cekirdek/sozluk_mobil.js",
    bul: '"Measurement Board"',
    koy: '""',
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-2: sablonda gomulu metin",
    dosya: "src/ekran/KartBul.vue",
    bul: '<h1>{{ c("m.kb.baslik") }}</h1>',
    koy: "<h1>Kartı bul</h1>",
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-2: gomulu metin ayiklayicisi duz ozellige bakmiyor",
    dosya: "test/yardim/gomulu_metin.mjs",
    bul: "if (HARF.test(deger)) bulunan.push(",
    koy: "if (false) bulunan.push(",
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-3: kayan pencere denetimi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: "if (!pencereKabul(pencereler.get(n), sayac)) {",
    koy: "if (false) {",
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-3: Host beyaz listesi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: 'return h === ip || h.toLowerCase() === "olcum.local" || h.toLowerCase() === "olcum";',
    koy: "return true;",
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-3: p0 serbestligi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: 'return k === "p0" || k === "?";',
    koy: 'return k === "?";',
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-4: 172.16/12 siniri 172/8 oldu",
    dosya: "src/cekirdek/hedef.js",
    bul: "(a === 172 && b >= 16 && b <= 31)",
    koy: "(a === 172)",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: bas sifirli (sekizlik gorunumlu) parca kabul",
    dosya: "src/cekirdek/hedef.js",
    bul: "/^(0|[1-9][0-9]{0,2})$/",
    koy: "/^[0-9]{1,4}$/",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: herkese acik IP reddi kalkti",
    dosya: "src/cekirdek/hedef.js",
    bul: 'throw new HedefHatasi("ozel-degil");',
    koy: "return { ad, port };",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: ad karsilastirmasi 'ile baslar' oldu",
    dosya: "src/cekirdek/hedef.js",
    bul: "if (ad.toLowerCase() === KART_ADI)",
    koy: "if (ad.toLowerCase().startsWith(KART_ADI))",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: yerel dongu secenek olmadan da izinli",
    dosya: "src/cekirdek/hedef.js",
    bul: "(yerelDongu && yerelDonguAdresi(ad))",
    koy: "yerelDonguAdresi(ad)",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: kartFetch hedef kuralini istekten once denetlemiyor",
    dosya: "src/cekirdek/ag.js",
    bul: "    urlDenetle(url, { yerelDongu });\n",
    koy: "",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-4: eklenti hatasinin ham kodu disari siziyor",
    dosya: "src/cekirdek/ag.js",
    bul: 'HATA_TURLERI.includes(e.code) ? e.code : "ic-hata"',
    koy: "true ? e.code : null",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-4: baslik adi buyuk/kucuk harfe duyarli",
    dosya: "src/cekirdek/ag.js",
    bul: "(basliklar.has(ad.toLowerCase()) ? basliklar.get(ad.toLowerCase()) : null)",
    koy: "(basliklar.has(ad) ? basliklar.get(ad) : null)",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-5: kimlik karsilastirmasi kalkti (yanlis karta baglanir)",
    dosya: "src/cekirdek/kesif.js",
    bul: "(!beklenenKimlik || s.kimlik === beklenenKimlik)",
    koy: "true",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: kimlik bicimi denetlenmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: '|| typeof b.kimlik !== "string" || !KIMLIK_DESENI.test(b.kimlik)',
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: elle adres hedef kuralindan gecmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: 'liste.push({ adres: hedefYazi(hedefAyir(elle, { yerelDongu })), kaynak: "elle" });',
    koy: 'liste.push({ adres: elle, kaynak: "elle" });',
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: NSD'den gelen herkese acik adres aday oluyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "try { adres = hedefYazi(hedefAyir(`${s.ip}:${s.port}`, { yerelDongu })); } catch { continue; }",
    koy: "adres = `${s.ip}:${s.port}`;",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: elle adres onceligi yok (hizli olan kazaniyor)",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (elleBekliyor) yedek = yedek || s; else kapat(s);",
    koy: "kapat(s);",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: 200 olmayan yanit kabul",
    dosya: "src/cekirdek/kesif.js",
    bul: 'if (y.status !== 200) return { ...aday, sonuc: "yanit-gecersiz" };',
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: bilgi govdesi siniri kalkti",
    dosya: "src/cekirdek/kesif.js",
    bul: "zamanAsimiMs, azamiGovde: AZAMI_BILGI });",
    koy: "zamanAsimiMs, azamiGovde: 64 * 1024 * 1024 });",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: ayni adres iki kez yoklaniyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (gorulen.has(aday.adres)) return;",
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: kimlik uymayan kart onbellege yaziliyor / hata turu ayrilmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: 'throw new KesifHatasi(yanlis ? "kimlik-uymuyor" : "bulunamadi", denenenler);',
    koy: 'throw new KesifHatasi("bulunamadi", denenenler);',
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-6: Capacitor kopru gunlugu acik (eklenti verisi logcat'e duser)",
    dosya: "capacitor.config.json",
    bul: '"loggingBehavior": "none"',
    koy: '"loggingBehavior": "debug"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: eklenti adresi logcat'e yaziyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/ag/KartAgPlugin.kt",
    bul: 'if (url == null) { call.reject("bicim", "bicim"); return }',
    koy: 'if (url == null) { call.reject("bicim", "bicim"); return }; android.util.Log.d("KartAg", url)',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: yedekleme acik",
    dosya: "android/app/src/main/AndroidManifest.xml",
    bul: 'android:allowBackup="false"',
    koy: 'android:allowBackup="true"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: bilesen ayri surecte (S1)",
    dosya: "android/app/src/main/AndroidManifest.xml",
    bul: 'android:launchMode="singleTask"',
    koy: 'android:launchMode="singleTask" android:process=":ayri"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: CSP connect-src disari acik",
    dosya: "index.html",
    bul: "connect-src 'self';",
    koy: "connect-src 'self' http:;",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: CSP cerceve yasagi kalkti",
    dosya: "index.html",
    bul: " frame-src 'none';",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: istek kapisi kalkti (shouldInterceptRequest)",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "                if (!WebKapi.INSTANCE.izinli(request.getUrl().toString())) {",
    koy: "                if (false) {",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: gezinti kapisi kalkti (dis adres tarayicida acilir)",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "                if (!WebKapi.INSTANCE.izinli(request.getUrl().toString())) return true;",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: cerez yoneticisi yerinde kaliyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "        CookieHandler.setDefault(null);",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: WebView hata ayiklamasi acik",
    dosya: "capacitor.config.json",
    bul: '"webContentsDebuggingEnabled": false',
    koy: '"webContentsDebuggingEnabled": true',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: uretim kodu WebView'in fetch'ini cagiriyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "    const t0 = simdi();",
    koy: '    const t0 = simdi(); fetch("http://example.com/").catch(() => {});',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-7: kartFetch'in kendi suresi yok (eklenti donmezse asili kalir)",
    dosya: "src/cekirdek/ag.js",
    bul: "sonuc = await sureli(eklenti.istek(istek), istek.zamanAsimiMs + SURE_PAYI_MS);",
    koy: "sonuc = await eklenti.istek(istek);",
    test: "test/curutucu/ag.curutucu.test.js",
  },
  {
    ad: "5A-7: bozuk yanit govdesi ham istisna olarak cikiyor",
    dosya: "src/cekirdek/ag.js",
    bul: '      throw new KartAgHatasi("ic-hata");       // bozuk base64 vb.: ham istisna disari cikmaz',
    koy: "      throw new Error(\"x\");",
    test: "test/curutucu/ag.curutucu.test.js",
  },
  {
    ad: "5A-7: URL'de ad cevresinde bosluk kabul",
    dosya: "src/cekirdek/ag.js",
    bul: "if (!m || /[^\\x21-\\x7e]/.test(m[1])) throw",
    koy: "if (!m) throw",
    test: "test/curutucu/ag.curutucu.test.js",
  },
  {
    ad: "5A-7: NSD taramasinin suresi yok (tarama donmezse kesif asili)",
    dosya: "src/cekirdek/kesif.js",
    bul: "(await sureli(eklenti.nsdTara({ sureMs: nsdSureMs }), nsdSureMs + NSD_PAYI_MS))",
    koy: "(await eklenti.nsdTara({ sureMs: nsdSureMs }))",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: yoklamanin kendi suresi yok (aday donmezse kesif asili)",
    dosya: "src/cekirdek/kesif.js",
    bul: "sureli(yokla(aday), zamanAsimiMs + TOPLAM_PAYI_MS).catch(() => ({ ...aday, sonuc: \"zaman-asimi\" })).then((s) => {",
    koy: "yokla(aday).then((s) => {",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: TXT kimligi uymayan duyuru eleniyor (kart gizlenebilir)",
    dosya: "src/cekirdek/kesif.js",
    bul: "      const onceki = adaylar.get(adres);",
    koy: "      if (beklenenKimlik && txtKimlik && txtKimlik !== beklenenKimlik) continue; const onceki = adaylar.get(adres);",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: kimligi uyan duyuru one alinmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "return [...adaylar.values()].sort((a, b) => puan(a) - puan(b))",
    koy: "return [...adaylar.values()]",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: CSP'de webrtc yasagi yok",
    dosya: "index.html",
    bul: "; webrtc 'block'",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-7: CSP'ye fazladan yonerge (worker-src) eklendi",
    dosya: "index.html",
    bul: "; webrtc 'block'",
    koy: "; webrtc 'block'; worker-src blob: data:",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-7: CSP meta etiketi tumuyle silindi",
    dosya: "index.html",
    bul: 'http-equiv="Content-Security-Policy"',
    koy: 'http-equiv="X-Yok"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: WebRTC kaldirma JS'te ilk ice aktarim degil",
    dosya: "src/main.js",
    bul: 'import "./cekirdek/rtc_kapat.js";',
    koy: '// import "./cekirdek/rtc_kapat.js";',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: yerelde belge basi betigi eklenmiyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "            WebViewCompat.addDocumentStartJavaScript(",
    koy: "            // WebViewCompat.addDocumentStartJavaScript(",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: WebRTC arayuzu geri konabiliyor (kilitli degil)",
    dosya: "src/cekirdek/rtc_kapat.js",
    bul: "{ value: undefined, writable: false, configurable: false }",
    koy: "{ value: undefined, writable: true, configurable: true }",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: Kotlin listesinde RTCPeerConnection yok",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/WebKapi.kt",
    bul: '        "RTCPeerConnection", "webkitRTCPeerConnection",',
    koy: '        "webkitRTCPeerConnection",',
    test: "test/gizlilik.test.js",
  },

  // ── 5B: kasa (A14, A16) ────────────────────────────────────────────────
  {
    ad: "5B: isaret istekten once yazilmiyor (kaydet yazimi beklemiyor)",
    dosya: "src/cekirdek/kasa.js",
    bul: '        await cagir("sayacYaz", { kimlik: cihaz.kimlik, isaret: String(hedef) });',
    koy: '        cagir("sayacYaz", { kimlik: cihaz.kimlik, isaret: String(hedef) }).catch(() => {});',
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: isaret istekten once yazilmiyor — uctan uca (istek yola cikarken disk geride)",
    dosya: "src/cekirdek/kasa.js",
    bul: '        await cagir("sayacYaz", { kimlik: cihaz.kimlik, isaret: String(hedef) });',
    koy: '        cagir("sayacYaz", { kimlik: cihaz.kimlik, isaret: String(hedef) }).catch(() => {});',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: blok ayirma kalkti (her istekte disk yazimi)",
    dosya: "src/cekirdek/kasa.js",
    bul: "      const hedef = s + blok;",
    koy: "      const hedef = s;",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: acilista sayac isaretten degil 0'dan basliyor",
    dosya: "src/cekirdek/kasa.js",
    bul: "sayac: isaret, acilis: null };",
    koy: "sayac: 0, acilis: null };",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: acilista sayac 0'dan basliyor — uctan uca (saat geri alinmis, kart reddeder)",
    dosya: "src/cekirdek/kasa.js",
    bul: "sayac: isaret, acilis: null };",
    koy: "sayac: 0, acilis: null };",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: tek yazim kuyrugu kalkti (es zamanli kaydet ust uste)",
    dosya: "src/cekirdek/kasa.js",
    bul: "    const soz = kuyruk.then(is);",
    koy: "    const soz = Promise.resolve().then(is);",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: 'geri'den once secilmis sayaclar reddedilmiyor (nesil artmiyor)",
    dosya: "src/cekirdek/kasa.js",
    bul: "        k.nesil += 1;",
    koy: "",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: 'geri'de sayac diskteki isarete cekilmiyor",
    dosya: "src/cekirdek/kasa.js",
    bul: "        k.nesil += 1;\n        if (cihaz.sayac < k.isaret) cihaz.sayac = k.isaret;",
    koy: "        k.nesil += 1;",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: bozuk isaret sessizce 0 sayiliyor",
    dosya: "src/cekirdek/kasa.js",
    bul: 'if (typeof metin !== "string" || !ISARET.test(metin)) throw new KasaHatasi("bozuk");',
    koy: 'if (typeof metin !== "string" || !ISARET.test(metin)) return 0;',
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: sil / degistirme bellekteki K'yi sifirlamiyor",
    dosya: "src/cekirdek/kasa.js",
    bul: "    if (k) k.cihaz.K.fill(0);",
    koy: "",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: kaydet kayitli olmayan cihaz nesnesini kabul ediyor",
    dosya: "src/cekirdek/kasa.js",
    bul: 'if (!k || k.cihaz !== cihaz || sifirMi(cihaz.K)) throw new KasaHatasi("kayitsiz");',
    koy: 'if (!k || sifirMi(cihaz.K)) throw new KasaHatasi("kayitsiz");',
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: cihazYukle her cagrida yeni nesne (iki nesne ayni sayaci secer)",
    dosya: "src/cekirdek/kasa.js",
    bul: "      if (onceki) return onceki.cihaz;",
    koy: "",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: yanlis boydaki anahtar kabul ediliyor",
    dosya: "src/cekirdek/kasa.js",
    bul: 'if (K.length !== ANAHTAR_BOYU) { K.fill(0); throw new KasaHatasi("bozuk"); }',
    koy: "",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: liste acilamayan kaydi tasimiyor",
    dosya: "src/cekirdek/kasa.js",
    bul: "&& k.bozuk === true) return { kimlik: k.kimlik, bozuk: true };",
    koy: "&& k.bozuk === 1) return { kimlik: k.kimlik, bozuk: true };",
    test: "test/kasa.test.js",
  },
  {
    ad: "5B: kasa hatasi eklentinin kodunu aynen tasiyor (tur suzgeci yok)",
    dosya: "src/cekirdek/kasa.js",
    bul: 'e && typeof e.code === "string" && EKLENTI_TURLERI.includes(e.code) ? e.code : "ic-hata"',
    koy: 'e && typeof e.code === "string" ? e.code : "ic-hata"',
    test: "test/kasa.test.js",
  },

  // ── 5B: kart (A2, A12–A19) ─────────────────────────────────────────────
  {
    ad: "5B: kimlik dogrulanmadan imzali istek (kesfin sonucuna guveniliyor)",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (cihaz && s.kimlik !== cihaz.kimlik) return yok("kimlik-uymuyor");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: kesfe beklenen kimlik verilmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: "beklenenKimlik: cihaz ? cihaz.kimlik : null, elle",
    koy: "beklenenKimlik: null, elle",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: baglanti surerken kart degisince kimlik yeniden dogrulanmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: "      if (yeni !== imzalanan) {",
    koy: "      if (false) {",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: eslesmemisken imzali istek denetimi kalkti",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (!c || b.kimlik !== c.kimlik) throw new KartHatasi("eslesmemis");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: 401 ayni acilista K siliniyor",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (e instanceof HttpHatasi) return e.durum === 401 ? new KartHatasi("cihaz-silinmis")',
    koy: '    if (e instanceof HttpHatasi && e.durum === 401) kasa.sil(cihaz.kimlik);\n    if (e instanceof HttpHatasi) return e.durum === 401 ? new KartHatasi("cihaz-silinmis")',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: 401 ayni acilis 'cihaz-silinmis' yerine genel HTTP hatasi",
    dosya: "src/cekirdek/kart.js",
    bul: 'return e.durum === 401 ? new KartHatasi("cihaz-silinmis") : new KartHatasi("http", { durum: e.durum });',
    koy: 'return new KartHatasi("http", { durum: e.durum });',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: kart kaniti yanlisken cihaz saklaniyor (taklit kart dogru kanit verirse test KIRMIZI olmali)",
    dosya: "test/kart.test.js",
    bul: "kanitDogru: false }));",
    koy: "kanitDogru: true }));",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: kart kaniti reddi 'kart-sahte' olarak ayirt edilmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (son && son.yol === "/eslestir/kanit" && son.durum >= 200 && son.durum < 300) return new KartHatasi("kart-sahte");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: kisa parola denetimi kalkti (karta gitmeden once tur 'parola-kisa')",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (typeof parola !== "string" || utf8Kodla(parola).length < PAROLA_EN_AZ) throw new KartHatasi("parola-kisa");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: kisa parola KARAKTER sayisiyla olculuyor (bayt degil)",
    dosya: "src/cekirdek/kart.js",
    bul: "utf8Kodla(parola).length < PAROLA_EN_AZ",
    koy: "utf8Kodla(parola).length < 5",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: tur sinir denetimi kalkti",
    dosya: "src/cekirdek/kart.js",
    bul: '        if (!Number.isInteger(j.tur) || j.tur < TUR_EN_AZ || j.tur > TUR_EN_COK) throw new KartHatasi("tur-sinir-disi");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: eslestirmede kartin kimligi ekrandakiyle karsilastirilmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '        if (!j || j.kimlik !== b.kimlik) throw new KartHatasi("kimlik-uymuyor");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: yanlis parola ile deneme siniri ayirt edilmiyor (bekle)",
    dosya: "src/cekirdek/kart.js",
    bul: '  "/eslestir/baslat 429": "bekle",',
    koy: '  "/eslestir/baslat 429": "parola-yanlis",',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: zaten esliyken yeniden eslestirme serbest",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (cihaz) throw new KartHatasi("zaten-esli");',
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: anahtar saklanamayinca karttaki yetim cihaz silinmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '        await ac(yeni, taban, "POST", "/cihaz/sil"',
    koy: '        await ac(yeni, taban, "POST", "/cihaz/yok"',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: 'sayac-geride' sonrasi yeniden imzalanmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '&& e.tur === "sayac-geride" && sayacDenemesi++ === 0) continue;',
    koy: '&& e.tur === "sayac-geride" && sayacDenemesi++ === 9) continue;',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: saat baglanti basina bir kez degil her cagrida veriliyor",
    dosya: "src/cekirdek/kart.js",
    bul: "    b.saatVerildi = true; ",
    koy: "    ",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: NTP'li karta da saat veriliyor",
    dosya: "src/cekirdek/kart.js",
    bul: "    if (b.bilgi && b.bilgi.saat === 1) return false;",
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: /saat 409 sessiz gecilmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '&& e.tur === "http" && e.durum === 409) return false;',
    koy: '&& e.tur === "http" && e.durum === 499) return false;',
    test: "test/kart.test.js",
  },
  {
    ad: "5B: eslesmeyi kaldir kartta silmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '        await istek("POST", "/cihaz/sil", [["n", String(cihaz.n)]]);\n        kartta = true;',
    koy: "        kartta = true;",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: eslesmeyi kaldir yerelde K'yi silmiyor",
    dosya: "src/cekirdek/kart.js",
    bul: "      for (const kimlik of kimlikler) await kasa.sil(kimlik);",
    koy: "",
    test: "test/kart.test.js",
  },
  {
    ad: "5B: KartHatasi izinli alanlarin (tur, durum, saniye, ag) disinda alan tasiyor",
    dosya: "src/cekirdek/kart.js",
    bul: '    if (ek && typeof ek.ag === "string") this.ag = ek.ag;',
    koy: '    if (ek && typeof ek.ag === "string") { this.ag = ek.ag; this.ayrinti = String(ek.ag); }',
    test: "test/kart.test.js",
  },

  // ── 5B: eslestirme ekrani (A13) ────────────────────────────────────────
  {
    ad: "5B: parola alani temizlenmiyor",
    dosya: "src/ekran/esles_durum.js",
    bul: '    parola.value = "";',
    koy: "",
    test: "test/esles.test.js",
  },
  {
    ad: "5B: esles'ten once kare beklenmiyor (ilerleme gostergesi cizilmez)",
    dosya: "src/ekran/esles_durum.js",
    bul: "      await kareBekle();",
    koy: "",
    test: "test/esles.test.js",
  },
  {
    ad: "5B: hata olarak istisnanin kendisi tutuluyor (sozluk anahtari degil)",
    dosya: "src/ekran/esles_durum.js",
    bul: "      hata.value = hataAnahtari(e);",
    koy: "      hata.value = e;",
    test: "test/esles.test.js",
  },
  {
    ad: "5B: parola alani gizli degil (type=password yok)",
    dosya: "src/ekran/Esles.vue",
    bul: 'type="password" ',
    koy: "",
    test: "test/esles.test.js",
  },
  {
    ad: "5B: parola alaninda otomatik doldurma acik",
    dosya: "src/ekran/Esles.vue",
    bul: 'autocomplete="off" ',
    koy: "",
    test: "test/esles.test.js",
  },
  {
    ad: "5B: parola etiketi 'Wi-Fi parolasi DEGIL' demiyor",
    dosya: "src/cekirdek/sozluk_mobil.js",
    bul: '"Kartın WEB parolası — Wi-Fi parolası DEĞİL"',
    koy: '"Kartın parolası"',
    test: "test/esles.test.js",
  },
  {
    ad: "5B: iki hata turu ayni metne bagli (parola-yok = parola-yanlis)",
    dosya: "src/ekran/esles_durum.js",
    bul: '"parola-yok": "m.es.hata_parola_yok",',
    koy: '"parola-yok": "m.es.hata_parola_yanlis",',
    test: "test/esles.test.js",
  },

  // ── 5B: gizlilik istisnasi ─────────────────────────────────────────────
  {
    ad: "5B: 'fetch:' ortam anahtari istisnasi her degeri kabul ediyor",
    dosya: "test/gizlilik.test.js",
    bul: String.raw`/\{ fetch: (?:ag\.)?[a-z][A-Za-z]*Fetch\b/g`,
    koy: String.raw`/\{ fetch: [^,}]*/g`,
    test: "test/gizlilik.test.js",
  },

  // ── 5B: logcat sir tarayicisi (A45) ────────────────────────────────────
  ...[
    ["imza basliklari", String.raw`re: /X-(?:Imza|Sayac|Cihaz)(?![A-Za-z0-9])/i`],
    ["imza sorgusu (_i/_s/_c)", String.raw`re: /(?:^|[?&\s"'(,;])_[isc]=/`],
    ["40+ onaltilik", String.raw`re: /(?<![0-9A-Fa-f])[0-9A-Fa-f]{40,}(?![0-9A-Fa-f])/`],
    ["kanit=", String.raw`re: /kanit["']?\s*[=:]/i`],
    ["parola + deger", String.raw`re: /(?:parola|password|passwd)[A-Za-z_]*["']?\s*[:=]\s*["']?(?!(?:yok|null|none|bos|undefined)(?![A-Za-z0-9]))[^\s"']/i`],
    ["methodData", String.raw`re: /methodData/`],
    ["kart kimligi", String.raw`re: /kimlik[^0-9A-Za-z]{0,12}(?<![0-9A-Fa-f])[0-9a-f]{16}(?![0-9A-Fa-f])/i`],
    ["ozel adres + kart yolu", String.raw`re: /(?<![0-9.])(?:10\.\d{1,3}|192\.168|172\.(?:1[6-9]|2\d|3[01]))\.\d{1,3}\.\d{1,3}(?::\d{1,5})?\/(?:eslestir|komut|kayit)/`],
  ].map(([ne, bul]) => ({
    ad: `5B: logcat tarayicisi '${ne}' desenini aramiyor`,
    dosya: "araclar/logcat_tara.mjs",
    bul,
    koy: "re: /(?!)/",
    test: "test/logcat_tara.test.js",
  })),
  {
    ad: "5B: logcat tarayicisi uzun onaltiligi yalniz kucuk harfle ariyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: String.raw`(?<![0-9A-Fa-f])[0-9A-Fa-f]{40,}(?![0-9A-Fa-f])/ }`,
    koy: String.raw`(?<![0-9A-Fa-f])[0-9a-f]{40,}(?![0-9A-Fa-f])/ }`,
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi verilen sirri duz aramiyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: "  const duz = [sir];",
    koy: "  const duz = [];",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi verilen sirrin onaltiligini aramiyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: '  const kucuk = [bayt.toString("hex")];',
    koy: "  const kucuk = [];",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi verilen sirrin base64'unu aramiyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: "  const b64 = base64Parcalari(bayt);",
    koy: "  const b64 = [];",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi base64'u yalniz tek hizada ariyor (gomulu sir kacar)",
    dosya: "araclar/logcat_tara.mjs",
    bul: "  for (let kayma = 0; kayma < 3; kayma++) {",
    koy: "  for (let kayma = 0; kayma < 1; kayma++) {",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi base64url alfabesini standarda cevirmiyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: String.raw`    const standart = satir.replace(/-/g, "+").replace(/_/g, "/");`,
    koy: "    const standart = satir;",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi onaltilik verilen sirrin ham baytlarini (base64) aramiyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: '    b64.push(...base64Parcalari(Buffer.from(sir, "hex")));',
    koy: "",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi buldugu satirin DEGERINI ciktiya yaziyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: "  for (const b of bulgular) console.log(`satir ${b.satir}: ${b.desen}`);",
    koy: "  for (const b of bulgular) console.log(`satir ${b.satir}: ${b.desen} ${metin.split(\"\\n\")[b.satir - 1]}`);",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi kirli dosyada cikis 0 veriyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: "  return bulgular.length ? 1 : 0;",
    koy: "  return 0;",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi bos dosyayi temiz sayiyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: '  if (metin.trim() === "") {',
    koy: "  if (false) {",
    test: "test/logcat_tara.test.js",
  },
  {
    ad: "5B: logcat tarayicisi BOM'suz UTF-16 dosyayi UTF-8 saniyor",
    dosya: "araclar/logcat_tara.mjs",
    bul: '  if (n >= 8 && sifir > n / 4) return b.toString("utf16le");',
    koy: "",
    test: "test/logcat_tara.test.js",
  },
];
