// Mutasyon listesi: her iddianin onu YALANLAYAN degisikligi.
//   ad    : "<dilim>: ne bozuluyor"  (--neden ONEK ile suzulur)
//   dosya : mobil/'e gore; bul: kaynakta TAM BIR KEZ gecen dizgi; koy: yerine konan
//   test  : vitest dosyasi (mobil/'e gore) ya da { komut: [...] }
export default [
  {
    ad: "5A-2: sozlukte EN metni bos",
    dosya: "src/cekirdek/sozluk_mobil.js",
    bul: '"Measurement Board"',
    koy: '""',
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-2: sablonda gomulu metin",
    dosya: "src/ekran/KartBul.vue",
    bul: '<h1>{{ c("m.kb.baslik") }}</h1>',
    koy: "<h1>Kartı bul</h1>",
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-2: gomulu metin ayiklayicisi duz ozellige bakmiyor",
    dosya: "test/sozluk.test.js",
    bul: "u.test(o[2])) bulunan.push",
    koy: "u.test(o[2]) && false) bulunan.push",
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-3: kayan pencere denetimi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: "if (!pencereKabul(pencereler.get(n), sayac)) {",
    koy: "if (false) {",
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-3: Host beyaz listesi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: 'return h === ip || h.toLowerCase() === "olcum.local" || h.toLowerCase() === "olcum";',
    koy: "return true;",
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-3: p0 serbestligi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: 'return k === "p0" || k === "?";',
    koy: 'return k === "?";',
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-4: 172.16/12 siniri 172/8 oldu",
    dosya: "src/cekirdek/hedef.js",
    bul: "(a === 172 && b >= 16 && b <= 31)",
    koy: "(a === 172)",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: bas sifirli (sekizlik gorunumlu) parca kabul",
    dosya: "src/cekirdek/hedef.js",
    bul: "/^(0|[1-9][0-9]{0,2})$/",
    koy: "/^[0-9]{1,4}$/",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: herkese acik IP reddi kalkti",
    dosya: "src/cekirdek/hedef.js",
    bul: 'throw new HedefHatasi("ozel-degil");',
    koy: "return { ad, port };",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: ad karsilastirmasi 'ile baslar' oldu",
    dosya: "src/cekirdek/hedef.js",
    bul: "if (ad.toLowerCase() === KART_ADI)",
    koy: "if (ad.toLowerCase().startsWith(KART_ADI))",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: yerel dongu secenek olmadan da izinli",
    dosya: "src/cekirdek/hedef.js",
    bul: "(yerelDongu && yerelDonguAdresi(ad))",
    koy: "yerelDonguAdresi(ad)",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: kartFetch hedef kuralini istekten once denetlemiyor",
    dosya: "src/cekirdek/ag.js",
    bul: "    urlDenetle(url, { yerelDongu });\n",
    koy: "",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-4: eklenti hatasinin ham kodu disari siziyor",
    dosya: "src/cekirdek/ag.js",
    bul: 'HATA_TURLERI.includes(e.code) ? e.code : "ic-hata"',
    koy: "true ? e.code : null",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-4: baslik adi buyuk/kucuk harfe duyarli",
    dosya: "src/cekirdek/ag.js",
    bul: "(basliklar.has(ad.toLowerCase()) ? basliklar.get(ad.toLowerCase()) : null)",
    koy: "(basliklar.has(ad) ? basliklar.get(ad) : null)",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-5: kimlik karsilastirmasi kalkti (yanlis karta baglanir)",
    dosya: "src/cekirdek/kesif.js",
    bul: "(!beklenenKimlik || s.kimlik === beklenenKimlik)",
    koy: "true",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: kimlik bicimi denetlenmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: '|| typeof b.kimlik !== "string" || !KIMLIK_DESENI.test(b.kimlik)',
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: elle adres hedef kuralindan gecmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: 'liste.push({ adres: hedefYazi(hedefAyir(elle, { yerelDongu })), kaynak: "elle" });',
    koy: 'liste.push({ adres: elle, kaynak: "elle" });',
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: NSD'den gelen herkese acik adres aday oluyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "try { adres = hedefYazi(hedefAyir(`${s.ip}:${s.port}`, { yerelDongu })); } catch { continue; }",
    koy: "adres = `${s.ip}:${s.port}`;",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: yanlis TXT kimligi elenmiyor (bos istek)",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (beklenenKimlik && txtKimlik && txtKimlik !== beklenenKimlik) continue;",
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: elle adres onceligi yok (hizli olan kazaniyor)",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (elleBekliyor) yedek = yedek || s; else kapat(s);",
    koy: "kapat(s);",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: 200 olmayan yanit kabul",
    dosya: "src/cekirdek/kesif.js",
    bul: 'if (y.status !== 200) return { ...aday, sonuc: "yanit-gecersiz" };',
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: bilgi govdesi siniri kalkti",
    dosya: "src/cekirdek/kesif.js",
    bul: "zamanAsimiMs, azamiGovde: AZAMI_BILGI });",
    koy: "zamanAsimiMs, azamiGovde: 64 * 1024 * 1024 });",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: ayni adres iki kez yoklaniyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (gorulen.has(aday.adres)) return;",
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: kimlik uymayan kart onbellege yaziliyor / hata turu ayrilmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: 'throw new KesifHatasi(yanlis ? "kimlik-uymuyor" : "bulunamadi", denenenler);',
    koy: 'throw new KesifHatasi("bulunamadi", denenenler);',
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-6: Capacitor kopru gunlugu acik (eklenti verisi logcat'e duser)",
    dosya: "capacitor.config.json",
    bul: '"loggingBehavior": "none"',
    koy: '"loggingBehavior": "debug"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: eklenti adresi logcat'e yaziyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/ag/KartAgPlugin.kt",
    bul: 'if (url == null) { call.reject("bicim", "bicim"); return }',
    koy: 'if (url == null) { call.reject("bicim", "bicim"); return }; android.util.Log.d("KartAg", url)',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: yedekleme acik",
    dosya: "android/app/src/main/AndroidManifest.xml",
    bul: 'android:allowBackup="false"',
    koy: 'android:allowBackup="true"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: bilesen ayri surecte (S1)",
    dosya: "android/app/src/main/AndroidManifest.xml",
    bul: 'android:launchMode="singleTask"',
    koy: 'android:launchMode="singleTask" android:process=":ayri"',
    test: "test/gizlilik.test.js",
  },
];
