// Mutasyon listesi: her iddianin onu YALANLAYAN degisikligi.
//   ad    : "<dilim>: ne bozuluyor"  (--neden ONEK ile suzulur)
//   dosya : mobil/'e gore; bul: kaynakta TAM BIR KEZ gecen dizgi; koy: yerine konan
//   test  : vitest dosyasi (mobil/'e gore) ya da { komut: [...] }
import curutucu from "../test/curutucu/yasayan-liste.mjs";

export default [
  ...curutucu.map((m) => ({ ...m, ad: `5A-7 ${m.ad}` })),
  {
    ad: "5A-2: sozlukte EN metni bos",
    dosya: "src/cekirdek/sozluk_mobil.js",
    bul: '"Measurement Board"',
    koy: '""',
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-2: sablonda gomulu metin",
    dosya: "src/ekran/KartBul.vue",
    bul: '<h1>{{ c("m.kb.baslik") }}</h1>',
    koy: "<h1>Kartı bul</h1>",
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-2: gomulu metin ayiklayicisi duz ozellige bakmiyor",
    dosya: "test/yardim/gomulu_metin.mjs",
    bul: "if (HARF.test(deger)) bulunan.push(",
    koy: "if (false) bulunan.push(",
    test: "test/sozluk.test.js",
  },
  {
    ad: "5A-3: kayan pencere denetimi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: "if (!pencereKabul(pencereler.get(n), sayac)) {",
    koy: "if (false) {",
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-3: Host beyaz listesi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: 'return h === ip || h.toLowerCase() === "olcum.local" || h.toLowerCase() === "olcum";',
    koy: "return true;",
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-3: p0 serbestligi kalkti",
    dosya: "test/sahte-kart/sunucu.mjs",
    bul: 'return k === "p0" || k === "?";',
    koy: 'return k === "?";',
    test: "test/sahte-kart.test.js",
  },
  {
    ad: "5A-4: 172.16/12 siniri 172/8 oldu",
    dosya: "src/cekirdek/hedef.js",
    bul: "(a === 172 && b >= 16 && b <= 31)",
    koy: "(a === 172)",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: bas sifirli (sekizlik gorunumlu) parca kabul",
    dosya: "src/cekirdek/hedef.js",
    bul: "/^(0|[1-9][0-9]{0,2})$/",
    koy: "/^[0-9]{1,4}$/",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: herkese acik IP reddi kalkti",
    dosya: "src/cekirdek/hedef.js",
    bul: 'throw new HedefHatasi("ozel-degil");',
    koy: "return { ad, port };",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: ad karsilastirmasi 'ile baslar' oldu",
    dosya: "src/cekirdek/hedef.js",
    bul: "if (ad.toLowerCase() === KART_ADI)",
    koy: "if (ad.toLowerCase().startsWith(KART_ADI))",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: yerel dongu secenek olmadan da izinli",
    dosya: "src/cekirdek/hedef.js",
    bul: "(yerelDongu && yerelDonguAdresi(ad))",
    koy: "yerelDonguAdresi(ad)",
    test: "test/hedef.test.js",
  },
  {
    ad: "5A-4: kartFetch hedef kuralini istekten once denetlemiyor",
    dosya: "src/cekirdek/ag.js",
    bul: "    urlDenetle(url, { yerelDongu });\n",
    koy: "",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-4: eklenti hatasinin ham kodu disari siziyor",
    dosya: "src/cekirdek/ag.js",
    bul: 'HATA_TURLERI.includes(e.code) ? e.code : "ic-hata"',
    koy: "true ? e.code : null",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-4: baslik adi buyuk/kucuk harfe duyarli",
    dosya: "src/cekirdek/ag.js",
    bul: "(basliklar.has(ad.toLowerCase()) ? basliklar.get(ad.toLowerCase()) : null)",
    koy: "(basliklar.has(ad) ? basliklar.get(ad) : null)",
    test: "test/ag.test.js",
  },
  {
    ad: "5A-5: kimlik karsilastirmasi kalkti (yanlis karta baglanir)",
    dosya: "src/cekirdek/kesif.js",
    bul: "(!beklenenKimlik || s.kimlik === beklenenKimlik)",
    koy: "true",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: kimlik bicimi denetlenmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: '|| typeof b.kimlik !== "string" || !KIMLIK_DESENI.test(b.kimlik)',
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: elle adres hedef kuralindan gecmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: 'liste.push({ adres: hedefYazi(hedefAyir(elle, { yerelDongu })), kaynak: "elle" });',
    koy: 'liste.push({ adres: elle, kaynak: "elle" });',
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: NSD'den gelen herkese acik adres aday oluyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "try { adres = hedefYazi(hedefAyir(`${s.ip}:${s.port}`, { yerelDongu })); } catch { continue; }",
    koy: "adres = `${s.ip}:${s.port}`;",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: elle adres onceligi yok (hizli olan kazaniyor)",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (elleBekliyor) yedek = yedek || s; else kapat(s);",
    koy: "kapat(s);",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: 200 olmayan yanit kabul",
    dosya: "src/cekirdek/kesif.js",
    bul: 'if (y.status !== 200) return { ...aday, sonuc: "yanit-gecersiz" };',
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: bilgi govdesi siniri kalkti",
    dosya: "src/cekirdek/kesif.js",
    bul: "zamanAsimiMs, azamiGovde: AZAMI_BILGI });",
    koy: "zamanAsimiMs, azamiGovde: 64 * 1024 * 1024 });",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: ayni adres iki kez yoklaniyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "if (gorulen.has(aday.adres)) return;",
    koy: "",
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-5: kimlik uymayan kart onbellege yaziliyor / hata turu ayrilmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: 'throw new KesifHatasi(yanlis ? "kimlik-uymuyor" : "bulunamadi", denenenler);',
    koy: 'throw new KesifHatasi("bulunamadi", denenenler);',
    test: "test/kesif.test.js",
  },
  {
    ad: "5A-6: Capacitor kopru gunlugu acik (eklenti verisi logcat'e duser)",
    dosya: "capacitor.config.json",
    bul: '"loggingBehavior": "none"',
    koy: '"loggingBehavior": "debug"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: eklenti adresi logcat'e yaziyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/ag/KartAgPlugin.kt",
    bul: 'if (url == null) { call.reject("bicim", "bicim"); return }',
    koy: 'if (url == null) { call.reject("bicim", "bicim"); return }; android.util.Log.d("KartAg", url)',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: yedekleme acik",
    dosya: "android/app/src/main/AndroidManifest.xml",
    bul: 'android:allowBackup="false"',
    koy: 'android:allowBackup="true"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-6: bilesen ayri surecte (S1)",
    dosya: "android/app/src/main/AndroidManifest.xml",
    bul: 'android:launchMode="singleTask"',
    koy: 'android:launchMode="singleTask" android:process=":ayri"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: CSP connect-src disari acik",
    dosya: "index.html",
    bul: "connect-src 'self';",
    koy: "connect-src 'self' http:;",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: CSP cerceve yasagi kalkti",
    dosya: "index.html",
    bul: " frame-src 'none';",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: istek kapisi kalkti (shouldInterceptRequest)",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "                if (!WebKapi.INSTANCE.izinli(request.getUrl().toString())) {",
    koy: "                if (false) {",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: gezinti kapisi kalkti (dis adres tarayicida acilir)",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "                if (!WebKapi.INSTANCE.izinli(request.getUrl().toString())) return true;",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: cerez yoneticisi yerinde kaliyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "        CookieHandler.setDefault(null);",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: WebView hata ayiklamasi acik",
    dosya: "capacitor.config.json",
    bul: '"webContentsDebuggingEnabled": false',
    koy: '"webContentsDebuggingEnabled": true',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-8: uretim kodu WebView'in fetch'ini cagiriyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "    const t0 = simdi();",
    koy: '    const t0 = simdi(); fetch("http://example.com/").catch(() => {});',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-7: kartFetch'in kendi suresi yok (eklenti donmezse asili kalir)",
    dosya: "src/cekirdek/ag.js",
    bul: "sonuc = await sureli(eklenti.istek(istek), istek.zamanAsimiMs + SURE_PAYI_MS);",
    koy: "sonuc = await eklenti.istek(istek);",
    test: "test/curutucu/ag.curutucu.test.js",
  },
  {
    ad: "5A-7: bozuk yanit govdesi ham istisna olarak cikiyor",
    dosya: "src/cekirdek/ag.js",
    bul: '      throw new KartAgHatasi("ic-hata");       // bozuk base64 vb.: ham istisna disari cikmaz',
    koy: "      throw new Error(\"x\");",
    test: "test/curutucu/ag.curutucu.test.js",
  },
  {
    ad: "5A-7: URL'de ad cevresinde bosluk kabul",
    dosya: "src/cekirdek/ag.js",
    bul: "if (!m || /[^\\x21-\\x7e]/.test(m[1])) throw",
    koy: "if (!m) throw",
    test: "test/curutucu/ag.curutucu.test.js",
  },
  {
    ad: "5A-7: NSD taramasinin suresi yok (tarama donmezse kesif asili)",
    dosya: "src/cekirdek/kesif.js",
    bul: "(await sureli(eklenti.nsdTara({ sureMs: nsdSureMs }), nsdSureMs + NSD_PAYI_MS))",
    koy: "(await eklenti.nsdTara({ sureMs: nsdSureMs }))",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: yoklamanin kendi suresi yok (aday donmezse kesif asili)",
    dosya: "src/cekirdek/kesif.js",
    bul: "sureli(yokla(aday), zamanAsimiMs + TOPLAM_PAYI_MS).catch(() => ({ ...aday, sonuc: \"zaman-asimi\" })).then((s) => {",
    koy: "yokla(aday).then((s) => {",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: TXT kimligi uymayan duyuru eleniyor (kart gizlenebilir)",
    dosya: "src/cekirdek/kesif.js",
    bul: "      const onceki = adaylar.get(adres);",
    koy: "      if (beklenenKimlik && txtKimlik && txtKimlik !== beklenenKimlik) continue; const onceki = adaylar.get(adres);",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: kimligi uyan duyuru one alinmiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "return [...adaylar.values()].sort((a, b) => puan(a) - puan(b))",
    koy: "return [...adaylar.values()]",
    test: "test/curutucu/kesif.curutucu.test.js",
  },
  {
    ad: "5A-7: CSP'de webrtc yasagi yok",
    dosya: "index.html",
    bul: "; webrtc 'block'",
    koy: "",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-7: CSP'ye fazladan yonerge (worker-src) eklendi",
    dosya: "index.html",
    bul: "; webrtc 'block'",
    koy: "; webrtc 'block'; worker-src blob: data:",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-7: CSP meta etiketi tumuyle silindi",
    dosya: "index.html",
    bul: 'http-equiv="Content-Security-Policy"',
    koy: 'http-equiv="X-Yok"',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: WebRTC kaldirma JS'te ilk ice aktarim degil",
    dosya: "src/main.js",
    bul: 'import "./cekirdek/rtc_kapat.js";',
    koy: '// import "./cekirdek/rtc_kapat.js";',
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: yerelde belge basi betigi eklenmiyor",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/MainActivity.java",
    bul: "            WebViewCompat.addDocumentStartJavaScript(",
    koy: "            // WebViewCompat.addDocumentStartJavaScript(",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: WebRTC arayuzu geri konabiliyor (kilitli degil)",
    dosya: "src/cekirdek/rtc_kapat.js",
    bul: "{ value: undefined, writable: false, configurable: false }",
    koy: "{ value: undefined, writable: true, configurable: true }",
    test: "test/gizlilik.test.js",
  },
  {
    ad: "5A-9: Kotlin listesinde RTCPeerConnection yok",
    dosya: "android/app/src/main/java/tr/olcumkarti/mobil/WebKapi.kt",
    bul: '        "RTCPeerConnection", "webkitRTCPeerConnection",',
    koy: '        "webkitRTCPeerConnection",',
    test: "test/gizlilik.test.js",
  },
];
