// 5C-p0 mutasyonlari (acil durdurma). Ana listeye (liste.mjs) dahil edilir.
export default [
  {
    ad: "5C-p0: durdur() eklentiye gitmeden once bir gorev turu bekliyor",
    dosya: "src/cekirdek/durdur.js",
    bul: "    const soz = p0(hedefler);",
    koy: "    const soz = Promise.resolve().then(() => p0(hedefler));",
    test: "test/durdur.test.js",
  },
  {
    ad: "5C-p0: ag.p0 eklentiye gitmeden once bekliyor",
    dosya: "src/cekirdek/ag.js",
    bul: "    try { cagri = eklenti.p0({ adresler: liste }); } catch { return Promise.resolve(yok()); }",
    koy: "    cagri = Promise.resolve().then(() => eklenti.p0({ adresler: liste }));",
    test: "test/durdur.test.js",
  },
  {
    ad: "5C-p0: kartin erisim noktasi adresi listede yok",
    dosya: "src/cekirdek/durdur.js",
    bul: "[...(Array.isArray(liste) ? liste : []), KART_AP_ADRESI]",
    koy: "[...(Array.isArray(liste) ? liste : [])]",
    test: "test/durdur.test.js",
  },
  {
    ad: "5C-p0: eklenti reddederse p0 atiyor",
    dosya: "src/cekirdek/ag.js",
    bul: "      yok,\n    );",
    koy: "    );",
    test: "test/durdur.test.js",
  },
  {
    ad: "5C-p0: eski (gec gelen) sonuc durumu eziyor",
    dosya: "src/cekirdek/durdur.js",
    bul: '(s) => { if (no === sira) bildir(',
    koy: '(s) => { if (true) bildir(',
    test: "test/durdur.test.js",
  },
  {
    ad: "5C-p0: adresler() atarsa durdurma da atiyor",
    dosya: "src/cekirdek/durdur.js",
    bul: "    try { liste = adresler(); } catch { liste = []; }",
    koy: "    liste = adresler();",
    test: "test/durdur.test.js",
  },
  {
    ad: "5C-p0: arayuz geri cagrisinin hatasi durdurmayi bozuyor",
    dosya: "src/cekirdek/durdur.js",
    bul: "if (degisti) { try { degisti(h); } catch { /* arayuz hatasi durdurmayi etkilemez */ } }",
    koy: "if (degisti) { degisti(h); }",
    test: "test/durdur.test.js",
  },
  {
    ad: "5B-olcum: PBKDF2 dogrulama isareti hep true",
    dosya: "src/cekirdek/olcum.js",
    bul: "dogru: tur === 20000 ? ozet === BEKLENEN_20000 : null,",
    koy: "dogru: true,",
    test: "test/olcum.test.js",
  },
  {
    ad: "5B-olcum: basvuru degeri bozuk",
    dosya: "src/cekirdek/olcum.js",
    bul: 'BEKLENEN_20000 = "3f04',
    koy: 'BEKLENEN_20000 = "3f05',
    test: "test/olcum.test.js",
  },
  {
    ad: "5C-kesif: duyuru taramasi 3 s'den kisa",
    dosya: "src/cekirdek/kesif.js",
    bul: "export const NSD_SURE_MS = 3000;",
    koy: "export const NSD_SURE_MS = 1200;",
    test: "test/kesif.test.js",
  },
  {
    ad: "5C-kesif: bulunamadi demeden once yeniden denemiyor",
    dosya: "src/cekirdek/kesif.js",
    bul: "for (let i = 0; i < yenidenDene && !sonuc",
    koy: "for (let i = 0; i < 0 && !sonuc",
    test: "test/kesif.test.js",
  },
  {
    ad: "5C-kesif: kimlik uymayan kartta da yeniden deniyor",
    dosya: "src/cekirdek/kesif.js",
    bul: ' && !sonuc && !denenenler.some((d) => d.sonuc === "tamam"); i++)',
    koy: " && !sonuc; i++)",
    test: "test/kesif.test.js",
  },
  {
    ad: "5C-kesif: varsayilan yeniden deneme sayisi 2",
    dosya: "src/cekirdek/kesif.js",
    bul: "yenidenDene = 1, yenidenBekleMs = 300,",
    koy: "yenidenDene = 2, yenidenBekleMs = 300,",
    test: "test/kesif.test.js",
  },
  {
    ad: "5C-tercih: gecersiz dil saklaniyor",
    dosya: "src/ekran/tercih.js",
    bul: "dil: parca && DILLER.includes(parca.dil) ? parca.dil : simdiki.dil,",
    koy: "dil: parca && parca.dil ? parca.dil : simdiki.dil,",
    test: "test/tercih.test.js",
  },
  {
    ad: "5C-tercih: sistem temasinda data-tema kaliyor",
    dosya: "src/ekran/tercih.js",
    bul: 'if (tercih.tema === "sistem") kok.removeAttribute("data-tema");',
    koy: 'if (tercih.tema === "sistem") kok.setAttribute("data-tema", "koyu");',
    test: "test/tercih.test.js",
  },
  {
    ad: "5C-tercih: tema degisince tuvale haber gitmiyor",
    dosya: "src/ekran/tercih.js",
    bul: "belge.dispatchEvent(new Event(TEMA_OLAYI));",
    koy: "void 0;",
    test: "test/tercih.test.js",
  },
  {
    ad: "5C-tercih: c() secilen dili kullanmiyor",
    dosya: "src/ekran/metin.js",
    bul: "return ceviriMobil(anahtar, dil.value, degerler);",
    koy: 'return ceviriMobil(anahtar, "tr", degerler);',
    test: "test/tercih.test.js",
  },
  {
    ad: "5C-tercih: bozuk kayitta okuma atiyor",
    dosya: "src/ekran/tercih.js",
    bul: "try { ham = JSON.parse(depo.getItem(DEPO_ANAHTARI)); } catch { ham = null; }",
    koy: "ham = JSON.parse(depo.getItem(DEPO_ANAHTARI));",
    test: "test/tercih.test.js",
  },
];
