// 5F — paylasim. Kosum (mobil/ icinden): node mutasyon/kos.mjs --neden 5F-J
const T = "test/paylasim.test.js";
// gonder()'in denetim blogu (src/cekirdek/paylas.js). genisTurDenetle (5P) ad / '..' / MIME-uzanti uyumunu YENIDEN
// denetler: tek satiri silen mutasyon esdeger kalirdi — her mutasyon blogun tamamini kendi eksigiyle degistirir.
const AD_SATIRI = '    if (typeof ad !== "string" || !AD_DESENI.test(ad) || ad.includes("..")) throw new PaylasHatasi("bicim");\n';
const MIME_SATIRI = '    if (typeof mime !== "string" || !MIME.test(mime)) throw new PaylasHatasi("bicim");\n';
const GENIS_SATIRI = '    if (genisTurDenetle(ad, mime) === null) throw new PaylasHatasi("bicim");      // MIME uzantiya uymali\n';
const DENETIM = AD_SATIRI + MIME_SATIRI + GENIS_SATIRI;

export default [
  { ad: "5F-J: paylasim: oturuma uymayan tur uretiliyor", dosya: "src/cekirdek/kayit_veri.js",
    bul: "if (!o || !paylasimTurleri(veri, oturumNo).includes(tur)) return null;", koy: "if (!o) return null;", test: T },
  { ad: "5F-J: paylasim: rapor turu listede yok", dosya: "src/cekirdek/kayit_veri.js",
    bul: "return o ? [...disariTurleri(o), RAPOR_TURU] : null;", koy: "return o ? [...disariTurleri(o)] : null;", test: T },
  { ad: "5F-J: paylasim: rapor hep Turkce", dosya: "src/cekirdek/kayit_veri.js",
    bul: "kayitlar: veri.kayitlar, dil: dil === \"en\" ? \"en\" : \"tr\" }), dil === \"en\" ? \"en\" : \"tr\")", koy: "kayitlar: veri.kayitlar, dil: \"tr\" }), \"tr\")", test: T },
  { ad: "5F-J: paylasim: boy siniri yok", dosya: "src/cekirdek/kayit_veri.js",
    bul: "  if (d.bayt.length > azami) throw new KayitVeriHatasi(\"cok-buyuk\");\n", koy: "", test: T },
  { ad: "5F-J: paylasim: boy siniri 480 MB", dosya: "src/cekirdek/kayit_veri.js",
    bul: "export const DISARI_AZAMI = 48 * 1024 * 1024;", koy: "export const DISARI_AZAMI = 480 * 1024 * 1024;", test: T },
  { ad: "5F-J: islemci: disari mesaji yok", dosya: "src/cekirdek/kayit_veri.js",
    bul: "      case \"disari\":\n        return paylasimUret(veri, a.oturum, a.tur, a.dil, DISARI_AZAMI, a.kal === undefined ? null : a.kal);\n", koy: "", test: T },
  { ad: "5F-J: kayitlar: paylasim oturum acilmadan calisiyor", dosya: "src/cekirdek/kayitlar.js",
    bul: "  async function disariKos(is, arguman) {\n    if (gorunenKimlik === null) return null;\n", koy: "  async function disariKos(is, arguman) {\n", test: T },
  { ad: "5F-J: kayitlar: paylasim hatasi TUR olarak cikmiyor", dosya: "src/cekirdek/kayitlar.js",
    bul: "    try { return await istemci.cagir(is, arguman); } catch (e) { throw hata(e); }\n  }\n\n  return {", koy: "    try { return await istemci.cagir(is, arguman); } catch (e) { return null; }\n  }\n\n  return {", test: T },
  { ad: "5F-J: paylas: ad denetimi yok", dosya: "src/cekirdek/paylas.js",
    bul: DENETIM, koy: MIME_SATIRI, test: T },
  { ad: "5F-J: paylas: '..' iceren ad kabul", dosya: "src/cekirdek/paylas.js",
    bul: DENETIM,
    koy: AD_SATIRI.replace(' || ad.includes("..")', "") + MIME_SATIRI + GENIS_SATIRI.replace("genisTurDenetle(ad, mime)", 'genisTurDenetle(ad.split("..").join("."), mime)'),
    test: T },
  { ad: "5F-J: paylas: mime denetimi yok", dosya: "src/cekirdek/paylas.js",
    bul: DENETIM, koy: AD_SATIRI, test: T },
  { ad: "5F-J: paylas: bos dosya gonderiliyor", dosya: "src/cekirdek/paylas.js",
    bul: "if (!(bayt instanceof Uint8Array) || bayt.length === 0) throw new PaylasHatasi(\"bos\");", koy: "if (!(bayt instanceof Uint8Array)) throw new PaylasHatasi(\"bos\");", test: T },
  { ad: "5F-J: paylas: es zamanli ikinci paylasim engellenmiyor", dosya: "src/cekirdek/paylas.js",
    bul: "    if (suruyor) throw new PaylasHatasi(\"mesgul\");\n", koy: "", test: T },
  { ad: "5F-J: paylas: hatadan sonra kilitli kaliyor", dosya: "src/cekirdek/paylas.js",
    bul: "    } finally {\n      suruyor = false;\n    }", koy: "    } finally {\n    }", test: T },
  { ad: "5F-J: paylas: parca 2 MiB (eklenti sinirini asar)", dosya: "src/cekirdek/paylas.js",
    bul: "export const PARCA = 512 * 1024;", koy: "export const PARCA = 2048 * 1024;", test: T },
  { ad: "5F-J: paylas: son parca gonderilmiyor", dosya: "src/cekirdek/paylas.js",
    bul: "for (let i = 0; i < bayt.length; i += PARCA) {", koy: "for (let i = 0; i + PARCA <= bayt.length; i += PARCA) {", test: T },
  { ad: "5F-J: paylas: mime karakter kumesiyle gidiyor", dosya: "src/cekirdek/paylas.js",
    bul: "mime: mime.split(\";\")[0], boy: bayt.length", koy: "mime, boy: bayt.length", test: T },
  { ad: "5F-J: paylas: eklentinin hata mesaji yukari cikiyor", dosya: "src/cekirdek/paylas.js",
    bul: "throw new PaylasHatasi(e && typeof e.code === \"string\" && TUR.test(e.code) ? e.code : \"ic-hata\");", koy: "throw new PaylasHatasi(e && e.message ? e.message : \"ic-hata\");", test: T },
  { ad: "5F-J: rapor: tr'de ondalik nokta", dosya: "src/cekirdek/rapor_metin.js",
    bul: "const y = sayiYaz(x, 6, dil === \"tr\" ? \",\" : \".\");", koy: "const y = sayiYaz(x, 6, \".\");", test: T },
  { ad: "5F-J: rapor: sondaki sifirlar atilmiyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "return y.replace(/([.,]\\d*?)0+$/, \"$1\").replace(/[.,]$/, \"\");", koy: "return y;", test: T },
  { ad: "5F-J: rapor: kod yazilmiyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "return v.kod === null || v.kod === undefined ? v.metin : `${v.metin} (${v.kod})`;", koy: "return v.metin;", test: T },
  { ad: "5F-J: rapor: ic alanlar (surum, dil) yaziliyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "    if (ATLA.has(k)) continue;\n    yaz(satirlar, etiket(k, dil), v, dil, 0);", koy: "    yaz(satirlar, etiket(k, dil), v, dil, 0);", test: T },
  { ad: "5F-J: rapor: etiketler sozlukten alinmiyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "  if (Object.hasOwn(RAPOR_ETIKET, anahtar)) return ceviri(RAPOR_ETIKET[anahtar], dil);\n", koy: "", test: T },
  { ad: "5F-J: rapor: telefon etiketleri kullanilmiyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "  if (Object.hasOwn(EK_ETIKET, anahtar)) return ceviriMobil(EK_ETIKET[anahtar], dil);\n", koy: "", test: T },
  { ad: "5F-J: rapor: bos dizi bos satir birakiyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "    if (v.length === 0) { satirlar.push(`${bas}${ad}: —`); return; }\n", koy: "", test: T },
  { ad: "5F-J: rapor: mantiksal deger true/false yaziliyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "  if (typeof v === \"boolean\") return ceviriMobil(v ? \"m.ps.evet\" : \"m.ps.hayir\", dil);\n", koy: "", test: T },
  { ad: "5F-J: rapor: kalibrasyon gecmisi rapora verilmiyor", dosya: "src/cekirdek/kayit_veri.js",
    bul: "kalibrasyonGecmisi: kalGecmisi(kal), kayitlar:", koy: "kalibrasyonGecmisi: null, kayitlar:", test: T },
  { ad: "5F-J: islemci: kal argumani tasinmiyor", dosya: "src/cekirdek/kayit_veri.js",
    bul: "a.kal === undefined ? null : a.kal);", koy: "null);", test: T },
  { ad: "5F-J: kayitlar: gecmis depodan okunmuyor", dosya: "src/cekirdek/kayitlar.js",
    bul: "kal: await kalOku() })),", koy: "kal: null })),", test: T },
  { ad: "5F-J: kayitlar: bicimsiz gecmis geciyor", dosya: "src/cekirdek/kayitlar.js",
    bul: "return d !== null && typeof d === \"object\" && Array.isArray(d.kayitlar) ? d : null;", koy: "return d;", test: T },
  { ad: "5F-J: kayitlar: gecmis okuma hatasi paylasimi durduruyor", dosya: "src/cekirdek/kayitlar.js",
    bul: "    } catch {\n      return null;\n    }\n  }\n\n  // Paylasim (5F)", koy: "    } finally {\n    }\n  }\n\n  // Paylasim (5F)", test: T },
  { ad: "5E-C: B16: satir sonu iceren metin rapora sahte satir sokuyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: ".replace(/\\s*[\\r\\n\\u0085\\u2028\\u2029]+\\s*/g, \" / \")", koy: "", test: "test/curutucu-5e" },
  { ad: "5E-C: B16: denetim karakterleri rapora giriyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: ".replace(/[\\u0000-\\u001f\\u007f]/g, \" \")", koy: "", test: "test/curutucu-5e" },
  { ad: "5E-C: J13: kodsuz deger '(null)' ile yaziliyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "return v.kod === null || v.kod === undefined ? v.metin : `${v.metin} (${v.kod})`;", koy: "return `${v.metin} (${v.kod})`;", test: "test/curutucu-5e" },
  { ad: "5E-C: J15: bos metin bos birakiliyor", dosya: "src/cekirdek/rapor_metin.js",
    bul: "if (v === null || v === undefined || v === \"\") return \"—\";", koy: "if (v === null || v === undefined) return \"—\";", test: "test/curutucu-5e" },
];
